### PR TITLE
[RFC] Workaround to mock Zephyr kernel API

### PR DESCRIPTION
**Pull request by metc**
In this draft/RFC PR, I would like to expose a limitation of the current framework when mocking kernel.h.

I am writing a unit test for a module that as a dependency to `kernel.h` malloc function and `mempool` API. In the unit test, I would like to mock the `calloc` function to return a null-pointer for instance and test the module implementation. In the current CMock/Unity framework implementation, we cannot mock functions that are also used by the framework itself (like the kernel API that is used to create the main Thread in the test app). Commit 19e9608 show this issue.

In commit b512545 I added an alias/proxy function to be able to mock the alloc function. This is a workaround, but the solution works.

1. This adds complexity to the code and makes it less readable but it is needed to have a good unit test. Are there other alternatives?
2. Is it acceptable to add alias functions for all modules that need to mock the Kernel APIs?

### CODE REVIEW

**Comment by metc** [comment]
FYI @nordic-krch

**Comment by nordic-krch** [comment]
I'm thinking about following solution:
- create modified version of `kernel.h` which replaces all declarations with static inline functions calling prefixed version of the function, like:
```
static inline k_calloc(...)
{
   ut_k_calloc(...);
}
```
- mock `ut_` functions.
- ensure that only module under test is including customized version of `kernel.h` instead of original

By doing that we will mock kernel only for module under test. To make that work we would need:
- cmake adding include path to one (or more?) particular file (@SebastianBoe  @tejlmand is it doable).
- extending scripting around cmock/unity to generate files.

What do you think? Other options?

**Comment by SebastianBoe** [comment]
> cmake adding include path to one (or more?) particular file (@SebastianBoe @tejlmand is it doable).

Yes, this can be done either with zephyr_library_include_directories, or by modifying the INCLUDE_DIRECTORY property of individual source files.

**Comment by metc** [comment]
Is there a way to call mocked `__wrap` functions only for the module under test and not for the whole test app?

**Comment by SebastianBoe** [comment]
Generally, when two different sets of sources need to reference the same API, but get a different implementation, one would want to have the build system change the include paths such that the sources end up using different implementations.

This can be done with zephyr_library_include_directories for instance.

**Comment by carlescufi** [comment]
'@{p.user.login} this Pull Request has not been updated for more than a
month. Please close it if not applicable anymore. CC {reviewers}

**Comment by carlescufi** [comment]
@metc this Pull Request has not been updated for more than a
month. Please close it if not applicable anymore. CC ['r.login ', 'r.login ']

**Comment by carlescufi** [comment]
@metc this Pull Request has not been updated for more than a
month. Please close it if not applicable anymore. CC ['carlescufi ', 'rlubos ']

**Comment by carlescufi** [comment]
@metc this Pull Request has not been updated for more than a
month. Please close it if not applicable anymore. CC @carlescufi  @rlubos

**Comment by carlescufi** [comment]
Note: This is an automated message.

**Comment by carlescufi** [comment]
Note: This is an automated message.
@{p.user.login} this Pull Request has not been updated for more than a month. Please close it if not applicable anymore.
{.join(reviewers)} please close it if the author is not available

**Comment by carlescufi** [comment]
Note: This is an automated message.
@metc this Pull Request has not been updated for more than a month. Please close it if not applicable anymore.
@carlescufi  @rlubos  please close it if the author is not available

**Comment by carlescufi** [comment]
Note: This is an automated message.
@metc this Pull Request has not been updated for more than a month. Please close it if not applicable anymore.
@carlescufi  @rlubos  please close it if the author is not available

**Comment by carlescufi** [comment]
Note: This is an automated message.
@metc this Pull Request has not been updated for more than a month. Please close it if not applicable anymore.

**Comment by carlescufi** [comment]
Note: This is an automated message.
@metc this Pull Request has not been updated for more than a month. Please close it if not applicable anymore.
@carlescufi  @rlubos  please close it if the author is not available

**Comment by carlescufi** [comment]
Closing this since this seems not applicable anymore.

**Comment by metc** [comment]
> Closing this since this seems not applicable anymore.

Is there a way to mock Zephyr kernel API now?

**Pull request closed without merging**
