### PR TITLE
Upmerge 20.08.2020

### PR DESCRIPTION
**Pull request by rlubos**
sdk-zephyr: https://github.com/nrfconnect/sdk-zephyr/pull/345
sdk-mcuboot: https://github.com/nrfconnect/sdk-mcuboot/pull/117
sdk-mcumgr: https://github.com/nrfconnect/sdk-mcumgr/pull/9

### CODE REVIEW

**Comment by rlubos** [comment]
@rugeGerritsen FYI, for now, I've stubbed the missing functions in `clock_control_mpsl.c` just to let the CI running.

**Comment by rlubos** [comment]
The samples/applications using Nordic BLE controller will likely not work until MPSL clock control driver is updated, so don't bother testing yet.

**Comment by rlubos** [comment]
@hakonfam @oyvindronningstad Please have a closer look at https://github.com/nrfconnect/sdk-nrf/pull/2743/commits/725d97ea439c1cbb2c140be6eb9a7999bc731341

The bootloader builds started to fail on this upmerge, as `nrf_rtc_timer.c` has now a hard dependency to CLOCK_CONTROL module.
The truth is, RTC was never really disabled in the bootloader, which was reported by the following warning:
```
warning: NRF_RTC_TIMER (defined at soc/arm/nordic_nrf/Kconfig.defconfig:16,
drivers/timer/Kconfig:141) was assigned the value 'n' but got the value 'y'. See
http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_NRF_RTC_TIMER.html and/or look up
NRF_RTC_TIMER in the menuconfig/guiconfig interface. The Application Development Primer, Setting
Configuration Values, and Kconfig - Tips and Best Practices sections of the manual might be helpful
too.
```
So we ended up with RTC enabled and CLOCK_CONTROL disabled, which is not a valid configuration. 

Initially, I wanted to fix this and disable RTC properly, but it turned out that disabling RTC is actually not an option ATM, as this would require to disable CONFIG_SYS_CLOCK_EXISTS, which cannot be done, as `k_busy_wait` is used in nrfx (UARTE driver specifically). So we either give up on the output from the application or keep RTC enabled.

Let me know if you're OK with this change, or if you want to get the bootloader issue resolved in another way.

**Comment by oyvindronningstad** [comment]
> Please have a closer look at [725d97e](https://github.com/nrfconnect/sdk-nrf/commit/725d97ea439c1cbb2c140be6eb9a7999bc731341)
> ...
> Let me know if you're OK with this change, or if you want to get the bootloader issue resolved in another way.

I think it's fine. IIRC it was just a space saving measure.

**Review by carlescufi — APPROVED** [review]
LGTM

**Review by nordic-auko — APPROVED** [review]
Connectivity bridge works fine

**Comment by carlescufi** [comment]
@rugeGerritsen could you take a look and check everything is OK?

**Review by rugeGerritsen — APPROVED** [review]
Looks good. @guwa , can you very that the CI has enough coverage for BLE?

**Comment by guwa** [comment]
> Looks good. @guwa , can you very that the CI has enough coverage for BLE?

@rugeGerritsen , the ble controller tests and some other tests were not executed due to docker issue (but not an issue for other ble test). I suppose the ble CI needs to be looked at and rerun.

**Review by pdunaj — APPROVED** [review]
Checked with `3dfcbb0e38b0e46034bbf4ced6a65df392a7e2da`. Mouse, dongle, keyboard was working. Mouse connected to Android, Win & dongle. Dongle connected to mouse & keyboard at the time.

**Review by lmaciejonczyk — APPROVED** [review]

**Comment by hakonfam** [comment]
We need to increase the stack size of the bootloader:
```
diff --git a/samples/bootloader/prj.conf b/samples/bootloader/prj.conf
index 633c0da71d..c9cd1ab565 100644
--- a/samples/bootloader/prj.conf
+++ b/samples/bootloader/prj.conf
@@ -26,6 +26,7 @@ CONFIG_BL_SECP256R1_EXT_API_ENABLED=y
 CONFIG_BL_VALIDATE_FW_EXT_API_ENABLED=y
 CONFIG_EXT_API_PROVIDE_EXT_API_ENABLED=y
 CONFIG_NRFX_NVMC=y
+CONFIG_MAIN_STACK_SIZE=2048
```

**Comment by rlubos** [comment]
@hakonfam Done

**Comment by pdunaj** [comment]
> We need to increase the stack size of the bootloader

Hi @hakonfam , can you tell why is that? Do we have to do it too on our side?

**Comment by hakonfam** [comment]
> > We need to increase the stack size of the bootloader
> 
> Hi @hakonfam , can you tell why is that? Do we have to do it too on our side (I mean BL configuration in nrf_desktop)?

I assume its only needed for nrf53 for now since it use software based crypto, I havent verified this. 
The overflow occurred during a regular boot-sequence, so you would notice if it was needed.

**Review by jtguggedal — APPROVED** [review]
Works well with `asset_tracker`, `cloud_client` and `nrf_cloud_agps` on nRF91 DK and Thingy:91

**Comment by sigvartmh** [comment]
`aws_fota` and `http_application_update` works the same way as they do in master. nrf91DK

**Review by hakonfam — APPROVED** [review]
verified b0-app with updates, b0-mcuboot-app with updates of mcuboot and b0, and mcuboot-app with app updates.

**Review by tejlmand — APPROVED** [review]
lgtm

**Review by joerchan — APPROVED** [review]

**Pull request merged**
