### PR TITLE
sample: http_update: Apply modem update after downloading

### PR DESCRIPTION
**Pull request by junqingzou**
Call lib_fota_download API to init DFU target and apply modem update, instead of using app function in main.

### CODE REVIEW

**Comment by eivindj-nordic** [comment]
I think the changes look good in itself. The question is whether we want to introduce another library to the sample or keep it closer to the modem library API.

**Comment by junqingzou** [comment]
> I think the changes look good in itself. The question is whether we want to introduce another library to the sample or keep it closer to the modem library API.

Hi Eivind, the API is from the fota_download lib, which has already been enabled by tha sample CONFIG_FOTA_DOWNLOAD=y

**Comment by junqingzou** [comment]
@rlubos could you help to invite Juha Heiskanen (jheiskan81) to review this PR?
For some reason I could not invite.

**Comment by eivindj-nordic** [comment]
After looking at this a bit more and discussing with @lemrey I think it makes sense to keep the modem library init and shutdown in the sample. Using the util might make sense in some applications, though I think we want to expose what is happening with the modem in the sample. The modem shutdown, re-init and its error handling is documented in the modem library documentation, while for the util one has to dive into the code to understand what is happening (I don't see any documentation anywhere). In the end the util does the same, just hides the modem calls, which I think makes it more complex to get started with and to understand.

**Comment by junqingzou** [comment]
> After looking at this a bit more and discussing with @lemrey I think it makes sense to keep the modem library init and shutdown in the sample. Using the util might make sense in some applications, though I think we want to expose what is happening with the modem in the sample. The modem shutdown, re-init and its error handling is documented in the modem library documentation, while for the util one has to dive into the code to understand what is happening (I don't see any documentation anywhere). In the end the util does the same, just hides the modem calls, which I think makes it more complex to get started with and to understand.

I understand. The original point of this PR is to be the first sample that utilizes the new APIs to simplify application development i.e. for customers' awareness. I'll close this PR now.

**Pull request closed without merging**
