### PR TITLE
doc: fw_info: Update docs to match implementation

### PR DESCRIPTION
**Pull request by SebastianBoe**
Docs are out-of-sync with implementation.

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by oyvindronningstad** [comment]
> I suppose the Kconfig docs also needs to be updated?
> To add the id field?

Yes, you're right. Step 2 in the EXT_API_REQ docs must also be edited to remove a level of indirection.

**Review by hakonfam — APPROVED** [review]

**Comment by SebastianBoe** [comment]
@mia-ko : No changelog should be necessary, AFAIK these docs have always been wrong, it's not a recent change to functionality.

**Comment by mia-ko** [comment]
> @mia-ko : No changelog should be necessary, AFAIK these docs have always been wrong, it's not a recent change to functionality.

No, not functionality, but doc improvements might also be added to changelog/release notes, for example see: https://github.com/nrfconnect/sdk-nrf/pull/8942

**Comment by SebastianBoe** [comment]
@mia-ko : That change makes sense to have in the changelog since it documents a new way to do something.

This patch is just correcting documentation that accidentally got out of sync with the implementation. It is not of interest to anyone to see this in the changelog.

(Whereas it is in interest of someone that wishes to know how to do this thing that we are now documenting in the linked issue).

**Review by mia-ko — APPROVED** [review]

**Pull request merged**
