### PR TITLE
soc: nordic: nrf54l15: fix APPROTECT handling

### PR DESCRIPTION
**Pull request by nika-nordic**
Updated sdk-zephyr aligns existing Kconfigs to nRF54L15, while updated TF-M excludes nRF54L15 from existing APPROTECT-related runtime code which is not yet aligned.

test-sdk-nrf: DRGN-23200_host_disconnects_upon_att_timeout

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Review by MarkusLassila — APPROVED** [review]

**Comment by nika-nordic** [comment]
@rlubos Is it possible to run TF-M integration tests that were previously failing only after merge?

**Comment by rlubos** [comment]
> @rlubos Is it possible to run TF-M integration tests that were previously failing only after merge?

I'm not sure, @PerMac does `ci-all-tests` affect twister?

**Comment by PerMac** [comment]
I am checking this now

**Comment by PerMac** [comment]
yes, setting `ci-all-test` label will force full twister scope (without dynamic scoping). However, it will also turn on all downstream jobs. There is no label to ask just full twister without affecting downstreams

**Comment by PerMac** [comment]
@nika-nordic do you remember which exact tests these were? Maybe they are already in scope?

**Comment by PerMac** [comment]
I believe these are those and are already in scope, passing the build
https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-18370/4/testReport/nrf54l15dk_nrf54l15_cpuapp_ns_tfm/regression_ipc_lvl1/
https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-18370/4/testReport/nrf54l15dk_nrf54l15_cpuapp_ns_tfm.regression_ipc_lvl2/
https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-18370/4/testReport/nrf54l15dk_nrf54l15_cpuapp_ns_tfm/regression_sfn_lvl1/
https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-18370/4/testReport/nrf54l15dk_nrf54l15_cpuapp_ns_tfm/regression_fp_hardabi/

**Comment by nika-nordic** [comment]
I have discussed scope of TF-M tests offline with @PerMac and they are fixed.

Therefore sdk-zephyr and TF-M PRs are ready to be merged.

**Comment by rlubos** [comment]
@nika-nordic Please update SHA and backport this

**Comment by rlubos** [comment]
Note this cannot be backported automatically, SHAs will not match

**Pull request merged**
