### PR TITLE
doc: update nrfxlib revision for nrfxlib PR #665

### PR DESCRIPTION
**Pull request by Avalei**
Update nrfxlib revision for [sdk-nrfxlib/pull/665](https://github.com/nrfconnect/sdk-nrfxlib/pull/665)

Signed-off-by: Deidre Casey <deidre.casey@nordicsemi.no>

### CODE REVIEW

**Review by tejlmand — CHANGES_REQUESTED** [review]
Use `pull/665/head` not a SHA when refering to a PR.
@carlescufi This is not caught be the labeller / CI and could easlily be merged by mistake.

**Review by tejlmand — APPROVED** [review]
lgtm

**Comment by DatGizmo** [comment]
With the new Integration Test Specification process we don't need the github labels.
I will remove them.

Right now this PR runs all Integration tests because it changes sdk-nrfxlib in west.yml and there is no test-spec.yml in that repo yet.
You can add changes to this PR [nrfconnect/sdk-nrfxlib#687](https://github.com/nrfconnect/sdk-nrfxlib/pull/687) to make the test spec here more targeted

To get the test spec feature working correctly on this PR, you need to rebase it to the latest main to get the [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml) file

Then run CI here to update the test spec.

[Information about the test spec feature](https://projecttools.nordicsemi.no/confluence/display/NCS/Test+Spec)
[CI-Help for issues](https://ci-help.nordicsemi.no/)

**Review by FrancescoSer — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
@Avalei https://github.com/nrfconnect/sdk-nrfxlib/pull/665 is merged. Please update west.yml in this PR to point to the SHA in that repository that was merged into the main branch and rebase.

**Comment by mbolivar-nordic** [comment]
> [@Avalei](/Avalei) [Avalei](/Avalei) removed [ changelog-entry-required ](/nrfconnect/sdk-nrf/labels/changelog-entry-required) [ DNM ](/nrfconnect/sdk-nrf/labels/DNM) labels [17 days ago](#event-6326339949)

@Avalei I just noticed this: the DNM label should not have been removed manually like this.

We do not allow merging pull requests with `pull/N/head` revisions. The bot which adds DNM in such cases will remove them automatically when you update your PR's west.yml revision to the final merged SHA in the affected repository.

**Comment by greg-fer** [comment]
Closing as no action is required: changes from nrfxlib were pulled in in another manifest update.

**Pull request closed without merging**
