### PR TITLE
subsys: adding event manager storage layer

### PR DESCRIPTION
**Pull request by GiulianoFranchetto**
Depending on the application, it can be useful to store transient
event into a specified storage technology to be able to replay
events that were not consumed by the application.

This may happen if the board ran out of battery or if the application
crashed during the processing of the event (or any other reason).

This commit adds a new storage layer to the event manager, similar
to the storage layer of the Zephyr settings API.
For now, only NVS is supported, but littlefs is planned. The
configuration file + a basic source file are already added to
that commit.

Each time an event is submitted, it is first sent to the storage
layer. This layer will give a unique id to the event and will
store the event. Once the storage of the event is done (and
regardless of the result of that operation), the event is truly
sent to the manager which will then call all the subscribers.

Each time an event is consumed, the storage layer removes it from
the storage.

When the board boots (or when event_manager_init() is called to be
more precise), the event storage layer is initialized.
Once that initialization is done, it will load each non-consumed event
present in the storage.
Each of these events will then be automatically re-submitted to the
application.
If the event is properly consumed, it will be removed from the storage.

Know issues:
-----------------------------
- Dynamic sized event are not supported yet

Roadmap:
-----------------------------
- [ ] Documentation
- [ ] Adding more storage option
- [ ] Supporting dynamically sized events
- [x] To prevent reading/writing too frequently we may add a flag in the
event header that will tell the storage layer to ignore an event.
For example a "button_pressed_event" can be forgotten without much
risk. However, "machine_about_to_blow_event" must be stored and
replayed if need be.

Signed-off-by: Giuliano Franchetto <giuliano.franchetto@intellinium.com>

### CODE REVIEW

**Comment by pdunaj** [comment]
Hi @GiulianoFranchetto , thanks. I was thinking about adding something similar for some time. Having possibility to store events in nv storage could be useful in multiple cases. Personally I was thinking more about creating a "log" of events that could be either sent outside or dumped when need comes. Writing flash on each event may be costly and wear flash fast, but it actually depends on the use case so in some occasions could be justified.

**Comment by pdunaj** [comment]
@GiulianoFranchetto I will try to review and add comments within next few days.

**Comment by pdunaj** [comment]
BTW @GiulianoFranchetto , could you tell more how do you use event manager? Do you use event profiler too?

**Comment by GiulianoFranchetto** [comment]
Hi @pdunaj! My main goal when writing that code was to mimic how events are treated in the cloud, where an event remain in the queue as long as it has not been consumed.
In our application, we shall send an alert if the user is doing a specific sequence of button pressure.
If a crash happens while the alert is sent, the alert *must* be resent, as the life of the user depends on it.
I agree that all events could not be treated with the same priority, as mentioned in the roadmap.
It should not be very difficult.
Just adding something like ```EVENT_SUBMIT_IMPORTANT()``` with a flag in the ```struct event_header``` to true should be enough

**Comment by GiulianoFranchetto** [comment]
> BTW @GiulianoFranchetto , could you tell more how do you use event manager? Do you use event profiler too?

@pdunaj I'm porting our firmware to event manager as our program is event driven by nature. Having deeply coupled module with callback functions is really not something sexy. In the same time, I also develop our cloud servers, which are also using event driven architecture. The goal here is to have somewhat of a similar architecture between our embedded code and our java code, and to decoupled every part of the embedded code as much as possible.

As for the profiler, I have not played with it yet

**Comment by GiulianoFranchetto** [comment]
Hi @pdunaj . I have pushed a new commit in the PR, but this time the compliance check is failing.
Could you please check for false positives, as it mostly fails because of "long lines" which are already here in the upstream header file

**Comment by pdunaj** [comment]
Hi @GiulianoFranchetto , will check and get back to the review but that will have to wait until Thursday (unless I manage to get other stuff done earlier).

**Comment by GiulianoFranchetto** [comment]
Hi @pdunaj ! Hope you're doing well.
Did you find some test to review the PR?

**Comment by pdunaj** [comment]
Hi @GiulianoFranchetto , I remember about this change but had no time yet :( We will be preparing event manager RFC to Zephyr so it might be better to wait and propose this change directly in Zephyr.

**Comment by pdunaj** [comment]
@nordic-krch

**Comment by GiulianoFranchetto** [comment]
Hi,
Where are we on this PR?

**Comment by pdunaj** [comment]
> @pdunaj Hi, Where are we on this PR?

Still upstreaming the event manager. I think it's at the end. Once done this PR could be taken directly to Zephyr.

**Comment by rodrigobrochado** [comment]
This is still planned given that the Zephyr PR had movements this week, right?

**Comment by pdunaj** [comment]
> This is still planned given that the Zephyr PR had movements this week, right?

Upstreaming the EM takes ages unfortunately. Nothing we can do about it...

**Comment by rodrigobrochado** [comment]
No problem. I'm just worried that the robot marked it as staled.

**Pull request closed without merging**
