### PR TITLE
samples: mss: Fix Wi-Fi connectivity

### PR DESCRIPTION
**Pull request by glarsennordic**
Two commits to fix Wi-Fi connectivity for MSS after upmerge.

One of these commits will also benefit any other users of `conn_mgr`

### CODE REVIEW

**Comment by glarsennordic** [comment]
This is a redo of https://github.com/nrfconnect/sdk-nrf/pull/17794

I want to leave that one in its original state since it is referenced right now by internal tickets

**Review by krish2718 — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by jayteemo — APPROVED** [review]

**Review by plskeggs — APPROVED** [review]

**Comment by glarsennordic** [comment]
Red CI here appears to be caused by `net/mqtt` sample, and is totally unrelated to this PR

**Comment by nordic-piks** [comment]
> Red CI here appears to be caused by `net/mqtt` sample, and is totally unrelated to this PR

CI - twister - at main is green - so either your PR is related to that fail or it needs rebase. CI should be green.

**Review by nordic-piks — DISMISSED** [review]
Rebase is needed to get green CI.

**Comment by glarsennordic** [comment]
My bad, the twister failure was actually related to my changes!

**Review by jayteemo — APPROVED** [review]

**Review by eivindj-nordic — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Pull request merged**
