### PR TITLE
KRKNWK-7779: zigbee: Add API for continuous carrier and CCA

### PR DESCRIPTION
**Pull request by tomchy**
Add APIs that are required by Zigbee PHY and/or MAC certification tests.

Signed-off-by: Tomasz Chyrowicz <tomasz.chyrowicz@nordicsemi.no>

### CODE REVIEW

**Review by wbober — APPROVED** [review]

**Comment by tomchy** [comment]
FYI: We probably can leave without this PR since those functions are used by the Test Harness  device, not the DUT.
I do not know how OpenThread covers the continuous carrier case in NCS, but they use the RAW API [here](https://github.com/openthread/openthread/blob/c2903713a18126ccf9e0a6aadf0596386e9480f5/examples/platforms/nrf528xx/src/diag.c#L111).

**Comment by tomchy** [comment]
Verification of those changes is in progress. I will let you know if that fixes the failing TP/154/MAC/CHANNEL-ACCESS-01 test case.

**Comment by wbober** [comment]
@tomchy Ah, sorry then I was a bit to fast on labeling. Remove the milestone and label if that's the case please.

**Comment by tomchy** [comment]
Test is still failing - I need to check manually TX power and channel.

**Comment by tomchy** [comment]
Channel jamming works as expected. Probably a TH script issue.

**Comment by tomchy** [comment]
The code is fine. There is an undocumented manual step in the TH script...

**Comment by tomchy** [comment]
Continuous carrier function moved to the test application due to the missing API inside radio API.
If we want to fully implement MAC certification test harness we need functions for:
 - Continuous carrier transmission (TP/154/MAC/CHANNEL-ACCESS-01)
 - Changing/breaking the FCS calculation (TP/154/MAC/FRAME-VALIDATION-01)

The CCA API is used by the DUT in one of the PHY certification tests (TP/154/PHY24/RECEIVER-07).

**Comment by wbober** [comment]
@carlescufi  this is green & aproved, do you think we could merge it?

**Review by rlubos — APPROVED** [review]

**Pull request merged**
