### PR TITLE
doc: fix broken sdk-nrf links for NCS 1.7.0

### PR DESCRIPTION
**Pull request by greg-fer**
Fixed a couple of broken links in sdk-nrf for NCS 1.7.0 release.
NCSDK-11020.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

### CODE REVIEW

**Comment by greg-fer** [comment]
I have issues with the following links that appear as "broken" for the linkcheck for different reasons, but look totally legit when I open them in the browser:
- `Bluetooth SIG company identifiers`: https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/
- `Bluetooth mesh study guide`: https://www.bluetooth.com/bluetooth-resources/bluetooth-mesh-developer-study-guide/
- `OpenThread Border Router Codelab tutorial step 3`: https://openthread.io/codelabs/openthread-border-router#2
- `nRF Cloud Patch Device State`: https://api.nrfcloud.com/v1#operation/UpdateDeviceState
- `nRF Cloud Location Services`: https://api.nrfcloud.com/v1#tag/Location-Services
@gmarull , could you have a look?

**Review by Avalei — APPROVED** [review]
Looks good to me. Links are working.

**Comment by greg-fer** [comment]
The following link from this page appears as broken due to "file not found": https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/tests/crypto/README.html
- `GEC 2: Test Vectors for SEC 1`: http://read.pudn.com/downloads168/doc/772358/TestVectorsforSEC%201-gec2.pdf
 @Vge0rge , @frkv , could you check what the link should point to?

**Comment by SebastianBoe** [comment]
@greg-fer : Do you want to await merging until all links are fixed?

**Comment by SebastianBoe** [comment]
> @Vge0rge , @frkv , could you check what the link should point to?

The whole site got taken down. I could not find a replacement. I think the link must be removed.

**Comment by greg-fer** [comment]
@SebastianBoe 

> The whole site got taken down. I could not find a replacement. I think the link must be removed.

Should I only remove the link or also update the table with some "No test vectors" or "Custom"?

**Comment by SebastianBoe** [comment]
> Should I only remove the link or also update the table with some "No test vectors" or "Custom"? (For now, I'm just going to remove the link.)

@Vge0rge : Georgios please advise

**Comment by Vge0rge** [comment]
> > Should I only remove the link or also update the table with some "No test vectors" or "Custom"? (For now, I'm just going to remove the link.)
> 
> @Vge0rge : Georgios please advise

Please just remove the link for now. I tried to find the pdf online but I only found some versions with some formatting issues. If we find a link later that has the correct pdf we can always re-add the link. But keep the name there, I think that it can be useful for some people to know.

**Comment by greg-fer** [comment]
Thanks, @Vge0rge . This means the PR is ready for merge, let me rebase.

**Pull request merged**
