### PR TITLE
samples: nrf53: Use SOC instead of BOARD

### PR DESCRIPTION
**Pull request by thomasstenersen**
Adding hci_rpmsg is dependent on the SOC, not BOARD. Same with timeslot
support. Use of the BOARD define will not work with custom boards.

Ref.: https://github.com/nrfconnect/sdk-nrf/pull/2467#discussion_r439854006

### CODE REVIEW

**Comment by hakonfam** [comment]
Maybe you can add the comment I added in #2479  ?

**Comment by tejlmand** [comment]
@hakonfam any thoughts on highlighting the auto inclusion of `hci_rpmsg` in the docs, either as an additional commit in this PR, or in #2479 
From: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_nrf5340.html#building-and-programming-a-sample
> The network sample Bluetooth: HCI RPMsg is automatically added to all Bluetooth Low Energy samples in the nRF Connect SDK. When CONFIG_BT_RPMSG_NRF53 is set to y (the default), the build system automatically includes the sample as a child image in the nrf5340_pdk_nrf5340_cpunet core.

User's might easily miss this sentence, and thus the inclusion `hci_rpmsg` could feel a bit magic to users, unless the docs are read very careful.

**Comment by tejlmand** [comment]
@thomasstenersen I agree with @hakonfam , please include this message to help users:
https://github.com/nrfconnect/sdk-nrf/blob/ba428badd9d042d74eed1d92231bc22ad5968408/samples/CMakeLists.txt#L33

**Comment by thomasstenersen** [comment]
Fun stuff. Should I rebase my sdk-zephyr on something else than `master`?

**Comment by joerchan** [comment]
> Fun stuff. Should I rebase my sdk-zephyr on something else than `master`?

No, you should rebase to master ;) Your sdk-zephyr is behind, from before the last upmerge.

**Comment by tejlmand** [comment]
@thomasstenersen and please remeber to link the PRs, helps a lot when reviewing:
This PR depends on: https://github.com/nrfconnect/sdk-zephyr/pull/323

**Comment by carlescufi** [comment]
@thomasstenersen please rebase

**Comment by thomasstenersen** [comment]
@carlescufi rebased this and https://github.com/nrfconnect/sdk-zephyr/pull/323 on latest masters.

**Comment by joerchan** [comment]
@thomasstenersen Need one more rebase :)

**Comment by thomasstenersen** [comment]
Rebased both PRs again.

**Comment by joerchan** [comment]
Verified SHA

**Pull request merged**
