### PR TITLE
manifest: Update zephyr repo

### PR DESCRIPTION
**Pull request by pdunaj**
Add fix for pwm operation.

Jira:NCSDK-11329

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by greg-fer** [comment]
@mbolivar-nordic , @carlescufi , @shantha-14 , do we need to bump the SHA indicated in the release notes?

**Comment by pdunaj** [comment]
CI failed on JLink issue. Will rerun this test.

**Comment by pdunaj** [comment]
Applied new revision. Rebased.

**Review by tejlmand — APPROVED** [review]

**Comment by pdunaj** [comment]
Rebased, will rerun CI at the same time.

**Comment by pdunaj** [comment]
Changed revision of zephyr to one from repo.

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
Closing this per @shantha-14 request. It has served its purpose testing the zephyr changes. We will get them in via an updated #5610.

**Comment by pdunaj** [comment]
@mbolivar-nordic ... wrong PR. That is actuall bug fix we need for 1.7.

**Comment by pdunaj** [comment]
And all green CI went away :(

**Comment by pdunaj** [comment]
Ok . you will get it in another manifest update. uff...

**Pull request closed without merging**
