### PR TITLE
MPSL as meta-irq, OpenThread as co-operative 

### PR DESCRIPTION
**Pull request by lmaciejonczyk**
This PR provides changes which were discussed [here](https://projecttools.nordicsemi.no/confluence/pages/viewpage.action?pageId=74402620)

### CODE REVIEW

**Comment by joerchan** [comment]
Would a rebase fix the kconfig issue?

**Comment by lmaciejonczyk** [comment]
> Would a rebase fix the kconfig issue?

It did, thanks.

**Comment by lmaciejonczyk** [comment]
@rugeGerritsen @joerchan the approval is welcome

**Comment by joerchan** [comment]
@lmaciejonczyk Waiting for @rugeGerritsen to confirm that this is supported.

The merge-conflicts needs to be fixed, sorry for the delay.

**Pull request merged**
