### PR TITLE
manifest: update zephyr for get flash simulator upgrade

### PR DESCRIPTION
**Pull request by nvlsianpu**
Upgraded sdk-zephyr zephyr version has flash simulator
patches which allows to:
- get RAM buffer address and to
- disable statistic usage

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Review by hakonfam — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Comment by SebastianBoe** [comment]
@nvlsianpu : SHA

**Comment by mbolivar-nordic** [comment]
@edmont what do you think of the Thread results in this PR? Is it mergeable despite the status?

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by edmont** [comment]
> @edmont what do you think of the Thread results in this PR? Is it mergeable despite the status?

I'm afraid no. There is a silly issue which breaks the Twister builds, thus none of the Thread tests were run. We are working right now on providing a quick fix to the build stages.

**Comment by SebastianBoe** [comment]
If https://github.com/nrfconnect/sdk-nrf/pull/5439 is merged it will cover this PR. So we can await merging this until it is clear whether 5439 goes in or not.

**Comment by nvlsianpu** [comment]
#5439 supersedes this PR.

**Pull request closed without merging**
