### PR TITLE
doc: zigbee: changes for NCS v1.5.1

### PR DESCRIPTION
**Pull request by greg-fer**
Added v1.5.1 release notes file with an entry for Zigbee.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

### CODE REVIEW

**Review by tomchy — APPROVED** [review]

**Comment by greg-fer** [comment]
@tomchy , @jangalda-nsc , @maciekfabia , can you please have a look at known issues for 1.5.1? Is any of the 1.5.0 known issues for Zigbee now fixed in v1.5.1? Are there any new known issues?

**Comment by tomchy** [comment]
@greg-fer: I can spot two updates:
`KRKNWK-9145: Corrupted payload in commands of the Scenes cluster`: Fixed by the ZBOSS library update (PR to  be created)
`KRKNWK-9119: Zigbee shell does not work with ZBOSS development libraries`: Will be fixed by: https://github.com/nrfconnect/sdk-nrf/pull/4195

**Review by jangalda-nsc — APPROVED** [review]

**Comment by thst-nordic** [comment]
the old doc repo is accidently being triggered and failing the CI.  I will remove it since doc builds in github actions stage now.

**Comment by greg-fer** [comment]
Removed known issues from the PR. The known issues will be updated in https://github.com/nrfconnect/sdk-nrf/pull/4265

**Review by tomchy — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
