### PR TITLE
bsdlib: mainfest update release 0.8.1

### PR DESCRIPTION
**Pull request by evenl**
Manifest update for bsdlib release 0.8.1

Signed-off-by: Even Falch-Larsen <even.falch-larsen@nordicsemi.no>

### CODE REVIEW

**Comment by lemrey** [comment]
Rebased; required by carrier library.

**Review by shantha-14 — APPROVED** [review]

**Comment by tejlmand** [comment]
Please update SHA: 33097a7450d14fc0fc52f05896606958c9d032b5

**Comment by lemrey** [comment]
SHA updated

**Review by lemrey — APPROVED** [review]

**Comment by tejlmand** [comment]
Closed, deprecated by: #3128

**Pull request closed without merging**
