### PR TITLE
samples:llpm: Stop advertising and scanning before printing debug logs

### PR DESCRIPTION
**Pull request by ryanjh**
This change eliminates the race condition that a device is connected as
both master and slave roles.

Signed-off-by: Ryan Chu <ryan.chu@nordicsemi.no>

### CODE REVIEW

**Review by KAGA164 — APPROVED** [review]

**Comment by joerchan** [comment]
Can you explain why?

**Comment by ryanjh** [comment]
> @joerchan: Can you explain why?

Similar to #2357, printing logs to UART console brings a delay to stop advertising and scanning in the connected callback.

**Comment by alwa-nordic** [comment]
Do I understand this correctly?: This sample uses two devices and has a configuration-less automatic negotiation of which will be central.

But is the race really eliminated here? This PR decreases the window in which the race can occur, but it's not clear that that guarantees no race. And in principle, timings can change in the future.

Maybe we can use a deterministic consensus algorithm for which device becomes central? E.g. The device with the smallest address.

**Comment by alwa-nordic** [comment]
I discussed this further with @ryanjh. This is an acceptable quickfix that has zero negative impact on code quality. Even though the fix may be inadequate in theory, it's an improvement we can ship in 1.7.0 with potential value for customers.

We identified a general need for a fixture for samples that establishes a link between two devices that this demo and and other demos like samples/bluetooth/throughput/ can rely on. Creating this is out of scope for @ryanjh currently.

**Comment by ryanjh** [comment]
> I discussed this further with @ryanjh. This is an acceptable quickfix that has zero negative impact on code quality. Even though the fix may be inadequate in theory, it's an improvement we can ship in 1.7.0 with potential value for customers.
> 
> We identified a general need for a fixture for samples that establishes a link between two devices that this demo and and other demos like samples/bluetooth/throughput/ can rely on. Creating this is out of scope for @ryanjh currently.

Per discussion offline, reword the commit message to explain the problem.

**Review by alwa-nordic — APPROVED** [review]

**Pull request merged**
