### PR TITLE
doc: working_with_nrf: squash structure for nRF70

### PR DESCRIPTION
**Pull request by greg-fer**
Reworked Working with nRF70 Series pages.
Removed "Developing with" pages and moved their contents to separate pages. Renamed Working with to Developing with.
NCSDK-22328.

### CODE REVIEW

**Review by gmarull — APPROVED** [review]

**Review by richabp — CHANGES_REQUESTED** [review]

**Review by richabp — COMMENTED** [review]
Isn't it necessary for "Developing with" guides to have a Requirements section anymore?

**Comment by greg-fer** [comment]
> Isn't it necessary for "Developing with" guides to have a Requirements section anymore?

No, but the compatible hardware is still listed on the EK (line 19) and EB (line 11) pages.

**Review by richabp — APPROVED** [review]
Since the names of guides are changing, would it be good to add it in Changelog?

**Review by divipillai — APPROVED** [review]

**Comment by greg-fer** [comment]
> Since the names of guides are changing, would it be good to add it in Changelog?

There will be one entry added at the end of this rework.

**Review by umapraseeda — APPROVED** [review]

**Pull request merged**
