### PR TITLE
Release 2.8.0-rc1 tagging

### PR DESCRIPTION
**Pull request by rlubos**

### CODE REVIEW

**Comment by rlubos** [comment]
CI is expected to fail for now as tags are not created yet.

**Review by tomi-font — APPROVED** [review]
TF-M and Mbed TLS

**Review by carlescufi — APPROVED** [review]
Checked everything except mcuboot, mbedtls and tf-m

**Review by nordicjm — APPROVED** [review]
sdk-mcuboot OK

**Review by jfischer-no — APPROVED** [review]

**Pull request merged**
