### PR TITLE
doc: pelion: Fix incorrect word

### PR DESCRIPTION
**Pull request by pdunaj**
Words have different meanings.

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Review by greg-fer — APPROVED** [review]

**Review by greg-fer — CHANGES_REQUESTED** [review]
@pdunaj , could you fix the link to the modem library in this PR?

**Review by greg-fer — APPROVED** [review]

**Review by emob-nordic — APPROVED** [review]
I like the commit message, its so deep :)

**Comment by greg-fer** [comment]
> I like the commit message, its so deep :)

Truly profound.

**Comment by pdunaj** [comment]
@greg-fer looks ok

**Pull request merged**
