### PR TITLE
samples: openthread: add openthread tag for samples

### PR DESCRIPTION
**Pull request by nordic-piks**
Extend list of paths used to check if openthread
samples should be executed.

### CODE REVIEW

**Comment by nordic-piks** [comment]
The idea behind this change is to allow automatic detection of PRs not related to given code area.
In this case, there is defined tag (e.g. openthread) and files/folder with source code related to that area.
This list of files/folders is then compared to files changed in PR. If particular PR does not change them,
tests related to specified tag should not be executed - will be excluded.

**Review by maciejbaczmanski — COMMENTED** [review]
Hi. Is the change going to affect changes covered by test-spec? https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml#L331

**Comment by nordic-piks** [comment]
> Hi. Is the change going to affect PRs with changes covered by test-spec? https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml#L331

This change will affect twister stage. If files listed in tags.yaml are not changed, then tests with such tag will not be executed.
Execution of downstreams will not be affected.

BTW, thanks for hint, I will update tags.yaml with content of test-spec.

**Review by maciejbaczmanski — APPROVED** [review]
Thanks for explanation @nordic-piks. As long as downstream triggers are not descoped (we've recently worked on the test scope and chose most crucial areas that **have to be covered**), approach sounds good to me. 
Please bare in mind that test spec tags for thread are also included in sdk-nrfxlib and sdk-zephyr:

https://github.com/nrfconnect/sdk-nrfxlib/blob/main/.github/test-spec.yml#L86
https://github.com/nrfconnect/sdk-zephyr/blob/main/.github/test-spec.yml#L163

@mariusz-nordicsemi could you take a look at the PR as well as @kszewenko is out of office?

**Comment by nordic-piks** [comment]
> Thanks for explanation @nordic-piks. As long as downstream triggers are not descoped (we've recently worked on the test scope and chose most crucial areas that **have to be covered**), approach sounds good to me. Please bear in mind that test spec tags for thread are also included in sdk-nrfxlib and sdk-zephyr:
> 
> https://github.com/nrfconnect/sdk-nrfxlib/blob/main/.github/test-spec.yml#L86 https://github.com/nrfconnect/sdk-zephyr/blob/main/.github/test-spec.yml#L163
> 
> @mariusz-nordicsemi could you take a look at the PR as well as @kszewenko is out of office?

Thanks, added them too.

**Comment by nordic-piks** [comment]
Updated after evaluation of:
https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml#L331-L340
https://github.com/nrfconnect/sdk-nrfxlib/blob/main/.github/test-spec.yml#L86-L99
https://github.com/nrfconnect/sdk-zephyr/blob/main/.github/test-spec.yml#L163-L170

Please note that the content is similar and syntax is different - the root path is NCS, all dependencies - from west modules - are stated at one place, tests and samples should not be included here, they are handled separately (but they will be build if changed)

**Comment by nordic-piks** [comment]
DNM until NCS 2.7

**Comment by nordic-piks** [comment]
> > Thanks for explanation @nordic-piks. As long as downstream triggers are not descoped (we've recently worked on the test scope and chose most crucial areas that **have to be covered**), approach sounds good to me. Please bear in mind that test spec tags for thread are also included in sdk-nrfxlib and sdk-zephyr:
> > https://github.com/nrfconnect/sdk-nrfxlib/blob/main/.github/test-spec.yml#L86 https://github.com/nrfconnect/sdk-zephyr/blob/main/.github/test-spec.yml#L163
> > @mariusz-nordicsemi could you take a look at the PR as well as @kszewenko is out of office?
> 
> The PR looks good to me as well. And I like the idea. Also my first thought was why not to use the test-spec.yml for that. Do you need to create a new file (tag.yml) really? I see it problematic to keep these files in sync (as they should be in sync) in the future.

I am basing currently on test-spec.yml to get list of folder dependencies. However syntax and elements are different.
But I will keep that in mind to possibly align them.

**Review by maciejbaczmanski — APPROVED** [review]
Thanks @nordic-piks , LGTM

**Review by tejlmand — APPROVED** [review]

**Comment by nordic-piks** [comment]
Just rebased after NCS 2.7 + added path for samples.

**Pull request merged**
