### PR TITLE
manifest: Point to the tf-m with EITS

### PR DESCRIPTION
**Pull request by Vge0rge**
-This points to the TF-M which supports
 encryption for the ITS objects.

Ref: NCSDK-7563

Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>

test-sdk-nrf: sdk-nrf-PR-6139

### CODE REVIEW

**Comment by tejlmand** [comment]
@Vge0rge should this be closed ?

**Comment by Vge0rge** [comment]
> @Vge0rge should this be closed ?

Not really, I will start working on it again now.

**Comment by DatGizmo** [comment]
With the new Integration Test Specification process we don't need the github labels.
I will remove them.

To get the test spec feature working correctly on this PR, you need to rebase it to the latest main to get the [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml) file

Then run CI here to update the test spec.

[Information about the test spec feature](https://projecttools.nordicsemi.no/confluence/display/NCS/Test+Spec)
[CI-Help for issues](https://ci-help.nordicsemi.no/)

**Review by frkv — APPROVED** [review]
LGTM

**Review by torsteingrindvik — APPROVED** [review]

**Pull request merged**
