### PR TITLE
drivers: wifi: Implement radio status event

### PR DESCRIPTION
**Pull request by krish2718**
For all radio test commands (init, TX and RX) UMAC now sends a status command primarily to handle OTP disable of 5GHz.

Fixes NRF7X-43.

@vivinordic @krga2022  Please test, I have only done basic testing as I don't have the setup.

### CODE REVIEW

**Comment by vivinordic** [comment]
Issuing init command when TX 1 command is running, gives an error message.
image

**Comment by krish2718** [comment]
@karun2796 The above issue is because UMAC doesn't send this for stop. Should we modify UMAC to always send status for both start and stop?

**Comment by karun2796** [comment]
> @karun2796 The above issue is because UMAC doesn't send this event for stop. Should we modify UMAC to always send status for both start and stop?
@krish2718 Currently Umac is sending event only for INIT, TX start, RX start commands since it has channel programming. Coming to TX stop, Rx stop there is no channel programming umac is simply sending reset command to lmac. Do we need to add this success event for all remaining commands like TX stop, RX stop & NRF_WIFI_CMD_RF_TEST too?

**Comment by krish2718** [comment]
Well that is the question. IMHO, sending a status for all is better, keeps the code uniform.

**Comment by krish2718** [comment]
@karun2796 I have tested your patch and it works, but I don't think we need this status for other commands as there already seems to be `NRF_WIFI_EVENT_RF_TEST` that takes care of it, so, I have not done any changes in driver, but test stop is working now.

**Comment by krish2718** [comment]
> Issuing init command when TX 1 command is running, gives an error message. image

Can you please re-check?

**Review by sachinthegreen — APPROVED** [review]

**Comment by vivinordic** [comment]
> > Issuing init command when TX 1 command is running, gives an error message. image
> 
> Can you please re-check?

image
I don't see the same issue.

**Review by vivinordic — APPROVED** [review]

**Pull request merged**
