### PR TITLE
manifest: SDC supports multiple advertising sets

### PR DESCRIPTION
**Pull request by rugeGerritsen**
See CHANGELOG for more changes

Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
Rebased to retrigger CI

**Comment by rugeGerritsen** [comment]
Rebased on master

**Comment by rugeGerritsen** [comment]
Pushing to retrigger CI?

**Review by carlescufi — APPROVED** [review]

**Comment by rajithavk** [comment]
Is there a documentation for this feature?

**Comment by rugeGerritsen** [comment]
> Is there a documentation for this feature?

@rajithavk , I would suggest you to take a look at https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/reference/bluetooth/gap.html?highlight=sid#c.bt_le_ext_adv_create and https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/reference/bluetooth/gap.html?highlight=sid#c.bt_le_ext_adv_start. Those two APIs let you create and start a given advertising set. 

https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/kconfig/CONFIG_BT_EXT_ADV_MAX_ADV_SET.html#cmdoption-arg-CONFIG_BT_EXT_ADV_MAX_ADV_SET configures the maximum number of supported advertising sets. 

Also remember that if you want to run N concurrent connectable advertisers, you need to support at least N slave connections. That can be configured through https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/kconfig/CONFIG_BT_MAX_CONN.html#cmdoption-arg-CONFIG_BT_MAX_CONN and https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/kconfig/CONFIG_SDC_SLAVE_COUNT.html#cmdoption-arg-CONFIG_SDC_SLAVE_COUNT.

**Pull request merged**
