### PR TITLE
samples: nrf9160: Cloud Client README correction

### PR DESCRIPTION
**Pull request by richardmccrae-nordicsemi**
[Jira 5583](https://projecttools.nordicsemi.no/jira/browse/NCSDK-5583)
Corrects the path to prj.conf for location of configuration options.

Signed-off-by: Richard McCrae <richard.mccrae@nordicsemi.no>

### CODE REVIEW

**Comment by richardmccrae-nordicsemi** [comment]
Needs to be added to NCS 1.3.0 milestone with Shankar, Shanthalakshmi as reviewer.

**Comment by mbolivar-nordic** [comment]
@richardmccrae-nordicsemi looks like you need to sign the CLA

**Comment by mbolivar-nordic** [comment]
@thst-nordic CI is failing with this message:

```
CI Aborted becuase PR author is not in "nRFConnect" github organization. Contact thomas.stilwell@nordicsemi.no
```

**Comment by mbolivar-nordic** [comment]
@richardmccrae-nordicsemi looks like this is blocked on your acceptance of the invitation to join the nrfconnect GitHub organization.

**Pull request merged**
