### PR TITLE
Updated CMake version to 3.20.5

### PR DESCRIPTION
**Pull request by tejlmand**
Zephyr is increasing the minimum required CMake version to 3.20.0.
See: https://github.com/zephyrproject-rtos/zephyr/pull/37575

Therefore we update the minimum required CMake version for
nRF Connect SDK to same version.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

### CODE REVIEW

**Review by pdunaj — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]

**Review by hubertmis — APPROVED** [review]

**Review by gmarull — CHANGES_REQUESTED** [review]
nit: https://github.com/nrfconnect/sdk-nrf/blob/master/scripts/tools-versions-minimum.txt should be updated

**Review by KAGA164 — APPROVED** [review]

**Comment by tejlmand** [comment]
> nit: https://github.com/nrfconnect/sdk-nrf/blob/master/scripts/tools-versions-minimum.txt should be updated

Done.

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
doc/nrf/gs_installing.rst needs updating

**Review by junqingzou — COMMENTED** [review]
Using CMAKE 3.21.0, reported NCSIDB-524

**Comment by tejlmand** [comment]
> doc/nrf/gs_installing.rst needs updating

Should not be needed as we take the content directly from the Zephyr docset, so all we have to do is to merge the updated documentation from Zephyr:
https://github.com/nrfconnect/sdk-nrf/blob/5291aa14b295fcb05c9a676c8d2883dce2b59a70/doc/nrf/gs_installing.rst#L60-64
```
      .. ncs-include:: getting_started/index.rst
         :docset: zephyr
         :dedent: 6
         :start-after: .. _install_dependencies_ubuntu:
         :end-before: group-tab:: macOS
```
and the same is true for Windows and MacOS.

**Review by gmarull — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by tejlmand** [comment]
> Using CMAKE 3.21.0, reported NCSIDB-524

Those are already fixed upstream and is part of the current upmerge here: https://github.com/nrfconnect/sdk-zephyr/pull/585

**Review by doki-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
@tejlmand please rebase

**Comment by tejlmand** [comment]
> @tejlmand please rebase

done

**Comment by thst-nordic** [comment]
All repos have been tested with Cmake 3.20.5 during toolchain testing, there were no problems.

**Review by thst-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
> All repos have been tested with CMake 3.20.5 during toolchain testing, there were no problems.

Then why are we seeing things like this in the test results?

```
CMake Error at CMakeLists.txt:6 (cmake_minimum_required):
  CMake 3.20.0 or higher is required.  You are running version 3.17.3
```

Is this OK to merge despite these failures?

**Comment by thst-nordic** [comment]
I released new toolchain just now.  Entire CI will use new CMake.  I restarted the jenkins test.

**Comment by thst-nordic** [comment]
This is ok to merge.  All tests passed  ( except 1 NRFJPROG-DLL error)

**Comment by ktaborowski** [comment]
Updated required cmake version in homekit private repository - https://github.com/nrfconnect/sdk-homekit/pull/

**Comment by mariusz-nordicsemi** [comment]
> Updated required cmake version in homekit private repository - [nrfconnect/sdk-homekit#227](https://github.com/nrfconnect/sdk-homekit/pull/227)

Could we update homekit revision in manifest with this PR so homekit tests could be performed?

**Comment by mbolivar-nordic** [comment]
Needs rebase :(

**Review by SeppoTakalo — APPROVED** [review]

**Review by mariusz-nordicsemi — APPROVED** [review]

**Pull request merged**
