### PR TITLE
lib: identity_key: CONFIG_IDENTITY_KEY no longer requires ASSERT

### PR DESCRIPTION
**Pull request by jonaias**
The ASSERT statements were removed on commit (ae412891d9a800e80c8024743c58d29fb8a9f712), but the KConfig was never updated.

In our current build, ASSERT increases ROM size by about 10%. It would be nice if, in the next SDK version, we didn't need to patch the library to fix it.

Before patch
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      507028 B     962048 B     52.70%
             RAM:      311132 B       440 KB     69.05%
        IDT_LIST:          0 GB        32 KB      0.00%
```
     
After patch
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      457156 B     962048 B     47.52%
             RAM:      310864 B       440 KB     69.00%
        IDT_LIST:          0 GB        32 KB      0.00%
```

Work sponsored by Limitless.ai

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Review by tomi-font — APPROVED** [review]
Thanks!

**Comment by nordicjm** [comment]
@jonaias will need to rebase this to get rid of Kconfig warning then fix these issues:
```
1: UC2 Commit message does not contain a 'Signed-off-by:' line
1: UC3 Commit title does not follow [subsystem]: [subject] (and should not start with literal subsys or treewide): "CONFIG_IDENTITY_KEY no longer requires ASSERT"
3: UC4 Commit message body line exceeds max length (122>72): "The ASSERT statements were removed on commit (ae412891d9a800e80c8024743c58d29fb8a9f712), but the KConfig was never updated"
```

**Comment by jonaias** [comment]
@nordicjm @tomi-font Please let me know if you need anything else.

Side note: There are a couple of examples where we can remove the assert. Please let me know if I should create a new PR or merge it into the commit from this PR (If you prefer to merge ASSERT removal from samples, let me know if the title still makes sense for the commit).

``` diff
diff --git a/samples/keys/identity_key_generation/prj.conf b/samples/keys/identity_key_generation/prj.conf
index 566caa64a0..947f7dc857 100644
--- a/samples/keys/identity_key_generation/prj.conf
+++ b/samples/keys/identity_key_generation/prj.conf
@@ -15,7 +15,6 @@ CONFIG_HW_UNIQUE_KEY_RANDOM=y
 
 CONFIG_IDENTITY_KEY=y
 CONFIG_IDENTITY_KEY_RANDOM=y
-CONFIG_ASSERT=y
 
 # NRF_SECURITY is needed to generate a random identity key
 CONFIG_NRF_SECURITY=y
diff --git a/samples/keys/identity_key_usage/prj.conf b/samples/keys/identity_key_usage/prj.conf
index 76a5d5e95a..84c045174c 100644
--- a/samples/keys/identity_key_usage/prj.conf
+++ b/samples/keys/identity_key_usage/prj.conf
@@ -5,7 +5,6 @@
 #
 
 CONFIG_IDENTITY_KEY=y
-CONFIG_ASSERT=y
 CONFIG_HW_UNIQUE_KEY=y
 CONFIG_MPU_ALLOW_FLASH_WRITE=y
 CONFIG_RESET_ON_FATAL_ERROR=n
diff --git a/samples/tfm/provisioning_image/prj.conf b/samples/tfm/provisioning_image/prj.conf
index 5941920f1f..2ba6ebf187 100644
--- a/samples/tfm/provisioning_image/prj.conf
+++ b/samples/tfm/provisioning_image/prj.conf
@@ -15,7 +15,6 @@ CONFIG_HW_UNIQUE_KEY_RANDOM=y
 
 CONFIG_IDENTITY_KEY=y
 CONFIG_IDENTITY_KEY_RANDOM=y
-CONFIG_ASSERT=y
 
 # NRF_SECURITY is needed to generate a random identity key
 CONFIG_NRF_SECURITY=y
```

**Comment by tomi-font** [comment]
> Side note: There are a couple of examples where we can remove CONFIG_ASSERT, see diff below. Please let me know if I should create a new PR or merge it into the commit from this PR (if you prefer to merge the removal of CONFIG_ASSERT from samples, let me know if the title still makes sense for the commit).

It makes sense to remove those occurrences as part of this PR. Either create a new commit dedicated to that, or amend your one commit (editing the commit message).

**Comment by jonaias** [comment]
@tomi-font Done!

**Comment by tomi-font** [comment]
Great! Thanks for that!

**Comment by jonaias** [comment]
@nordicjm @tomi-font I'm Just following up in case I need to do anything else.

**Comment by nordicjm** [comment]
> @nordicjm @tomi-font I'm following up in case I need to do anything else.

Nope, all good, has been merged, thanks!

**Pull request merged**
