### PR TITLE
net: lib: aws_iot: clarify use of topic type

### PR DESCRIPTION
**Pull request by coderbyheart**
This clarifies the use of the `type` property when defining
a topic.

### CODE REVIEW

**Comment by carlescufi** [comment]
@coderbyheart please rebase
@rlubos can you take a look?

**Review by simensrostad — APPROVED** [review]

**Comment by coderbyheart** [comment]
Rebased.

**Review by rlubos — APPROVED** [review]

**Review by jtguggedal — APPROVED** [review]

**Comment by coderbyheart** [comment]
Rebased and squash. Ready to merge.

**Review by umapraseeda — APPROVED** [review]

**Comment by coderbyheart** [comment]
Rebased again.

**Pull request merged**
