### PR TITLE
applications: nrf_desktop: Use custom private keys for applications

### PR DESCRIPTION
**Pull request by MarekPieta**
Change adds possibility to use custom private key for application.

### CODE REVIEW

**Comment by MarekPieta** [comment]
Renamed to trigger nrf_desktop tests

**Comment by tejlmand** [comment]
@MarekPieta why was the signature key file `CONFIG_BOOT_SIGNATURE_KEY_FILE` added to the `app_ZReleaseMCUBoot.conf` files, and not the `mcuboot_ZReleaseMCUBoot.conf` files ?

This is a MCUBoot setting, not an app setting.

**Comment by MarekPieta** [comment]
Hi @tejlmand
Actually it was added for both application and MCUBoot config files.
The CONFIG_BOOT_SIGNATURE_KEY_FILE from application configuration was previously used to sign the application (if undefined, default value was used). After the f72e0b81620a0a9bc0fe5449dccfddae3495ad57 commit (added after this PR), the CONFIG_BOOT_SIGNATURE_KEY_FILE is defined only in MCUBoot configuration and it's passed to the application build system.

**Comment by tejlmand** [comment]
yes I noticed later.
I think we need to look more into this, cause I see a couple of more flaws in current design.

**Comment by pdunaj** [comment]
Hi @tejlmand , just to provide a justification for the feature.
Application should be considered a source of all the configuration files as it the place of system customization. This is especially important for out-of-tree applications as in such cases keeping any files in bootloader or nrf repo will make application vendor to fork these repositories too only to change these files.

**Pull request merged**
