### PR TITLE
lib: identity_key: Do panic instead of assert

### PR DESCRIPTION
**Pull request by vili-nordic**
In case of failures in the identity key library we want to panic, and not use asserts that can be compiled out.

### CODE REVIEW

**Review by lemrey — DISMISSED** [review]
yeah `assert` is not an error check macro :)
but `k_panic` is not a reasonable behavior in case of errors either. That litelly crashes the application, all of it. You should return an error from this library and let the application decide what is the most sensible thing to do to handle this error instead.

**Comment by vili-nordic** [comment]
> yeah `assert` is not an error check macro :) but `k_panic` is not a reasonable behavior in case of errors either. That litelly crashes the application, all of it. You should return an error from this library and let the application decide what is the most sensible thing to do to handle this error instead.

We will create a follow task up for this. For now, this is just to make implementation consistent with documentation (independent of CONFIG_ASSERT). We also have another library (hw_unique_key) with the same issue.

**Review by Vge0rge — APPROVED** [review]

**Comment by lemrey** [comment]
I removed the -1 but a failure to initialize a library is not a reason to panic the kernel; panicking prevents the application from doing anything, blinking an LED, printing an error message for the user etc. it is the exact opposite of what it should do, trying to fail gracefully.

**Comment by vili-nordic** [comment]
We will look into this later in NCSDK-21839

**Review by frkv — APPROVED** [review]
LGTM

**Pull request merged**
