### PR TITLE
west.yml: update memfault-firmware-sdk

### PR DESCRIPTION
**Pull request by jhn-nordic**
Update memfault-firmware-sdk to version 0.28.2

Signed-off-by: Jon Helge Nistad <jon.helge.nistad@nordicsemi.no>

### CODE REVIEW

**Review by simensrostad — APPROVED** [review]

**Comment by jhn-nordic** [comment]
Removed change log entry label as we have earlier agreed that we should not update changlog on these updates

**Review by jtguggedal — APPROVED** [review]

**Comment by lemrey** [comment]
We need to get rid of references to the `at_cmd` and `at_notif` libraries in `memfault` for this release. There is at least one hit for one of the `at_cmd` Kconfig options.

**Comment by jhn-nordic** [comment]
Added DNM. Will wait for an a new version of the Memfault SDK

**Comment by jhn-nordic** [comment]
@lemrey memfault sdk is now updated

**Pull request merged**
