### PR TITLE
doc: changelog: Add missing changes for NCS 1.9.0 (Protocols scope).

### PR DESCRIPTION
**Pull request by grochu**
- Add note about aligning macro usage in BT samples (as per https://github.com/nrfconnect/sdk-nrf/pull/6441).

### CODE REVIEW

**Review by peknis — APPROVED** [review]

**Comment by kapi-no** [comment]
@grochu, I was thinking about adding a general note about the connection parameters negotiation feature for the BT SMP module, Now I am not sure if we are listing upstream features in NCS release notes as well.

**Comment by grochu** [comment]
> @grochu, I was thinking about adding a general note about the connection parameters negotiation feature for the BT SMP module, Now I am not sure if we are listing upstream features in NCS release notes as well.

No, definitely we should not list any upstream changes in the NCS changelog. I just wanted to mark the DFU speed will improve on Thingy:53. @kapi-no do you have a suggestion where to put such a general note? Did you think of release highlights?

**Comment by grochu** [comment]
I removed the entries related to adapting the BT SMP configuration in the samples for Thingy:53 as the original update was done in sdk-zephyr.

**Review by kapi-no — APPROVED** [review]

**Comment by grochu** [comment]
Will be fixed as part of https://github.com/nrfconnect/sdk-nrf/pull/6812

**Pull request closed without merging**
