### PR TITLE
Production support for AoA

### PR DESCRIPTION
**Pull request by yuxCai**

### CODE REVIEW

**Comment by shantha-14** [comment]
removed 2.0.0 milestone, too late to get in.

**Comment by Tschet1** [comment]
@shantha-14 Why is it too late to get in? We have until 14:00 today.

**Review by Tschet1 — APPROVED** [review]

**Review by olavst-nordic — APPROVED** [review]

**Review by b-gent — APPROVED** [review]

**Comment by Tschet1** [comment]
Discussed with @b-gent and readded the 2.0.0 milestone.

**Comment by Tschet1** [comment]
CI failure is known instability and passes on rerun: https://jenkins-ncs.nordicsemi.no/blue/organizations/jenkins/latest%2Fsub%2Ftest-sdk-homekit/detail/master/4776/tests

**Pull request merged**
