### PR TITLE
doc: wifi: update memory footprint table

### PR DESCRIPTION
**Pull request by richabp**
Updated the memory footprint table with the latest values.

### CODE REVIEW

**Comment by ioannisg** [comment]
@krish2718  I wonder if we should just wait for this until the scan-only patch PR is merged (assuming this would lower the ROM numbers)

**Comment by krish2718** [comment]
> @krish2718 I wonder if we should just wait for this until the scan-only patch PR is merged (assuming this would lower the ROM numbers)

Its merged today :).

**Comment by krish2718** [comment]
@richabp can you please rebase this PR and re-run the CI as well?

**Comment by ioannisg** [comment]
> > @krish2718 I wonder if we should just wait for this until the scan-only patch PR is merged (assuming this would lower the ROM numbers)
> 
> Its merged today :).

So confirming the scan-only ROM numbers are updated with the scan-only patch size?

**Comment by krish2718** [comment]
> > > @krish2718 I wonder if we should just wait for this until the scan-only patch PR is merged (assuming this would lower the ROM numbers)
> > 
> > 
> > Its merged today :).
> 
> So confirming the scan-only ROM numbers are updated with the scan-only patch size?

Yup, the diff shows 76->36, 40K reduction.

**Review by krish2718 — APPROVED** [review]

**Review by visinor — APPROVED** [review]

**Review by kittydepa — APPROVED** [review]

**Pull request merged**
