### PR TITLE
Nrf security mbedtls 3.0.0

### PR DESCRIPTION
**Pull request by SebastianBoe**

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
What is this?

**Comment by SebastianBoe** [comment]
@mbolivar-nordic : WIP support for mbedtls 3.0.0 in nrf_security, will be merged to the upmerge branch when it is greener than the upmerge branch.

**Comment by SebastianBoe** [comment]
@mbolivar-nordic : I see I targeted the main branch. That was an accident.

**Comment by SebastianBoe** [comment]
These patches are now merged to the upmerge branch, making this PR unnecessary.

**Pull request closed without merging**
