### PR TITLE
samples: nrf9160: pdn: Add NEWLIBC

### PR DESCRIPTION
**Pull request by trond-snekvik**
Adds NEWLIBC to prj.conf to resolve new dependency for AT_CMD_PARSER.

Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Review by lemrey — APPROVED** [review]
Ok, to get CI green again.

But @rlubos @simensrostad we should look again at 4eaab481ef35ea3a9d33322727bfb13d5b01e227 which introduced this dependency for all users of the `at_cmd_parser`, which through the `lte_lc` are almost all samples under `samples/nrf9160`. I argue we should have rather `#ifdef`-ed the functionality that depends on `newlibc` and enabled as necessary, per sample. Forcing a C library is not desirable and not necessary; we should avoid it.

**Comment by rlubos** [comment]
@lemrey That'd be some nasty `#ifdef`ing to be honest given that we'd need to keep in mind not only `at_cmd_parser`, but also `lte_lc` which makes use of the 64-bit integer (and all of the potential users). 

IMO we should rather strive for adding the missing `strtoll()` implementation to the minimal libc, which would allow to remove the dependency.

**Comment by lemrey** [comment]
That sounds good to me, if it saves us the `#ifdef` fiesta. The goal should be to remove the C library requirement that we introduced for the samples.

**Comment by simensrostad** [comment]
@lemrey @rlubos It's definitely not ideal. I think adding it to minimal lib c is probably the best choice. I suspected that there would be some forehead wrinkles when I added https://github.com/nrfconnect/sdk-nrf/commit/4eaab481ef35ea3a9d33322727bfb13d5b01e227 but I didn't see any clear way around it without inferring some sort of hack. The current implementation of the ```at_cmd_parser``` uses ```strtoll``` for all instances where an integer is parsed from an AT response into an AT param list, agnostic of the integer size. This is used quite frequently in the link controller and AT-related libraries/samples. I would preferably not partake in any ```#ifdef``` fiesta 🎉🎉.

**Pull request merged**
