### PR TITLE
Followup on PR-17502

### PR DESCRIPTION
**Pull request by rghaddab**
This PR fixes some comments raised in this merged PR:
https://github.com/nrfconnect/sdk-nrf/pull/17502

### CODE REVIEW

**Review by ArekBalysNordic — APPROVED** [review]
Thanks!

**Comment by rghaddab** [comment]
@nordicjm @tejlmand can you approve this PR ?

**Comment by tomi-font** [comment]
@rghaddab You're not meant to touch the DNM label that was set by the bot. It's removed automatically when the manifest file doesn't point to a PR anymore.

**Comment by rghaddab** [comment]
> @rghaddab You're not meant to touch the DNM label that was set by the bot. It's removed automatically when the manifest file doesn't point to a PR anymore.

You are right, I forgot that this PR has a change in the manifest file.
Let's wait until this PR gets merged : https://github.com/nrfconnect/sdk-connectedhomeip/pull/496

**Review by nordicjm — APPROVED** [review]

**Comment by rghaddab** [comment]
@maje-emb  @ppryga-nordic can you approve this PR on behalf of muffin and dragoon teams ?

**Comment by rghaddab** [comment]
@nrfconnect/ncs-si-muffin @nrfconnect/ncs-dragoon  can I get some help to merge this PR ?

**Review by hermabe — APPROVED** [review]
Again, dragoon doesnt own these samples, but LGTM

**Review by dchat-nordic — APPROVED** [review]

**Pull request merged**
