### PR TITLE
Add options_from_kconfig Sphinx extension

### PR DESCRIPTION
**Pull request by utzig**
Add new Sphinx directive that can be used to automatically extract options from a Kconfig file and populate a README file. Its purpose is to prevent options between README and Kconfig to get out of sync.

To automatically extract options from a Kconfig file add:

```
.. options-from-kconfig: <optional-path>
   :prefix: "This option "
   :suffix: .
   :only-visible:
   :show-type:
```

Where:

* <optional-path> if provided will use Sphinx rules for path search, if not provided this extension will look for Kconfig in the same directory as the source rST file (normalized to NRF_BASE).
* `prefix` and `suffix` are optional text that can be enclosed in `"` or `'` characters to avoid stripping spaces. When prefix is given the help text from Kconfig will be de-capitalized.
* `only-visible` will not show config options that have visibility set to "n". This is optional and by default all options are shown.
* `show-type` will prepend a literal type, eg, `(string) ` to the text output. It is optional and the type will be added before `prefix`.

JIRA: NCSDK-6295

### CODE REVIEW

**Comment by utzig** [comment]
The current output for `samples/nrf9160/cloud_client/README.html` looks like this:

options_from_kconfig

**Comment by ru-fu** [comment]
I think that is really nice - of course it's not anything that we can just introduce in all samples with a search and replace, but it would need to be included when we create or update the documentation for a sample. And it might not be needed for every sample, but we would need to decide for each sample whether it makes sense to use it or not.

@umapraseeda @simensrostad You originally brought this up, what do you think?
@greg-fer @pdunaj I think you wanted something similar for nRF Desktop a while ago?

**Comment by simensrostad** [comment]
> I think that is really nice - of course it's not anything that we can just introduce in all samples with a search and replace, but it would need to be included when we create or update the documentation for a sample. And it might not be needed for every sample, but we would need to decide for each sample whether it makes sense to use it or not.
> 
> @umapraseeda @simensrostad You originally brought this up, what do you think?
> @greg-fer @pdunaj I think you wanted something similar for nRF Desktop a while ago?

Fantastic!

**Comment by umapraseeda** [comment]
> I think that is really nice - of course it's not anything that we can just introduce in all samples with a search and replace, but it would need to be included when we create or update the documentation for a sample. And it might not be needed for every sample, but we would need to decide for each sample whether it makes sense to use it or not.
> 
> @umapraseeda @simensrostad You originally brought this up, what do you think?
> @greg-fer @pdunaj I think you wanted something similar for nRF Desktop a while ago?
Great! Thanks!

**Review by carlescufi — APPROVED** [review]
Very nice. I'd like @ru-fu to test and approve before merging.

**Comment by simensrostad** [comment]
```aws_iot```, ```udp``` and possibly other samples also has unhinged configuration sections in the ```README.rst``` Those should be updated as well.

**Comment by utzig** [comment]
> `aws_iot`, `udp` and possibly other samples also has this unhinged configuration section in the `README.rst` Those should be updated as well.

By "unhinged configuration section" you mean something like this: http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/nrf9160/udp/README.html#configuration ?

Where you click the option and jump 30 px down? :-) I had not seen this but should be very easy to add an extra option to produce it.

**Comment by simensrostad** [comment]
> > `aws_iot`, `udp` and possibly other samples also has this unhinged configuration section in the `README.rst` Those should be updated as well.
> 
> By "unhinged configuration section" you mean something like this: http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/nrf9160/udp/README.html#configuration ?
> 
> Where you click the option and jump 30 px down? :-) I had not seen this but should be very easy to add an extra option to produce it.

Yes, that's a good idea too. But I meant more like doing the same changes to those samples the same way it is done in the cloud_client sample in this PR.

**Comment by utzig** [comment]
> Yes, that's a good idea too. But I meant more like doing the same changes to those samples the same way it is done in the `cloud_client` sample in this PR. So that the `README.rst` points to kconfig.

I see, that's why I added the RFC label, it is not just metadata that changes in README.rst files. The phrasing of the options has to be reworked to read appropriately both in a config menu and in the final documentation, which is why it seemed wasteful to go and re-phrase everything, before I gathered some feedback, but I can do.

**Comment by ru-fu** [comment]
I would keep the updates to the existing samples out of this PR. Let's get the functionality in first and then update the samples as we work on them. It's not a straight-forward search&replace but needs some work.

Also, I don't think we need the list of options. We've updated the sample template a bit ago, and it doesn't have the list, so no need to add it.

I'll do some testing, but didn't get to it yet. Functionality-wise I think we have what we need. :)

**Review by ru-fu — APPROVED** [review]
I tested it on another sample and it worked fine (but would need some work on the Kconfig files of course to make the output look okay).

I also added a commit that updates the sample template. I think for now we should keep it optional to use this extension.

**Review by tejlmand — APPROVED** [review]

**Comment by greg-fer** [comment]
This looks great, and the feature is a useful improvement.
Two questions:

- Can this be used for samples only or also for other NCS features, say libraries?
- Given the purpose to prevent options between README and Kconfig to get out of sync, is there any tracing of options that are out of sync? If not, can it be implemented in a second iteration?

**Review by simensrostad — APPROVED** [review]

**Pull request merged**
