### PR TITLE
manifest: update nrfxlib for MPSL and SoftDevice controller

### PR DESCRIPTION
**Pull request by kromancer**
Highlights:
- Fixes [known-issue DRGN-15064 for MPSL](http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/known_issues.html#multiprotocol-service-layer-mpsl)
- MPSL will now respect `CONFIG_SYSTEM_CLOCK_NO_WAIT`
- Adds new signal in MPSL timeslot: `MPSL_TIMESLOT_SIGNAL_OVERSTAYED`
- Fixes build error for nrf52dk_nrf52805

### CODE REVIEW

**Review by rugeGerritsen — APPROVED** [review]
You could consider adding MPSL_TIMESLOT_SIGNAL_OVERSTAYED to flash_sync_mpsl.c and samples/mpsl/timeslot

**Review by hurricaneFromMoscow — APPROVED** [review]

**Review by MarekPieta — APPROVED** [review]
I verified that the change fixes reported issue.

**Comment by kromancer** [comment]
Re-based on ncs/master

**Comment by kromancer** [comment]
Re-based on master

**Comment by kromancer** [comment]
Updated sha

**Review by joerchan — APPROVED** [review]
Checked SHA.

**Pull request merged**
