### PR TITLE
typo: Fix typo in download_client

### PR DESCRIPTION
**Pull request by kamnxt**
Finnished -> finished

### CODE REVIEW

**Comment by rlubos** [comment]
Hello @kamnxt, the commit message should follow the commit guidelines: https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines
i.e the  signoff entry is missing. Also, please use `net: lib: download_client: ` prefix for the commit title.

**Review by SeppoTakalo — APPROVED** [review]
Change is OK, but please fix the commit message to follow the guidelines.

**Comment by kamnxt** [comment]
Fixed the commit message.

**Comment by rlubos** [comment]
@kamnxt The compliance failed on author verification, it seems that `ż` used in the signoff entry might be the issue here.

> 610702f80dda80c23a894cb1f9e353c0bd8b932d: author email (Kamil Krzyzanowski <kamnxt@kamnxt.com>) needs to match one of the signed-off-by entries.

**Comment by kamnxt** [comment]
:facepalm: should be done now, sorry for wasting your time

**Review by lemrey — APPROVED** [review]
It was a typo, but it does change the event name which is part of the API.
What kind of policy should we use for the changelog in this case, @rlubos ?

**Comment by SeppoTakalo** [comment]
> It was a typo, but it does change the event name which is part of the API. What kind of policy should we use for the changelog in this case, @rlubos ?

No it is not an event.
This is an internal and undocumented `state` variable inside `struct download_client`.

To be fair, whole structure should have been inside `/** @cond INTERNAL_HIDDEN */` but that is not part of this PR.

**Comment by rlubos** [comment]
I agree with @SeppoTakalo on this, let's not overcomplicate this.

**Review by rlubos — APPROVED** [review]

**Comment by lemrey** [comment]
Right, my bad! Good to go then.

**Pull request merged**
