### PR TITLE
samples: wifi: provisioning: use wifi_credentials library

### PR DESCRIPTION
**Pull request by maxd-nordic**
This patch makes the wifi_provisioning sample use the wifi_credentials library to store the provisioned network.
    
Signed-off-by: Maximilian Deubel <maximilian.deubel@nordicsemi.no>

Depends on another PR: https://github.com/nrfconnect/sdk-nrf/pull/9007

### CODE REVIEW

**Comment by maxd-nordic** [comment]
There are some open questions for me here:
* should we store the network channel as supported by the app? (could be too volatile)
* what would be a good way to handle bands (possibly using flags?)
* should the provisioning sample support multiple setting slots like `wifi_credentials`?

Also, I noticed that the password field in the Android app is just a text field (I can now auto-complete the password :P)

**Comment by wentong-li** [comment]
It seems that wifi subsystem cannot build on non-secure target at this moment.

**Comment by bama-nordic** [comment]
Some of the changes in this PR break some system level design aspects of the Provisioning application. I will schedule a review with the authors/designers of this sample to resolve this and then we move forward.

**Comment by wentong-li** [comment]
Hi @maxd-nordic , can you rebase the PR? Thanks.

**Pull request closed without merging**
