### PR TITLE
homekit: add west documentation

### PR DESCRIPTION
**Pull request by ktaborowski**
KRKNWK-9428
Add documentation on how to install NCS, including the HomeKit add-on.

Signed-off-by: Krzysztof Taborowski <krzysztof.taborowski@nordicsemi.no>

### CODE REVIEW

**Review by RobertGalatNordic — APPROVED** [review]
ok, the revision points to correct pull request in HK

**Review by tejlmand — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@ktaborowski homekit CI is failing

**Comment by ktaborowski** [comment]
> @ktaborowski homekit CI is failing

It fails a few times, but it finally passed

**Comment by carlescufi** [comment]
> > @ktaborowski homekit CI is failing
> 
> It fails a few times, but it finally passed

Can you point me to it?

**Comment by ktaborowski** [comment]
> > > @ktaborowski homekit CI is failing
> > 
> > 
> > It fails a few times, but it finally passed
> 
> Can you point me to it?

https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-sdk-homekit/job/master/430/
https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-4198/15/

**Comment by ktaborowski** [comment]
> @ktaborowski homekit CI is failing

Now CI is failing generally, I rises ci-help Ticket# 32434

**Comment by RobertGalatNordic** [comment]
This change is already included in https://github.com/nrfconnect/sdk-nrf/pull/4350

**Comment by ktaborowski** [comment]
Included in https://github.com/nrfconnect/sdk-nrf/pull/4350

**Pull request closed without merging**
