### PR TITLE
manifest: Update reference to Pelion client repository

### PR DESCRIPTION
**Pull request by pdunaj**
Move to tag 4.9.

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by rakons** [comment]
Side note - After updating I am still able to block stopwatch - so it does not fix a problem that is referenced in #4608.

**Review by rakons — APPROVED** [review]

**Review by emob-nordic — APPROVED** [review]
The doc generation issue will be fixed once uppon the upmerge lands in the repo.
Exact commit fixing that  issue: https://github.com/nrfconnect/sdk-zephyr/pull/518/commits/827d1652ac2fd28fcb9d5b3787bf7b38c66da14a

**Comment by pdunaj** [comment]
Hi @emob-nordic , make sure this enters the repo once upmerge is done. Thanks :)

**Comment by emob-nordic** [comment]
Rebased at recent master after the upmerged landed in. Waiting for CI to merge.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
