### PR TITLE
partition_manager: Add generated alignment partitions to parent spans

### PR DESCRIPTION
**Pull request by jonathannilsen**
When an empty partition is created to fulfill an alignment requirement,
it is not added to the span of the partition being aligned.

This commit adds the empty partitions to any spans
that contain the partition being aligned, as long as it doesn't
change the size or start/end addresses of the span.

Ref: NCSDK-3997

Signed-off-by: Jonathan Nilsen <Jonathan.Nilsen@nordicsemi.no>

### CODE REVIEW

**Review by oyvindronningstad — COMMENTED** [review]
Looks good, but I'm wondering if we should spend the effort to not add the empty partition to spans if it's at the start or end of the span. Thoughts, @hakonfam?

**Comment by hakonfam** [comment]
> Looks good, but I'm wondering if we should spend the effort to not add the empty partition to spans if it's at the start or end of the span. Thoughts, @hakonfam?

I'm not sure I understand what you mean. Why would you not want to do that?

**Comment by oyvindronningstad** [comment]
> 
> 
> > Looks good, but I'm wondering if we should spend the effort to not add the empty partition to spans if it's at the start or end of the span. Thoughts, @hakonfam?
> 
> I'm not sure I understand what you mean. Why would you not want to do that?

Because it messes with the start address and size of the container partition. Say you align SPM on 32k, and add a container partition "mcuboot_primary_spm" that contains spm. Now, suddenly the mcuboot_primary_spm partition doesn't start at the same place as SPM even though that's the "only" thing it contains.

**Comment by hakonfam** [comment]
> > > Looks good, but I'm wondering if we should spend the effort to not add the empty partition to spans if it's at the start or end of the span. Thoughts, @hakonfam?
> > 
> > 
> > I'm not sure I understand what you mean. Why would you not want to do that?
> 
> Because it messes with the start address and size of the container partition. Say you align SPM on 32k, and add a container partition "mcuboot_primary_spm" that contains spm. Now, suddenly the mcuboot_primary_spm partition doesn't start at the same place as SPM even though that's the "only" thing it contains.

Makes sense, do you agree @jonathannilsen ?

**Comment by jonathannilsen** [comment]
> > > > Looks good, but I'm wondering if we should spend the effort to not add the empty partition to spans if it's at the start or end of the span. Thoughts, @hakonfam?
> > > 
> > > 
> > > I'm not sure I understand what you mean. Why would you not want to do that?
> > 
> > 
> > Because it messes with the start address and size of the container partition. Say you align SPM on 32k, and add a container partition "mcuboot_primary_spm" that contains spm. Now, suddenly the mcuboot_primary_spm partition doesn't start at the same place as SPM even though that's the "only" thing it contains.
> 
> Makes sense, do you agree @jonathannilsen ?

Yeah, I can make that change. I can update it so that an empty partition at the start/end of a span is moved up to the first ancestor span where it is not at the start/end.

**Comment by oyvindronningstad** [comment]
> 
> 
> > > > > Looks good, but I'm wondering if we should spend the effort to not add the empty partition to spans if it's at the start or end of the span. Thoughts, @hakonfam?
> > > > 
> > > > 
> > > > I'm not sure I understand what you mean. Why would you not want to do that?
> > > 
> > > 
> > > Because it messes with the start address and size of the container partition. Say you align SPM on 32k, and add a container partition "mcuboot_primary_spm" that contains spm. Now, suddenly the mcuboot_primary_spm partition doesn't start at the same place as SPM even though that's the "only" thing it contains.
> > 
> > 
> > Makes sense, do you agree @jonathannilsen ?
> 
> Yeah, I can make that change. I can update it so that an empty partition at the start/end of a span is moved up to the first ancestor span where it is not at the start/end.

Perfect!

**Comment by jonathannilsen** [comment]
Closing since, after reviewing it, I'm not sure what difference this change will make

**Pull request closed without merging**
