### PR TITLE
applications: nrf5340_audio: refactor tone

### PR DESCRIPTION
**Pull request by koffes**
Tone module moved

Signed-off-by: Kristoffer Rist Skøien <kristoffer.skoien@nordicsemi.no>

### CODE REVIEW

**Review by rick1082 — APPROVED** [review]

**Review by alexsven — APPROVED** [review]
Unit test is failing and the two commits should be squashed.
Beside from that, approved

**Review by greg-fer — APPROVED** [review]
Approving, but please check my edits and squash my PR.

**Review by gopiotr — COMMENTED** [review]
Please add to this PR commit with entry into CODEOWNERS file (https://github.com/nrfconnect/sdk-nrf/blob/main/CODEOWNERS) with path to test `/tests/lib/tone/` and person/people responsible for this test.

**Review by gopiotr — APPROVED** [review]

**Comment by greg-fer** [comment]
Please remember to either remove the changelog label or add a changelog entry about the new library being added to the NCS.

**Pull request merged**
