### PR TITLE
tests: asset_tracker_v2: change tests location

### PR DESCRIPTION
**Pull request by gopiotr**
To maintain some standardization in `sdk-nrf` project I suggest to move `asset_tracker_v2` tests to dedicated directory in `tests\` folder. 

I face with a problem that together with @karhama we're trying to establish building of `sdk-nrf` applications and samples on Windows in CI. Tests from `applications/asset_tracker_v2/tests` directory are written with Unity test framework which demands installed `ruby` package. This one is not available on Windows toolchain and due to that fact this tests cannot be built with this toolchain. @karhama tried to add this package to toolchain in this PR: https://github.com/nrfconnect/sdk-nrf/pull/6382 but most of codeowners said that this package is used only for inside tests and shouldn't be part of official toolchain. 

So I came to the conclusion that perhaps some kind of solution for this problem is just moving those tests to right place because they are not samples.

I am open for discussion - if you have other idea to solve this problem please write about it.

### CODE REVIEW

**Comment by coderbyheart** [comment]
My 2 øre are that these tests are not *internal*, they are equally part of the application sample as the implementation itself. Tests are an essential part of every software development project so IMHO we absolutely must educate and enable our users to use the tests for their own development. Therefore, toolchain should provide the neccessary dependencies, if possible as an optional add-on because not all users are using the `asset_tracker_v2` application.

**Review by jhn-nordic — CHANGES_REQUESTED** [review]
I agree with @coderbyheart here. We bundle application specific tests together with the application specific code. When customers make an out of tree setup based on asset_tracker_v2 for as base for  developing their own application tests should follow. 
Moving the tests is not an option as we see it.

**Comment by gregersrygg** [comment]
@gopiotr I read through the comments on #6382 now, and I think there's a misunderstanding. They have approved it, but added a DNM tag - probably because it was right before a release. So I think you can ask them if it can be merged now.

**Comment by balaji-nordic** [comment]
> @karhama tried to add this package to toolchain in this PR: https://github.com/nrfconnect/sdk-nrf/pull/6382 but most of codeowners said that this package is used only for inside tests and shouldn't be part of official toolchain.

I dont think the code owners opposed it. I think it is worth to add ruby to the tool chain. Unit tests are important for customers as well and they should be able to run them

**Review by balaji-nordic — CHANGES_REQUESTED** [review]
I request you to reconsider this and push for getting ruby into our tool chain instead. You can get my support in the other PR if need be

**Comment by balaji-nordic** [comment]
https://github.com/nrfconnect/sdk-nrf/pull/6382 is now merged. This makes ruby part of the toolchain. Hence this PR can be closed.

**Comment by gopiotr** [comment]
@coderbyheart @jhn-nordic 

To be clear - I totally agree, that tests are fundamental part of every project (I work as a tester) and I do not want to limit our clients' access to the tests. I just wondering if `application/` directory is right place to them when we have dedicated folder for such stuff in `tests\` directory. 

Our source tree structure base mostly on Zephyr source tree and there are simply division, that programs which contain `testcase.yaml` file are placed in `tests\` folder, and programs with `sample.yaml` file are placed in `samples\` directory to make easier to tell what is sample and what is test.

The next reason of my proposition is that `asset_tracker_v2` application is only one among all applications and samples with dedicated `tests` folder inside them. I think that reasonable solution is proposed in `cryptography` sample, where tests are placed in `tests\` directory, but to make it more accessible for users, there is dedicated entry in documentation, which explains where they are placed and how to run them:
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/tests/crypto/README.html

But this is only my opinion and especially after merging this PR with `Add ruby as requirement` I will close this PR. Thank you for your feedback :)

**Comment by gopiotr** [comment]
> When customers make an out of tree setup based on asset_tracker_v2 as base for developing their own application tests should follow.

@jhn-nordic - But are you aware that those tests from `applications/asset_tracker_v2/tests` cannot be simply made "out of tree", because they base strongly on Unity defined in `tests/unity`? Due to the fact that this tests have `CONFIG_UNITY` option set as `y` they use code defined in `tests/unity` folder.

**Pull request closed without merging**
