### PR TITLE
doc: Move Thingy:53 under application development

### PR DESCRIPTION
**Pull request by divipillai**
Moved Thingy:53 under application development.

NCSDK-29643

### CODE REVIEW

**Review by greg-fer — APPROVED** [review]
Should thingy53_application_guide.rst be split into several pages?

**Comment by divipillai** [comment]
> Should thingy53_application_guide.rst be split into several pages?

The reason for not splitting it into several pages was because some of the sections are too small to convert it into a subpage and were not able to merge with other sections. We can still see the section heading on the container page - 
https://ncsdoc.z6.web.core.windows.net/PR-19390/nrf/app_dev/device_guides/thingy53/index.html#developing-with-thingy-53.
Would that be sufficient?

**Review by gmarull — APPROVED** [review]

**Review by umapraseeda — APPROVED** [review]
Missing changelog entry or may be it is getting added in the release notes directly?

**Comment by divipillai** [comment]
> Missing changelog entry or may be it is getting added in the release notes directly?

Plan to add a comment on Pekka's PR after this PR is merged.

**Pull request merged**
