### PR TITLE
west.yml: Update zephyr revision 

### PR DESCRIPTION
**Pull request by LundinJohan**
Signed-off-by: Johan Lundin <johan.lundin@nordicsemi.no>

### CODE REVIEW

**Comment by LundinJohan** [comment]
The failing checks seem unrelated to my change in pull/663. Can we move forward with this?

**Comment by tejlmand** [comment]
> The failing checks seem unrelated to my change in pull/663. Can we move forward with this?

you should rebase: https://github.com/nrfconnect/sdk-zephyr/pull/663
The failing check is because CI will automatically rebase this PR on top of `sdk-nrf/main` but doesn't rebase your `sdk-zephyr` PR#663 where the referenced PR is taken as-is.
PR^663 is missing this commit: https://github.com/nrfconnect/sdk-zephyr/commit/e7af53ea7775f253b4e44c3bd7b2dc3c7f12efe1

**Comment by nvlsianpu** [comment]
Pleas rebase

**Review by rugeGerritsen — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
superseded by https://github.com/nrfconnect/sdk-nrf/pull/6313

**Pull request closed without merging**
