### PR TITLE
Cleanup porting to new AT interface

### PR DESCRIPTION
**Pull request by eivindj-nordic**
Cleanup leftovers after porting to new AT interface. 
@lemrey, @MirkoCovizzi and codeowners: Please verify that I have not removed anything that is intended to keep.  

[DNM]: Do not merge until modem_shell, sms and lwm2m carrier libraries have been updated.

### CODE REVIEW

**Review by coderbyheart — APPROVED** [review]

**Review by jtguggedal — APPROVED** [review]

**Review by divipillai — APPROVED** [review]

**Review by SeppoTakalo — APPROVED** [review]

**Review by lemrey — COMMENTED** [review]
Nice

**Review by simensrostad — APPROVED** [review]

**Comment by lemrey** [comment]
I think 568be2f can be dropped since https://github.com/nrfconnect/sdk-nrf/pull/6573 has the same change.
This has also tech-writer approval, so I would remove the `DNM` label and prefix, drop that commit and re-spin CI @eivindj-nordic

**Comment by eivindj-nordic** [comment]
> I think [568be2f](https://github.com/nrfconnect/sdk-nrf/commit/568be2f5472110b00e655cc3b562bc8fdf97955e) can be dropped since #6573 has the same change. This has also tech-writer approval, so I would remove the `DNM` label and prefix, drop that commit and re-spin CI @eivindj-nordic

That is correct, so I dropped that commit now. I can remove the DNM label. However, I expect it to fail in CI until #6363 is merged.

**Comment by lemrey** [comment]
@eivindj-nordic could you try giving this a rebase please?

**Comment by eivindj-nordic** [comment]
Closing this as the changes are included in #6699.

**Pull request closed without merging**
