### PR TITLE
doc: Update doc versions for 2.8.0 release

### PR DESCRIPTION
**Pull request by richabp**
Updated doc versions for 2.8.0 release.
NCSDK-29831

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Comment by gmarull** [comment]
> @shanthanordic / @carlescufi / @gmarull - Please confirm if we need the version updates for Matter, TF-M, and MCUboot.

Owners of these modules should tell.

**Review by LuDuda — COMMENTED** [review]
Matter revision is the same for 2.8.0 - Matter 1.3 (it will be changed in NCS 2.9.0).

We will have a Thread 1.4 though in NCS 2.8.0.

**Comment by richabp** [comment]
@nvlsianpu Please confirm if we need the version updates for MCUboot.

**Comment by maciejbaczmanski** [comment]
@richabp we will  need to update thread version to 1.4 in few places. will create a PR in few minutes

**Comment by nvlsianpu** [comment]
MCUboot version is 2.1.99

**Comment by richabp** [comment]
> MCUboot version is 2.1.99

Added.

**Review by greg-fer — APPROVED** [review]

**Review by divipillai — APPROVED** [review]

**Review by b-gent — APPROVED** [review]

**Review by peknis — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Review by umapraseeda — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by frkv — APPROVED** [review]
I don't think TF-M use the x.y.99 versioning, standardisation constructed by Zephyr.

"TF-M v2.1.0 with patches" is the most accurate representation, but this is only possible using a .99 scheme.

I am fine with 2.1.0 for NCS 2.8.0

**Pull request merged**
