### PR TITLE
openthread: Use HW mutex lock for CC312 backend in nrf_security

### PR DESCRIPTION
**Pull request by lmaciejonczyk**
Hardware mutex lock is the fastest way for exclusive access to
the ARM CryptoCell on platform which supports it.

### CODE REVIEW

**Comment by tejlmand** [comment]
Please update sha: 0c7b0c58721359c1feb3f495d926eeb6c6bca0ea

**Review by MarekPorwisz — APPROVED** [review]
change looks good. SHA to be updated

**Review by edmont — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]
SHA verified.
Please rebase.

**Comment by lmaciejonczyk** [comment]
Opss missing define. This https://github.com/nrfconnect/sdk-nrfxlib/pull/386 should be merged first it fixes the regression.

**Comment by tejlmand** [comment]
Please update SHA: 70994a63a43f8738acab62123b0e180505ee0443

**Pull request merged**
