### PR TITLE
drivers: gps: fix gps_agps_type values

### PR DESCRIPTION
**Pull request by JanErikFoss**
Fixes wrong AGPS data type values.

Painfully debugged and tested with GPS driver and SUPL library.

### CODE REVIEW

**Comment by jtguggedal** [comment]
Thanks for your contribution, @JanErikFoss!
Could you sign the CLA and amend the commit to add a signed-off entry?
`git commit --amend --signoff`

The changes look good, although I'm not sure why we specified the enum values in the first place.
Note that the values of various enums and constants in the GPS API can't be trusted to align with the ones found in `nrf_socket.h`, which I suspect was the issue that you ran into. An example of translation between the two can be seen here:
https://github.com/nrfconnect/sdk-nrf/blob/2a432dd330db255f409ec148882eea3acb53c534/subsys/net/lib/nrf_cloud/src/nrf_cloud_agps.c#L29

**Comment by JanErikFoss** [comment]
I've ammended the commit and force pushed, I hope that was the correct way to do it.

Actually the lookup function was where I encountered an error.
That function uses the values I changed in this commit, and since they previously didn't match it would return type 0 when given type 6.

**Comment by jtguggedal** [comment]
> I've ammended the commit and force pushed, I hope that was the correct way to do it.
> 
> I actually encountered my error in the lookup function _type_lookup_gps2socket_ found in nrf9160_gps.c, when calling _agps_write_.
> That function uses the values I changed in this commit, and since they previously didn't match the incoming data from SUPL sessions it would return type 0 when given type 6 and the SUPL session would throw an error.

@JanErikFoss Thanks for the changes. Just one more thing, the commit message must contain a message body describing the patch so that the structure is like this:
```
<commit tag><subject line>
<empty line>
<commit message body>
<empty line>
<Signed-off-by line(s)>
```

Thanks for the explanations on what happened. I assume you used `gps_agps_write(...)` when injecting the assistance data received from SUPL? That function would require the use of the lookup table I linked to above first, to convert from nrf_socket format which SUPL uses to the GPS API format. With your changes this now works as expected without the conversion prior to calling `gps_agps_write(...)`, but it would fail again in the (probably unlikely, but who knows) event of more changes to the enum in the GPS API.

**Comment by rlubos** [comment]
@JanErikFoss Could you please rebase your PR?

**Pull request closed without merging**
