### PR TITLE
manifest: ipc: use highest coop priority for IPM workqueue

### PR DESCRIPTION
**Pull request by ankuns**
Signed-off-by: Andrzej Kuroś <andrzej.kuros@nordicsemi.no>

### CODE REVIEW

**Comment by ankuns** [comment]
pushed amend to trigger CI again. No code changes.

**Review by hubertmis — COMMENTED** [review]
I have some concerns described in https://github.com/zephyrproject-rtos/zephyr/pull/40623

But I'm not blocking this PR, because I understand it includes a workaround required for the next release.

My only comment is that we are taking technical debt here that I believe we should pay soon.

**Comment by ankuns** [comment]
One downstream job passed after rerun.

**Comment by ankuns** [comment]
rebased on `main`

**Review by carlocaione — APPROVED** [review]
ACK but this will be moved to Kconfig as discussed upstream

**Review by hubertmis — APPROVED** [review]
Approving with hope the debt will be paid soon

**Review by carlescufi — APPROVED** [review]

**Comment by nvlsianpu** [comment]
I'm awaiting on CI result of https://github.com/nrfconnect/sdk-nrf/pull/6169 (It introdces newer SHA) before merging this.

**Comment by nvlsianpu** [comment]
superseded by #6156 as it references newer sdk-zephyr SHA

**Pull request closed without merging**
