### PR TITLE
samples: nrf9160: shutdown when finished

### PR DESCRIPTION
**Pull request by lemrey**
Shutdown the modem library to put the modem in CFUN0.
There might be other samples that "finish", haven't looked too closely; can add more commits.

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Comment by MirkoCovizzi** [comment]
This is a grep of nrf_modem_lib_init inside the samples/nrf9160 directory:

`fmfu_smp_svr/src/main.c
19:     int err = nrf_modem_lib_init(NORMAL_MODE);
44:     nrf_modem_lib_init(FULL_DFU_MODE);

modem_shell/src/shell.c
46:extern struct k_sem nrf_modem_lib_initialized;
122:            k_sem_give(&nrf_modem_lib_initialized);

modem_shell/src/main.c
64:K_SEM_DEFINE(nrf_modem_lib_initialized, 0, 1);
120:    err = nrf_modem_lib_init(NORMAL_MODE);
155:    k_sem_take(&nrf_modem_lib_initialized, K_FOREVER);

at_monitor/src/main.c
124:    err = nrf_modem_lib_init(NORMAL_MODE);

download/src/main.c
197:    err = nrf_modem_lib_init(NORMAL_MODE);

azure_fota/src/main.c
207:    err = nrf_modem_lib_init(NORMAL_MODE);

aws_fota/src/main.c
415:    err = nrf_modem_lib_init(NORMAL_MODE);

aws_iot/src/main.c
418:    err = nrf_modem_lib_init(NORMAL_MODE);

http_update/full_modem_update/src/main.c
69:     err = nrf_modem_lib_init(FULL_DFU_MODE);
71:             printk("nrf_modem_lib_init(FULL_DFU_MODE) failed: %d\n", err);
87:     err = nrf_modem_lib_init(NORMAL_MODE);
89:             printk("nrf_modem_lib_init() failed: %d\n", err);
193:    err = nrf_modem_lib_init(NORMAL_MODE);

http_update/common/src/update.c
161:    /* Initialize AT only if nrf_modem_lib_init() is manually

http_update/modem_delta_update/src/main.c
105:    err = nrf_modem_lib_init(NORMAL_MODE);
108:     * fetch the returned error code instead of nrf_modem_lib_init

http_update/application_update/src/main.c
54:     err = nrf_modem_lib_init(NORMAL_MODE);

https_client/src/main.c
158:    err = nrf_modem_lib_init(NORMAL_MODE);`

Other than the `download` sample and the `https_client` sample, there are another number of samples that initialize libmodem, so I assume these require a shutdown too now. Regarding the PDN sample, I've checked the code and there is no call to `nrf_modem_lib_init`, so I wonder if calling shutdown there is correct or not (doesn't look explicit to me).

**Review by MirkoCovizzi — COMMENTED** [review]
This is a grep of nrf_modem_lib_init inside the samples/nrf9160 directory (that don't already have a shutdown):

```
modem_shell/src/main.c
64:K_SEM_DEFINE(nrf_modem_lib_initialized, 0, 1);
120:    err = nrf_modem_lib_init(NORMAL_MODE);
155:    k_sem_take(&nrf_modem_lib_initialized, K_FOREVER);

azure_fota/src/main.c
207:    err = nrf_modem_lib_init(NORMAL_MODE);

aws_fota/src/main.c
415:    err = nrf_modem_lib_init(NORMAL_MODE);

aws_iot/src/main.c
418:    err = nrf_modem_lib_init(NORMAL_MODE);

http_update/full_modem_update/src/main.c
69:     err = nrf_modem_lib_init(FULL_DFU_MODE);
71:             printk("nrf_modem_lib_init(FULL_DFU_MODE) failed: %d\n", err);
87:     err = nrf_modem_lib_init(NORMAL_MODE);
89:             printk("nrf_modem_lib_init() failed: %d\n", err);
193:    err = nrf_modem_lib_init(NORMAL_MODE);

http_update/common/src/update.c
161:    /* Initialize AT only if nrf_modem_lib_init() is manually

http_update/modem_delta_update/src/main.c
105:    err = nrf_modem_lib_init(NORMAL_MODE);
108:     * fetch the returned error code instead of nrf_modem_lib_init

http_update/application_update/src/main.c
54:     err = nrf_modem_lib_init(NORMAL_MODE);
```

There are another number of samples that initialize libmodem, so I assume these require a shutdown too now. Regarding the PDN sample, I've checked the code and there is no call to nrf_modem_lib_init, so I wonder if calling shutdown there is correct or not (doesn't look explicit to me).

**Review by jtguggedal — APPROVED** [review]

**Comment by jtguggedal** [comment]
Note that `lte_lc_power_off()` will achieve the same, if the goal is to send an `AT+CFUN=0`

**Comment by lemrey** [comment]
Rebased and changed to `lte_lc_power_off()`

**Review by eivindj-nordic — APPROVED** [review]

**Comment by lemrey** [comment]
Thanks @MirkoCovizzi, `nrf_modem_lib_init` is called automatically in some cases (via `SYS_INIT`); as for those samples, they are doing firmware updates so I did not update those.

**Comment by MirkoCovizzi** [comment]
> 
> 
> Thanks @MirkoCovizzi, `nrf_modem_lib_init` is called automatically in some cases (via `SYS_INIT`); as for those samples, they are doing firmware updates so I did not update those.

What about modem shell?

**Comment by lemrey** [comment]
These are examples that "finish" and return from main; they should power off the modem so that if the user resets the chip quickly after the sample has finished, that won't anger the modem. Modem shell is not that kind of sample, because it runs indefinitely.

**Pull request merged**
