### PR TITLE
fatal_error: Have RESET_ON_FATAL_ERROR be opt-in

### PR DESCRIPTION
**Pull request by SebastianBoe**
See commit message

### CODE REVIEW

**Review by grochu — CHANGES_REQUESTED** [review]
Documentation needs update in 2 places:
https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/samples.rst
https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/libraries/others/fatal_error.rst

**Comment by SebastianBoe** [comment]
Will update docs after the change is accepted.

**Comment by grochu** [comment]
General comment: I'd like to see other opinions on this. My personal view is that the current configuration is better as the samples resemble a bit more a final application. If one wants to debug, they will typically change the configuration anyway e.g. change compiler optimizations, and this config can be changed at that point too. The upstream samples don't behave like this, so we wanted to add the reboot feature in NCS by overriding the default Zephyr's fatal error handler.

**Comment by SebastianBoe** [comment]
In my experience it is often not possible to change compiler optimizations or options like this without affecting the thing you are trying to debug.

So having both samples and test code be debuggable from the get-go is quite important. If there is a particular sample that desires the resiliency that comes from resetting on fatal errors then they can explicitly enable this behaviour.

**Comment by SebastianBoe** [comment]
Perhaps there could be a "CONFIG_DEMO_MODE" or similar, for when acting as close to an application as possible is desired.

**Comment by SebastianBoe** [comment]
I see there is CONFIG_NCS_SAMPLES_DEFAULTS, perhaps, as a compromise, it could select RESET_ON_FATAL_ERROR.

Then tests and zephyr samples would not be affected.

Assuming this is how CONFIG_NCS_SAMPLES_DEFAULTS works.

**Comment by grochu** [comment]
You have valid points @SebastianBoe, I was just wondering if we should change this default behavior back to how it is in upstream. Let's see other opinions too and agree on some solution.

**Comment by KAGA164** [comment]
> I see there is CONFIG_NCS_SAMPLES_DEFAULTS, perhaps, as a compromise, it could select RESET_ON_FATAL_ERROR.
> 
> Then tests and zephyr samples would not be affected.
> 
> Assuming this is how CONFIG_NCS_SAMPLES_DEFAULTS works.

I agree that we can disable resetting as a default but it would be good if CONFIG_NCS_SAMPLES_DEFAULTS could select it for samples

**Review by KAGA164 — APPROVED** [review]
I agree that we can disable resetting as a default but it would be good if

**Comment by SebastianBoe** [comment]
Changed such that it is set for NCS samples.

**Comment by sigurdnev** [comment]
This change would mean that all customers need to remember to set RESET_ON_FATAL_ERROR=y themselves in their production code. Many customers will definitely miss this. Let’s say a customer have a product in the field based on e.g. v1.7.0, they update to v1.8.0 where this change is introduced, and they now risk bricking their products that are in the field.

**Comment by SebastianBoe** [comment]
"and they now risk bricking their products that are in the field."

I would expect any in-field product that wants resilicency to use a watchdog.
All this does is cut down on the time it takes to recover.

I would also expect any product deployment to review it's configuration and explicitly
turn on/off the functionality that makes sense to have in production.

**Comment by SebastianBoe** [comment]
NB: After discussions, it is opt-out when CONFIG_NCS_SAMPLES_DEFAULTS. Which I assume covers most things that users will deploy.

**Comment by einarthorsrud** [comment]
RESET_ON_FATAL_ERROR needs to _always_ be on by default, as before. Risking a lot of bricked devices in the field to make debugging slightly more convenient is not a good idea. (Also, resetting on unhandled errors has always been the default behavior in the nRF5 SDK.)

**Comment by SebastianBoe** [comment]
I want to make sure we are not blowing this out of proportion.

What is your definition of bricked?

Note that a power-cycle will also reset the device.

**Comment by grochu** [comment]
I think that this compromised approach where CONFIG_NCS_SAMPLES_DEFAULTS enables RESET_ON_FATAL_ERROR in fact covers most cases and once it's clearly documented (including the changelog), there shouldn't be too much confusion for the users.
Regarding the risk during upgrade to 1.8.0 and comparison to nRF5 SDK - was this an issue with NCS < 1.2.0 (when the NCS fatal error handler was introduced)? Before then all samples used the default Zephyr's fatal error handler which doesn't perform the reboot.

**Comment by einarthorsrud** [comment]
Definition of bricked is an unrecoverable state. Remember that many end products have no easy way for the end user to remove battery or forcefully reset the device in other ways. So from our customers perspective this is one of the worst things that could happen to their products out in the field.

**Comment by SebastianBoe** [comment]
I thought you meant it would be awkward during a demo that the device hangs instead of resets itself.

Surely in the scenario you describe a watchdog will be enabled.

Anything else would be madness, there are many ways to crash without triggering this fault handler.

**Comment by SebastianBoe** [comment]
If anything, this handler might be giving the false impression that he has resiliency on crashes.

We should have this disabled so that the customer understands that he needs to enable watchdog.

**Comment by einarthorsrud** [comment]
I agree customers should use a WDT in most cases. But I do not see that using a WDT to compensate for inappropriate error handling makes a good design.

**Comment by SebastianBoe** [comment]
I'm not sure I agree that it is inappropriate behaviour.

1. If you consistently crash early you will burn through your battery before it can be fixed in the field. Then the device will truly be bricked. It is better to wait in a sleep loop until the WDT resets you[0]. The WDT resets retained registers as well, so for some obscure cases the WDT will fix the device better than a soft reset will (a minor point).

2. The same type of users that don't know how their production application is configured might also not understand that their application will not be reset for all types of faults. Seeing that the app hangs during development will force them to enable some type of resiliency.

[0] I see that the current implementation of arch_system_halt is actually burning battery as well, but that can and should be fixed easily independently of this change.

**Comment by einarthorsrud** [comment]
I agree with both your points. However, It is likely that in some products some rare errors will occur in real life which was never though about or seen during development and testing. And you want to recover from that somehow (having the WDT as the last resort is good, but to rely on it more than necessary). Therefore I believe most will want to reset on otherwise unhandled errors in their products, and not doing so by default is a bit of a tripwire which some product designers might not notice before complaints start coming in from end users in the field.

**Comment by SebastianBoe** [comment]
Closing.

We need some kind of "CONFIG_PRODUCTION_DEFAULTS".

Until this exists it will not be obvious whether options should be configured for production or for development.

**Pull request closed without merging**
