### PR TITLE
mpsl: Make APP core FEM support independent from MPSL presence

### PR DESCRIPTION
**Pull request by pkwiek**
FEM support would not be enabled due to MPSL module not present on nRF53
APP core. This commit removes the dependency, hence allowing FEM
dependent code to be compiled on the APP core.

### CODE REVIEW

**Review by rugeGerritsen — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

**Review by czeslawmakarski — APPROVED** [review]

**Comment by hubertmis** [comment]
Why is FEM support needed on app core?

**Comment by czeslawmakarski** [comment]
@hubertmis APP Core needs to be aware of the FEM to be able to forward (i.e. give control) of the steering pins to the NET Core.

**Comment by hubertmis** [comment]
Do I understand correctly there are following modules needed on nRF53?

1. FEM driver running on the net core (the one that manages GPIO pins according to current radio operation)
2. FEM pins forwarder running on the app core (the one that forwards appropriate pin control from the app to the net core)

I know that FEM driver is enabled with Kconfig `MPSL_FEM`, but I don't understand why we use conflicting Kconfig entry to enable FEM pins forwarder on the application core. I think it would be clearer if it was enabled with a separated Kconfig entry. Then `MPSL_FEM` could keep its dependency to `MPSL`, which seems obvious.

**Comment by hubertmis** [comment]
How about sth like this instead:

Kconfig:
Keep MPSL_FEM as it is, add a new entry
```
config MPSL_FEM_PIN_FORWARDER
  bool "Forward pin control for front-end module (FEM) to the radio core"
  depends on SOC_NRF5340_CPUAPP
  default y
```

And `MPSL_FEM_CHOICE` would be guarded by a new condition:
`if MPSL_FEM || MPSL_FEM_PIN_FORWARDER`, because choice details are used by both modules.

Then in CMakeList you could select proper source file based on software module enabled in Kconfig (`MPSL_FEM` or `MPSL_FEM_PIN_FORWARDER`) instead of selected SoC, what seems like an error prone indirection.

**Comment by pkwiek** [comment]
As discussed with @hubertmis, this PR is good to go and another one will be opened to address Kconfig concerns.

**Review by LuDuda — APPROVED** [review]

**Comment by LuDuda** [comment]
Would like to merge it, but building of a few examples failed on CI e.g.:
```
/home/work/nrf/subsys/mpsl/fem/mpsl_fem.c:11:10: fatal error: mpsl_fem_config_nrf21540_gpio.h: No such file or directory
   11 | #include <mpsl_fem_config_nrf21540_gpio.h>
```

@pkwiek could you look at it?

**Review by hubertmis — APPROVED** [review]
The design is clear to me now :+1:

**Pull request merged**
