### PR TITLE
doc improvement: Fix cell formatting in table

### PR DESCRIPTION
**Pull request by wiba-nordic**
Bullet points format badly inside table cells.
This rephrases the content to not need the bullets.

Signed-off-by: Wille Backman <wille.backman@nordicsemi.no>

### CODE REVIEW

**Comment by wiba-nordic** [comment]
Small change to a table that was added for this release, so no need for a changelog entry for this PR.

**Review by b-gent — APPROVED** [review]

**Comment by wiba-nordic** [comment]
Waiting for comments from Krzystof Loska.

**Comment by krlo** [comment]
I am not able to provide review comments on large parts of the file (they are grayed out) so I am providing my review here.

**Intro**
Old:
"Supported - Features that are maintained and are suitable for product development.
Experimental - Features that can be used for development but not recommended for production."

New:
"Supported - Features that are maintained and are suitable for integration in end-products.
Experimental - Features that are suitable for prototyping or evaluation but should not be deployed in end-products."

**Technical support/Supported**
Old: "Customer issues raised for features supported for development on tagged [|NCS|](https://github.com/nrfconnect/sdk-nrf/blob/e8df41fe084b98576e6fd68e97cf7735ebd066e8/doc/nrf/software_maturity.rst#id1) releases are handled by technical support on DevZone."
New: "Customer issues raised for features suitable for end-product development on tagged [|NCS|](https://github.com/nrfconnect/sdk-nrf/blob/e8df41fe084b98576e6fd68e97cf7735ebd066e8/doc/nrf/software_maturity.rst#id1) releases are handled by technical support on DevZone."

**Bug fixing/Experimental**
Old: "Bug fixes and improvements are not guaranteed to be applied to current versions."
New: "Bug fixes and improvements are not guaranteed to be applied."

**API definition/Experimental**
Old: "API definition is not stable and may change before going to production."
New: "API definition is not stable and may change."

**Maturity/Supported**
Old: "Suitable for integration in end-product development.

A feature or component that is either fully complete on first commit, or has previously been labelled "experimental" and is now ready for use in end-product projects."

New: "Suitable for integration in end-products.

A feature or component that is either fully complete on first commit, or has previously been labelled "experimental" and is now ready for use in end-products."

**Maturity/Experimental**
Old: "Suitable for prototyping or evaluation. Should not be deployed in end-products.

A feature or component that is in a core supported sub-system and either not fully tested according to existing test plans or currently being developed, meaning it is changing or incomplete."

New: "Suitable for prototyping or evaluation. Not recommended to be deployed in end-products.

A feature or component that is either not fully verified according to existing test plans or currently being developed, meaning it is changing or incomplete."

**Verification/Supported**
Old: "Verified for product development."
New: "Fully verified according to existing test plans."

**Others**

- Please remove the following sentence from the "Matter feature support" section: "The matter features are still experimental for now:"
- Please remove "Matter - Amazon Frustration Free Setup support" row from the "Matter feature support" section
- Please remove "Thread + WiFi coex" row from the "Thread feature support" section
- Please remove "Zigbee + WiFi coex" row from the "Zigbee feature support" section

**Comment by b-gent** [comment]
@krlo 
About your last comments - we cannot modify the table rows in this PR, the tables are generated automatically by a script and their source does not reside in the RST file.

**Pull request merged**
