### PR TITLE
lib: date_time: update to use new AT APIs

### PR DESCRIPTION
**Pull request by lemrey**
Update to use new AT APIs from libmodem.

### CODE REVIEW

**Review by simensrostad — APPROVED** [review]
Looks good to me

**Comment by lemrey** [comment]
I did not testing on this to be honest, anybody knows how to check if it's still working?

**Comment by simensrostad** [comment]
Did some quick testing, seems to be working fine.

**Review by jtguggedal — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
LGTM 👍

**Pull request merged**
