### PR TITLE
samples: net: http_server: Increase POSIX_MAX_FDS

### PR DESCRIPTION
**Pull request by gregersrygg**
Max posix file descriptors needs to be increased for TLS to work.

Also decreased HTTP_SERVER_SAMPLE_CLIENTS_MAX to 1 because there is no need for multiple clients.

### CODE REVIEW

**Comment by gregersrygg** [comment]
This change was necessary after the last upmerge because of a change in Zephyr increasing the number of file descriptors pr socket. We have needed to adjust `CONFIG_POSIX_MAX_FDS` other places as well, and this will most likely hit our customers in their applications.

@carlescufi @divipillai How do we document migration notes for Zephyr related changes?

**Comment by divipillai** [comment]
> This change was necessary after the last upmerge because of a change in Zephyr increasing the number of file descriptors pr socket. We have needed to adjust `CONFIG_POSIX_MAX_FDS` other places as well, and this will most likely hit our customers in their applications.
> 
> @carlescufi @divipillai How do we document migration notes for Zephyr related changes?

@gregersrygg :  The NCS-related changes are documented in the NCS migration guide https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/migration/migration_guide_2.7.html (Please note we can also update the previous NCS release migration guide if it affects the previous release as well), mentioning what changes in Zephyr have caused this change: 
For example: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/migration/migration_guide_2.6.html#serial-lte-modem-slm - 1st bullet point.

**Review by simensrostad — APPROVED** [review]
lgtm

**Review by bjda — APPROVED** [review]

**Review by DematteisGiacomo — APPROVED** [review]

**Comment by divipillai** [comment]
> > This change was necessary after the last upmerge because of a change in Zephyr increasing the number of file descriptors pr socket. We have needed to adjust `CONFIG_POSIX_MAX_FDS` other places as well, and this will most likely hit our customers in their applications.
> > @carlescufi @divipillai How do we document migration notes for Zephyr related changes?
> 
> @gregersrygg : The NCS-related changes are documented in the NCS migration guide https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/migration/migration_guide_2.7.html (Please note we can also update the previous NCS release migration guide if it affects the previous release as well), mentioning what changes in Zephyr have caused this change: For example: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/migration/migration_guide_2.6.html#serial-lte-modem-slm - 1st bullet point.

Discussed offline and updates to NCS migration Guide is not required.

**Review by divipillai — APPROVED** [review]

**Pull request merged**
