### PR TITLE
Updated mpsl cx cmake file for bug fix

### PR DESCRIPTION
**Pull request by tadw-nordic**
Defined 1-wire coex flag

Signed-off-by: Dwivedi, Tanmay <tanmay.dwivedi@nordicsemi.no>

### CODE REVIEW

**Comment by Tschet1** [comment]
Looks good. Only nitpick would be that you could make the commit message more informative.

**Review by Tschet1 — APPROVED** [review]

**Review by rugeGerritsen — CHANGES_REQUESTED** [review]
Please make the commit message more informative. For example:
```
mpsl: Fix inclusion of 1-wire coex when MPSL_CX_BT_1WIRE is enabled

Also removes a duplicate check for MPSL_CX_THREAD
```

**Comment by rugeGerritsen** [comment]
@tadw-nordic , please update the commit message as suggested. The commit must include a prefix that identifies the subsystem being changed. See http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/contribute/index.html#commit-guidelines

**Comment by tadw-nordic** [comment]
> @tadw-nordic , please update the commit message as suggested. The commit must include a prefix that identifies the subsystem being changed. See http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/contribute/index.html#commit-guidelines
>Updated comments.
CI fails but it's not related to our PR

**Review by rugeGerritsen — APPROVED** [review]

**Comment by tadw-nordic** [comment]
Rebase code to main.

**Pull request merged**
