### PR TITLE
manifest: update nrfxlib

### PR DESCRIPTION
**Pull request by lemrey**
Update nrfxlib to introduce nrf_modem v1.0.3

### CODE REVIEW

**Review by jtguggedal — APPROVED** [review]
Looks good. Tested cloud client, HTTPS sample and asset trackers v1 and v2.

**Review by richardmccrae-nordicsemi — APPROVED** [review]
passes on-commit tests

**Review by jorgenmk — APPROVED** [review]

**Comment by lemrey** [comment]
Did a rebase and descoped CI a bit because the build takes very long.
DFU tests have been run by @mswarowsky in https://github.com/nrfconnect/sdk-nrfxlib/pull/450.

**Review by rlubos — APPROVED** [review]

**Comment by lemrey** [comment]
CI has been run manually by the testers, so I have removed the `CI-all-test` label.

**Pull request merged**
