### PR TITLE
manifest: Update sdk-ant revision

### PR DESCRIPTION
**Pull request by sarah-read**
Update to ANT for nRF Connect SDK v1.2.0.

### CODE REVIEW

**Comment by sarah-read** [comment]
@jori-nordic @shanthanordic 
PR for sdk-nrf v2.6 compatible release, can you please add to the milestone?

**Review by carlescufi — APPROVED** [review]
lgtm

**Review by jfischer-no — APPROVED** [review]

**Comment by jfischer-no** [comment]
@jori-nordic Please take a look.

**Review by SeppoTakalo — APPROVED** [review]

**Comment by jfischer-no** [comment]
@sarah-read Can you please rebase it on the latest sdk-nrf main? Thanks.

**Comment by SeppoTakalo** [comment]
This breaks the CI.

We are soon closing the RC2.
Is there anyone working on this to get it building? It is on high risk to be left out from release.

Thanks.

**Comment by sarah-read** [comment]
The twister CI in sdk-ant was green prior to merging the PR there last week. I've reached out for logs and manually granted @jfischer-no repo access.

Our builds must sync with MPSL so we can't PR until nrfxlib is locked down, and we can't diagnose sdk-nrf CI on our own. Would appreciate help getting this through.

**Comment by sarah-read** [comment]
Thank you @PerMac and @jfischer-no for the help, this should be ready now. 

I'm putting steps in place to ensure we're running CI outside the ANT repo consistently prior to PR. @jori-nordic and I will also be working on improving test coverage for future releases.

**Pull request merged**
