### PR TITLE
samples: mqtt: Add missing board file

### PR DESCRIPTION
**Pull request by jorgenmk**
Board file for nrf9161 dk was missing.

### CODE REVIEW

**Comment by jorgenmk** [comment]
@jtguggedal Updated PR, added new board to `sample.yaml`. Need to rebase after #11308 is merged.

**Review by simensrostad — CHANGES_REQUESTED** [review]
The docs references the overlay file that know has changed:

* :file:`overlay-tls-nrf9160.conf` - TLS overlay configuration file for nRF9160 DK and Thingy:91.

**Comment by simensrostad** [comment]
> The docs references the overlay file that know has changed:
> 
> * :file:`overlay-tls-nrf9160.conf` - TLS overlay configuration file for nRF9160 DK and Thingy:91.

Actually there are multiple places where the nrf9160 is mentioned specifically that needs to be updated.
I wonder it should be discussed with the tech writers how to do this through the docs in sdk-nrf in general.
cc @umapraseeda @divipillai

**Comment by divipillai** [comment]
> > The docs references the overlay file that know has changed:
> > 
> > * :file:`overlay-tls-nrf9160.conf` - TLS overlay configuration file for nRF9160 DK and Thingy:91.
> 
> Actually there are multiple places where the nrf9160 is mentioned specifically that needs to be updated. I wonder it should be discussed with the tech writers how to do this through the docs in sdk-nrf in general. cc @umapraseeda @divipillai

agree with you @simen - With nRF9161 support, there are some document updates needed to this sample and also to NCS documentation in general. Jira's for these has been created NCSDK-22136 and NCSDK-22133, and we could cover the doc updates separately.

**Pull request closed without merging**
