### PR TITLE
application: serial_lte_modem: Add modem fault handler

### PR DESCRIPTION
**Pull request by junqingzou**
Enable CONFIG_NRF_MODEM_LIB_ON_FAULT_APPLICATION_SPECIFIC
Detect modem fault by libmodem callback;
Schedule shutdown of libmodem;
Schedule re-init of libmodem;
Send URC for all above steps.

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

### CODE REVIEW

**Comment by junqingzou** [comment]
DNM: this PR is used for discussion with libmodem as of now

**Review by lemrey — COMMENTED** [review]
Looks okay. Keep in mind that `#XMODEM: SHUTDOWN` and `#XMODEM: INIT` will only be emitted if the modem is re-initialized due to a fault, not on every initialization/shutdown. You could use the callbacks for that, which would work in either case.

**Comment by junqingzou** [comment]
> Looks okay. Keep in mind that `#XMODEM: SHUTDOWN` and `#XMODEM: INIT` will only be emitted if the modem is re-initialized due to a fault, not on every initialization/shutdown. You could use the callbacks for that, which would work in either case.

Thanks for the comments, it's intentionally kept for modem fault scenario only.

**Comment by junqingzou** [comment]
The solution has been verified by simulated modem crash.
Fault handler in SLM has no dependency on on-going lib_pdn improvement and no issue to re-config PDN after libmodem is re-initialized.
So please consider this PR for NCSv2.0.0, as the first sample of libmodem fault handling in NCS.

**Review by rlubos — APPROVED** [review]

**Review by tokangas — APPROVED** [review]

**Review by FrancescoSer — APPROVED** [review]

**Review by pirun — APPROVED** [review]

**Review by lemrey — APPROVED** [review]

**Pull request merged**
