### PR TITLE
configure GNSS LNA after modem library init

### PR DESCRIPTION
**Pull request by tokangas**
Moved GNSS Low Noise Amplifier (LNA) configuration to modem library initialization callback for GNSS, location and modem_shell samples.

### CODE REVIEW

**Comment by lemrey** [comment]
funny commit hash `aeeeeee3ed4afe53400eed6196e7da6e6c63072d` :) I was wondering whether it would make sense to have a dedicated component setup this stuff so that it can be shared with `asset_tracker` and the application.

**Comment by tokangas** [comment]
> funny commit hash `aeeeeee3ed4afe53400eed6196e7da6e6c63072d` :) I was wondering whether it would make sense to have a dedicated component setup this stuff so that it can be shared with `asset_tracker`, the various samples, the user application? Ref: CIA-385

True, I was probably too enthusiastic to take this new feature into use. 😄

Any good ideas how to do that? A new library? And probably it should be more generic than just for configuring the LNA.

**Comment by lemrey** [comment]
I was thinking about a dedicated new library, yeah.
What do you mean by "more generic than just LNA"?

**Comment by tokangas** [comment]
> I was thinking about a dedicated new library, yeah. What do you mean by "more generic than just LNA"?

Just that the new library could be used for other modem configuration as well, so not just for this GNSS LNA configuration. In the Thingy board configuration there seems to be sending of %XMODEMTRACE, but that's now handled by modem library. So not sure if we currently have something else which should be initially in the new library.

Maybe I should just close this PR then?

**Comment by lemrey** [comment]
I think that GNSS related configuration could be done by a dedicated module.
I'll see if I can cleanup the trace instead, that can now be done all in one place, `nrf_modem_lib`.

**Comment by tokangas** [comment]
Maybe that's the way to go, I couldn't figure out what else could be configured by the same library. I marked this PR as DNM and will move the configuration into a new module.

**Comment by tokangas** [comment]
Closing this PR, I created a new PR #7338 for the library instead.

**Pull request closed without merging**
