### PR TITLE
Fetch LwM2M and CoAP related updates from upstream Zephyr.

### PR DESCRIPTION
**Pull request by SeppoTakalo**
* Fetch LwM2M and CoAP related updates from upstream Zephyr.
* Refactor LwM2M client utils RAI module to use new socket state indication.
* Refactor CoAP client to use transmission parameters.

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
@plskeggs please review.

As the upstream Coap-client now uses transmission parameter structure, not just retry count, and also it does not anymore retry NON confirmable CoAP packets, I believe that was a bug, I need your opinion if it was OK to remove the Kconfig `NON_RESP_RETRIES`.
Now the cases that I found, use just `NULL` as a transmission parameter, which means that it uses whatever default is set in CoAP client.

**Review by juhaylinen — APPROVED** [review]

**Comment by SeppoTakalo** [comment]
Find-my test failure seem unrelated:
```
fatal: clone of 'https://github.com/google/pigweed.git' into submodule path '/jenkins_workspace_b/workspace/test_sub_test-sdk-find-my_master/modules/lib/matter/third_party/pigweed/repo' failed

Failed to clone 'third_party/pigweed/repo'. Retry scheduled

Cloning into '/jenkins_workspace_b/workspace/test_sub_test-sdk-find-my_master/modules/lib/matter/third_party/pigweed/repo'...

fatal: the remote end hung up unexpectedly

fatal: early EOF

fatal: index-pack failed
```

**Comment by SeppoTakalo** [comment]
I'll submit a changelog on a separate PR once this goes in, so we don't end up running 3 hours of tests for two lines of changelog changes.

**Review by rlubos — APPROVED** [review]

**Review by plskeggs — APPROVED** [review]

**Comment by SeppoTakalo** [comment]
Rebased on top of main, west.yml updated to contain the merged SHA.

**Pull request merged**
