### PR TITLE
tfm: Add configuration for reset of nRF peripherals on boot

### PR DESCRIPTION
**Pull request by joerchan**
Add reset of nRF peripherals during boot in order to be compatible
with MCUBoot versions that leave the peripherals in a running state.
This trigger an SPU fault when the SPU interrupt is enabled in TF-M.

NCSDK-15570

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Comment by balaji-nordic** [comment]
Serial DFU on factory programmed Thingy91 v1.5.0 works as expected. 

Upgrade path I tested: Asset tracker v1 from NCS Tag1.3.1 (with MCUboot also from ncs tag 1.3.1) to asset_tracker_v2 build from this Pull request's current head (794c4cc7575a0cba4515e112fba4560335ef0fd4) .

**Review by balaji-nordic — APPROVED** [review]

**Review by sigvartmh — APPROVED** [review]

**Comment by balaji-nordic** [comment]
Can this be merged anytime soon?

**Comment by joerchan** [comment]
> Can this be merged anytime soon?

Rebased the dependent PR, which was stuck behind last TF-M upmerge. Hopefully this can be merged after a CI run.

**Review by oyvindronningstad — APPROVED** [review]

**Comment by joerchan** [comment]
Rebased and updated to final SHA

**Review by divipillai — APPROVED** [review]

**Pull request merged**
