### PR TITLE
manifest: Pull settings nvs fixes

### PR DESCRIPTION
**Pull request by PavelVPV**
Pull settings nvs fixes from upstream.

### CODE REVIEW

**Comment by jfischer-no** [comment]
@PavelVPV You need to get CI green.

**Comment by PavelVPV** [comment]
> @PavelVPV You need to get CI green.

Green now

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Please **do not update** sdk-zephyr here.

**Comment by PavelVPV** [comment]
> Please **do not update** sdk-zephyr here.

Closing the PR then

**Pull request closed without merging**
