### PR TITLE
manifest: Pull in minimal MCUboot update

### PR DESCRIPTION
**Pull request by kyberdin**
Pulls in update for minimal MCUboot builds from PR 137.

Signed-off-by: Stephen Stauts <stephen.stauts@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
@kyberdin Can you fix CI failures?

**Review by tejlmand — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@kyberdin Can this be refreshed?

**Comment by nvlsianpu** [comment]
@kyberdin rebase?

**Comment by nvlsianpu** [comment]
@kyberdin is this for 1.6.0?

**Comment by kyberdin** [comment]
@nvlsianpu Not to my knowledge. It has been open for a long time waiting for CI to be green. Latest changes to sdk-mcuboot upstream fixed the CI issues for its [related PR](https://github.com/nrfconnect/sdk-mcuboot/pull/137), and current CI failures here do not look related to the content from those changes.

So it could probably go in to 1.6 if we would like, or we could wait until after the release.

Either way, both are ready to merge if we wish to overlook the unrelated CI failures.

**Comment by nvlsianpu** [comment]
There are communication time-out issues in CI.

**Comment by kyberdin** [comment]
> There are communication time-out issues in CI.

@nvlsianpu do you think these are ok for getting these changes merged, or would it be best for me to keep restarting CI to see if the timeouts eventually pass?

**Comment by nvlsianpu** [comment]
I prefer to have them green. You can clarify with the CI suite owners whether there is an CI related issue.

**Comment by kyberdin** [comment]
@nvlsianpu @carlescufi I spoke with the CI suite owner for our apps tests, and the failures blocking green CI for this PR are known issues that are not related to the MCUboot changes here.

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@kyberdin Please update SHA.

**Pull request merged**
