### PR TITLE
Fix docs for nRF7001

### PR DESCRIPTION
**Pull request by D-Triveni**
Fixes SHEL-2267

### CODE REVIEW

**Review by krish2718 — APPROVED** [review]
The PR title should be `Fix twister builds` (sample document is misleading).

**Comment by D-Triveni** [comment]
> The PR title should be `Fix twister builds` (sample document is misleading).

ok, will change.

**Comment by krish2718** [comment]
> [samples: wifi: Add support for nRF7001 target]
>
> Add entry for emulated nRF7001 target but skip
> twister run.

Can you please add a reason why this has to be skipped? IIUC, the title should be 

```
Fix docs for nRF700

 Add entry for emulated nRF7001 target but skip
the twister build, this is mainly for the target to show
up in the supported targets list but don't want to increase
CI time by duplicating (using nRF7002 for CI).
```

**Review by bama-nordic — APPROVED** [review]

**Review by ioannisg — COMMENTED** [review]
Could you also add support for nrf7000 in the scan only related samples (in wifi directory and maybe also the location sample in nrf cloud). Guess the shutdown same is also a good candidate for 7000. 

Or are you planning to fix the support for 7000 in a separate PR?

**Comment by D-Triveni** [comment]
> Could you also add support for nrf7000 in the scan only related samples (in wifi directory and maybe also the location sample in nrf cloud). Guess the shutdown same is also a good candidate for 7000.
> 
> Or are you planning to fix the support for 7000 in a separate PR?

The support for nRF7000 was already added in the Wi-Fi samples (shell, scan and shutdown).

**Review by ioannisg — APPROVED** [review]
Thanks

**Review by krga2022 — APPROVED** [review]

**Pull request merged**
