### PR TITLE
nRF54L15 PDK revision v0.3.0: indicate support in Readme files and add to CI

### PR DESCRIPTION
**Pull request by kapi-no**

### CODE REVIEW

**Review by mkapala-nordic — APPROVED** [review]

**Review by alstrzebonski — APPROVED** [review]

**Comment by kapi-no** [comment]
Rebased my PR to pull in the fix from the linked PR

**Review by MarekPieta — APPROVED** [review]

**Comment by kapi-no** [comment]
I plan to move ahead with this PR and finalize it, as the Thread team decided to use this approach in their samples

https://github.com/nrfconnect/sdk-nrf/pull/14984
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/openthread/cli/README.html

**Comment by kapi-no** [comment]
Rebased without any changes to make sure that CI still passes

**Comment by kapi-no** [comment]
Update the find my revision in west manifest to point to the main branch revision

**Pull request merged**
