### PR TITLE
doc: nrf21540: fix typo in shield name

### PR DESCRIPTION
**Pull request by greg-fer**
Fixed -DSHIELD=nrf21540ek_fwd to -DSHIELD=nrf21540_ek_fwd. Reported by a customer.

### CODE REVIEW

**Review by erikrobstad — APPROVED** [review]

**Review by koffes — COMMENTED** [review]
Has this changed recently? If so, we need to change our build script as well. Any comments @rick1082 ?

**Review by rick1082 — APPROVED** [review]

**Comment by greg-fer** [comment]
> Has this changed recently? If so, we need to change our build script as well. Any comments @rick1082 ?

No clue. @jciupis , would you know?

**Comment by erikrobstad** [comment]
That is a good point @koffes.
We have been able to build for nRF21540 using our script before, so it has probably changed at some point

**Comment by rick1082** [comment]
Hello all, thanks for the remind!
We might need to reconsider this PR, since the name just updated from this commit:
https://github.com/nrfconnect/sdk-nrf/commit/18c27de5eb3d43ef4583210fe69d50b8b657abf6

I saw the issue report from the customer, I would assume there's a mismatch between the SDK version they are using now and the doc.

**Review by erikrobstad — CHANGES_REQUESTED** [review]
We can not merge this change.

**Comment by greg-fer** [comment]
Clarified with @rick1082 and this is going against the recent changes from https://github.com/nrfconnect/sdk-nrf/commit/18c27de5eb3d43ef4583210fe69d50b8b657abf6

**Pull request closed without merging**
