### PR TITLE
Applications: nrf5340_audio: timestamp fix

### PR DESCRIPTION
**Pull request by koffes**
OCT-2864
Change so timestamp is sent on every interval over zbus

### CODE REVIEW

**Review by alexsven — APPROVED** [review]

**Review by rick1082 — APPROVED** [review]

**Comment by FARLY7** [comment]
Hi @koffes, I've been following the updates being made to the nrf53840_audio application.

Apologies if this is not the correct place to ask this, but what are the commonly used OCT identifiers referring to? E.g. OCT-2864. I noticed the same tag used to denote Known Issues in the NCS documentation; however, all of the OCT tags I searched for from the audio application pull requests are not found in this documentation. Is there another resource that lists the known issues with the nrf53480_audio application?

Thanks,
Sean

**Comment by alexsven** [comment]
> Hi @koffes, I've been following the updates being made to the nrf53840_audio application.
> 
> Apologies if this is not the correct place to ask this, but what are the commonly used OCT identifiers referring to? E.g. OCT-2864. I noticed the same tag used to denote Known Issues in the NCS documentation; however, all of the OCT tags I searched for from the audio application pull requests are not found in this documentation. Is there another resource that lists the known issues with the nrf53480_audio application?
> 
> Thanks, Sean

These are internal JIRA-issues, so it is solely for internal tracking purposes

**Comment by koffes** [comment]
@FARLY7, thanks for following our development. If you do have any specific questions, please raise them on our support portal https://devzone.nordicsemi.com/ :)

**Comment by FARLY7** [comment]
Thanks for the clarification guys 👍🏻

**Pull request merged**
