### PR TITLE
net: lib: azure_iot_hub: Increase default topic element max size

### PR DESCRIPTION
**Pull request by jtguggedal**
Messages sent from the Azure IoT Explorer to a device now comes with
larger property bags than before, resulting in error messages.
Increase the max length for topic elements to match the required
length.
The stack also needs to be bumped to process the larger elements.

Closes CIA-416

Signed-off-by: Jan Tore Guggedal <jantore.guggedal@nordicsemi.no>

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Comment by coderbyheart** [comment]
@jtguggedal Do you have an example of a topic with the new property bags?

**Review by coderbyheart — APPROVED** [review]
**nitpick:** a test would be nice that uses the new, longer property bags as an example.

**Comment by jtguggedal** [comment]
> @jtguggedal Do you have an example of a topic with the new property bags?

@coderbyheart  Thanks for the reminder, I have now updated the `test_topic_parse_long` test case with an example of the longer `%24.mid` field that I observe in messages that are sent from Azure IoT Explorer.
The topic for messages sent from the Azure Portal looks like this now:
`devices/my-device-name/messages/devicebound/%24.to=%2Fdevices%2Fmy-device-name%2Fmessages%2FdeviceBound&%24.ct=text%2Fplain%3B%20charset%3DUTF-8&%24.ce=utf-8`

**Comment by coderbyheart** [comment]
I see, they've added the message id parameter. Thanks!

**Pull request merged**
