### PR TITLE
samples: matter: Align nRF54L15 internal pm_static

### PR DESCRIPTION
**Pull request by ArekBalysNordic**
We need to reach 35% of the compression rate, so we need to align the nRF54L15 internal partition map in the pm_static file.

### CODE REVIEW

**Comment by ArekBalysNordic** [comment]
DNM before merging: https://github.com/nrfconnect/sdk-nrf/pull/19148

**Comment by ArekBalysNordic** [comment]
@LuDuda is the **34.80%** compression rate appropriate?

**Review by adigie — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]
Ranges look correct. Thanks.

**Comment by ArekBalysNordic** [comment]
@nrfconnect/ncs-doc-release FYI: I've removed release-notes from here.

**Pull request merged**
