### PR TITLE
Bluetooth: enocean: Add unit test

### PR DESCRIPTION
**Pull request by omkar3141**
Adds a simple unit test for enocean module using sample data from
enocean specifications and real devices.

Also, updates the CODEOWNERS file to add Ludvig as code owner for
this test.

### CODE REVIEW

**Comment by omkar3141** [comment]
I think that should be done as a seperate PR? Our team basically owns this part, I don't think it is appropriate to change codeowners file in this PR.

**Comment by ludvigsj** [comment]
> I think that should be done as a seperate PR? Our team basically owns this part, I don't think it is appropriate to change codeowners file in this PR.

No she is correct, it should have my name on it, to match the ownership for the implementation in enocean.c

**Comment by katgiadla** [comment]
> I think that should be done as a seperate PR? Our team basically owns this part, I don't think it is appropriate to change codeowners file in this PR.

Usually, if the new test configuration is added, the CODEOWNER should be specified. It makes easier looking for responsible for this test configuration. IMO adding code owner at once is easier and more readible.  
If you want to separate adding code owner from this process, you could add new commit to this PR.

**Comment by omkar3141** [comment]
Touching CODEOWNERS file triggers bunch of errors due to non-existent users.

**Review by katgiadla — APPROVED** [review]

**Review by alxelax — APPROVED** [review]

**Review by ludvigsj — APPROVED** [review]

**Pull request merged**
