### PR TITLE
drivers: wifi: Framework to use OTP programmed values

### PR DESCRIPTION
**Pull request by sachinthegreen**
[SHEL-1000] Add framework to use OTP programmed values for MAC address and RF parameters, if present.

Signed-off-by: Sachin D Kulkarni <sachin.kulkarni@nordicsemi.no>

### CODE REVIEW

**Review by krish2718 — APPROVED** [review]
Would be good to separate in to rename commit + actual OTP changes for easier review, but its tough to do that now, anyways, LGTM.

**Review by sr1dh48r — APPROVED** [review]

**Review by bama-nordic — APPROVED** [review]

**Review by richabp — APPROVED** [review]

**Review by kspraveeen — APPROVED** [review]

**Review by prsi98 — APPROVED** [review]

**Comment by nordicjm** [comment]
@sachinthegreen I keep getting added to wifi reviews and not really sure why as wifi isn't really an area I have knowledge in (I have IPv4 knowledge i.e. frames, routing, ethernet/transport, application but that seems unrelated to these PRs)

**Comment by rlubos** [comment]
[test-sdk-wifi/master](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-sdk-wifi/job/master/1069/) is failing on this PR (build error)

**Comment by sachinthegreen** [comment]
> [test-sdk-wifi/master](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-sdk-wifi/job/master/1069/) is failing on this PR (build error)

Hi @rlubos : Looks like it has passed now.

**Pull request merged**
