### PR TITLE
doc: updating documentation for AT#XHTTPCCON

### PR DESCRIPTION
**Pull request by akash-patel**
<op> parameter had the wrong values for disconnect/connect

### CODE REVIEW

**Review by lats1980 — APPROVED** [review]
Thanks for the fix!

**Review by rlubos — APPROVED** [review]

**Comment by rlubos** [comment]
Please address the compliance check issues (missing signoff entry, lack of commit title prefix (`doc: serial_lte_modem: `).

**Comment by akash-patel** [comment]
> Please address the compliance check issues (missing signoff entry, lack of commit title prefix (`doc: serial_lte_modem: `).

I believe I have fixed this, please let me know if there are still any issues. First time doing a pull request to sdk-nrf so hopefully will be smoother next time!

**Comment by rlubos** [comment]
> > Please address the compliance check issues (missing signoff entry, lack of commit title prefix (`doc: serial_lte_modem: `).
> 
> I believe I have fixed this, please let me know if there are still any issues. First time doing a pull request to sdk-nrf so hopefully will be smoother next time!

Looking good now :+1:

**Review by FrancescoSer — APPROVED** [review]

**Pull request merged**
