### PR TITLE
NCS v2.6.0 rc1 tagging

### PR DESCRIPTION
**Pull request by jfischer-no**
NCS v2.6.0 rc1 tagging

### CODE REVIEW

**Review by SebastianBoe — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by mswarowsky — APPROVED** [review]
Fine for TF-M and mbed TLS

**Review by carlescufi — APPROVED** [review]
Zephyr revision checked

**Comment by carlescufi** [comment]
@nvlsianpu @de-nordic please check mcuboot

**Review by shanthanordic — APPROVED** [review]

**Review by shanthanordic — CHANGES_REQUESTED** [review]
REvisions are fining, giving a -1 to understand why downstream are not triggered ?

**Review by de-nordic — APPROVED** [review]
The MCUboot tag v2.0.99-ncs1-rc1 looks OK and tag record https://github.com/nrfconnect/sdk-mcuboot/releases/tag/v2.0.99-ncs1-rc1 correctly points to https://github.com/nrfconnect/sdk-mcuboot/commit/323fb663e832d4c45eb2fc2d30a3955684791b7d, current top of main.

**Review by thst-nordic — APPROVED** [review]

**Pull request merged**
