### PR TITLE
doc: Fix Sphinx 3.3.1 warnings

### PR DESCRIPTION
**Pull request by utzig**
Fixes two issues building on Sphinx==3.3.1. This should be merged once the Docker image is updated from 3.2.1 to 3.3.1.

### CODE REVIEW

**Comment by ru-fu** [comment]
Will the required Sphinx version be updated to 3.3.1 then as well?
If not, the filter should probably contain both variants.

**Comment by utzig** [comment]
> Will the required Sphinx version be updated to 3.3.1 then as well?
> If not, the filter should probably contain both variants.

Makes sense, there is not reason to force it, yet!

**Comment by utzig** [comment]
> Will the required Sphinx version be updated to 3.3.1 then as well?
> If not, the filter should probably contain both variants.

I updated the regex to work on both, thanks for the suggestion!

**Comment by ru-fu** [comment]
I've been trying to check the output, but the CI doesn't create the doc artifact even though it's green?

**Comment by utzig** [comment]
> I've been trying to check the output, but the CI doesn't create the doc artifact even though it's green?

Yeah weird, I just rebuilt on my machine and it generates the proper output files. Also it seems that it does run filter-known-issues. I looked at other PRs (not this one!) and they have the same issue. I will investigate the CI changes and try to find where it stopped working correctly.

**Comment by ru-fu** [comment]
> Yeah weird, I just rebuilt on my machine and it generates the proper output files. Also it seems that it does run filter-known-issues. I looked at other PRs (not this one!) and they have the same issue. I will investigate the CI changes and try to find where it stopped working correctly.

It works fine on for example https://github.com/nrfconnect/sdk-nrf/pull/3292 - could it be related to the CI-doc-build tag?

**Review by ru-fu — APPROVED** [review]
Will

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
