### PR TITLE
tools: Update zephyr-sdk version to 0.16.0

### PR DESCRIPTION
**Pull request by jangalda-nsc**
Update zephyr-sdk version to 0.16.0

### CODE REVIEW

**Review by tejlmand — APPROVED** [review]
lgtm

**Comment by jangalda-nsc** [comment]
Release artifacts of zephyr-sdk:0.16.0 are in different format than previous ones.
Packages are in 7z/tar.xz instead of zip/tar.gz format, so changes in toolchain bundler are required.

I created ticket for it: https://projecttools.nordicsemi.no/jira/browse/NCSDK-20499
@kenr do you want to track progress using above ticket, or you want to create new one for in wayland project?

**Comment by shanthanordic** [comment]
NRFU-452 is closed @jangalda-nsc  is anything else needed more ?

**Comment by jangalda-nsc** [comment]
> NRFU-452 is closed @jangalda-nsc is anything else needed more ?

If I remember correctly, we agreed to wait for upmerge PR to be merged before we change zephyr-sdk https://github.com/nrfconnect/sdk-nrf/pull/10535. But I do not know if we want to wait longer.

In theory, some actions might be needed on upmerge PR to align with new zephyr-sdk. On the other hand, the risk is not high, because I didn't have to change any existing samples to work with zephyr-sdk:0.16.0

**Pull request merged**
