### PR TITLE
esb: samples: Add HMPAN-102 workaround to ESB and samples

### PR DESCRIPTION
**Pull request by dchat-nordic**
Add HMPAN-102 workaround for:
-ESB
-DTM sample
-radio_test sample

Jira: NCSDK-29392

### CODE REVIEW

**Review by maje-emb — COMMENTED** [review]
Should this workaround be applied only once or every time the radio is used?

**Comment by maje-emb** [comment]
What about nRF54L15?

**Comment by dchat-nordic** [comment]
> Should this workaround be applied only once or every time the radio is used?

AFAIK this should be applied every time after radio is reset/reinitialized/initialized. So in case of ESB in the init, but for dtm and radio_test the tests reset the radio, so the workaround need to be applied again.

**Review by pdunaj — APPROVED** [review]

**Review by sigurdnev — APPROVED** [review]

**Comment by dchat-nordic** [comment]
@maje-emb this applies to nRF54H20 only. The application of the workaround can be applied once if the register is not cleared (by task, or explicitly). In this case the workaround for radio_test and dtm could probably be applied once in the main function (right after hfxo starts)

**Comment by dchat-nordic** [comment]
@maje-emb Moved the workaround to one time setting.

**Comment by maje-emb** [comment]
> @maje-emb Moved the workaround to one time setting.

Thank you!

**Review by ppryga-nordic — APPROVED** [review]

**Pull request merged**
