### PR TITLE
zigbee: kconfig: Mark Zigbee subsystem as experimental

### PR DESCRIPTION
**Pull request by sebastiandraus**
This commit changes Zigbee subsystem Kconfig to select EXPERIMENTAL whenever Zigbee is enabled.

### CODE REVIEW

**Comment by greg-fer** [comment]
Hey @gautesl , can you check this PR and see why the Experimental status is not appearing for Zigbee in the doc build?

**Comment by greg-fer** [comment]
Info from @gautesl : the software maturity script pulls data from the nightly build. This PR needs to be merged first to see the table change tomorrow.

**Review by greg-fer — APPROVED** [review]

**Comment by greg-fer** [comment]
(I strongly suggest to consider adding a changelog entry for this change)

**Comment by gautesl** [comment]
It is worth noting that the top level table will not display Experimental, so this must be manually overridden if desired. As to the features, they are dependent on the options listed in the input file https://github.com/nrfconnect/sdk-nrf/blob/main/doc/_scripts/software_maturity/software_maturity_features.yaml#L30

**Comment by sebastiandraus** [comment]
> It is worth noting that the top level table will not display Experimental, so this must be manually overridden if desired. As to the features, they are dependent on the options listed in the input file https://github.com/nrfconnect/sdk-nrf/blob/main/doc/_scripts/software_maturity/software_maturity_features.yaml#L30

@gautesl , how to override the `Zigbee` entry in `top_table` to have `experimental` instead of `supported`?

**Comment by gautesl** [comment]
> > It is worth noting that the top level table will not display Experimental, so this must be manually overridden if desired. As to the features, they are dependent on the options listed in the input file https://github.com/nrfconnect/sdk-nrf/blob/main/doc/_scripts/software_maturity/software_maturity_features.yaml#L30
> 
> @gautesl , how to override the `Zigbee` entry in `top_table` to have `experimental` instead of `supported`?

The `:insert-value:` option to the `sml-table` directive will replace the autogenerated values for the specified cells: https://github.com/nrfconnect/sdk-nrf/blob/main/doc/_extensions/software_maturity_table.py#L53-L94

**Comment by sebastiandraus** [comment]
@gautesl Can you take a look into the latest changes?

**Review by gautesl — APPROVED** [review]
Looks good, these changes should appear in the generated docs when the build finishes

**Review by mariusz-nordicsemi — APPROVED** [review]

**Comment by sebastiandraus** [comment]
Looks like the Protocol support table was updated correctly, we should be ready to merge once we get CI green

**Comment by sebastiandraus** [comment]
Force-pushed to trigger CI

**Comment by sebastiandraus** [comment]
Forced push to retrigger stuck CI

**Pull request merged**
