### PR TITLE
scripts: update quarantine for nrf54h20/cpurad.

### PR DESCRIPTION
**Pull request by nordic-babu**
Samples will be automatically filtered after upmerging https://github.com/zephyrproject-rtos/zephyr/pull/73777.

### CODE REVIEW

**Review by nordic-piks — APPROVED** [review]

**Review by nordic-segl — APPROVED** [review]

**Review by miha-nordic — APPROVED** [review]

**Review by nordic-bami — APPROVED** [review]

**Review by rlubos — CHANGES_REQUESTED** [review]
Don't use sauce tags in the commit titles in this repo. Drop `[noup patch] `

**Comment by nordic-babu** [comment]
> Don't use sauce tags in the commit titles in this repo. Drop `[noup patch] `

done

**Review by rlubos — APPROVED** [review]

**Review by miha-nordic — APPROVED** [review]

**Comment by shanthanordic** [comment]
@PerMac  FYI

**Comment by anangl** [comment]
@nordic-babu please resolve the conflict.

**Comment by nordic-babu** [comment]
> @nordic-babu please resolve the conflict.

done

**Pull request merged**
