### PR TITLE
manifest: Pull PPI bugfix in sdk-zephyr

### PR DESCRIPTION
**Pull request by jori-nordic**
Pulling fix for showstopper PPI allocator bug.

### CODE REVIEW

**Review by olivier-le-sage — APPROVED** [review]

**Comment by nordic-piks** [comment]
@jori-nordic CI is failing on some tests (uart).
To have it working, please rebase sdk-zephyr PR on top of https://github.com/nrfconnect/sdk-zephyr/commit/a56fee6870e152b71a7baf5b85bfa0b9746286a0

**Comment by jori-nordic** [comment]
rebased both PRs

**Review by tejlmand — APPROVED** [review]

**Review by nordic-segl — APPROVED** [review]

**Comment by anangl** [comment]
Rebased.

**Comment by jori-nordic** [comment]
Since people apparently don't know how to use kconfig, I just added `MPSL` to the allowlist for the check.
Someone else can fix it properly when the time pressure is gone.

**Pull request merged**
