### PR TITLE
samples: matter: Enable Matter OTA on nRF54H20

### PR DESCRIPTION
**Pull request by ArekBalysNordic**
Enabled DFU over Matter OTA for nRF54H20 target.
It works using dfu_target_suit and dfu_multi_target implementations.

### CODE REVIEW

**Review by LuDuda — APPROVED** [review]

**Review by tomchy — APPROVED** [review]

**Comment by tomchy** [comment]
@ahasztag , @SylwesterKonczyk : The changes in this PR boots the flash companion as part of the `suit-candidate-verification` and skips it in `suit-install`. What do you think about it?

IMO it is fine for matter, but rather not acceptable for SUIT samples:
- the `suit-candidate-verification` in general case is not obligatory to be implemented by suit processor
- if a user starts to play with manifests and removes it from the root manifest, the update will fail).

**Comment by ArekBalysNordic** [comment]
> @ahasztag , @SylwesterKonczyk : The changes in this PR boots the flash companion as part of the `suit-candidate-verification` and skips it in `suit-install`. What do you think about it?
> 
> 
> 
> IMO it is fine for matter, but rather not acceptable for SUIT samples:
> 
> - the `suit-candidate-verification` in general case is not obligatory to be implemented by suit processor
> 
> - if a user starts to play with manifests and removes it from the root manifest, the update will fail).

I discussed it with @SylwesterKonczyk today and it seems that if we want to verify the candidate image which is stored in ext flash, we need to boot flash companion within that part. Without that the image is not applied.

**Comment by wiba-nordic** [comment]
Does this mean the nRF54H20 should be added to the list of supported devices in the DFU support section for the samples?

**Comment by ArekBalysNordic** [comment]
> Does this mean the nRF54H20 should be added to the list of supported devices in the DFU support section for the samples?

Yes, it should. I'm going to add it to the doc PR related to the release. Are you ok with this approach?

**Comment by wiba-nordic** [comment]
> > Does this mean the nRF54H20 should be added to the list of supported devices in the DFU support section for the samples?
> 
> Yes, it should. I'm going to add it to the doc PR related to the release. Are you ok with this approach?

That is absolutely fine.

**Comment by ArekBalysNordic** [comment]
@nrfconnect/ncs-code-owners @nrfconnect/ncs-co-build-system Could you please review?

**Review by kkasperczyk-no — APPROVED** [review]
Should we add release notes entry?

**Comment by wiba-nordic** [comment]
> Should we add release notes entry?

Since documentation is addressed later, it's okay to add the changelog entry at the same time.

**Comment by ArekBalysNordic** [comment]
@tejlmand @nordicjm @jukkar @jfischer-no Could you please review as code-owners?

**Review by nordicjm — APPROVED** [review]

**Pull request merged**
