### PR TITLE
doc: protcols: Update Wi-Fi samples memory footprints

### PR DESCRIPTION
**Pull request by krish2718**
* Remove non-Wi-Fi sample MQTT on 9160
* Use "twister --size" over "size" to get accurate foot prints
* Use proper sample for location that uses Wi-Fi
* Add scan sample to 9160

### CODE REVIEW

**Review by visinor — APPROVED** [review]
Looks good to me.

**Review by richabp — COMMENTED** [review]
Does it require a changelog entry?

Also, unable to see the doc preview.

**Review by sachinthegreen — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]
Thanks @krish2718

**Comment by krish2718** [comment]
> Does it require a changelog entry?
No, this is just updating the footprints.
 
> Also, unable to see the doc preview.

Yeah, not sure why though.

**Review by richabp — APPROVED** [review]

**Pull request merged**
