### PR TITLE
net: openthread: Remove overlaying for default CC3XX_LOCK_VARIANT

### PR DESCRIPTION
**Pull request by emob-nordic**
Having CC3XX_LOCK_VARIANT overlayed to atomic/hw mutexes
leads to unexpected resetes when crypto is accessed concurently
from more than one thread.
In fact both atomic and HW mutexes are just an imitation
of what mutex should do. None of above mentioned implementations
provides mutual exclusion acces to crypto backend. If any
concurency is present the whole application would restart.

Signed-off-by: Emil Obalski <emil.obalski@nordicsemi.no>

### CODE REVIEW

**Review by pdunaj — APPROVED** [review]

**Comment by MarekPorwisz** [comment]
Did you verify what is the performance drop on nRF52840?

**Comment by emob-nordic** [comment]
> Did you verify what is the performance drop on nRF52840?

In our case the performance does not matter. It wasn't working with selected options, now it does. We have more threads that are concurrently accessing crypto so we must have a well designed locking mechanism.

**Comment by emob-nordic** [comment]
I think both atomic and hardware mechanism for locking crypto are not a good thing. If you are accesing crypto from only one context there could be no locking at all and this should work. From what i checked towards hardware mutexes those are designed for other purpose and shall not be used here too.

**Comment by pdunaj** [comment]
> Did you verify what is the performance drop on nRF52840?

I back @emob-nordic here. Performance has no value in itself if the device is unstable or does not serve the primary function.
The atomic locking mechanism could be used but then the architecture design should take into account the situation where lock cannot be obtained. At the moment crypto aborts and takes down the entire device with it.

This said we have the problem understood and covered. Emil wanted to fix it so others won't get this issue but I think it's up to OT team to decide how they would like to handle it. I recommend leaving the default lock as mutex and if somebody needs performance boost and knows what their doing, let them change the lock manually.

**Comment by emob-nordic** [comment]
I would like to clarify my provious statement, because i could be misconstrued. As @pdunaj said i just want others not to fall the same issue we had. This PR is proposal, rather than thing i enforce to merge. In my opinion this could be resolved as present in PR, but its up to OT team to decide.

**Comment by emob-nordic** [comment]
Force pushed to correct commit message.

**Review by MarekPorwisz — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
