### PR TITLE
manifest: update softdevice controller and mpsl

### PR DESCRIPTION
**Pull request by ryanjh**
Added support for nRF21540 GPIO Front-End Module for nRF53 Series.

Corresponding PR in nrf: nrfconnect/sdk-nrfxlib#534

Signed-off-by: Ryan Chu <ryan.chu@nordicsemi.no>

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
According to @czeslawmakarski , this PR is now blocked by https://github.com/nrfconnect/sdk-nrf/pull/5189

**Comment by joerchan** [comment]
@czeslawmakarski @rugeGerritsen Why is there a dependency on the upmerge?

**Comment by czeslawmakarski** [comment]
@joerchan This PR updates the API of the MPSL FEM, so the 802.15.4 Radio Driver in the nrfxlib also needs to be updated. However, there is an ongoing change of the Radio Driver in the upmerge (because public API of the Radio Driver was updated also, needing a change in the sdk-zephyr, which is covered by the upmerge).

**Comment by joerchan** [comment]
Ok, thanks. Sounds like a valid reason.

DNM: Blocked by https://github.com/nrfconnect/sdk-nrf/pull/5189.

**Comment by jciupis** [comment]
I think that this PR is missing a relevant entry in the changelog. An example entry representing changes in MPSL, based on release notes for v1.5.0:
```
Front-end module (FEM)
----------------------

* Added support for RF front-end Modules (FEM) for nRF5340 in :ref:`mpsl` library. The front-end module feature for nRF5340 in MPSL currently supports nRF21540, but does not support SKY66112-11 device.
```

**Comment by rugeGerritsen** [comment]
> I think that this PR is missing a relevant entry in the changelog. An example entry representing changes in MPSL, based on release notes for v1.5.0:
> 
> ```
> Front-end module (FEM)
> ----------------------
> 
> * Added support for RF front-end Modules (FEM) for nRF5340 in :ref:`mpsl` library. The front-end module feature for nRF5340 in MPSL currently supports nRF21540, but does not support SKY66112-11 device.
> ```

@jciupis , can you add your requested release note updates in a separate PR?

**Review by rugeGerritsen — APPROVED** [review]

**Comment by e-rk** [comment]
@ryanjh  The https://github.com/nrfconnect/sdk-nrfxlib/pull/534 was merged. Can you update the nrfxlib revision to `7d93adccdf04686f5910b22362c816a54b921bc5`?

**Comment by e-rk** [comment]
In the meantime someone else (4af2c283eea8e2a1d5f7663a0ebe659e2cbd7d82) updated nrfxlib revision to `d048f584bb79997e1f60e3539b4520026ebb7745` in a different PR. I guess this pull request can be closed now.

**Pull request closed without merging**
