### PR TITLE
net: lib: Fix issues related to recent changes in AWS FOTA

### PR DESCRIPTION
**Pull request by simensrostad**
Previous to this PR AWS FOTA would fail for applications depending on ```nrf_cloud.c``` and ```aws_iot.c```.

This PR:
 * Increases the default stack size of the connection_poll thread in ```nrf_cloud.c``` and ```aws_iot.c```
 * Changes the default value for ```CONFIG_AWS_FOTA_DOWNLOAD_SECURITY_TAG```

Closes [CIA-116]

### CODE REVIEW

**Review by coderbyheart — APPROVED** [review]
Good, I have requested the change of the `AWS_FOTA_DOWNLOAD_SECURITY_TAG` default value also in #3060.

**Comment by simensrostad** [comment]
> Good, I have requested the change of the `AWS_FOTA_DOWNLOAD_SECURITY_TAG` default value also in #3060.

Yes, I've synced with @sigvartmh on this matter.

**Review by jhn-nordic — APPROVED** [review]

**Review by plskeggs — APPROVED** [review]
Works now, thanks.

**Review by sigvartmh — APPROVED** [review]
LGTM, will this fix it for asset tracker also or is a separate fix needed?

**Comment by simensrostad** [comment]
> LGTM, will this fix it for asset tracker also or is a separate fix needed?

This fix applies for the asset tracker as well.

**Pull request merged**
