### PR TITLE
manifest: update nrfxlib

### PR DESCRIPTION
**Pull request by evenl**
Manifest update for bsdlib release 0.8.0

Signed-off-by: Even Falch-Larsen <even.falch-larsen@nordicsemi.no>

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
It's be good to update the `bsd_os_errno_set()` function with the new `NRF_ECONNABORTED` rightaway.

**Comment by lemrey** [comment]
Rebased.

**Comment by lemrey** [comment]
SHA updated

**Review by rlubos — APPROVED** [review]
LGTM

**Pull request merged**
