### PR TITLE
net: lib: fota_download: Add missing log_strdup

### PR DESCRIPTION
**Pull request by plskeggs**
Add a missing log_strdup.

Signed-off-by: Pete Skeggs <peter.skeggs@nordicsemi.no>

### CODE REVIEW

**Comment by hakonfam** [comment]
IMO we should execute both DFU/bootloader and thingy91 tests on this PR since the module is used there.

**Review by rlubos — APPROVED** [review]

**Comment by plskeggs** [comment]
> IMO we should execute both DFU/bootloader and thingy91 tests on this PR since the module is used there.

@hakonfam I am not familiar with these tests.  Are they tests that can be run automatically by labelling the PR, or are you requesting someone run these tests manually?

**Comment by hakonfam** [comment]
I think we are good, considering how small the change is, and assuming you have verified this manually yourself.

There are github labels you can add to the PR in order to trigger different sets of tests.

**Comment by plskeggs** [comment]
@hakonfam yes, I tested on a 9160DK with asset tracker, with bootloader updates enabled, both with and without CONFIG_LOG_IMMEDIATE=y.  Logging looked OK and BOOT FOTA succeeded.

**Pull request merged**
