### PR TITLE
samples: serial_lte_modem: Gracefully end UDP thread

### PR DESCRIPTION
**Pull request by bjda**
Avoids aborting the UDP socket thread while blocking on the socket

Fixes NCSIDB-225

Signed-off-by: Bernt Johan Damslora <bernt.johan.damslora@nordicsemi.no>

### CODE REVIEW

**Comment by bjda** [comment]
This change consolidates the behaviour around closing the UDP socket and consistently runs slm_at_udp_proxy_init() after closing the socket, to reset all state associated with it. Please let me know if this breaks some behaviour.

**Review by rlubos — APPROVED** [review]
Looks correct to me

**Comment by bjda** [comment]
This should not be merged while https://github.com/nrfconnect/sdk-nrf/pull/3215 is open, since that PR will make changes to UDP as well as TCP client that will affect this PR

**Comment by bjda** [comment]
Closing since NCSIDB-225 is closed

**Pull request closed without merging**
