### PR TITLE
samples: zigbee: Add overlay to enable 802154 FEM & WiFi Coex

### PR DESCRIPTION
**Pull request by wbober**
This adds an overlay file to enable 802154 fem and wifi coex.

This PR depends on:
https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/2208
https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/2210

Signed-off-by: Wojciech Bober <wojciech.bober@nordicsemi.no>

### CODE REVIEW

**Comment by thst-nordic** [comment]
Hi, can you take ownership of the samples/zigbee folder in CODEOWNERS?

**Comment by wbober** [comment]
> Hi, can you take ownership of the samples/zigbee folder in CODEOWNERS?

Yes we will do it. We have modified the CODEOWNERS file in one of PRs which is prerequisite to this.

**Comment by wbober** [comment]
Apparently doesn't work on default settings, so I need to fix this.

**Comment by wbober** [comment]
Rebased and updated with changes authored by @MarekPorwisz.

**Pull request merged**
