### PR TITLE
manifest: Update the nrfxlib revision to NFC library changes

### PR DESCRIPTION
**Pull request by KAGA164**
Updates nrfxlib revision which provides the
NFC library changes.

### CODE REVIEW

**Review by grochu — APPROVED** [review]
Changes are approved in the related nrfxlib PR, so this looks good.

**Comment by carlescufi** [comment]
closed by mistake.

**Review by tejlmand — APPROVED** [review]

**Review by kapi-no — APPROVED** [review]

**Comment by jfischer-no** [comment]
@KAGA164 please rebase

**Comment by SebastianBoe** [comment]
Let us wait and see if https://github.com/nrfconnect/sdk-nrf/pull/5497
goes green.

Then we can merge it and close this.

This is the path with the least amount of paperwork.

**Comment by mbolivar-nordic** [comment]
This has red CI and conflicts with master, and as mentioned above by @SebastianBoe , #5497 is ahead, so there's no need for this one anymore as it can't be merged anyway.

**Pull request closed without merging**
