### PR TITLE
ci: use v1.7-branch fork of CI

### PR DESCRIPTION
**Pull request by thst-nordic**
Loads the exact CI when sdk-nrf:v1.7.0 was tagged

Signed-off-by: Thomas Stilwell <Thomas.Stilwell@nordicsemi.no>

### CODE REVIEW

**Comment by PerMac** [comment]
Why do we want such change? Does it mean we want to use only a strictly defined version of CI_LIB for all consecutive PRs until the next release? Shouldn't CI be based on "master" i.e. the latest version of the libraries?

**Comment by thst-nordic** [comment]
yes, this just freezes the CI configuration for the v1.7-branch.

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
I'll wait for @PerMac 's ACK before merging

**Comment by PerMac** [comment]
Right, I missed that this affects v1.7 branch

**Review by PerMac — APPROVED** [review]

**Pull request merged**
