### PR TITLE
Updated OpenThread libraries and memory usage info

### PR DESCRIPTION
**Pull request by maciejbaczmanski**
KRKNWK-16317

### CODE REVIEW

**Review by canisLupus1313 — APPROVED** [review]

**Review by mariuszpos — APPROVED** [review]

**Review by wiba-nordic — APPROVED** [review]

**Review by canisLupus1313 — COMMENTED** [review]
You should update https://github.com/nrfconnect/sdk-nrf/blob/main/subsys/net/openthread/Kconfig.defconfig library avaliable config

**Review by canisLupus1313 — CHANGES_REQUESTED** [review]
And squash commits.

**Review by edmont — APPROVED** [review]

**Comment by edmont** [comment]
> You should update https://github.com/nrfconnect/sdk-nrf/blob/main/subsys/net/openthread/Kconfig.defconfig library avaliable config

This is already present in this PR.

> And squash commits.

You mean manifest and doc update commits? IMO it's okay to have them separately.

**Comment by maciejbaczmanski** [comment]
> And squash commits.

@canisLupus1313 this PR was prepared to look the same as last one (https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html) to keep consistency

**Comment by canisLupus1313** [comment]
@maciejbaczmanski Ok the previos one had a bug.

**Review by LuDuda — APPROVED** [review]

**Review by canisLupus1313 — APPROVED** [review]

**Pull request merged**
