### PR TITLE
Ncs1.2.1 bsdlib 0.6.1.2

### PR DESCRIPTION
**Pull request by evenl**

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
@carlescufi I see this is for the 1.2 branch. Should we backport the repository move to nrfconnect into the manifest for this branch as well (in a separate PR)?

**Comment by carlescufi** [comment]
> @carlescufi I see this is for the 1.2 branch. Should we backport the repository move to nrfconnect into the manifest for this branch as well (in a separate PR)?

I don't think that is necessary, and has the potential for confusion. Unless there is a reason to do so, I would be conservative and leave it as-is.

**Comment by rlubos** [comment]
@evenl Please update the manifest: 8d46f44ba488d36e5a83bc2fc57d313f4db8d1f4

**Comment by rlubos** [comment]
@mbolivar-nordic Your request was addressed, could you revisit this PR?

**Pull request merged**
