### PR TITLE
scripts: Add ruby as requirement to all tools-versions files

### PR DESCRIPTION
**Pull request by karhama**
Adding Ruby as a requirement because it is required for application tests

### CODE REVIEW

**Review by tejlmand — COMMENTED** [review]
Is this required for v1.8.0 ?

And in which way is this used for application tests ?
Could you please provide some more details.

@bencefr I assume that if this is a requirement, then the toolchain must be updated.
@shantha-14 FYI.

**Comment by bencefr** [comment]
Is this required for end users? This will break the toolchain installations as the toolchain does not include ruby.

**Comment by tejlmand** [comment]
@karhama if not having ruby installed, then I think we should prepare a known issue here: https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/known_issues.rst
describing what is not working for the release.

**Comment by karhama** [comment]
Anything using this: https://github.com/nrfconnect/sdk-nrf/blob/main/tests/unity/CMakeLists.txt#L17  will fail if you don't have ruby. We have seen twister & west build failures in applications/asset_tracker_v2/tests/

@thst-nordic had discussion with @nvlsianpu about this issue and based on this I was asked to create PR. Unfortunately I cannot comment if this is required for end users.

**Comment by nvlsianpu** [comment]
@tejlmand Should this patch go in? I thought it should.

**Review by thst-nordic — APPROVED** [review]

**Comment by tejlmand** [comment]
> @tejlmand Should this patch go in? I thought it should.

A little late now, but should not go in for the release, cause it won't be part of the official toolchain.
Thus we should wait merging till after the release.

**Comment by thst-nordic** [comment]
good to merge?  @tejlmand @nvlsianpu

**Comment by bencefr** [comment]
I am not convinced about this change. As far as I know this file is used by the online documentation to list the required tools for the end users where it is stated that it these tools are installed by the toolchain manager. That is not going to be true for ruby. Besides if ruby is only needed for internal testing systems, I see no reason to list it here. Please correct me if I'm wrong.

**Comment by tejlmand** [comment]
> Besides if ruby is only needed for internal testing systems, I see no reason to list it here.

ruby is used by all unit tests that are based on unity.
end-users are expected to be able to run unit tests locally to verify that source code is working as expected.

**Comment by kenr** [comment]
Is this decision thought through? We are adding an additional ecosystem to sandbox and maintain... We already have python and pip, this would be ruby and gem.

**Comment by tejlmand** [comment]
> We already have python and pip, this would be ruby and gem.

@kenr But ruby was already a requirement since March, 2019.
https://github.com/nrfconnect/sdk-nrf/pull/519
https://github.com/nrfconnect/sdk-nrf/blob/3e9be15495f57cc1d923a976157a02e11e617fb8/tests/unity/unity_test.cmake#L27

just never informed to our users that ruby was such a requirement.

This PR only ensures that this requirement is now informed to users and can be made part of the NCS Toolchain.

**Review by tejlmand — APPROVED** [review]

**Comment by nvlsianpu** [comment]
[DNM] on @kenr suggestion.

**Review by nvlsianpu — APPROVED** [review]

**Review by balaji-nordic — APPROVED** [review]

**Comment by balaji-nordic** [comment]
@nvlsianpu I have removed the DNM label as @kenr 's question had been  answered.

**Pull request merged**
