### PR TITLE
manifest: Update Zephyr to pull in GATT Caching fixes

### PR DESCRIPTION
**Pull request by MarekPieta**
Change updates Zephyr to pull in fixes for GATT caching issues.

Jira: NCSDK-19554

### CODE REVIEW

**Comment by MarekPieta** [comment]
If possible, fix for https://github.com/zephyrproject-rtos/zephyr/issues/54770 should be also pulled in (as soon as the issue is fixed in Zephyr upstream)

**Comment by miha-nordic** [comment]
It is good to merge. No issues on test plans related to this PR.

**Review by miha-nordic — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Comment by MarekPieta** [comment]
Discussed with @pdunaj, decided that the fix is too risky to introduce it after RC1. Removed milestone.

**Comment by MarekPieta** [comment]
The `west.yml` was already updated, so that the used `sdk-zephyr` revision contains my changed. I close the ticekt.

**Pull request closed without merging**
