### PR TITLE
manifest: zephyr update for l2cap fix

### PR DESCRIPTION
**Pull request by ilhanates**
Updates zephyr for ble l2cap fix
Zephyr issue: #42862

Signed-off-by: Ilhan Ates <ilhan.ates@nordicsemi.no>

### CODE REVIEW

**Comment by jfischer-no** [comment]
@ilhanates please update manifest

**Comment by jfischer-no** [comment]
@ilhanates please rebase

**Comment by ilhanates** [comment]
> @ilhanates please rebase

do i still need as other PRs are merged to sdk-zephyr?

**Comment by jfischer-no** [comment]
Yes this one is targeting main branch.

**Comment by ilhanates** [comment]
Ok then i will set it to sdk-zephyr's tip 8d85e222974cef658a35e1d024b7cec26d446062
as manifest already passed.

**Review by jfischer-no — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]
lgtm

**Pull request closed without merging**
