### PR TITLE
Fix nrf53 build failing in mpsl/timeslot sample.

### PR DESCRIPTION
**Pull request by weeTike**
Fix mpsl/timeslot sample not compiling for nrf5340dk_nrf5340_cpunet because of missing kconfig flag.

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
I thought https://github.com/nrfconnect/sdk-nrf/pull/3885/files should have fixed it. Is that not the case? @hakonfam

**Comment by joerchan** [comment]
@weeTike What is the compilation error when partition manager is not enabled? Seems strange that enabling it would be required.
If there is there is a dependency missing in Kconfig IMO.

**Comment by rugeGerritsen** [comment]
It would be nice to get https://github.com/nrfconnect/sdk-nrf/pull/3888 as part of this PR

**Comment by joerchan** [comment]
@weeTike Looks like the issue has been fixed in Kconfig. Please confirm, and close this PR as it should not be needed.

**Comment by weeTike** [comment]
Yes. My mistake.

**Pull request closed without merging**
