### PR TITLE
[backport-v1.9] lib: nrf_modem_os: Use IRQ_PRIO_LOWEST instead of hard-coded 6

### PR DESCRIPTION
**Pull request by anangl**
Backport of #7774 into v1.9-branch.

### CODE REVIEW

**Review by lemrey — APPROVED** [review]
Thanks

**Comment by PerMac** [comment]
@mbolivar-nordic Can you please help sorting out the failure of the OSS History action?

**Comment by PerMac** [comment]
@thst-nordic Are the checks here configured correctly? It shows it is waiting for required CI/Jenkins/twister, and integration, however there are already other checks for twister and also CI/Jenkins/NRF

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic Can you please help sorting out the failure of the OSS History action?

@PerMac this should be fixed by https://github.com/nrfconnect/sdk-nrf/pull/8041

**Review by rlubos — APPROVED** [review]

**Pull request merged**
