### PR TITLE
SPM: Make SPM and TF-M use soc_secure API

### PR DESCRIPTION
**Pull request by joerchan**
This PR is to remove some noup commits in sdk-zephyr.
- SPM secure service usage
- TFM_BL2 not supported.
- overlay-tfm in echo server sample

### SPM secure service usage:
Refoctor the way that non-secure accesses the secure services by introducing a soc_secure API that is independent of the secure image used.

These functions are:
- soc_secure_mem_read
- soc_secure_gpio_pin_mcu_select 

For SPM and TF-M an adaption layer is added that aligns it to the secure service exposed by the secure image.

In this setup out-of-tree patches in zephyr code is no longer needed for SPM secure services support.

NOTE: soc_secure_gpio_pin_mcu_select is not implemented in SPM.
This is because this is not needed since in SPM zephyr is used in the secure image and all GPIO pin configured will be done from that image.
SPM also does not expose a secure service for this functionality at the moment.

### TF-M BL2 not supported:
Introduce a configuration that can be selected in out-of tree (nrfxlib) instead of carrying a depends on in downstream.

### Overlay-tfm in echo-server
Does not compile, and commit message said this was temporary. Reported as an issue and if this is still required an updated overlay file will be added back.

### CODE REVIEW

**Review by mbolivar-nordic — COMMENTED** [review]
Is this a draft? The description says it adds a set of functions, but I just see one function. Sorry if this is a basic question; I am not familiar with this area.

**Comment by joerchan** [comment]
> Is this a draft? The description says it adds a set of functions, but I just see one function. Sorry if this is a basic question; I am not familiar with this area.

Not a draft no, but I understand the confusion since the PR description was not very descriptive.
I've updated it now, hopefully it should be more clear what this is doing now.

**Review by sigvartmh — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
Needs rebase; looks like CI is failing due to the conflict in west.yml

**Comment by carlescufi** [comment]
https://github.com/nrfconnect/sdk-zephyr/pull/771 is merged now.

**Comment by mbolivar-nordic** [comment]
Seems like we're having trouble with CI on this one. @joerchan if you get another red result when you rebase and you can confirm in a comment here in this PR that it's not related to your changes, I will force merge

**Comment by joerchan** [comment]
Rebased and updated SHA.

**Comment by joerchan** [comment]
@mbolivar-nordic Rebased, the CI issue is not related to the PR, there is an unstable test, which passed on re-run.

**Pull request merged**
