### PR TITLE
doc: wifi: improve structure of protocols/wi-fi page

### PR DESCRIPTION
**Pull request by richabp**
Improved the structure of the Protocols/Wi-Fi page by splitting the memory requirements page into two sections for station mode and scan mode.

Regrouped other guides based on different modes.

NCSDK-25529

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]
Thanks!

**Review by sachinthegreen — APPROVED** [review]

**Comment by richabp** [comment]
@sachinthegreen @mjd90 : For consistency in the documentation, I have replaced the _Wi-Fi driver or nRF70 Series driver_ with **nRF70 Series Wi-Fi driver** at all instances in all guides (as different terms are used in different guides at present). 

@ioannisg pointed out in an offline discussion that once the nRF71 Series comes (aprox. in a year), everything under Protocols/Wi-Fi will eventually apply for the nRF71 Series.

So, should the driver's name be changed to a more generic term like "nRF Wi-Fi host driver" or "nRF Wi-Fi driver" in all Protocols/Wi-Fi user guides at all instances now, or it can be changed later?

**Comment by sachinthegreen** [comment]
> @sachinthegreen @mjd90 : For consistency in the documentation, I have replaced the _Wi-Fi driver or nRF70 Series driver_ with **nRF70 Series Wi-Fi driver** at all instances in all guides (as different terms are used in different guides at present).
> 
> @ioannisg pointed out in an offline discussion that once the nRF71 Series comes (aprox. in a year), everything under Protocols/Wi-Fi will eventually apply for the nRF71 Series.
> 
> So, should the driver's name be changed to a more generic term like "nRF Wi-Fi host driver" or "nRF Wi-Fi driver" in all Protocols/Wi-Fi user guides at all instances now, or it can be changed later?

My vote would be for `nRF Wi-Fi driver`. I would also vote for doing this sooner rather than later so that we can follow the same terminology for any further documentation.

**Comment by richabp** [comment]
> > @sachinthegreen @mjd90 : For consistency in the documentation, I have replaced the _Wi-Fi driver or nRF70 Series driver_ with **nRF70 Series Wi-Fi driver** at all instances in all guides (as different terms are used in different guides at present).
> > @ioannisg pointed out in an offline discussion that once the nRF71 Series comes (aprox. in a year), everything under Protocols/Wi-Fi will eventually apply for the nRF71 Series.
> > So, should the driver's name be changed to a more generic term like "nRF Wi-Fi host driver" or "nRF Wi-Fi driver" in all Protocols/Wi-Fi user guides at all instances now, or it can be changed later?
> 
> My vote would be for `nRF Wi-Fi driver`. I would also vote for doing this sooner rather than later so that we can follow the same terminology for any further documentation.

Thanks Sachin!
This PR replaces the _nRF70 Series Wi-Fi driver_ with _nRF Wi-Fi driver_ in all Protocols/Wi-Fi user guides only.

**Review by bama-nordic — APPROVED** [review]

**Review by kittydepa — APPROVED** [review]

**Pull request merged**
