### PR TITLE
tree: Remove CI checks on nrf51 boards

### PR DESCRIPTION
**Pull request by pdunaj**
Do not check code on nrf51 boards.

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Review by MarekPieta — APPROVED** [review]

**Comment by shantha-14** [comment]
Added DNM as Kenneth suggested to consult other Tech Support and we need to update to release notes highlights @greg-fer @umapraseeda

**Comment by greg-fer** [comment]
@shantha-14 , @pdunaj , if we need to update the release notes highlights, this means we need a changelog entry. Pawel, can you add one, and closer to release we promote it to a highlight?

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@PerMac please review this.

**Review by PerMac — APPROVED** [review]

**Comment by PerMac** [comment]
"Integration" failure looks unrelated to the PR

**Pull request merged**
