### PR TITLE
lib: bsdlib: Update nRF91 offloading support

### PR DESCRIPTION
**Pull request by tommi-m**
Add MSG_TRUNC flag and SO_SNDTIMEO socket option support
in nRF91 offloading.

Signed-off-by: Tommi Mammela <tommi.mammela@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
You should update `west.yml` zephyr revision to `pull/295/head` in order to get the CI running (after checkpatch issues are resolved). Otherwise LGTM.

Adding DNM until fw-nrfconnect-zephyr dependency is merged.

**Comment by tommi-m** [comment]
> You should update `west.yml` zephyr revision to `pull/295/head` in order to get the CI running (after checkpatch issues are resolved). Otherwise LGTM.
> Adding DNM until fw-nrfconnect-zephyr dependency is merged.

@rlubos Is the checkpatch already solved?

**Comment by rlubos** [comment]
@tommi-m It seems it was passing in one of the earlier builds, right now the CI is failing due to a conflict during a rebase.

**Comment by tommi-m** [comment]
Seems that my rebase was not succesful. I'll close this PR and start a new one with updated master.

**Comment by plskeggs** [comment]
Looks good to me.

**Comment by rlubos** [comment]
Please rebase this PR after upmerge, as well as corresponding `sdk-zephyr` PR.

**Comment by rlubos** [comment]
Finally... Please update sdk-zephyr SHA in `west.yml`:
7bd90a18c319548415ede8f7a2edc752661aecdb

**Comment by rlubos** [comment]
@tommi-m The CLA status got reset after the transition to `nrfconnect` GH space, I assume you have not signed it after that? Please do it (see the CLAassistant comment above).

**Pull request merged**
