### PR TITLE
manifest: update twister for dynamic scope selection

### PR DESCRIPTION
**Pull request by PerMac**
Needed in order to use test_plan.py script generating a dynamic scope for twister

### CODE REVIEW

**Comment by PerMac** [comment]
The failures are random nrfjprog issues in hm setups. I rerun the failed downstreams and they passed, but it is not seen in statuses the here.

**Review by gchwier — APPROVED** [review]

**Review by alexsven — APPROVED** [review]
This include cherry-picks needed for Audio,  so I'll just tag along on this PR

**Comment by rugeGerritsen** [comment]
Your changes were included by https://github.com/nrfconnect/sdk-nrf/pull/12984

**Comment by PerMac** [comment]
no longer needed, already pulled with later manifest update

**Pull request closed without merging**
