### PR TITLE
Disable legacy mbedtls by default

### PR DESCRIPTION
**Pull request by SebastianBoe**
I don't know why we are enabling legacy mbedtls by default for TF-M builds.

This PR changes the defaults to default n.

I have observed that we save 4kB of RAM in the sha256 sample with this PR.

### CODE REVIEW

**Review by vili-nordic — APPROVED** [review]

**Comment by maciejbaczmanski** [comment]
Internal tests on Thread samples have been scheduled for this PR as well, so please wait for results before merging

**Comment by frkv** [comment]
Note that this PR is exploratory work. Likely there are still internal and external dependencies for legacy crypto toolbox configurations and legacy Mbed TLS APIs

**Review by krish2718 — COMMENTED** [review]
For Wi-Fi parts.

**Review by krish2718 — APPROVED** [review]

**Review by maciejbaczmanski — APPROVED** [review]
OpenThread's side looks good

**Review by mswarowsky — APPROVED** [review]
Should run a crypto nightly on this as well, else looks fine for me

**Comment by SebastianBoe** [comment]
I'm giving up on this.

We are getting much closer to be able to deprecate legacy mbedtls, and at that time it should be much easier to disable it.

**Pull request closed without merging**
