### PR TITLE
Add NeQuick ionospheric correction support

### PR DESCRIPTION
**Pull request by plskeggs**
Finish implementation of NeQuick in various libraries and samples.

### CODE REVIEW

**Comment by hiltunent** [comment]
Looks good but there is one more place you could change. In samples/nrf9160/modem_shell/src/gnss/gnss.c there is function gnss_inject_agps_data() which is supposed to set every a-gps data flag. I think you should add Nequick flag there too.

**Comment by plskeggs** [comment]
> Looks good but there is one more place you could change. In samples/nrf9160/modem_shell/src/gnss/gnss.c there is function gnss_inject_agps_data() which is supposed to set every a-gps data flag. I think you should add Nequick flag there too.

What will happen if we inject NeQuick data to a modem running older firmware which does not support it?

**Comment by hiltunent** [comment]
> > Looks good but there is one more place you could change. In samples/nrf9160/modem_shell/src/gnss/gnss.c there is function gnss_inject_agps_data() which is supposed to set every a-gps data flag. I think you should add Nequick flag there too.
> 
> What will happen if we inject NeQuick data to a modem running older firmware which does not support it?

Okay, I see the potential problem now. Modem should just reject it. If it happens silently, I think that is ok. That being said, I have not tried it. I would test it but I am not sure if the cloud is serving up the NeQuick already, and if so, do I need to use e.g. the beta channel?

**Comment by tokangas** [comment]
> What will happen if we inject NeQuick data to a modem running older firmware which does not support it?

I tried with MFW v1.3.4 and GNSS accepts NeQuick data without an error even though the data is not used. So, it should be safe to add the `NRF_MODEM_GNSS_AGPS_NEQUICK_REQUEST` flag to modem_shell `gnss_inject_agps_data()` function as Tuomas suggested.

**Comment by plskeggs** [comment]
I went ahead and enabled it everywhere.  Hopefully that's not a mistake.  Testing needed using a variety of modem firmware versions.

**Review by glarsennordic — APPROVED** [review]

**Review by jayteemo — APPROVED** [review]

**Review by tokangas — APPROVED** [review]

**Review by simensrostad — APPROVED** [review]

**Pull request merged**
