### PR TITLE
doc: Fixed generating software maturity table for Matter

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
Currently the software maturity table is generated in a wrong way for Matter, because it shows experimental support for all features on nRF5340 instead of supported. That's because nRF7002DK configuration that is experimental affects nRF5340 results due to using the same SoC.

Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>

### CODE REVIEW

**Comment by kkasperczyk-no** [comment]
@greg-fer I wasn't sure if I should add tech writer to the review, so please remove doc-required label in case you don't see the point of reviewing this change.

**Review by greg-fer — APPROVED** [review]

**Comment by gautesl** [comment]
I tested this with a local build from 2.1.1, and it still outputs experimental for nRF5340. I will look into why.

**Review by LuDuda — COMMENTED** [review]
LGTM :+1:

Could we add Matter to the `top_table` above?

**Comment by kkasperczyk-no** [comment]
Sorry for confusion, but something is broken with this PR and I cannot update the content of it to address the changes (github bug?). I'm closing this PR and opening new one here: https://github.com/nrfconnect/sdk-nrf/pull/9119

**Pull request closed without merging**
