### PR TITLE
tree-wide: Update sample.yaml

### PR DESCRIPTION
**Pull request by MarekPieta**
Change updates sample.yaml files for:

- Event Manager sample
- Profiler sample
- EI data forwarder sample
- Event Manager test

See #4444 for details.

Jira: NCSDK-9292

### CODE REVIEW

**Comment by PerMac** [comment]
@MarekPieta For start, I would suggest leaving platform_allow lists in the samples. Twister always does some prefiltering first, before running tests. The simplest option is to have platform_allow list, everything outside will be blocked. A more "sophisticated" one requires using `filter` or `depends_on` in the yaml. Then the filtering won't be name dependant but feature dependant. In other words, if a sample is highly platform-specific, then `platform_allow` is a way to go. However, if it is feature-specific then filtering on feature is better and more future-proof (no need of modification of the sample when new platforms are added) 
If the current PR no filtering is left, so in the nightly build, where a greater plarform scope is chosen (not limited to integration platforms) you probably will get a lot of failures on unsupported boards.

**Comment by MarekPieta** [comment]
@PerMac I think that our samples do not have too many special requirements related to boards (I did not see anything relevant that I could put under depends on). I was wondering about running a nightly on the PR to see if there will be failures. In case there would be unsupported boards, we could add them as `platform_exclude` (I expect that the sample would work on most of the boards).

If bringing back the platform_allow list is a preferred approach for now, I could of course do it.

**Comment by MarekPieta** [comment]
Adding `platform_allow` would definitely be better approach for nrf_desktop application. The application configuration supports only predefined subset of boards.

**Comment by PerMac** [comment]
There is no requirement for having any specific filtration. Your approach (try broad and then limit if needed) is perfectly valid

**Review by PerMac — APPROVED** [review]

**Comment by MarekPieta** [comment]
Excluded `native_posix` and `qemu_x86` from some tests - RTT is not supported and it causes build failure.

**Review by pdunaj — APPROVED** [review]

**Pull request merged**
