### PR TITLE
samples: allow sanity check to build and run on nRF5340 DK

### PR DESCRIPTION
**Pull request by ioannisg**
Modify samples .yml files to allow sanitycheck to
build and execute the samples on nRF5340 DK HW as well.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Comment by ioannisg** [comment]
FYI, added a 1.4.0 milestone @shantha-14 @carlescufi (feel free to drop this if needed)

**Review by PerMac — APPROVED** [review]
Should work, but keep in mind that calling sanitycheck also requires arguments with the boards the tests should be run on, so the CI plan might have to be modified as well to run those tests.
And allow listing is very sub-optimal way of handling tests. I've seen it being abused in internal tests and it looks like becoming a standard... We will have to have a new standard defined but I am waiting for the upstream PR with filtering based on DTS, so we won't have to repeat a "tutorial"

**Comment by PerMac** [comment]
To clarify: allow listing doesn't make the CI (or sanitycheck) to run by default on the listed platforms. It prevents anything that is not on the list to be run.

**Comment by ioannisg** [comment]
> To clarify: allow listing doesn't make the CI (or sanitycheck) to run by default on the listed platforms. It prevents anything that is not on the list to be run.

Noted thanks

**Comment by ioannisg** [comment]
> Should work, but keep in mind that calling sanitycheck also requires arguments with the boards the tests should be run on, so the CI plan might have to be modified as well to run those tests.
> And allow listing is very sub-optimal way of handling tests. I've seen it being abused in internal tests and it looks like becoming a standard... We will have to have a new standard defined but I am waiting for the upstream PR with filtering based on DTS, so we won't have to repeat a "tutorial"

My intention is to ensure that sanity check won't block the build/execution of the tests on the DK. What needs to be done in CI is out of scope of this PR.

**Comment by ioannisg** [comment]
@shantha-14 overlay files are added now, where it was needed.

**Comment by PerMac** [comment]
> > Should work, but keep in mind that calling sanitycheck also requires arguments with the boards the tests should be run on, so the CI plan might have to be modified as well to run those tests.
> > And allow listing is very sub-optimal way of handling tests. I've seen it being abused in internal tests and it looks like becoming a standard... We will have to have a new standard defined but I am waiting for the upstream PR with filtering based on DTS, so we won't have to repeat a "tutorial"
> 
> My intention is to ensure that sanity check won't block the build/execution of the tests on the DK. What needs to be done in CI is out of scope of this PR.

And mine was to give a general remark, as this seems to be a topic of confusion and I used this forum were some broader audience is present:)

**Comment by rugeGerritsen** [comment]
@ioannisg , will you consider adding samples/mpsl/timeslot as well? See https://github.com/nrfconnect/sdk-nrf/pull/3021

**Review by trond-snekvik — APPROVED** [review]

**Review by kapi-no — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by torsteingrindvik — APPROVED** [review]

**Comment by ioannisg** [comment]
> @ioannisg , will you consider adding samples/mpsl/timeslot as well? See #3021

@rugeGerritsen this was out-of-scope for this PR: the sample is not selected at all for nRF5340 platform. The purpose here was to run the samples on the DK, if they already build/run on the PDK.

**Review by KAGA164 — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

**Review by shantha-14 — APPROVED** [review]

**Pull request merged**
