### PR TITLE
SoftDevice Controller: Unify configuration names

### PR DESCRIPTION
**Pull request by rugeGerritsen**
Prefixes all configuration names with either BT_CTLR or BT_LL_.

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
Added DNM as there are some changes required to test repositories.

**Review by pdunaj — APPROVED** [review]

**Review by KAGA164 — APPROVED** [review]

**Comment by carlescufi** [comment]
@rugeGerritsen please rebase and address the CI failures.

**Comment by rugeGerritsen** [comment]
Rebased on main

**Comment by rugeGerritsen** [comment]
This PR needs additional changes to nrfxlib. Will create that PR soon

**Review by alwa-nordic — APPROVED** [review]

**Comment by rugeGerritsen** [comment]
Rebased on main to bring in homekit changes

**Review by AyturkDuzen — APPROVED** [review]

**Comment by rugeGerritsen** [comment]
Updated manifest file to point to the sha of nrfxlib

**Comment by rugeGerritsen** [comment]
Rebased on main to retrigger CI. Removing some CI labels

**Pull request merged**
