### PR TITLE
scripts/tools-versions-*.txt: Update to current versions

### PR DESCRIPTION
**Pull request by martingalvan-nordic**
The PR updates the tools-versions{linux,win10,darwin}.txt files to use
the versions of the tools that we've been testing the toolchain bundles
with.

* For all three OSs, we removed gnuarmemb, SES, and ruby, and added
zephyr-sdk and nanopb.
* For Windows and macOS, we removed the GN version since in practice the
bundler will ignore it and retrieve the latest release.
* For macOS we changed the versions to those that will actually work
with the current bundler code. Since the bundler uses homebrew to
retrieve many of the tools, versions such as Python 3.8.2 were not
available and had to be updated. We also removed the version 'hashes',
since they were not used by the bundler code.
* For Linux, while the bundler currently ignores the file, we still
updated the versions to show what the bundler will retrieve.

### CODE REVIEW

**Review by LuDuda — APPROVED** [review]
`GN` part is ok. Thanks.

**Review by jangalda-nsc — APPROVED** [review]

**Comment by martingalvan-nordic** [comment]
I noticed that this failed the Documentation Build job. Apparently, the docs require some of the versions that I removed, so that would have to be fixed as well.

If anyone wants to add that fix, feel free to push it to this branch. In the meanwhile I will leave this PR open since merging it would break things. Thanks!

**Review by carlescufi — APPROVED** [review]

**Review by shantha-14 — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by gmarull** [comment]
Please make sure to update https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/versions.txt.in, some deleted entries may be still referenced there.

**Comment by martingalvan-nordic** [comment]
> Please make sure to update https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/versions.txt.in, some deleted entries may be still referenced there.

I believe it would be better if the maintainers of this repository fixed it, and perhaps added a reference to the Zephyr SDK somewhere. I sent this PR to make the transition easier, but we not really maintaining any of this code nor would know how to build/test it, etc. Thanks!

**Pull request merged**
