### PR TITLE
nrf: lib: multi_callback: Create multi_callback util lib

### PR DESCRIPTION
**Pull request by glarsennordic**
Create a utility library, multi_callback, for defining multiple-listener callbacks.

IRIS-4902

Signed-off-by: Georges Oates_Larsen <georges.larsen@nordicsemi.no>

### CODE REVIEW

**Comment by glarsennordic** [comment]
Not yet ready for review, just a draft.

**Comment by glarsennordic** [comment]
I still need to write unit tests and work out how best to actually integrate this into NCS, but I could use an initial review just to make sure this is actually a sane approach to this problem.

I went with static inline functions rather than straight-up function-like macros as much as possible to hopefully make error messages a bit friendlier if things go wrong. The CALL macro has to be a function-like macro in order to avoid true var-args. This means arg count and types can be checked for correctness at build-time, although the error messages produced when this happens are a bit hard to interpret. I am open to suggestions on how to improve on that.

**Comment by glarsennordic** [comment]
Sample usage:

```c
typedef void (*test_cb_t)(int x, int y);
MCB_DEFINE(my_test_mcb, test_cb_t, 20);

static void test_cb_a(int x, int y) {
	LOG_ERR("I am a callback A! %d %d", x, y);
}

static void test_cb_b(int x, int y) {
	LOG_ERR("I am a callback B! %d %d", x, y);
}
```

Then, later:

```c
(void)MCB_LISTEN(my_test_mcb, test_cb_a);
(void)MCB_LISTEN(my_test_mcb, test_cb_b);
MCB_CALL(my_test_mcb, 10, 20);
```

**Comment by glarsennordic** [comment]
Another example:

```C
#include <multi_callback.h>
typedef void (*test_cb_t)(int x, int y);
MCB_DEFINE(my_test_mcb, test_cb_t, 20);

static void test_cb_a(int x, int y) {
	LOG_ERR("I am a callback A! %d %d", x, y);
}

static void test_cb_b(int x, int y) {
	LOG_ERR("I am a callback B! %d %d", x, y);
}

static void test_cb_c(int x, int y) {
	LOG_ERR("I am a callback C! %d %d", x, y);
}
```

Later:
```C

```
	int slot;

	(void) MCB_LISTEN(my_test_mcb, test_cb_a);
	(void) MCB_LISTEN(my_test_mcb, test_cb_b);
	slot = MCB_LISTEN(my_test_mcb, test_cb_c);

	MCB_CALL(my_test_mcb, 10, 20);

	(void) MCB_UNLISTEN_SLOT(my_test_mcb, slot);

	MCB_CALL(my_test_mcb, 30, 40);

	(void) MCB_UNLISTEN(my_test_mcb, test_cb_a);

	MCB_CALL(my_test_mcb, 50, 60);

	(void) MCB_UNLISTEN(my_test_mcb, test_cb_b);

	MCB_CALL(my_test_mcb, 70, 80);
```

Output:

```
[00:00:00.494,995] <err> application: I am a callback A! 10 20
[00:00:00.495,025] <err> application: I am a callback B! 10 20
[00:00:00.495,025] <err> application: I am a callback C! 10 20
[00:00:00.495,056] <err> application: I am a callback A! 30 40
[00:00:00.495,086] <err> application: I am a callback B! 30 40
[00:00:00.495,086] <err> application: I am a callback B! 50 60
```

**Comment by lemrey** [comment]
This is a functionality of the common application framework (`caf`), in particular of the `event_manager`, which allows different parts of the application to define and subscribe to events. There are some libraries that support similar mechanisms for their own purposes, like the Modem library integration layer for `_init` and `_shutdown` callbacks, or the AT monitor for dispatching AT notifications; but that's a slightly different use case, since there is one producer of events and many consumers.

If you need to subscribe/send events from/to different parts of the application, check the `event_manager`. It's used in `asset_tracker_v2` for example.

**Comment by glarsennordic** [comment]
> but that's a slightly different use case, since there is a single producer of events (the library) and many listeners.

Ah, yes, sorry, I should have said this:

Single-producer, multiple-listener libraries is exactly the use case this was meant to target. I was not intending to overlap with CAF's multiple source, multiple listener capabilities. I was hoping that this could be a utility that libraries like the ones you mention could rely on instead of having it re-implemented on a per-library basis as is currently the case. This is almost a verbatim copy of the multi-listener callback in `sms.c`. 

The use-cases I have in mind for this are some libraries that are currently single-producer, single-listener that I would like to upgrade to single-producer multi-listener without changing too much else about them. Switching to CAF for those libraries would require a lot of refactoring. Or do you feel that would be preferable to this? @lemrey

**Comment by lemrey** [comment]
It seems this use case is yet different, and I don't understand it that well. Maybe you could provide a sample showing how this would work? The snippet is lacking an important information: am I correct that these callbacks defined and invoked from the same C file?

**Comment by glarsennordic** [comment]
You're absolutely right, a more complete demonstration would have been a good idea. Sorry about that!

I'll throw on a hypothetical commit that demonstrates what upgrading one of the libraries I have my eye on to support multiple listeners would look like.

And yes, you are correct, the callbacks are defined and invoked from within the same C file, and are meant only to be used (directly, at least) by that C file.

**Comment by glarsennordic** [comment]
Okay, I've gone ahead and created the commit! I've tested it with MMSS, and it does work.

I decided to add a built-in mutex, since I couldn't think of a scenario where it would not be wanted, and it significantly reduced the amount of boiler-plate in my demo.

One major caveat: Nothing prevents a listener from attempting to modify the listener list in response to being called. That should be explicitly disallowed. But I'm not sure if whether should actually hard-code protection against it, or just warn about it in the header docs.

**Review by lemrey — COMMENTED** [review]
I think this use case is better served by placing variables in a section like it's done for example in `at_monitor.h`. Instead of runtime registration you have compile-time registration which does not waste any RAM and does not have the overhead of registering the callbacks at runtime.

It is also more flexible because each library can decide how to use those callbacks, e.g. protect them with mutexes, dispatch them via a workqueue etc. depending on the use case.

**Pull request closed without merging**
