### PR TITLE
applications: asset_tracker: Upgrade BSEC to version 1.4.8.0

### PR DESCRIPTION
**Pull request by jhn-nordic**
Added support for Bosch BSEC library 1.4.8.0.
This breaks compatibility with older versions of the library.

Signed-off-by: Jon Helge Nistad <jon.helge.nistad@nordicsemi.no>

### CODE REVIEW

**Comment by DurandA** [comment]
Thread size should also be increased for AWS IoT.
https://github.com/nrfconnect/sdk-nrf/blob/651027c5b93c04673e1c460e4bb0045c4a2c2eaa/subsys/net/lib/aws_iot/src/aws_iot.c#L1113-L1117

**Comment by jtguggedal** [comment]
Is it an option to offload the initialization to application workqueue to not have to bump the stack size in the cloud backends?

**Comment by jhn-nordic** [comment]
Added DNM. Should be fixed more properly with changes in the asset tracker application instead. To avoid having BSEC related defines in cloud backends

**Comment by jhn-nordic** [comment]
Now does sensor init on application workqueue. No need to increase stack size with bsec enabled

**Comment by jhn-nordic** [comment]
> Is it an option to offload the initialization to application workqueue to not have to bump the stack size in the cloud backends?

Fixed

**Comment by jhn-nordic** [comment]
> Thread size should also be increased for AWS IoT.
> https://github.com/nrfconnect/sdk-nrf/blob/651027c5b93c04673e1c460e4bb0045c4a2c2eaa/subsys/net/lib/aws_iot/src/aws_iot.c#L1113-L1117

Fixed by changes in main.c instead

**Review by jtguggedal — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
