### PR TITLE
bluetooth: softdevice_controller: Use adv and scan buffer configs

### PR DESCRIPTION
**Pull request by rugeGerritsen**
For now use the default values.

### CODE REVIEW

**Review by joerchan — APPROVED** [review]

**Comment by rugeGerritsen** [comment]
Rebased on master to rerun CI

**Comment by joerchan** [comment]
@rugeGerritsen Should this one have a milestone for 1.7?

**Comment by rugeGerritsen** [comment]
> @rugeGerritsen Should this one have a milestone for 1.7?

It is not strictly needed for NCS, so it can be left out. It would be nice to get it merged though

**Comment by rugeGerritsen** [comment]
Retriggered CI

**Pull request merged**
