### PR TITLE
samples: Enable FPU in TF-M samples for nRF9160_ns

### PR DESCRIPTION
**Pull request by magnev**
- Enables FPU by default on nRF9160_ns for both TF-M samples,
and the psa_tls sample.

Ref: NCSDK-15534

Signed-off-by: Magne Værnes <magne.varnes@nordicsemi.no>

### CODE REVIEW

**Comment by joerchan** [comment]
@magnev We still need this one: https://github.com/zephyrproject-rtos/zephyr/pull/45906

**Comment by joerchan** [comment]
DNM: This PR needs to be rebased and merged after https://github.com/nrfconnect/sdk-nrf/pull/8375

**Review by frkv — APPROVED** [review]
LGTM  (pending merge order)

**Comment by joerchan** [comment]
This can be rebased, now that FPU with Hard ABI has been merged.

**Review by SebastianBoe — APPROVED** [review]

**Comment by SebastianBoe** [comment]
awaiting CI

**Comment by SebastianBoe** [comment]
CI was pending strangely. This was assumed to be harmless.

**Pull request merged**
