### PR TITLE
FMDN upstream part 7: DULT documentation

### PR DESCRIPTION
**Pull request by kapi-no**
Follow-up upstreaming activity for the documentation content after the following PR (sample Readme):

https://github.com/nrfconnect/sdk-nrf/pull/15412

### CODE REVIEW

**Review by mkapala-nordic — APPROVED** [review]

**Comment by kapi-no** [comment]
> There is a problem with how the API header renders in the documentation: https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15643/nrf/libraries/others/dult.html#api-documentation. Some enums and define lacks the description. Also some of the struct members are not shown. @divipillai, do you know why this happens? I looked into `dult.h` file and everything looks good in this file,

Could it be because we don't use the @brief syntax?

**Comment by kapi-no** [comment]
> > There is a problem with how the API header renders in the documentation: https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15643/nrf/libraries/others/dult.html#api-documentation. Some enums and define lacks the description. Also some of the struct members are not shown. @divipillai, do you know why this happens? I looked into `dult.h` file and everything looks good in this file,
> 
> Could it be because we don't use the @brief syntax?

Okay, I think this is because we use `/* xxxx` instead of `/** xxx` when documenting defines and struct fields

**Comment by divipillai** [comment]
> I pushed an update as an attempt to fix the incorrect oxygen documentation

This should fix the issue. Checked the local build, and works as expected.

**Comment by kapi-no** [comment]
> > I pushed an update as an attempt to fix the incorrect oxygen documentation
> 
> This should fix the issue. Checked the local build, and works as expected.

Yes, API docs seem to be rendered correctly now :)

**Review by greg-fer — COMMENTED** [review]
Doc structure looks OK. Please consider adding a changelog entry.
Leaving the detailed doc review to @divipillai .

**Review by alstrzebonski — APPROVED** [review]

**Comment by kapi-no** [comment]
> Doc structure looks OK. Please consider adding a changelog entry. Leaving the detailed doc review to @divipillai .

We agreed with @divipillai and @annwoj to add a changelog at the end of the upstreaming process. As you can see this is part 7 and we haven't documented any changelog entries since part 1. Would that be okay with you?

We have even bigger documentation PR (part 8) after this one as we want to squeeze in the FMDN support before the NCS feature freeze.

**Comment by kapi-no** [comment]
Depends on the following PR:

https://github.com/nrfconnect/sdk-nrf/pull/15662

**Review by divipillai — APPROVED** [review]

**Comment by kapi-no** [comment]
> ~Depends on the following PR:~
> 
> #15662

Removing the dependency as fixing the FMDN (Bluetooth) header causes the Bluetooth integration test to fail. This test suite is broken currently so I am just bringing the DULT header fixes as part of this PR and removing the dependency on the mentioned PR.

**Pull request merged**
