### PR TITLE
doc: Update release-notes-changelog.rst

### PR DESCRIPTION
**Pull request by maciejpietras**
Update of Zigbee release notes for NCS 1.7.0

Signed-off-by: Maciej Pietras <maciej.pietras@nordicsemi.no>

### CODE REVIEW

**Review by greg-fer — APPROVED** [review]

**Review by tomchy — APPROVED** [review]

**Comment by jfischer-no** [comment]
It would be nice if commit message would mention that this patch updates Zigbee related release notes.

**Comment by maciejpietras** [comment]
> It would be nice if commit message would mention that this patch updates Zigbee related release notes.
Edited

**Comment by jfischer-no** [comment]
> > It would be nice if commit message would mention that this patch updates Zigbee related release notes.
> 
> Modified.

PR description, but not the commit message. Once merged, from `git log` it is not obvious what changes this commit has brought.

**Comment by maciejpietras** [comment]
> > > It would be nice if commit message would mention that this patch updates Zigbee related release notes.
> > 
> > 
> > Modified.
> 
> PR description, but not the commit message. Once merged, from `git log` it is not obvious what changes this commit has brought.

Done

**Review by totyz — APPROVED** [review]

**Pull request merged**
