### PR TITLE
drivers: Remove SDC flash driver

### PR DESCRIPTION
**Pull request by eugmes**
This driver is obsoleted by MPSL flash sync support for nrf flash
driver.

Ref: DRGN-12509

Signed-off-by: Ievgenii Meshcheriakov <ievgenii.meshcheriakov@nordicsemi.no>

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
@MarekPieta , you may want to run some quick sanity checks on this PR. nrf_desktop-CI is already run as part of this PR

**Review by rugeGerritsen — APPROVED** [review]

**Comment by eugmes** [comment]
desktop passes: https://jenkins-ncs.nordicsemi.no/blue/organizations/jenkins/latest%2Fsub%2Ftest-fw-nrfconnect-nrf/detail/master/10318/pipeline/2790

**Comment by eugmes** [comment]
Both ble and desktop are now passing.

**Review by joerchan — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Comment by eugmes** [comment]
Here is the successful CI run: https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-3407/30/

After this the CI was retriggered for some reson and fails for reasons unrelated to the PR. I think it is waste of time to try making the build pass again.

**Review by MarekPieta — APPROVED** [review]
I made locally some basic tests for nRF Desktop application (mainly related to DFU and bond erase). No issues were observed.

**Comment by kapi-no** [comment]
This PR causes compilation failure for the BLE Peripheral LBS sample built for the following target nrf52dk_nrf52810. I used the following command in the samples/bluetooth/peripheral_lbs directory:

west build -b nrf52dk_nrf52810 -- -DCONF_FILE='prj_minimal.conf'

I am getting the following build output:

```
-- west build: generating a build system
Including boilerplate (Zephyr base): /home/kapi/Repos/ncs/zephyr/cmake/app/boilerplate.cmake
-- Application: /home/kapi/Repos/ncs/nrf/samples/bluetooth/peripheral_lbs
-- Zephyr version: 2.4.99 (/home/kapi/Repos/ncs/zephyr)
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.5") found components: Interpreter 
-- Found west (found suitable version "0.9.0", minimum required is "0.7.1")
-- Board: nrf52dk_nrf52810
-- Cache files will be written to: /home/kapi/.cache/zephyr
-- Found dtc: /usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found toolchain: gnuarmemb (/opt/gnuarmemb)
-- Found BOARD.dts: /home/kapi/Repos/ncs/zephyr/boards/arm/nrf52dk_nrf52810/nrf52dk_nrf52810.dts
-- Generated zephyr.dts: /home/kapi/Repos/ncs/nrf/samples/bluetooth/peripheral_lbs/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/kapi/Repos/ncs/nrf/samples/bluetooth/peripheral_lbs/build/zephyr/include/generated/devicetree_unfixed.h
-- Generated device_extern.h: /home/kapi/Repos/ncs/nrf/samples/bluetooth/peripheral_lbs/build/zephyr/include/generated/device_extern.h
Parsing /home/kapi/Repos/ncs/nrf/samples/bluetooth/peripheral_lbs/Kconfig
Loaded configuration '/home/kapi/Repos/ncs/zephyr/boards/arm/nrf52dk_nrf52810/nrf52dk_nrf52810_defconfig'
Merged configuration 'prj_minimal.conf'
Configuration saved to '/home/kapi/Repos/ncs/nrf/samples/bluetooth/peripheral_lbs/build/zephyr/.config'
Kconfig header saved to '/home/kapi/Repos/ncs/nrf/samples/bluetooth/peripheral_lbs/build/zephyr/include/generated/autoconf.h'

warning: GPIO (defined at soc/arm/microchip_mec/mec1501/Kconfig.defconfig.mec1501hsz:19,
soc/arm/nordic_nrf/Kconfig.defconfig:41, soc/arm/nxp_imx/mcimx7_m4/Kconfig.defconfig.mcimx7_m4:14,
soc/arm/nxp_imx/rt/Kconfig.defconfig.mimxrt1010:27,
soc/arm/nxp_imx/rt/Kconfig.defconfig.mimxrt1015:23,
soc/arm/nxp_imx/rt/Kconfig.defconfig.mimxrt1021:23,
soc/arm/nxp_imx/rt/Kconfig.defconfig.mimxrt1052:23,
soc/arm/nxp_imx/rt/Kconfig.defconfig.mimxrt1062:23,
soc/arm/nxp_imx/rt/Kconfig.defconfig.mimxrt1064:23,
soc/arm/nxp_kinetis/k2x/Kconfig.defconfig.mk22f12:23,
soc/arm/nxp_kinetis/k6x/Kconfig.defconfig.mk64f12:37,
soc/arm/nxp_kinetis/k6x/Kconfig.defconfig.mk66f18:28,
soc/arm/nxp_kinetis/k8x/Kconfig.defconfig.series:44,
soc/arm/nxp_kinetis/ke1xf/Kconfig.defconfig.series:61,
soc/arm/nxp_kinetis/kv5x/Kconfig.defconfig.series:27,
soc/arm/nxp_lpc/lpc54xxx/Kconfig.defconfig.lpc54114_m0:15,
soc/arm/nxp_lpc/lpc55xxx/Kconfig.defconfig.lpc55S69_cpu1:15, drivers/gpio/Kconfig:6) was assigned
the value 'n' but got the value 'y'. See
http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_GPIO.html and/or look up GPIO in the
menuconfig/guiconfig interface. The Application Development Primer, Setting Configuration Values,
and Kconfig - Tips and Best Practices sections of the manual might be helpful too.


warning: HW_STACK_PROTECTION (defined at arch/Kconfig:214) was assigned the value 'y' but got the
value 'n'. Check these unsatisfied dependencies: ARCH_HAS_STACK_PROTECTION (=n). See
http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_HW_STACK_PROTECTION.html and/or look
up HW_STACK_PROTECTION in the menuconfig/guiconfig interface. The Application Development Primer,
Setting Configuration Values, and Kconfig - Tips and Best Practices sections of the manual might be
helpful too.

-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /opt/gnuarmemb/bin/arm-none-eabi-gcc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kapi/Repos/ncs/nrf/samples/bluetooth/peripheral_lbs/build
-- west build: building application
[1/185] Preparing syscall dependency handling

[178/185] Building C object modules/nrf/drivers/mpsl/flash...__nrf__drivers__mpsl__flash_sync.dir/flash_sync_mpsl.c.ob
FAILED: modules/nrf/drivers/mpsl/flash_sync/CMakeFiles/..__nrf__drivers__mpsl__flash_sync.dir/flash_sync_mpsl.c.obj 
ccache /opt/gnuarmemb/bin/arm-none-eabi-gcc -DBUILD_VERSION=v2.4.99-ncs1-40-g5acae16d9ea8 -DDEVELOP_IN_NRF52832 -DKERNEL -DNRF52810_XXAA -DNRFX_COREDEP_DELAY_US_LOOP_CYCLES=3 -DUSE_PARTITION_MANAGER=0 -D_FORTIFY_SOURCE=2 -D__PROGRAM_START -D__ZEPHYR__=1 -I../../../../drivers/mpsl/clock_control -I/home/kapi/Repos/ncs/zephyr/include -Izephyr/include/generated -I/home/kapi/Repos/ncs/zephyr/soc/arm/nordic_nrf/nrf52 -I/home/kapi/Repos/ncs/zephyr/subsys/settings/include -I/home/kapi/Repos/ncs/zephyr/subsys/bluetooth -I../../../../include -I../../../../lib/multithreading_lock/. -I../../../../subsys/bluetooth/controller/. -I/home/kapi/Repos/ncs/zephyr/drivers/flash -I/home/kapi/Repos/ncs/nrfxlib/mpsl/include -I/home/kapi/Repos/ncs/nrfxlib/softdevice_controller/include -I/home/kapi/Repos/ncs/modules/hal/cmsis/CMSIS/Core/Include -I/home/kapi/Repos/ncs/modules/hal/nordic/nrfx -I/home/kapi/Repos/ncs/modules/hal/nordic/nrfx/drivers/include -I/home/kapi/Repos/ncs/modules/hal/nordic/nrfx/mdk -I/home/kapi/Repos/ncs/zephyr/modules/hal_nordic/nrfx/. -I/home/kapi/Repos/ncs/modules/crypto/tinycrypt/lib/include -isystem /home/kapi/Repos/ncs/zephyr/lib/libc/minimal/include -isystem /opt/gnuarmemb/bin/../lib/gcc/arm-none-eabi/9.2.1/include -isystem /opt/gnuarmemb/bin/../lib/gcc/arm-none-eabi/9.2.1/include-fixed -Os -imacros /home/kapi/Repos/ncs/nrf/samples/bluetooth/peripheral_lbs/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -mcpu=cortex-m4 -mthumb -mabi=aapcs -imacros /home/kapi/Repos/ncs/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wno-address-of-packed-member -Wno-unused-but-set-variable -Werror=implicit-int -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/home/kapi/Repos/ncs/nrf/samples/bluetooth/peripheral_lbs=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/kapi/Repos/ncs/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/home/kapi/Repos/ncs=WEST_TOPDIR -ffunction-sections -fdata-sections -std=c99 -nostdinc -MD -MT modules/nrf/drivers/mpsl/flash_sync/CMakeFiles/..__nrf__drivers__mpsl__flash_sync.dir/flash_sync_mpsl.c.obj -MF modules/nrf/drivers/mpsl/flash_sync/CMakeFiles/..__nrf__drivers__mpsl__flash_sync.dir/flash_sync_mpsl.c.obj.d -o modules/nrf/drivers/mpsl/flash_sync/CMakeFiles/..__nrf__drivers__mpsl__flash_sync.dir/flash_sync_mpsl.c.obj   -c /home/kapi/Repos/ncs/nrf/drivers/mpsl/flash_sync/flash_sync_mpsl.c
In file included from /home/kapi/Repos/ncs/zephyr/include/kernel_includes.h:35,
                 from /home/kapi/Repos/ncs/zephyr/include/kernel.h:17,
                 from /home/kapi/Repos/ncs/zephyr/include/zephyr.h:18,
                 from ../../../../lib/multithreading_lock/./multithreading_lock.h:20,
                 from /home/kapi/Repos/ncs/nrf/drivers/mpsl/flash_sync/flash_sync_mpsl.c:13:
/home/kapi/Repos/ncs/nrf/drivers/mpsl/flash_sync/flash_sync_mpsl.c: In function 'nrf_flash_sync_exe':
/home/kapi/Repos/ncs/zephyr/drivers/flash/soc_flash_nrf.h:39:28: error: 'FLASH_PAGE_ERASE_MAX_TIME_US' undeclared (first use in this function)
   39 | #define FLASH_TIMEOUT_MS ((FLASH_PAGE_ERASE_MAX_TIME_US) * \
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kapi/Repos/ncs/zephyr/include/sys_clock.h:86:55: note: in definition of macro 'Z_TIMEOUT_TICKS'
   86 | #define Z_TIMEOUT_TICKS(t) ((k_timeout_t) { .ticks = (t) })
      |                                                       ^
/home/kapi/Repos/ncs/zephyr/include/sys_clock.h:91:74: note: in expansion of macro 'MAX'
   91 | # define Z_TIMEOUT_MS(t) Z_TIMEOUT_TICKS((k_ticks_t)k_ms_to_ticks_ceil64(MAX(t, 0)))
      |                                                                          ^~~
/home/kapi/Repos/ncs/zephyr/include/kernel.h:1118:24: note: in expansion of macro 'Z_TIMEOUT_MS'
 1118 | #define K_MSEC(ms)     Z_TIMEOUT_MS(ms)
      |                        ^~~~~~~~~~~~
/home/kapi/Repos/ncs/nrf/drivers/mpsl/flash_sync/flash_sync_mpsl.c:178:40: note: in expansion of macro 'K_MSEC'
  178 |  if (k_sem_take(&_context.timeout_sem, K_MSEC(FLASH_TIMEOUT_MS)) < 0) {
      |                                        ^~~~~~
/home/kapi/Repos/ncs/nrf/drivers/mpsl/flash_sync/flash_sync_mpsl.c:178:47: note: in expansion of macro 'FLASH_TIMEOUT_MS'
  178 |  if (k_sem_take(&_context.timeout_sem, K_MSEC(FLASH_TIMEOUT_MS)) < 0) {
      |                                               ^~~~~~~~~~~~~~~~
/home/kapi/Repos/ncs/zephyr/drivers/flash/soc_flash_nrf.h:39:28: note: each undeclared identifier is reported only once for each function it appears in
   39 | #define FLASH_TIMEOUT_MS ((FLASH_PAGE_ERASE_MAX_TIME_US) * \
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kapi/Repos/ncs/zephyr/include/sys_clock.h:86:55: note: in definition of macro 'Z_TIMEOUT_TICKS'
   86 | #define Z_TIMEOUT_TICKS(t) ((k_timeout_t) { .ticks = (t) })
      |                                                       ^
/home/kapi/Repos/ncs/zephyr/include/sys_clock.h:91:74: note: in expansion of macro 'MAX'
   91 | # define Z_TIMEOUT_MS(t) Z_TIMEOUT_TICKS((k_ticks_t)k_ms_to_ticks_ceil64(MAX(t, 0)))
      |                                                                          ^~~
/home/kapi/Repos/ncs/zephyr/include/kernel.h:1118:24: note: in expansion of macro 'Z_TIMEOUT_MS'
 1118 | #define K_MSEC(ms)     Z_TIMEOUT_MS(ms)
      |                        ^~~~~~~~~~~~
/home/kapi/Repos/ncs/nrf/drivers/mpsl/flash_sync/flash_sync_mpsl.c:178:40: note: in expansion of macro 'K_MSEC'
  178 |  if (k_sem_take(&_context.timeout_sem, K_MSEC(FLASH_TIMEOUT_MS)) < 0) {
      |                                        ^~~~~~
/home/kapi/Repos/ncs/nrf/drivers/mpsl/flash_sync/flash_sync_mpsl.c:178:47: note: in expansion of macro 'FLASH_TIMEOUT_MS'
  178 |  if (k_sem_take(&_context.timeout_sem, K_MSEC(FLASH_TIMEOUT_MS)) < 0) {
      |                                               ^~~~~~~~~~~~~~~~
/home/kapi/Repos/ncs/zephyr/drivers/flash/soc_flash_nrf.h:40:7: error: 'FLASH_PAGE_MAX_CNT' undeclared (first use in this function)
   40 |      (FLASH_PAGE_MAX_CNT) / 1000)
      |       ^~~~~~~~~~~~~~~~~~
/home/kapi/Repos/ncs/zephyr/include/sys_clock.h:86:55: note: in definition of macro 'Z_TIMEOUT_TICKS'
   86 | #define Z_TIMEOUT_TICKS(t) ((k_timeout_t) { .ticks = (t) })
      |                                                       ^
/home/kapi/Repos/ncs/zephyr/include/sys_clock.h:91:74: note: in expansion of macro 'MAX'
   91 | # define Z_TIMEOUT_MS(t) Z_TIMEOUT_TICKS((k_ticks_t)k_ms_to_ticks_ceil64(MAX(t, 0)))
      |                                                                          ^~~
/home/kapi/Repos/ncs/zephyr/include/kernel.h:1118:24: note: in expansion of macro 'Z_TIMEOUT_MS'
 1118 | #define K_MSEC(ms)     Z_TIMEOUT_MS(ms)
      |                        ^~~~~~~~~~~~
/home/kapi/Repos/ncs/nrf/drivers/mpsl/flash_sync/flash_sync_mpsl.c:178:40: note: in expansion of macro 'K_MSEC'
  178 |  if (k_sem_take(&_context.timeout_sem, K_MSEC(FLASH_TIMEOUT_MS)) < 0) {
      |                                        ^~~~~~
/home/kapi/Repos/ncs/nrf/drivers/mpsl/flash_sync/flash_sync_mpsl.c:178:47: note: in expansion of macro 'FLASH_TIMEOUT_MS'
  178 |  if (k_sem_take(&_context.timeout_sem, K_MSEC(FLASH_TIMEOUT_MS)) < 0) {
      |                                               ^~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

It looks like the _FLASH_PAGE_ERASE_MAX_TIME_US_ definition is not visible in the _zephyr/drivers/flash/soc_flash_nrf.h_
header. Adding

`#include <soc.h>`

to the header solves the build failure. This header, located in the zephyr/soc/arm/nordic_nrf/nrf52 folder, contains _FLASH_PAGE_ERASE_MAX_TIME_US_ definition. Should we fix it this way or do you have any other idea on how to solve this issue? @anangl

**Comment by eugmes** [comment]
> to the header solves the build failure. This header, located in the zephyr/soc/arm/nordic_nrf/nrf52 folder, contains _FLASH_PAGE_ERASE_MAX_TIME_US_ definition. Should we fix it this way or do you have any other idea on how to solve this issue? @anangl

@kapi-no I think the right solution would be including <soc.h> and <autoconf.h> in soc_flash_nrf.h

**Comment by eugmes** [comment]
I also wonder how this was not found by CI.

**Comment by eugmes** [comment]
I've create a PR here: https://github.com/zephyrproject-rtos/zephyr/pull/32871

**Comment by joerchan** [comment]
Cherry-picked fix here: https://github.com/nrfconnect/sdk-zephyr/pull/478

**Pull request merged**
