### PR TITLE
manifest: Pull in MRAM driver

### PR DESCRIPTION
**Pull request by 57300**
from sdk-zephyr.

### CODE REVIEW

**Comment by gmarull** [comment]
note: branches cannot be pushed to upstream repo ;-)

**Comment by 57300** [comment]
> note: branches cannot be pushed to upstream repo ;-)

Wow, did I really just do that...

**Comment by gmarull** [comment]
> > note: branches cannot be pushed to upstream repo ;-)
> 
> Wow, did I really just do that...

no worries, sometimes happens, just seen this while fetching this morning

**Comment by 57300** [comment]
> > > note: branches cannot be pushed to upstream repo ;-)
> > 
> > 
> > Wow, did I really just do that...
> 
> no worries, sometimes happens, just seen this while fetching this morning

Thanks for catching. Seems I can't change the source branch, might have to open a new PR.

**Comment by 57300** [comment]
Replaced by #14408

**Pull request closed without merging**
