### PR TITLE
Esb latency reduction

### PR DESCRIPTION
**Pull request by LGrosbois-WTK**
Improvement inside ESB driver to reduce fly time between emission and reception.
These modification achieve under 100µs fly time with 2MBPS transmission speed, 8bit CRC, **no acknowledgement**.

esb_config struct has been added 2 options :

- optimize_txen_delay
When this feature is enabled, radio TXEN delay is
cut off from 130µs to 40 µs.
The radio peripheral needs some time to start-up
analogs components of the radio. On nRF51 and nRF24L series,
a hard coded 130 µs delay is implemented. If ESB connection
is achieved only between nRF52 devices, this delay can be cut off
to 40 µs.

- never_disable_tx
When this feature is enabled,
if mode is NRF_ESB_MODE_PTX and if packet
is not acknowledged, then radio peripheral will
remain in TXIDLE state instead of TXDISABLE when
transmission is pending. This reduce delay between

This upstream follows a conversation on nordic devzone where this feature has been implemented for NRF Connect SDK v2.2.0.
As we needed upstream, modification have been backported to the main branch.
Original discussion: https://devzone.nordicsemi.com/f/nordic-q-a/94577/minimum-esb-latency

### CODE REVIEW

**Comment by lemrey** [comment]
great! thanks a lot. Adding @too1

**Comment by lemrey** [comment]
+@magnev can check tests are good.

**Comment by LGrosbois-WTK** [comment]
Hello !
I've seen there have been some CI run errors: 
- CI/Jenkins/integration 
- CI/Jenkins/twister

Is there anything I can do to help ?

**Comment by lemrey** [comment]
```
[2023-01-03T15:31:43.865Z] ../../../../../nrf/subsys/esb/esb_dppi.c: In function 'esb_ppi_for_wait_for_rx_set':
[2023-01-03T15:31:43.865Z] ../../../../../nrf/subsys/esb/esb_dppi.c:164:63: error: 'radio_end_timer_start' undeclared (first use in this function)
[2023-01-03T15:31:43.865Z]   164 |         nrf_radio_publish_set(NRF_RADIO, NRF_RADIO_EVENT_END, radio_end_timer_start);
[2023-01-03T15:31:43.865Z]       |                                                               ^~~~~~~~~~~~~~~~~~~~~
[2023-01-03T15:31:43.865Z] ../../../../../nrf/subsys/esb/esb_dppi.c:164:63: note: each undeclared identifier is reported only once for each function it appears in
[2023-01-03T15:31:43.865Z] In file included from ../../../../../zephyr/include/zephyr/sys/util.h:17,
[2023-01-03T15:31:43.865Z]                  from ../../../../../zephyr/include/zephyr/devicetree.h:21,
[2023-01-03T15:31:43.865Z]                  from ../../../../../zephyr/modules/hal_nordic/nrfx/nrfx_config.h:10,
[2023-01-03T15:31:43.865Z]                  from ../../../../../modules/hal/nordic/nrfx/nrfx.h:37,
[2023-01-03T15:31:43.865Z]                  from ../../../../../modules/hal/nordic/nrfx/hal/nrf_egu.h:37,
[2023-01-03T15:31:43.865Z]                  from ../../../../../nrf/subsys/esb/esb_dppi.c:7:
[2023-01-03T15:31:43.865Z] ../../../../../nrf/subsys/esb/esb_dppi.c: In function 'esb_ppi_for_wait_for_rx_clear':
[2023-01-03T15:31:43.865Z] ../../../../../nrf/subsys/esb/esb_dppi.c:177:30: error: 'radio_end_timer_start' undeclared (first use in this function)
[2023-01-03T15:31:43.865Z]   177 |         channels_mask = (BIT(radio_end_timer_start));
[2023-01-03T15:31:43.865Z]       |                              ^~~~~~~~~~~~~~~~~~~~~
[2023-01-03T15:31:43.865Z] ../../../../../zephyr/include/zephyr/sys/util_macro.h:44:26: note: in definition of macro 'BIT'
[2023-01-03T15:31:43.865Z]    44 | #define BIT(n)  (1UL << (n))
[2023-01-03T15:31:43.865Z]       |                          ^
[2023-01-03T15:31:43.865Z] ../../../../../nrf/subsys/esb/esb_dppi.c: In function 'esb_ppi_init':
[2023-01-03T15:31:43.865Z] ../../../../../nrf/subsys/esb/esb_dppi.c:224:40: error: 'radio_end_timer_start' undeclared (first use in this function)
[2023-01-03T15:31:43.866Z]   224 |         err = nrfx_dppi_channel_alloc(&radio_end_timer_start);
[2023-01-03T15:31:43.866Z]       |                                        ^~~~~~~~~~~~~~~~~~~~~
[2023-01-03T15:31:43.866Z] ../../../../../nrf/subsys/esb/esb_dppi.c: In function 'esb_ppi_disable_all':
[2023-01-03T15:31:43.866Z] ../../../../../nrf/subsys/esb/esb_dppi.c:253:39: error: 'radio_end_timer_start' undeclared (first use in this function)
[2023-01-03T15:31:43.866Z]   253 |                                   BIT(radio_end_timer_start));
[2023-01-03T15:31:43.866Z]       |                                       ^~~~~~~~~~~~~~~~~~~~~
[2023-01-03T15:31:43.866Z] ../../../../../zephyr/include/zephyr/sys/util_macro.h:44:26: note: in definition of macro 'BIT'
[2023-01-03T15:31:43.872Z]    44 | #define BIT(n)  (1UL << (n))
[2023-01-03T15:31:43.872Z]       |                          ^
[2023-01-03T15:31:43.872Z] ../../../../../nrf/subsys/esb/esb_dppi.c: In function 'esb_ppi_deinit':
[2023-01-03T15:31:43.872Z] ../../../../../nrf/subsys/esb/esb_dppi.c:295:15: error: implicit declaration of function 'nrfx_ppi_channel_free'; did you mean 'nrfx_dppi_channel_free'? [-Werror=implicit-function-declaration]
[2023-01-03T15:31:43.872Z]   295 |         err = nrfx_ppi_channel_free(radio_end_timer_start);
[2023-01-03T15:31:43.872Z]       |               ^~~~~~~~~~~~~~~~~~~~~
[2023-01-03T15:31:43.872Z]       |               nrfx_dppi_channel_free
[2023-01-03T15:31:43.872Z] ../../../../../nrf/subsys/esb/esb_dppi.c:295:37: error: 'radio_end_timer_start' undeclared (first use in this function)
[2023-01-03T15:31:43.872Z]   295 |         err = nrfx_ppi_channel_free(radio_end_timer_start);
[2023-01-03T15:31:43.872Z]       |                                     ^~~~~~~~~~~~~~~~~~~~~
[2023-01-03T15:31:43.872Z] cc1: all warnings being treated as errors
```

**Comment by lemrey** [comment]
There are some compilation errors in the `esb` samples it seems

**Comment by LGrosbois-WTK** [comment]
As I'm working with nrf52 which embeds PPI, I've extensively tested for this plaform.
Migration from esb_ppi.c to esb_dppi.c is straightforward, but I forgot to test the build for nrf53 which embeds DPPI...

=> Compilation is now OK, sorry about this...

**Comment by lemrey** [comment]
No worries. Please squash the commits, so that only one commit is left; prefix it like so: `esb: ...`, write a nice commit message, and add a signed-off at the end, so that `gitlint` is happy (you can look at other commits in the repo to see what they should look like).

**Comment by LGrosbois-WTK** [comment]
Closing this pull request.
My git history is not clean enough for a proper squash. I will create a new branch.
Sorry about the bothering...

**Comment by LGrosbois-WTK** [comment]
Here is the new PR: https://github.com/nrfconnect/sdk-nrf/pull/9835

**Pull request closed without merging**
