### PR TITLE
tests: lwm2m_client_utils: Add unittests for connmon & device module

### PR DESCRIPTION
**Pull request by jheiskan81**
Add unittests for lwm2m_connmon.c & lwm2m_device.c using FFF framework from Zephyr.
Moved APP_HOLD_TIME_RSRP from app to libutils and rename to LWM2M_CONN_HOLD_TIME_RSRP.

Signed-off-by: Juha Heiskanen <juha.heiskanen@nordicsemi.no>

### CODE REVIEW

**Comment by jheiskan81** [comment]
@SeppoTakalo @VeijoPesonen @rlubos Please review.

**Review by SeppoTakalo — APPROVED** [review]

**Review by VeijoPesonen — APPROVED** [review]

**Comment by jheiskan81** [comment]
@SeppoTakalo & @VeijoPesonen  Added also Device module unit test to same PR.

**Review by rlubos — COMMENTED** [review]
Please address the compliance issues (spaces instead of tabs etc)

**Comment by jheiskan81** [comment]
@rlubos I fixed device.c the compliance issues

**Review by rlubos — APPROVED** [review]

**Review by SeppoTakalo — APPROVED** [review]

**Comment by jheiskan81** [comment]
@jarlamsa Please review APP_HOLD_TIME_RSRP  move from app to libutils and rename to and rename LWM2M_CONN_HOLD_TIME_RSRP.

**Pull request merged**
