### PR TITLE
doc: Change warnings to notes

### PR DESCRIPTION
**Pull request by rakons**
Update API documentation to use rather notes instead of warnings.

### CODE REVIEW

**Review by coderbyheart — APPROVED** [review]
Please explain reason for change in the commit message so developers understand when they should use `@warnging` and when not.

**Review by jayteemo — APPROVED** [review]

**Review by plskeggs — APPROVED** [review]
LGTM

**Review by pdunaj — APPROVED** [review]

**Review by peknis — APPROVED** [review]

**Review by Balaklaka — APPROVED** [review]

**Comment by pdunaj** [comment]
> Please explain reason for change in the commit message so developers understand when they should use `@warning` and when not.

Will anybody really look for coding standard in message of some random commit? It's better to update our pages talking about doc/code style.

**Comment by rakons** [comment]
@coderbyheart @jayteemo - Do you really think that commit message is good place to mention it? Would anybody search for such an information in commit messages? The general rule is we must not use warnings unless there is a risk for personal injury or loss of life. It can be simplified to not to use warnings at all, as it is hard to judge just providing the libraries it something may lead to injury here.

**Comment by rakons** [comment]
As you wish. Not time to waste on commit message fight.

**Comment by rakons** [comment]
There were issues with CI - but on the CI page all the tests that was failing passed finally.
Note that this is only documentation change and should not change the test results anyway.

**Comment by rakons** [comment]
@carlescufi - can we merge this?

**Review by b-gent — APPROVED** [review]
This change is correct and follows the general styleguide of Nordic techpubs. Thanks @rakons

**Review by umapraseeda — APPROVED** [review]

**Pull request merged**
