### PR TITLE
tfm: Kconfig: Increase crypto heap when using RSA on cc3xx

### PR DESCRIPTION
**Pull request by magnev**
- Extends the TFM_CRYPTO_ENGINE_BUF_SIZE to 12k
  when RSA is enabled in cc3xx.

Ref: NCSDK-15359

Signed-off-by: Magne Værnes <magne.varnes@nordicsemi.no>

### CODE REVIEW

**Review by joerchan — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
I would have +1'ed and merged this, but the commit log doesn't say why the change is needed, so I can't tell if this is fixing a bug or not. Leaving this to Monday.

**Review by frkv — APPROVED** [review]
LGTM

**Review by Vge0rge — APPROVED** [review]
LGTM

**Comment by magnev** [comment]
> I would have +1'ed and merged this, but the commit log doesn't say why the change is needed, so I can't tell if this is fixing a bug or not. Leaving this to Monday.

I've added the Jira ticket to the commit

**Pull request merged**
