### PR TITLE
samples: bluetooth: Add DTM support for we_proteus3ev_nrf52840

### PR DESCRIPTION
**Pull request by mah-eiSmart**
Add direct test mode support for board we_proteus3ev_nrf52840

### CODE REVIEW

**Comment by mah-eiSmart** [comment]
@nordicjm , do you know who can review this?
Thank you!

**Comment by nordicjm** [comment]
@nrfconnect/ncs-si-muffin please review

**Review by nordicjm — COMMENTED** [review]
Actually this should not be needed, I will submit an alternative fix

**Comment by nordicjm** [comment]
https://github.com/nrfconnect/sdk-nrf/pull/19069 will fix the issue

**Comment by mah-eiSmart** [comment]
Thank you @nordicjm !

**Pull request closed without merging**
