### PR TITLE
application: serial_lte_modem: BUG-FIX native-tls

### PR DESCRIPTION
**Pull request by pirun**
The features of mbedtls 3.1 are not enabled default which causes SLM native tls not having ciphersuites to handshake with TLS client.
Enable MBEDTLS options explicitly for mbedtls 3.1 to make native tls working.
Modify socket option number in document.

Signed-off-by: Pirun Lee <pirun.lee@nordicsemi.no>

### CODE REVIEW

**Comment by ns-tolu** [comment]
Could you prioritize review of this PR?

**Review by rlubos — APPROVED** [review]

**Review by junqingzou — APPROVED** [review]

**Review by FrancescoSer — APPROVED** [review]
Approving, but an entry is required in the Release Notes 2.1.0 PR

**Comment by greg-fer** [comment]
Please add the changelog entry to this PR and I'll rebase my release notes PR. I originally thought we would have only 1 or 2 PRs before the tag, but the number is growing, so let's keep the changelog entry close to the code it changes.

**Comment by rlubos** [comment]
Agreed offline to add release notes entry in #8510.

**Comment by greg-fer** [comment]
Entry added in https://github.com/nrfconnect/sdk-nrf/pull/8510#pullrequestreview-1103927559

**Pull request merged**
