### PR TITLE
applications: serial_lte_modem: Adapt NCS child_image changes

### PR DESCRIPTION
**Pull request by junqingzou**
In PR#3247, child image config files are changed to below:
 child_image/mcuboot/prj.conf
 child_image/spm/spm_prj.conf
But the correct way should be:
  child_image/mcuboot.conf
  child_image/spm.conf
After this, both files carry SLM-specific CONFIG items only.

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Comment by tejlmand** [comment]
> 
> 
> In PR#3247, "child_image/ < ACI > / < ACI >_prj.conf" is expected to be merged
> with 'samples/ < ACI_name > /prj.conf'. But based on test,
> child_image\spm\spm_prj.conf
> is not merged with
> samples\spm\prj.conf

No they are not.
`child_image/<ACI>.conf` is expected to be merge with `samples/<ACI_name>/prj.conf`.

Files under:
``child_image/<ACI>/prj.conf` is expected to be used instead of `samples/<ACI_name>/prj.conf`.

So if you want the files merged, you should rename `child_image/spm/spm_prj.conf` into `child_image/spm.conf`.

See more here:
http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_multi_image.html#image-specific-variables

**Review by tejlmand — CHANGES_REQUESTED** [review]
If you only want to overwrite specific Kconfig settings, then it would be sufficient to place the file at the right location, instead of creating a complete conf file replacement.

**Comment by tejlmand** [comment]
Seems #3247 named and placed the `spm_prj.conf` file wrongly.

**Comment by junqingzou** [comment]
> If you only want to overwrite specific Kconfig settings, then it would be sufficient to place the file at the right location, instead of creating a complete conf file replacement.

Thanks, I'll test mcuboot and spm with the new scheme.
Prefer merge instead of overwrite

**Review by tejlmand — CHANGES_REQUESTED** [review]
Could you do a:
```
git mv  applications/serial_lte_modem/child_image/spm/spm_prj.conf   applications/serial_lte_modem/child_image/spm.conf
```
instead, to preserve the comment and history of the existing file ?

Current commit removes the file, and adds a new one with different comments so the `git` cannot see it is a simple rename.

**Comment by junqingzou** [comment]
> Could you do a:
> 
> ```
> git mv  applications/serial_lte_modem/child_image/spm/spm_prj.conf   applications/serial_lte_modem/child_image/spm.conf
> ```
> 
> instead, to preserve the comment and history of the existing file ?
> 
> Current commit removes the file, and adds a new one with different comments so the `git` cannot see it is a simple rename.

@tejlmand Break into two commits. Please review again

**Review by tejlmand — APPROVED** [review]
lgtm, thanks for the cleanup

**Pull request merged**
