### PR TITLE
samples: net: Use default TCP stack size with Wi-Fi

### PR DESCRIPTION
**Pull request by rlubos**
The Wi-Fi driver by default runs on a separate TX thread, therefore it shouldn't really be needed to increase the TCP stack size, just rely on the defaults.

### CODE REVIEW

**Comment by rlubos** [comment]
For reviewers - I've tested this with `https_client` sample, and even with logging enabled and forced retransmissions we've barely exceeded half kbyte of the TCP stack usage (default size is 1k). But please let me know if you observe some abnormalities with this change.

**Review by ioannisg — APPROVED** [review]
Thanks!

**Review by glarsennordic — APPROVED** [review]
MSS Wi-Fi connectivity builds work!

**Review by plskeggs — APPROVED** [review]

**Review by simensrostad — APPROVED** [review]
Thanks! @jorgenmk Can we do a nightly run on this one?

**Review by bjda — APPROVED** [review]

**Pull request merged**
