### PR TITLE
application: serial_lte_modem: Disable MCUBOOT RTT logging

### PR DESCRIPTION
**Pull request by junqingzou**
In order to save power, SLM configure MCUBOOT to use RTT in stead of UART for logging. SLM itself uses RTT for logging as well. It works until recent change by Zephyr upmerge or MCUBOOT update, now MCUBOOT exclusively take control of RTT logging.

MCUBOOT logging has no significant usage, while SLM logs are crucial for issue debugging. Thus we disable RTT logging for MCUBOOT sub-image and leave RTT logging for SLM app.

Another minor update is to bring back the UART TX dump in debug logging mode, which is useful into debug UART problem with MCU.

### CODE REVIEW

**Comment by junqingzou** [comment]
Investigated by @pirun , related to #9780 merged on Feb 17th.

**Comment by MarkusLassila** [comment]
The code change itself is trivial, but I do not know the implications of disabling the mcuboot logging completely. @SeppoTakalo: Can you comment on this?

**Comment by MarkusLassila** [comment]
@junqingzou: Is this intended as a quick fix to get the SLM traces working? For me, it seems that the PR https://github.com/nrfconnect/sdk-nrf/pull/9780 most likely had an unwanted consequence and the fix should be done somewhere else. What's your take on this?

**Review by MarkusLassila — APPROVED** [review]
Clarified by @junqingzou to be an emergency fix for 2.3.0.

**Comment by pirun** [comment]
Talked to @sigvartmh. 

> The clue here is to create a rtt ram region which is in non-secure.
> And make sure RTT uses this region.
> 
That is out of scope of SLM. I believe that every non-secure application wouldn't have mcuboot and application log in RTT together.

**Comment by SeppoTakalo** [comment]
I'm dropping the milestone.

This is not a bug that has been seen in a CI so it is not a critical to get into the release.

**Comment by junqingzou** [comment]
> 

Then customer will get no logs with default build with 2.3.0 baseline

**Comment by SeppoTakalo** [comment]
> > 
> 
> Then customer will get no logs with default build with 2.3.0 baseline

Works as intented.

Documentation states:
```
To save power, both the console and the output logs over UART_0 are disabled in this application. This information is logged using RTT instead.
```
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/applications/serial_lte_modem/doc/slm_description.html#additional-configuration

This is too late to change a functionality for a release.
Please create a Jira ticket that describes the problem.

**Comment by junqingzou** [comment]
@SeppoTakalo #10405 as agreed

**Review by SeppoTakalo — APPROVED** [review]

**Comment by junqingzou** [comment]
Please review in time and hopefully the changes could be merged soon.
It's essential to have SLM logs working with Main branch.

**Review by MarkusLassila — APPROVED** [review]

**Review by SeppoTakalo — APPROVED** [review]

**Review by VTPeltoketo — APPROVED** [review]

**Pull request merged**
