### PR TITLE
snippets: add hw-flow-control snippet

### PR DESCRIPTION
**Pull request by nordic-piks**
To be applied for tests which require HWFC
but board does not have it by default.

### CODE REVIEW

**Review by miha-nordic — APPROVED** [review]

**Review by nordicjm — CHANGES_REQUESTED** [review]
Why is this a shield and not a snippet?

**Comment by nordic-piks** [comment]
> Why is this a shield and not a snippet?

I believe this can be with both of them.
However, for flow control at nrf5340 you need to do modification at board - flow control needs to be physically enabled by switch.
(beside using it at host side)

**Comment by nordicjm** [comment]
That's no different than the usb cdc acm snippet, you need to plug the dedicated USB cable in, you are not using a physical shield therefore this should be a snippet.

**Comment by nordicjm** [comment]
See https://docs.zephyrproject.org/latest/hardware/porting/shields.html

**Review by nordicjm — APPROVED** [review]

**Pull request merged**
