### PR TITLE
Change/update device shadow to nrfcloud format

### PR DESCRIPTION
**Pull request by sigvartmh**
Based on top of https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1802

So see the 2nd commit.

This is to use a similar structure which is compatible with nrfcloud in the AWS FOTA sample since it contains an `NRF_CLOUD` configuration which sets the sample up to use nrfcloud. It does however not do pairing at the moment so it still needs to be paired with nRF Cloud through the use of an `asset_tracker` sample.

### CODE REVIEW

**Comment by hakonfam** [comment]
Please rebase @sigvartmh

**Comment by sigvartmh** [comment]
done @hakonfam does this one need another rebase?

**Comment by hakonfam** [comment]
Looks good. Since this is so old, and we are in the lack of proper CI in this context, could you verify that the changes work as expected?

**Comment by hakonfam** [comment]
FYI waiting for PING after you have green CI and verified that the change works :)

**Comment by carlescufi** [comment]
Note: This is an automated message.
@sigvartmh this Pull Request has not been updated for more than a month, please close it if not applicable anymore.
@hakonfam  @oyvindronningstad  @bjda  @lemrey  @rlubos  @joakimtoe  please close it if the author is not available

**Pull request closed without merging**
