### PR TITLE
manifest: cherry-pick Bluetooth host hotfix

### PR DESCRIPTION
**Pull request by jori-nordic**
Cherry-pick the fromlist PR:
https://github.com/zephyrproject-rtos/zephyr/pull/69738

### CODE REVIEW

**Comment by jfischer-no** [comment]
@jori-nordic please rebase on the latest main and get CI green.

**Comment by jori-nordic** [comment]
> get CI green.

done

**Review by laxiLang — APPROVED** [review]

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Please do not update sdk-zephyr revision here.

**Comment by jori-nordic** [comment]
> Please do not update sdk-zephyr revision here.

Thanks, closing my PR then

**Pull request closed without merging**
