### PR TITLE
zigbee: Move scheduler API to the platform header

### PR DESCRIPTION
**Pull request by tomchy**
This PR adds the following changes:
 - The scheduler API should be available from the main zboss_api.h. As a result, the function prototypes has to be moved to the
zb_osif_platform.h header file.
 - Device configuration 254 is required to conform to the requirements in section TP/154/PHY24/TRANSMIT-05 of the ZigBee IEEE 802.15.4 Test Specification. This configuration shall be applied by default, unless overridden by the user.
 - Revert "nrf_rpc: Modify the nRF RPC transport to use the RPMsg Service"

Signed-off-by: Tomasz Chyrowicz <tomasz.chyrowicz@nordicsemi.no>

### CODE REVIEW

**Review by sebastiandraus — APPROVED** [review]

**Comment by tomchy** [comment]
ZBOSS updated. Ready for merges.

**Review by rlubos — APPROVED** [review]

**Review by ioannisg — CHANGES_REQUESTED** [review]
Does not seem to point to the top of master in sdk-nrfxlib

**Review by KAGA164 — APPROVED** [review]

**Comment by ioannisg** [comment]
@grochu it seems the RPC is still failing, after I have reverted the latest changes.

**Comment by grochu** [comment]
> @grochu it seems the RPC is still failing, after I have reverted the latest changes.

@maje-emb will look at this with a tester from our team.

**Comment by ioannisg** [comment]
> > @grochu it seems the RPC is still failing, after I have reverted the latest changes.
> 
> @maje-emb will look at this with a tester from our team.

Thanks @grochu

**Comment by frkv** [comment]
FI: I think the CI run for the RPC is 2 hours old. I don't think it has been rerun  with a fix

**Pull request merged**
