### PR TITLE
samples: common: mcumgr_bt_ota_dfu Remove setting QSPI driver

### PR DESCRIPTION
**Pull request by hellesvik-nordic**
CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU no longer implies QSPI drivers. Implying QSPI here breaks projects using SPI external flash. The board or app should be responsible for setting flash driver. I think this option was added for easier use with the Thingy:53, but this has now been fixed in sdk-zephyr commit e7415e4.

### CODE REVIEW

**Comment by hellesvik-nordic** [comment]
Alternativley, we could instead do 
```
imply NORDIC_QSPI_NOR if $(dt_chosen_enabled,$(DT_CHOSEN_EXT_FLASH) && \
        $(dt_compat_on_bus,$(DT_COMPAT_NORDIC_QSPI_NOR),qspi))
```
But I do not think the external flash driver belongs here in general, so I propose we just remove it

**Comment by hellesvik-nordic** [comment]
And for some extra context:
I work in DevZone in Tech Support, and this specific imply has wasted countless hours for myself, multiple of my colleagues, and our customers cause it is so hard to debug why your SPI driver is ignored.

**Review by nvlsianpu — COMMENTED** [review]
LGTM
alternative also looks good.
@MarekPieta Can you give review?

**Comment by hellesvik-nordic** [comment]
@miha-nordic Rebased to main and force pushed.

**Review by miha-nordic — APPROVED** [review]

**Review by gchwier — APPROVED** [review]

**Pull request merged**
