### PR TITLE
doc: zzhc: additional edits

### PR DESCRIPTION
**Pull request by greg-fer**
Edited the file based on input from Heidi-Irene.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

### CODE REVIEW

**Comment by greg-fer** [comment]
Setting up an additional PR, because the previous one was merged without approval from Heidi. Before I even asked her, it was merged and closed in a nick of time...

**Comment by heidisollie** [comment]
It makes more sense for the sentence "The following required options are automatically selected when the ZZHC library is enabled:" to be moved to point 1. Set CONFIG_ZZHC to y.

**Comment by greg-fer** [comment]
@carlescufi , @rlubos , is there a way to add @heidisollie as reviewer to this PR?

**Comment by rlubos** [comment]
@greg-fer You don't need to be on the reviewers list to leave reviews/comments - anyone can do that.

**Review by pkchan — APPROVED** [review]
Putting the master switch CONFIG_ZZHC to the beginning of the document has made the document easier to follow. Nice change.

**Comment by greg-fer** [comment]
@heidisollie approved in a comment to me on Teams, as she cannot join the Reviewers.

**Review by rlubos — APPROVED** [review]

**Pull request merged**
