### PR TITLE
NFC split NDEF messsage encoding into two function

### PR DESCRIPTION
**Pull request by KAGA164**
This PR contains changes in NDEF message library which allows to encode valid nested NDEF message.

### CODE REVIEW

**Comment by KAGA164** [comment]
@kapi-no The solution with additional `ndef file` module would be more transparent. However this solution affect not only the T4T sample. Some our NDEF module encodes the NDEF messages inside itself like the URI or TEXT NDEF library and the TNEP protocols. If we create separated `ndef file` library for T4T then existing NDEF module would have to distinguish between NFC Tag types.

**Comment by kapi-no** [comment]
Yes, you are right, I haven't thought about NDEF message modules and their API (e.g URI). Alternatively, we could encode NDEF message without NLEN and add NLEN field afterwards using ``ndef_file_encode``. I imagine it to look similar to this:

```
static u8_t ndef_file_buf[CONFIG_NDEF_FILE_SIZE];

int main()
{
int err;
u32_t size = nfc_ndef_file_msg_size_get(sizeof(ndef_file_buf));

(...)

err = nfc_ndef_uri_msg_encode(NFC_URI_HTTP_WWW, m_url, sizeof(m_url),
              nfc_ndef_file_msg_get(ndef_file_buf), &size)
if (err) {
    goto fail;
}

err = nfc_ndef_file_encode(ndef_file, size)
if (err) {
    goto fail;
}

err = nfc_t4t_ndef_rwpayload_set(ndef_file_buf, sizeof(ndef_file_buf))
if (err) {
    goto fail;
}

(...)
}
```

**Comment by grochu** [comment]
I like the idea with the additional NDEF File module better - this will be transparent and clean. To use T4T it is not enough to use clear NDEF, but you need to create the NDEF file.

**Comment by KAGA164** [comment]
The new NDEF File module is introduced in the #2609. This PR will be closed

**Pull request closed without merging**
