### PR TITLE
doc: add support for nRF21540 FEM to Low power UART sample doc

### PR DESCRIPTION
**Pull request by peknis**
This commit adds support for nRF21540 Front-End Module to
the Low Power UART sample doc.
Ref NCSDK-10897

Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>

### CODE REVIEW

**Comment by anangl** [comment]
> Should I also update the related sample.yaml file to include the board?

I think that first of all you should add the actual support for that board, i.e. add the related .conf and .overlay files in the `boards/` directory (it should be enough to just copy the nrf52840dk_nrf52840 ones). Then, yes, I think that `sample.yaml` should be updated as well, so that this board can be checked by CI.

**Review by nordic-krch — APPROVED** [review]

**Comment by peknis** [comment]
I have included the sample_fem_support.txt and it looks like we don't need to add the overlay files. But I will update the sample.yaml accordingly.

**Comment by anangl** [comment]
> I have included the sample_fem_support.txt and it looks like we don't need to add the overlay files. But I will update the sample.yaml accordingly.

I guess I'm missing something here. How is then the lpuart driver supposed to compile for the nrf21540_nrf52840 board without a `"nordic,nrf-sw-lpuart"` node present in devicetree? I think you need to add such node like it is done for nrf52840dk_nrf52840: https://github.com/nrfconnect/sdk-nrf/blob/c2bbba159487ba59f3f72e1a109c7490caf90b4f/samples/peripheral/lpuart/boards/nrf52840dk_nrf52840.overlay#L3-L16

**Comment by peknis** [comment]
From the sample_fem_support.txt
Provide nRF21540 FEM capabilities by using a shield, for example the nRF21540 EK shield that is available in the nRF Connect SDK. In this case, build the project for a board connected to the shield you are using with an appropriate variable included in the build command. This variable instructs the build system to append the appropriate devicetree overlay file. For example, to build the sample from the command line for an nRF52833 DK with the nRF21540 EK attached, use the following command within the sample directory:

west build -b nrf52833dk_nrf52833 -- -DSHIELD=nrf21540_ek
To add support for other front-end modules, add the respective devicetree file entries to the board devicetree file or the devicetree overlay file.

**Review by anangl — APPROVED** [review]

**Pull request merged**
