### PR TITLE
tf-m: sourcing Kconfig.mbedtls.defconfig when not using minimal config

### PR DESCRIPTION
**Pull request by tejlmand**
Fixes: NCSDK-9954

The file Kconfig.mbedtls.defconfig was introduced in #4745.
However, only sourcing of Kconfig.mbedtls_minimal.defconfig was done
when TFM_MINIMAL=y.

This commit sources the corresponding Kconfig.mbedtls.defconfig when
not using the minimal config.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

### CODE REVIEW

**Comment by tejlmand** [comment]
This is an alternative to: https://github.com/nrfconnect/sdk-zephyr/pull/565

**Comment by tejlmand** [comment]
DNM until PR is approved by @hakonfam

**Comment by frkv** [comment]
I don't understand the additional addition (removal of default n). Removing LGTM

**Review by andvib — APPROVED** [review]
Fixes tests

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
Thanks for working on this fix @tejlmand @andvib

**Pull request merged**
