### PR TITLE
Adapt to the new PSA_WANT symbols for ECC keys

### PR DESCRIPTION
**Pull request by Vge0rge**
Adapt to the new configurations from the
Oberon PSA core.

The PSA_WANT_KEY_TYPE_ECC_KEY_PAIR is deprecated
and will be replaced by options for specific operations for key generation, importing, exporting and key derivation.

test_crypto: PR-622

### CODE REVIEW

**Comment by RobertGalatNordic** [comment]
adding back reference for PR in sidewalk repo https://github.com/nrfconnect/sdk-sidewalk/pull/523

**Comment by thst-nordic** [comment]
draft mode = no reviews, but CI can still be run manually

**Comment by SebastianBoe** [comment]
@thst-nordic : I'd rather avoid the extra paperwork of running manually.

**Review by SebastianBoe — APPROVED** [review]

**Review by canisLupus1313 — APPROVED** [review]

**Review by mswarowsky — APPROVED** [review]

**Review by MarkusLassila — APPROVED** [review]

**Review by SeppoTakalo — APPROVED** [review]

**Comment by RobertGalatNordic** [comment]
sidewalk is already merged, You can use the latest HEAD (3ea0a33dd64703068b49783b3bd1d5620f70e57e)

**Review by canisLupus1313 — APPROVED** [review]

**Pull request merged**
