### PR TITLE
samples: openthread: remove unsupported dfu overlay.

### PR DESCRIPTION
**Pull request by canisLupus1313**
This commit removes unsupported DFU overlay in openthread sample.

Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>

### CODE REVIEW

**Review by edmont — CHANGES_REQUESTED** [review]
Documentation should be updated as well to remove reference to this  file.

**Comment by kkasperczyk-no** [comment]
I don't know what are the plans for this PR, but if you want to remove DFU over BLE support at all you should probably also remove that code: https://github.com/nrfconnect/sdk-nrf/blob/main/samples/openthread/coap_client/src/coap_client.c#L141

**Review by lmaciejonczyk — APPROVED** [review]

**Review by kkasperczyk-no — COMMENTED** [review]
Those lines could be removed too:
https://github.com/nrfconnect/sdk-nrf/pull/6994/files#diff-1561330efe0db58f8dca63004264b9e31add7c6b2e52301c273e1b3267c0be81R20
https://github.com/nrfconnect/sdk-nrf/blob/main/samples/openthread/coap_client/src/ble_utils.c#L16
https://github.com/nrfconnect/sdk-nrf/blob/main/samples/openthread/coap_client/src/coap_client.c#L20

**Review by wiba-nordic — APPROVED** [review]

**Comment by wiba-nordic** [comment]
Does this need a changelog entry?

**Comment by canisLupus1313** [comment]
> Does this need a changelog entry?

Removed it You are wright no need for it.

**Comment by edmont** [comment]
What about the Readme sections?

`Device Firmware Upgrade extension`

`Testing Device Firmware Upgrade extension`

**Review by kkasperczyk-no — APPROVED** [review]

**Review by edmont — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
