### PR TITLE
doc: Added links to RST files in bluetooth header files

### PR DESCRIPTION
**Pull request by richabp**
Provided comments in the include/bluetooth/services/ header files
about the location of corresponding RST files and
rendered documentation for the particular library.

Ref: NCSDK-11624

Signed-off-by: Richa Pandey <richa.pandey@nordicsemi.no>

### CODE REVIEW

**Review by alwa-nordic — APPROVED** [review]

**Review by KAGA164 — COMMENTED** [review]
Would it be possible to keep the common part of links and paths in some kind of variable or include sentence in RST. I worried if website address or path would change then we will need to update every header file and someone needs to remember about it also

**Comment by grochu** [comment]
> Would it be possible to keep the common part of links and paths in some kind of variable or include sentence in RST. I worried if website address or path would change then we will need to update every header file and someone needs to remember about it also

I agree it may be a significant maintenance cost to have hardcoded paths and even URLs to the docs. Is it possible to have it parameterized as @KAGA164 proposed?

**Review by KAGA164 — APPROVED** [review]

**Review by KAGA164 — APPROVED** [review]
Looks good. I did not notice that this links are in the header files so they cannot be parametrized

**Review by mia-ko — CHANGES_REQUESTED** [review]
LGTM :)
We are now missing the following:
- ams_client
- adv_prov
- cgms
- ddfs
- fast_pair
- mds

**Review by MarekPieta — APPROVED** [review]
Looks fine.
Maybe we could consider adding some automatic check that are triggered periodically to ensure that links and paths are valid (may be done in the future; e.g. we may consider using a Python script to ensure that links and paths lead to places that contain the needed API definitions). Aligning these manually may lead to issues in the future.

**Review by mia-ko — APPROVED** [review]

**Review by kapi-no — APPROVED** [review]

**Pull request closed without merging**
