### PR TITLE
doc: move all include and lib docs to the doc folder

### PR DESCRIPTION
**Pull request by gmarull**
This PR moves all docs files inside `include/` and `lib/` to their corresponding `doc/nrf/libraries` folder.

The reason for this change:
- Presence of docs outside the source folder is in general a bad Sphinx practice (in fact, it is not officially supported)
- Mixing source code and docs (not including Doxygen) should be considered a bad practice. I've personally never seen that before.
- This structure leads to a poor layout (there are a few toctrees that can be flattened)
- It's not trivial to guess where docs will be
- Developers may open first .rst files other than going to the full docs. This means that they may look at incomplete docs: includes, directives, links to references, etc. are only available on rendered docs. 

This change is an initial step to split the nrf docset into a "main" (general guides, etc.) docset and a "nrf" (technical nrf stuff) docset.

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by greg-fer** [comment]
Two questions:

- Why no tech writer has been asked for review for a PR that concerns moving docs around? I'm thinking especially about either @umapraseeda or @b-gent ...
- `It's not trivial to guess where docs will be` -- wouldn't the new structure mean it is even harder to understand if there are docs available for the given library? Keeping .rst files next to headers was a clear and easy indicator of this. What other way of tracking missing documentation you propose?

**Comment by greg-fer** [comment]
@gmarull , it's great to have order in the repo, but I have few remarks:

- This is a doc framework task about moving docs around. Would it be possible to have either @umapraseeda or @b-gent added from the start to such PRs? Having no tech writer in doc-related PRs seems odd...
- With regard to `It's not trivial to guess where docs will be` and the Sphinx bad practice notes -- This might be true from framework perspective, but the current structure was meant to 1) Allow users to quickly understand if a given library is documented and 2) Allow us (tech writers, devs...) to see at a glance if a given library is missing documentation. I don't think we are fully happy with that, but it would be great to keep the current structure...

**Review by trond-snekvik — APPROVED** [review]

**Comment by gmarull** [comment]
> @gmarull , it's great to have order in the repo, but I have few remarks:
> 
> * This is a doc framework task about moving docs around. Would it be possible to have either @umapraseeda or @b-gent added from the start to such PRs? Having no tech writer in doc-related PRs seems odd...

It's planned to discuss these moves, we're not going to merge this before.

> * With regard to `It's not trivial to guess where docs will be` and the Sphinx bad practice notes -- This might be true from framework perspective, but the current structure was meant to 1) Allow users to quickly understand if a given library is documented and 2) Allow us (tech writers, devs...) to see at a glance if a given library is missing documentation. I don't think we are fully happy with that, but it would be great to keep the current structure...

I think that the docs content structure is something it is ought to tech writers, definitely. However, when it introduces a programming bad practice (e.g. docs together with headers) or doesn't follow framework (Sphinx) good practices, then _doc framework_ should also have a vote. In the end, this affects the maintainability of the project from a technical perspective, not only its content. We should probably create a list of current issues that should be addressed in the long term and provide a list of projects that do things the _expected_ way to use them as a reference.

**Comment by b-gent** [comment]
This is a huge change that needs discussion, do not merge.

**Comment by b-gent** [comment]
I understand this was planned to be discussed, but in such case please open such PRs as draft or with DNM. This had two approvals already and I can easily imagine it getting merged immediately.

**Review by carlescufi — APPROVED** [review]
This is an excellent change that we should've done ages ago.

**Review by carlopaparo — APPROVED** [review]

**Comment by carlescufi** [comment]
@Rallare would be great to get Tech support's perspective on this.

**Comment by too1** [comment]
Håkon (Rallare) is back on the 9th of August, hopefully it can wait til then. 
Personally I have advocated for keeping the doc files for a couple of reasons:
- It makes it obvious that the example/driver is documented, and when working on the code you can easily take a peek at it
- For anyone not trained in internal documentation and SW development practices (ie support, customers) it makes it more obvious how you should include documentation, and how the documentation should be formatted
- When copying a driver or example you will copy the documentation as well, and know that is must be updated

That said, it would be very good to get Håkon's input on this as he has a much better Zephyr understanding than me, while also being able to see it from the customer perspective.

**Comment by carlescufi** [comment]
Note to both Tech Support and Tech doc writers: This is not only about convention, but also about simplifying the doc build process in order to be able to split the current main docset into two. The cleanups in this PR will allow @gmarull to proceed with the split in a scalable, maintainable way.

**Comment by Rallare** [comment]
This is a nice cleanup, can only see positive changes here. Good work!

**Review by Rallare — APPROVED** [review]

**Comment by Rallare** [comment]
@too1 : I understand your concerns, but we are talking about looking at raw .rst files in this scenario; where things like direct linking does not work. Copying a driver or library to make changes is a valid case, but I do not think that this is a very common use-case.

The generated docs does not look differently, its a pure move of the .rst files of supporting libraries/drivers to a dedicated ../docs folder to follow a more standardized way of handling documentation folder structure.

**Comment by umapraseeda** [comment]
The library listing here: http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5134/nrf/libraries/index.html has entries of NFC libraries(NFC Data Exchange Format (NDEF), Type 2 Tag, Type 4 Tag, Tag NDEF Exchange Protocol (TNEP)) one level up. Also, there is duplication of entries here: http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5134/nrf/libraries/modem/index.html

**Comment by gmarull** [comment]
> The library listing here: http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5134/nrf/libraries/index.html has entries of NFC libraries(NFC Data Exchange Format (NDEF), Type 2 Tag, Type 4 Tag, Tag NDEF Exchange Protocol (TNEP)) one level up. Also, there is duplication of entries here: http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5134/nrf/libraries/modem/index.html

@umapraseeda should be fixed now

**Comment by plskeggs** [comment]
Unfortunately, just last Thursday, the nRF Cloud team did its big launch, which included a large cloud documentation update from Patrick Barnes in Portland.

That documentation ([https://docs.dev.nrfcloud.com/OtherDocsAndTools]) linked specifically to nRF Cloud-related NCS libraries in the old, seemingly stable location.  So this PR being merged today caused newly launched cloud documentation to now be broken.  This is a shame.

In the future, any changes to the locations of documentation files need to have auto-forwarding from the previous locations, if at all possible.  Or, at a minimum, at least be mindful that there are other doc systems at Nordic that need to be kept in the loop of reorganization of these docs.

**Comment by mbolivar-nordic** [comment]
> That documentation (https://docs.nrfcloud.com/OtherDocsAndTools) linked specifically to nRF Cloud-related NCS libraries in the old, seemingly stable location.

I see links like https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/include/net/nrf_cloud_pgps.html in there which are now broken, for sure.

But there is a `/latest/` in that URL. You could have linked to https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.6.1/nrf/include/net/nrf_cloud_pgps.html (with `/1.6.1/` in the URL), which is still there.

You would have to update your docs when there is a new version of NCS, of course, but I think there's always going to be a risk of having to keep updating your links if you link to `/latest/`. It's like a GitHub link with a `/master/` branch in the URL; there are no guarantees it's forever.

**Comment by gmarull** [comment]
@plskeggs My apologies, I was not aware of that. We've been discussing this change for a while, and yesterday was approved by tech writers. As Martí suggests, using `latest` version links has such associated risk.

**Comment by plskeggs** [comment]
@gmarull and @mbolivar-nordic -- yes, normally I would agree that `latest` is not the right version to link to, but, keep in mind that nrfcloud is not bound to nor limited by the same release schedule as NCS (e.g., "internet time").  Sometimes cloud changes require matching NCS changes that will first appear in master, and only later be in an official point release.

**Comment by mbolivar-nordic** [comment]
I'm really sympathetic to the situation, and I would certainly give you a heads-up in the future about anything similar, but ultimately I think the onus is on your team to handle such situations.

If new cloud features are being rolled out before the corresponding NCS release, and your external docs for them link to the master branch documentation for NCS, then you need to make sure to keep those links up to date, because "master" is not an officially supported NCS release, and I don't think there is any agreement anywhere to keep docs links stable between releases.

Asking the maintainers to remember every group which might be impacted by some change doesn't really scale either IMO. That's what CODEOWNERS is for: you can send a PR adding yourself to the docs .rst files that generate whatever HTML in master that you link to, and then you'll get the warnings you need.

**Comment by plskeggs** [comment]
All good points.  The cloud team is putting in place an automatic link checker on their side to detect such problems moving forward, in order to prompt someone here to fix the cloud docs accordingly.

**Pull request merged**
