### PR TITLE
mpsl: cx: 3-wire generic coexistence implementation fixes

### PR DESCRIPTION
**Pull request by alexstanoev-nordic**
- `MPSL_CX_THREAD` currently does not build, as it was not updated when the function signatures for `nrfx_gpiote_trigger_*` changed.
- The KConfig dependency on !BT is not correct, as this implementation supports Bluetooth as well, due to using the generic coex API.
- The SDC multirole library was not correctly selected when using generic coex on nRF52-series devices.
- Rename `MPSL_CX_THREAD` to `MPSL_CX_3WIRE` to avoid confusion, as this implements a generic 3-wire PTA interface.
- The documentation mentions the PRIORITY pin also being used to indicate direction, but this does not match the implementation.

### CODE REVIEW

**Comment by ankuns** [comment]
Looks okay.
Would it be valuable to mention these changes in
https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst?plain=1#L413 regarding:
delault value of BT_LL_SOFTDEVICE_VARIANT 

and 
https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst?plain=1#L455

regarding the rename of Kconfig MPSL_CX_TRHEAD to MPLS_CX_3WIRE

**Review by rugeGerritsen — APPROVED** [review]
Looked through the changes in subsys/bluetooth and subsys/mpsl

**Review by ankuns — APPROVED** [review]
Looks good.
Just consider https://github.com/nrfconnect/sdk-nrf/pull/16427#issuecomment-2242560417

**Review by FrancescoSer — APPROVED** [review]
Added a small doc suggestion, approving

**Pull request merged**
