### PR TITLE
Spm nrf53 doc update

### PR DESCRIPTION
**Pull request by kapi-no**

### CODE REVIEW

**Comment by kapi-no** [comment]
Related with: #2368

**Comment by carlescufi** [comment]
@kapi-no please rebase

**Comment by kapi-no** [comment]
@carlescufi, done. Thanks for heads-up.

**Comment by carlescufi** [comment]
@kapi-no needs yet another rebase :)

**Comment by b-gent** [comment]
The output looks good, I made some small changes. I also looked through the docset to see if any other parts of documentation are affected by this, by it doesn't seem like that.

**Comment by kapi-no** [comment]
@b-gent, thanks for doc review. I have already integrated your changes.

This PR is ready to be merged once the CI is green.

**Comment by kapi-no** [comment]
@carlescufi, could you merge this?

**Pull request merged**
