### PR TITLE
Allow setting of azure_iot_hub DPS idscope at runtime in application

### PR DESCRIPTION
**Pull request by aldras**
Details here

https://devzone.nordicsemi.com/f/nordic-q-a/85590/nrf9160-azure_iot_hub-change-dps-username-during-run-time

I would like to have the ability added to change the Azure DPS idscope at runtime as the application pulls this username from an SD card based on which Azure IoT hub the application will attempt to provision with.  Having the DPS idscope fixed at build time does not allow the flexibility to be able to support multiple IoT hubs with the same build.

Up until now I add this change myself every release, but would be nice to have it already in the library so I don't need to change it each time I update to a new SDK.  I am sure some other users will benefit from this.  I am not sure this is the best way to implement this, and I honestly think its a little messy, but this is the basic idea.  Please feel free to rethink the way I chose to add this feature to be more in line with local code constantly.

### CODE REVIEW

**Comment by coderbyheart** [comment]
The [Azure IoT Hub DPS username](https://docs.microsoft.com/en-us/azure/iot-dps/iot-dps-mqtt-support#using-the-mqtt-protocol-directly-as-a-device) follows a specific schema (`{idScope}/registrations/{registration_id}/api-version=2019-03-31`), so rather than make the entire string configurable (which will lead to unexpected errors), I'd rather allow to set the ID scope at runtime.

**Comment by aldras** [comment]
Hi coderbyheart,
Thank you for the quick reply and the suggestions.  I do agree it is not the best solution but I am not very experienced with the Azure implementation and how Azure works internally.

The only goal that I had in mind is being able to set the DPS username (idscope) at runtime, this pull request was only an attempt at that effort.  Any solution that would be more more in line with a stable solution would be better than my suggestion.

This solution came about when I had to dig deep into the code to figure out a method to allow setting the DPS idscope at runtime as I set the idscope based on settings on an SD card.  This allows me to have only one build for the project and store site specific settings on an SD card.  The current implementation allows setting the (after DPS) normal connection idscope at runtime, but not the idscope used for DPS.  Currently it is set at buildtime through a define.  I was hoping to see if we can get that functionality added in to allow it to be set at runtime somehow, it would be greatly appreciated.

Summary, feel free to change around what I have done, if time permits before the next release, and see if we can't get something into worked in that is stable and does not change current functionality for current users.

--Allan

**Comment by aldras** [comment]
Hi coderbyheart,

I just thought again about what you wrote, bad choice of words on my part, the above merge request only allows changing the idscope, however, in the code the work "username" is used.  Yes I do have to agree with this, I would rather only like to allow altering the idscope as well, which is what I attempted.  Only the variable names are not named in an easy understood way.

**Comment by jtguggedal** [comment]
Hi @aldras. First, sorry for the delayed response! Thanks for your contribution. The option of setting the ID scope runtime seems like a good idea. We're currently in the middle of a major overhaul of the Azure IoT Hub implementation, so we'll make sure to add such an API at the same time.

**Comment by aldras** [comment]
Hi @jtguggedal
Thank you for the response and I am happy to hear it will be implemented in a coming release.
I am looking forward to the coming release.
You may close this pull request when you are ready, it is only remaining open as a reminder.

**Pull request closed without merging**
