### PR TITLE
manifest: Update zephyr to add missing HAS_HW_NRF_* entries for nRF5340

### PR DESCRIPTION
**Pull request by anangl**
This update adds a few missing selections of HAS_HW_NRF_* Kconfig
options for peripherals available in nRF5340.

Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]

**Review by pdunaj — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
sdk-zephyr PR is merged; I updated to a SHA here

**Comment by mbolivar-nordic** [comment]
Updated again to pull in the (trivial) sdk-zephyr change from https://github.com/nrfconnect/sdk-nrf/pull/5732 which is also merged now

**Review by tejlmand — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
Kicked off CI again

**Comment by anangl** [comment]
No longer needed. Zephyr revision was updated by another PR.

**Pull request closed without merging**
