### PR TITLE
doc: post-release doc update after 2.7.99-cs1

### PR DESCRIPTION
**Pull request by divipillai**
post-release doc update after 2.7.99-cs1

### CODE REVIEW

**Review by umapraseeda — CHANGES_REQUESTED** [review]
Please add back 2.7.99 to versions.json

**Comment by umapraseeda** [comment]
Also revert the versions on adding_code.rst and shortcuts.txt as in https://github.com/nrfconnect/sdk-nrf/pull/15085/files#diff-0cfe603f37e6b6a0bbd6cc31806ea087f474791a98cbeb30aca38b2f0b15500eR165

**Comment by divipillai** [comment]
> Also revert the versions on adding_code.rst and shortcuts.txt as in https://github.com/nrfconnect/sdk-nrf/pull/15085/files#diff-0cfe603f37e6b6a0bbd6cc31806ea087f474791a98cbeb30aca38b2f0b15500eR165

Shouldn't we keep the latest release version in these two files?

**Comment by richabp** [comment]
> > Also revert the versions on adding_code.rst and shortcuts.txt as in https://github.com/nrfconnect/sdk-nrf/pull/15085/files#diff-0cfe603f37e6b6a0bbd6cc31806ea087f474791a98cbeb30aca38b2f0b15500eR165
> 
> Shouldn't we keep the latest release version in these two files?

I think the latest release version is ok in these files.

**Comment by divipillai** [comment]
> > > Also revert the versions on adding_code.rst and shortcuts.txt as in https://github.com/nrfconnect/sdk-nrf/pull/15085/files#diff-0cfe603f37e6b6a0bbd6cc31806ea087f474791a98cbeb30aca38b2f0b15500eR165
> > 
> > 
> > Shouldn't we keep the latest release version in these two files?
> 
> I think the latest release version is ok in these files.

Discussed with Uma offline, and made the relevant changes.

**Review by umapraseeda — APPROVED** [review]

**Review by ns-tolu — APPROVED** [review]

**Review by richabp — APPROVED** [review]

**Pull request merged**
