### PR TITLE
manifest: Update softdevice-controller and MPSL revision

### PR DESCRIPTION
**Pull request by ibaz-nordic**
revision: update-ble-controller-and-mpsl-202105121530

Signed-off-by: Azizah Ibrahim <azizah.ibrahim@nordicsemi.no>

### CODE REVIEW

**Comment by wiminordic** [comment]
@pdunaj Desktop52 dongle is throwing an exception in one of the tests:
 [00010013] <err> sdc_hci_driver: SoftDevice Controller ASSERT: 21, 459
 [00010014] <err> os: ***** HARD FAULT *****
 [00010014] <err> os:   Fault escalation (see below)
 [00010014] <err> os: r0/a1:  0x00000003  r1/a2:  0x00000000  r2/a3:  0x200023a8
 [00010014] <err> os: r3/a4:  0x00000003 r12/ip:  0x2000a02a r14/lr:  0x0003cb8b
 [00010015] <err> os:  xpsr:  0x41000000
 [00010015] <err> os: Faulting instruction address (r15/pc): 0x0003cb96
 [00010015] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
 [00010015] <err> os: Current thread: 0x20003088 (unknown)
 [00308095] <err> os: Halting system

**Comment by joerchan** [comment]
@rugeGerritsen Can you have a look at the assert?

**Comment by pdunaj** [comment]
@wiminordic thanks!

**Review by pdunaj — CHANGES_REQUESTED** [review]
should not fail nrf_desktop tests

**Pull request closed without merging**
