### PR TITLE
doc: software maturity: add DECT NR+ PHY

### PR DESCRIPTION
**Pull request by lemrey**
Add DECT NR+ PHY to software maturity page.

### CODE REVIEW

**Comment by divipillai** [comment]
I don't see the DECT NR+ updated in the Software maturity page. - https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15743/nrf/releases_and_maturity/software_maturity.html.

**Comment by divipillai** [comment]
> I don't see the DECT NR+ updated in the Software maturity page. - https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15743/nrf/releases_and_maturity/software_maturity.html.

@gmarull : Could you please check this?

**Comment by divipillai** [comment]
> > I don't see the DECT NR+ updated in the Software maturity page. - https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15743/nrf/releases_and_maturity/software_maturity.html.
> 
> @gmarull : Could you please check this?

My bad, forgot that the page gets updated only after the nightly build is run, after the PR is merged.

**Review by divipillai — APPROVED** [review]

**Comment by lemrey** [comment]
Is there any way to check how this looks before merging? Can I build this locally?

**Comment by lemrey** [comment]
@divipillai I am unable to proceed further with this; CI does not build this page, and I struggle running it locally.

Running the script on `twister` output from:
```twister -vc -p nrf9161dk/nrf9161/ns --build-only -T samples/cellular/ -j 2``` produces something that I can't quite see how would be translated into the table in the documentation page.

The information should be correct, just don't know how it will render.

**Comment by gmarull** [comment]
> Is there any way to check how this looks before merging? Can I build this locally?

It's not (easily) possible, nightly artifacts are used.

**Review by umapraseeda — APPROVED** [review]

**Pull request merged**
