### PR TITLE
subsy/bootloader/cmake/debug_keys: fix SB_SIGNING_KEY supply

### PR DESCRIPTION
**Pull request by nvlsianpu**
ref:NCSDK-28124

### CODE REVIEW

**Review by sigvartmh — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@tejlmand
@shanthanordic 
If this PR won't go into NCS 2.7.0 then I have to add known issue instead.

**Comment by shanthanordic** [comment]
Pushed it to NCS 2.8.0 as this was already there

**Review by hakonfam — APPROVED** [review]

**Review by tejlmand — CHANGES_REQUESTED** [review]
Has this been tested to work ?

For sure it doesn't work with absolute paths.

**Review by tejlmand — CHANGES_REQUESTED** [review]
This has not been working for several NCS releases, so therefore this functionality was removed for sysbuild here: https://github.com/nrfconnect/sdk-nrf/pull/16154

If we consider this to be a bug that we want to fix for parent/child images, then we should support the same for sysbuild.

@nordicjm feel free to give additional comments.

Also, if this PR should be merged then a proper commit message should be written.

**Comment by nordicjm** [comment]
I do not think this should be fixed, it should be listed as a known issue and references to it removed from the help text. Fixing this gives a false sense of security of the feature working for users that might go back to older versions and be aware that this is a silent failure. The feature has never worked, let's just remove it.

**Comment by nvlsianpu** [comment]
@nordicjm @tejlmand I agree with your opinion.
This was never been seen working, child images are close to the end-of-life.

**Pull request closed without merging**
