### PR TITLE
boards: arm: thingy91: Rename static partitions file

### PR DESCRIPTION
**Pull request by jtguggedal**
Rename pm_static.yml to thingy91_pm_static.yml.
The previous filename would be picked up by the build system and
apply the partition configuration for both secure and non-secure
builds. This would make the secure application not work.
Renaming fixes this issue.

Fixes CIA-638

### CODE REVIEW

**Review by pdunaj — APPROVED** [review]

**Review by gregersrygg — APPROVED** [review]
LGTM 👍

**Review by jhn-nordic — APPROVED** [review]

**Review by balaji-nordic — APPROVED** [review]

**Review by shantha-14 — CHANGES_REQUESTED** [review]
downtream CI not executed, I need someone from test team to confirm this would work

**Review by MarekPieta — APPROVED** [review]

**Comment by jtguggedal** [comment]
> why is downstream thingy job not executed @jtguggedal or @jorgenmk

That's because the Thingy job doesn't run on target, so it wouldn't use the board files. @jorgenmk runs the nightly test (which runs on Thingy91 hw) manually

**Comment by jhn-nordic** [comment]
@shantha-14  this should go in.

**Review by jorgenmk — APPROVED** [review]
Nightly looks good

**Pull request merged**
