### PR TITLE
applications: asset_tracker_v2: Remove testcase

### PR DESCRIPTION
**Pull request by simensrostad**
Remove testcase for qemu cortex m3.
We already support native sim which is sufficient.

NCSDK-26369

### CODE REVIEW

**Review by bjda — APPROVED** [review]

**Review by balaji-nordic — APPROVED** [review]

**Review by gregersrygg — COMMENTED** [review]
native_sim does not work on macOS 😞

**Comment by jfischer-no** [comment]
@gregersrygg , @simensrostad is it ready to be merged? There are PRs (e.g. #14258) that fail on this test case.
```
[2024-03-04T13:52:30.118Z] INFO    - The following issues were found (showing the top 10 items):

[2024-03-04T13:52:30.118Z] INFO    - 1) asset_tracker_v2/tests/ui_module/asset_tracker_v2.ui_module_test.tester on qemu_cortex_m3 failed 
```

**Comment by simensrostad** [comment]
> @gregersrygg , @simensrostad is it ready to be merged? There are PRs (e.g. #14258) that fail on this test case.
> 
> ```
> [2024-03-04T13:52:30.118Z] INFO    - The following issues were found (showing the top 10 items):
> 
> [2024-03-04T13:52:30.118Z] INFO    - 1) asset_tracker_v2/tests/ui_module/asset_tracker_v2.ui_module_test.tester on qemu_cortex_m3 failed 
> ```

+1 from me

**Comment by gregersrygg** [comment]
> > native_sim does not work on macOS 😞
> 
> Sure, but do we need these tests to run on Mac?

No, but `qemu_cortex_m3` should work on macOS and is a way for me to run the tests. So I was thinking that we might want to keep `qemu_cortex_m3` in `platform_allow` and only remove it from `integration_platforms`. But looks like `qemu_cortex_m3` is failing anyways, and if it's blocking others it should probably just be merged as is.

**Pull request merged**
