### PR TITLE
doc: Updating known crypto issues for nRF Connect SDK v1.5.0

### PR DESCRIPTION
**Pull request by frkv**
-Adding known issues for

ref: NCSDK-7857
ref: NCSDK-7914
ref: NCSDK-8075

Signed-off-by: Frank Audun Kvamtrø <frank.kvamtro@nordicsemi.no>

### CODE REVIEW

**Comment by b-gent** [comment]
I'm adding a few edits, I wasnt sure which commit to amend so adding another one on top, please squash this as you fit. Perhaps we could turn all of it into one commit to make it easier. I'll approve if the doc CI passes.

**Comment by b-gent** [comment]
just to verify - @frkv  you are aware that the first two items you added are not marked for 1.5.0?

**Comment by frkv** [comment]
> just to verify - @frkv you are aware that the first two items you added are not marked for 1.5.0?

No. Now added milestone

**Comment by frkv** [comment]
Green CI, I think this is ready to go in

**Review by b-gent — APPROVED** [review]

**Review by umapraseeda — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]

**Pull request merged**
