### PR TITLE
application: asset_tracker: Send A-GPS request with small delay

### PR DESCRIPTION
**Pull request by jtguggedal**
Adds a workaround for corner-case where the A-GPS request would
never be sent if the A-GPS work was submitted immediately.
The solution is to add a delay of 1 seconds before sending
the request.

The PR is rebased on top of upmerge #2284.

### CODE REVIEW

**Comment by jtguggedal** [comment]
So... rebasing on top of the upmerge resulted in pulling in a gazillion reviewers. Apologies for that.

**Comment by rlubos** [comment]
DNM until upmerge is in and PR branch is rebased

**Comment by rlubos** [comment]
What about this commit https://github.com/nrfconnect/sdk-nrf/pull/2346/commits/de94a9e4b00697487a3fbca02ae291afc76ff963, it no longer seems to be needed?

**Comment by jtguggedal** [comment]
> What about this commit [de94a9e](https://github.com/nrfconnect/sdk-nrf/commit/de94a9e4b00697487a3fbca02ae291afc76ff963), it no longer seems to be needed?

Yeah that looked like a rebase going terribly wrong. Dropped that commit and rebased on master.

**Pull request merged**
