### PR TITLE
manifest: Update sdk-mcuboot revision

### PR DESCRIPTION
**Pull request by nordicjm**
Adds support for configuring the number of KMU slot numbers and changes the default to 1

### CODE REVIEW

**Review by michalek-no — APPROVED** [review]

**Comment by gchwier** [comment]
To fix tests number of KMU slots should be configured here:
https://github.com/nrfconnect/sdk-nrf/blob/main/tests/subsys/kmu/hello_for_kmu/sysbuild/mcuboot.conf
just add
`CONFIG_BOOT_SIGNATURE_KMU_SLOTS=3`

**Comment by gchwier** [comment]
In logs from CI tests I see, that `west ncs-provision` command receives success (configured 1 KMU slot and uploading 3 keys):
```
12:49:52.73:INFO:common: CMD: west ncs-provision upload --soc nrf54l15 --key /jenkins_workspace/workspace/latest_sub_test-sdk-mcuboot_main/bootloader/mcuboot/root-ed25519.pem --key /jenkins_workspace/workspace/latest_sub_test-sdk-mcuboot_main/nrf/tests/subsys/kmu/keys/root-ed25519-1.pem --key /jenkins_workspace/workspace/latest_sub_test-sdk-mcuboot_main/nrf/tests/subsys/kmu/keys/root-ed25519-2.pem --dev-id 001057783514
12:49:57.279:INFO:common: Keys provisioned successfully
```
(only the first key works). Is it ok? Should not this command receive any warning?
FYI @michalek-no

**Comment by nvlsianpu** [comment]
> In logs from CI tests I see, that `west ncs-provision` command receives success (configured 1 KMU slot and uploading 3 keys):
> 
> ```
> 12:49:52.73:INFO:common: CMD: west ncs-provision upload --soc nrf54l15 --key /jenkins_workspace/workspace/latest_sub_test-sdk-mcuboot_main/bootloader/mcuboot/root-ed25519.pem --key /jenkins_workspace/workspace/latest_sub_test-sdk-mcuboot_main/nrf/tests/subsys/kmu/keys/root-ed25519-1.pem --key /jenkins_workspace/workspace/latest_sub_test-sdk-mcuboot_main/nrf/tests/subsys/kmu/keys/root-ed25519-2.pem --dev-id 001057783514
> 12:49:57.279:INFO:common: Keys provisioned successfully
> ```
> 
> (only the first key works). Is it ok? Should not this command receive any warning? FYI @michalek-no

Yes, that's fine. All KMU slot are available to be populated as this is independent thing. Only 1st one will be used.

**Comment by nvlsianpu** [comment]
> To fix tests number of KMU slots should be configured here: https://github.com/nrfconnect/sdk-nrf/blob/main/tests/subsys/kmu/hello_for_kmu/sysbuild/mcuboot.conf just add `CONFIG_BOOT_SIGNATURE_KMU_SLOTS=3`

@nordicjm Can you apply?

**Comment by nordicjm** [comment]
> > To fix tests number of KMU slots should be configured here: https://github.com/nrfconnect/sdk-nrf/blob/main/tests/subsys/kmu/hello_for_kmu/sysbuild/mcuboot.conf just add `CONFIG_BOOT_SIGNATURE_KMU_SLOTS=3`
> 
> @nordicjm Can you apply?

Applied

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
CI failure, for instance:
> nrf54l15dk/nrf54l15/cpuapp mcuboot.kmu.west.provision.wrong_key                ERROR Build failure (build)

**Review by gchwier — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
