### PR TITLE
samples: nrf9160: aws_iot: Add reconnection work

### PR DESCRIPTION
**Pull request by simensrostad**
Add delayed work item that tries to reconnect upon an
AWS_IOT_DISCONNECT event with configurable interval
in between retries.

 **This PR also changes the default log level for certain log output in AWS jobs/fota

NCSDK-6623

### CODE REVIEW

**Comment by greg-fer** [comment]
Hey @simensrostad , given this:

> **This PR also changes the default log level for certain log output in AWS jobs/fota

Shouldn't these changes be mentioned in release notes? Not to mention updates to documentation?

**Comment by simensrostad** [comment]
> Hey @simensrostad , given this:
> 
> > **This PR also changes the default log level for certain log output in AWS jobs/fota
> 
> Shouldn't these changes be mentioned in release notes? Not to mention updates to documentation?

Hi, this change really doesn't impose any impact rather than hiding unnecessary log output from the app (which usually uses LOG_INF). To get log output from these libraries the appropriate log level must be set in the prj.conf just as any other library only omitting debug prints.

**Review by rlubos — APPROVED** [review]
LGTM

**Review by lemrey — APPROVED** [review]

**Review by sigvartmh — APPROVED** [review]
Looks reasonable

**Review by shantha-14 — APPROVED** [review]

**Pull request merged**
