### PR TITLE
zigbee: Add support for nRF5340

### PR DESCRIPTION
**Pull request by wbober**
This PR adds support for nRF5340. This is fine for review but there are many dependencies that must go in before this can get merged. 

https://github.com/nrfconnect/sdk-zephyr/pull/390
~~https://github.com/nrfconnect/sdk-nrf/pull/3357~~
https://github.com/nrfconnect/sdk-nrfxlib/pull/339

### CODE REVIEW

**Review by greg-fer — APPROVED** [review]
Please check my changes in the commit and squash it.
We need to wait until the requirement reference file is updated with the nRF5340 entry.
(Same as #3345)

**Review by maciekfabia — APPROVED** [review]
lgtm

**Review by tomchy — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
@rlubos can you take a look as well?

**Comment by wbober** [comment]
@ioannisg Doing a re-run of the CI build. It failed on unrelated error (JLINK error) on a downstream job.

**Review by tejlmand — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]
oe of commit message mentions the change on which it is depend:
```
zigbee: Align with new ZBOSS scheduler API

Since 11/30/2020 ZBOSS the scheduler API has been simplified to match
the macro defines.
```

better to post commit SHA and repo where change was made than a date.

**Review by rlubos — COMMENTED** [review]
Looks good (verified SHA's), but commit https://github.com/nrfconnect/sdk-nrf/pull/3405/commits/254796d32f3dcb29423fa6cc24e4e31f9451123a was just introduced into master by OT PR https://github.com/nrfconnect/sdk-nrf/pull/3345, not sure why isn't GH marking a conflict.

**Review by rlubos — APPROVED** [review]

**Comment by tomchy** [comment]
> better to post commit SHA and repo where the change was made than a date.

This might not be so intuitive, but dates are the official way of naming ZBOSS releases. Those dates are always put as a metadata in nrfxlib's update commits.

**Comment by thst-nordic** [comment]
This fixes sanitycheck failures on master, we agreed to merge without system-integration tests because of time.

**Pull request merged**
