### PR TITLE
lib: nrf_modem: Revert "lib: nrf_modem: Move trace processing to thread"

### PR DESCRIPTION
**Pull request by balaji-nordic**
This reverts commit 2125825e7a83f973257f1c7d8a4164b8033be70d.
The changes are reverted to due to failing modem shell tests. Will bring
the changes back after fixing the modem shell application.

Signed-off-by: Balaji Srinivasan <balaji.srinivasan@nordicsemi.no>

### CODE REVIEW

**Review by gregersrygg — APPROVED** [review]

**Comment by lemrey** [comment]
Can we please add one commit to make sure the CI that failed is triggered when these files will be modified again?

**Comment by gregersrygg** [comment]
@lemrey We can add the failing CI test to the next PR that reverts the revert. Another team has identified #6930 to be the cause of the failing tests, and their CI is now broken. Please approve.

**Review by lemrey — COMMENTED** [review]
It seems the test suite is (and was) triggered correctly. @moksanen said some changes were made to increase the extent to which the fidoless tracing functionality is exercised, to catch this kind of issues next time. Have added him as a reviewer.

**Review by moksanen — APPROVED** [review]
Lgtm, full revert should fix issues seen in modem_shell and location sample.
We can set up a custom test plan to test the change throughly before next merge attempt. CI tests that are run for PR's will catch most issues, but it has 15min time limitation, so it cannot contain all modem_shell tests. With custom test plan we can make sure that the change will pass NCS CI nightly checks after merge, too.

**Pull request merged**
