### PR TITLE
Kconfig: fix default ESB interrupt priorities

### PR DESCRIPTION
**Pull request by psykana**
This sets the default IRQ priorities to match the requirements in documentation:
https://github.com/nrfconnect/sdk-nrf/blob/ea83b7edbce161873baec8828400579f8c96f035/doc/nrf/ug_esb.rst#resources

### CODE REVIEW

**Review by KAGA164 — CHANGES_REQUESTED** [review]
Please add ``Signed-off-by:`` in commit message and maximum line length in commit message is 80 characters. Please split your commit message into several lines

**Comment by lemrey** [comment]
@too1 could you please have a look?

**Comment by KAGA164** [comment]
Sorry I was wrong about commit message max line length. It is 72 due to the compliance check. You need to split your commit message into two lines.

**Comment by psykana** [comment]
@KAGA164 That I can see. But what about the first error? I don't really get what that is.

**Comment by KAGA164** [comment]
> @KAGA164 That I can see. But what about the first error? I don't really get what that is.

If you mean first compliance error I think this is about your commit message line length as well. It is probably displayed every time when compliance check detect any issue. I suggest rebasing your PR on current main and splitting commit message into two lines

**Review by grochu — CHANGES_REQUESTED** [review]
The changes looks good to me. Just please add a relevant statement in https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/releases/release-notes-changelog.rst so the change gets visibility as it can affect the user applications.

**Comment by psykana** [comment]
My god, this is embarrassing.

**Pull request closed without merging**
