### PR TITLE
net: lib: aws jobs: Add missing dependency for random number generator

### PR DESCRIPTION
**Pull request by sigvartmh**
Add a dependency to the AWS Jobs library to the zephyr random API for
random number generation.

Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>

### CODE REVIEW

**Comment by sigvartmh** [comment]
required by https://github.com/NordicPlayground/nrfxlib/pull/99#pullrequestreview-400783049

**Comment by sigvartmh** [comment]
> Thanks for this.
> 
> For sure this is one step in right direction, as there is a dependency to `ENTROPY_GENERATOR` but based on this comment:
> [NordicPlayground/nrfxlib#99 (comment)](https://github.com/NordicPlayground/nrfxlib/pull/99#discussion_r414536670)
> then I assume we need something more, cause in the situation described by the comment, then `ENTROPY_GENERATOR=y`

Looking at the CMake file of zephyr's random subsys the only requirements should be and `(CONFIG_ENTROPY_DEVICE_RANDOM_GENERATOR or CONFIG_HARDWARE_DEVICE_CS_GENERATOR)` 

Since the API missing is hidden behind an
`#if defined(CONFIG_ENTROPY_DEVICE_RANDOM_GENERATOR)`

I would say it's safe to say that `CONFIG_ENTROPY_DEVICE_RANDOM_GENERATOR` is the only dependency which is actually needed for this.

**Comment by tejlmand** [comment]
@sigvartmh could you rebase

**Comment by sigvartmh** [comment]
Rebased

**Comment by rlubos** [comment]
@sigvartmh The CI apparently goes crazy on this PR, could you rebase?

**Comment by sigvartmh** [comment]
Sure ;)

**Pull request merged**
