### PR TITLE
[RFC] Add initial nrfx docs integration

### PR DESCRIPTION
**Pull request by utzig**
This PR adds new cmake rules, sphinx and doxygen configs to enable building documentation for `modules/hal/nordic/nrfx`. Also adds a theme for nrfx and update other themes to show nrfx on the sidebar. Add some initial content based on the doxygen .dox files available in the main `nrfx` repo and try to mimic the results of running doxygen in the repo itself.

JIRA: NCSDK-2932

### CODE REVIEW

**Comment by carlescufi** [comment]
I am getting thousands of errors similar to this ones:
```
If the function has a return type:
  Error in declarator or parameters and qualifiers
  If pointer to member declarator:
    Invalid definition: Expected '::' in pointer to member (function). [error at 27]
      NRF_STATIC_INLINE uint32_t nrf_mwu_subregions_read_accesses_get(NRF_MWU_Type  const * p_reg, uint8_t per_reg_idx)
      ---------------------------^
  If declarator-id:
    Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 27]
      NRF_STATIC_INLINE uint32_t nrf_mwu_subregions_read_accesses_get(NRF_MWU_Type  const * p_reg, uint8_t per_reg_idx)
      ---------------------------^
/home/carles/src/ncs/nrf/doc/build/nrfx/rst/doc/nrfx/nrfx_api.rst:268: WARNING: Error when parsing function declaration.
If the function has no return type:
  Error in declarator or parameters and qualifiers
  Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 18]
    NRF_STATIC_INLINE void nrf_mwu_subregions_read_accesses_clear(NRF_MWU_Type  * p_reg, uint8_t per_reg_idx, uint32_t subregion_mask)
    ------------------^
If the function has a return type:
  Error in declarator or parameters and qualifiers
  If pointer to member declarator:
    Invalid definition: Expected identifier in nested name, got keyword: void [error at 22]
      NRF_STATIC_INLINE void nrf_mwu_subregions_read_accesses_clear(NRF_MWU_Type  * p_reg, uint8_t per_reg_idx, uint32_t subregion_mask)
      ----------------------^
  If declarator-id:
    Invalid definition: Expected identifier in nested name, got keyword: void [error at 22]
      NRF_STATIC_INLINE void nrf_mwu_subregions_read_accesses_clear(NRF_MWU_Type  * p_reg, uint8_t per_reg_idx, uint32_t subregion_mask)
      ----------------------^
/home/carles/src/ncs/nrf/doc/build/nrfx/rst/doc/nrfx/nrfx_api.rst:277: WARNING: Parsing of expression failed. Using fallback parser. Error was:
Error in postfix expression, expected primary expression or type.
If primary expression:
  Invalid definition: Expected identifier in nested name. [error at 95]
    nrf_nfct_hal::NRF_NFCT_SENSRES_NFCID1_SIZE_SINGLE=        NFCT_SENSRES_NFCIDSIZE_NFCID1Single << NFCT_SENSRES_NFCIDSIZE_Pos
    -----------------------------------------------------------------------------------------------^
If type:
  Invalid definition: Expected identifier in nested name. [error at 95]
    nrf_nfct_hal::NRF_NFCT_SENSRES_NFCID1_SIZE_SINGLE=        NFCT_SENSRES_NFCIDSIZE_NFCID1Single << NFCT_SENSRES_NFCIDSIZE_Pos
    -----------------------------------------------------------------------------------------------^
/home/carles/src/ncs/nrf/doc/build/nrfx/rst/doc/nrfx/nrfx_api.rst:277: WARNING: Parsing of expression failed. Using fallback parser. Error was:
```

**Comment by carlescufi** [comment]
@kl-cruz and @anangl could you please review?

**Comment by utzig** [comment]
> Please update:
> https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/doc_build.html#building-documentation-output

done

> I am getting thousands of errors similar to this ones:

Yeah, I fixed the easy ones, and I'm investigating the few remaining ones that are for shift amount masks. I temporarily commented out lpcomp/ncft/uart/uarte HALs from the generated documentation, so no warning are generated.

**Comment by b-gent** [comment]
> @kl-cruz and @anangl could you please review?

Please put this PR on hold for now, do not invest time in it yet. We are having a meeting on Friday where we will discuss the future of nrfx docs once again and determine how to proceed.

This PR converts the current doxygen documentation of nrfx into RST so it leaves us with the same docs in two different places, in two different formats. This is something we don't want. 

The original idea for nrfx doc integration was to generate an HTML docset from the original doxygen source and then embed this HTML into the NCS docset in as seamless way as possible. But right now we are also seriously considering an option of moving this doc to the infocenter and only referring to it from NCS. I will come back to you about this on Friday afternoon.

**Comment by carlescufi** [comment]
Note: This is an automated message.
@utzig this Pull Request has not been updated for more than a month, please close it if not applicable anymore.
@kl-cruz  @ru-fu  @anangl  @jdstapes  @b-gent  please close it if the author is not available

**Comment by ru-fu** [comment]
This isn't needed anymore. nrfx docs are in Infocenter now.

**Pull request closed without merging**
