### PR TITLE
samples: alexa_gadget: Add ci_build tag

### PR DESCRIPTION
**Pull request by nordic-auko**
Add ci_build tag to alexa_gadget bluetooth sample.

Signed-off-by: Audun Korneliussen <audun.korneliussen@nordicsemi.no>

### CODE REVIEW

**Review by joerchan — APPROVED** [review]

**Comment by joerchan** [comment]
@nordic-auko There seems to be some problems in CI.
```
AttributeError: module 'nanopb.generator.proto.nanopb_pb2' has no attribute 'IS_8'
```

**Comment by nordic-auko** [comment]
> 
> 
> @nordic-auko There seems to be some problems in CI.
> 
> ```
> AttributeError: module 'nanopb.generator.proto.nanopb_pb2' has no attribute 'IS_8'
> ```

Yeah, trying to figure it out. It builds fine on the CI dockerimage locally

**Comment by nordic-auko** [comment]
> 
> 
> > @nordic-auko There seems to be some problems in CI.
> > ```
> > AttributeError: module 'nanopb.generator.proto.nanopb_pb2' has no attribute 'IS_8'
> > ```
> 
> Yeah, trying to figure it out. It builds fine on the CI dockerimage locally

Found the problem. Will have to make an adjustment to the CI Dockerfile.

**Review by carlescufi — APPROVED** [review]

**Review by PerMac — APPROVED** [review]

**Comment by joerchan** [comment]
@nordic-auko Is the dockerfile issue resolved? The CI is still red.

**Comment by nordic-auko** [comment]
> 
> 
> @nordic-auko Is the dockerfile issue resolved? The CI is still red.

It should be fixed in v2.4 of the docker image. Still waiting for this image to be deployed to CI

**Pull request merged**
