### PR TITLE
lib: modem_key_mgmt: convert PSK to hex string

### PR DESCRIPTION
**Pull request by mniestroj**
"nRF91 AT Commands" document specifies that PSK should be sent over
serial in hex string representation. modem_key_mgmt_write() gets binary
data now, so convert PSK to hex string implicitly in the function.

### CODE REVIEW

**Comment by rlubos** [comment]
> modem_key_mgmt_write() gets binary data now, so convert PSK to hex string implicitly in the function.

Sorry, I'm a bit confused here, why the assumption that `modem_key_mgmt_write()` expects binary, did we document it like this somewhere? We have already example usage of this API in the tree, where PSK is simply provided as a hexstring (https://github.com/nrfconnect/sdk-nrf/blob/master/samples/nrf9160/lwm2m_client/src/main.c#L263 for instance).

**Comment by mniestroj** [comment]
>Sorry, I'm a bit confused here, why the assumption that modem_key_mgmt_write() expects binary, did we document it like this somewhere?

No, it is not documented explicitly what should be passed as argument. This is only based on "how **I would** expect it to work" looking at the type of arguments (`const void *buf, size_t len`) this functions gets. Also, this function is similar to `tls_credential_add()` from mainline Zephyr, so I once again I was expecting the same behavior from `modem_key_mgmt_write()` when porting code from vanilla Zephyr to nRF9160 specific code.

>We have already example usage of this API in the tree, where PSK is simply provided as a hexstring (https://github.com/nrfconnect/sdk-nrf/blob/master/samples/nrf9160/lwm2m_client/src/main.c#L263 for instance).

I was searching for usage examples, but I missed that somehow.

**Comment by rlubos** [comment]
@lemrey Perhaps we should improve the documentation then? It seems that the library docs (https://github.com/nrfconnect/sdk-nrf/blob/master/include/modem/modem_key_mgmt.rst) only covers a certificate provisioning.

**Comment by rlubos** [comment]
> Also, this function is similar to tls_credential_add() from mainline Zephyr, so I once again I was expecting the same behavior from modem_key_mgmt_write() when porting code from vanilla Zephyr to nRF9160 specific code.

Unfortunately, this API was designed more in a modem-centric way, so it handles credentials in a format that modem expects.

**Comment by mniestroj** [comment]
>Perhaps we should improve the documentation then? It seems that the library docs (https://github.com/nrfconnect/sdk-nrf/blob/master/include/modem/modem_key_mgmt.rst) only covers a certificate provisioning.

Having an example with PSK and PSK-ID will definitely be helpful. Apart from that doxygen description of `modem_key_mgmt_write()` should clearly state what is expected format of PSK.

>Unfortunately, this API was designed more in a modem-centric way, so it handles credentials in a format that modem expects.

Okay. Shoudn't there be an API that abstracts the limitations / details of AT commands (so that PSK is converted to hex string implicitly)?

**Comment by rlubos** [comment]
> > Unfortunately, this API was designed more in a modem-centric way, so it handles credentials in a format that modem expects.
> 
> Okay. Shoudn't there be an API that abstracts the limitations / details of AT commands (so that PSK is converted to hex string implicitly)?

I think there is a place for such an API, ideally, the `tls_credential` module could be updated to support custom credential providers, so that we could provide a shim for `modem_key_mgmt`. However, there were no strong push (nor need) for that yet.

**Comment by mniestroj** [comment]
>I think there is a place for such an API, ideally, the tls_credential module could be updated to support custom credential providers, so that we could provide a shim for modem_key_mgmt. However, there were no strong push (nor need) for that yet.

It would be ideal to handle modem credentials over `tls_credential` module, so have single API for vanilla Zephyr (with mbedTLS sockets) as well as for nRF91 specific code. The question is how would we know which credential provider should be used? Based on the network interface? That is a tricky thing to design I guess.

**Comment by lemrey** [comment]
Thanks for the feedback @mniestroj , food for thoughs :)

**Pull request closed without merging**
