### PR TITLE
Changing service name to nRF Cloud from Connect for Cloud

### PR DESCRIPTION
**Pull request by melwee01**
Do not merge yet--need approval from PMT.

### CODE REVIEW

**Comment by peknis** [comment]
The three links.txt files are a bit weird. I think you only should have one of them (without any extra text, like for example BASE).

**Comment by melwee01** [comment]
Ah, something's gone wrong in the conflict resolution then. That's from my diff software.

**Review by jhn-nordic — APPROVED** [review]

**Comment by jayteemo** [comment]
@melwee01 the name change has been approved, are you able get back to this pr?

**Comment by plskeggs** [comment]
Good thing I searched for this... I was about to make the same changes.

**Comment by whelppi** [comment]
Please change the naming convention wherever needed: "nRF Cloud" instead of "nRF Connect for Cloud"

**Comment by melwee01** [comment]
Running into issues with build. Going to start from a fresh PR.

**Pull request closed without merging**
