### PR TITLE
Fix minor (D)PPI issues in MPSL/FEM

### PR DESCRIPTION
**Pull request by czeslawmakarski**
This PR several minor bugs in MPSL FEM.

### CODE REVIEW

**Review by joerchan — APPROVED** [review]

**Comment by joerchan** [comment]
These are both cherry-picked from master, right?

**Comment by czeslawmakarski** [comment]
@joerchan No, these are the original commits - no such commits present on master (yet). Should I open the same PR to the master branch right now and merge it there? What are the procedures?

**Review by JakubPegza — APPROVED** [review]

**Comment by joerchan** [comment]
@czeslawmakarski well one of the commits are from here: https://github.com/nrfconnect/sdk-nrf/pull/4234
Submitting to master and backport through cherry-picking is the procedure.

Can you please submit the other commit to master as well? You can just include it in the already open PR.

**Review by kromancer — APPROVED** [review]

**Comment by czeslawmakarski** [comment]
@joerchan Done.

**Review by ktaborowski — APPROVED** [review]
The fix works fine with HomeKit application

**Pull request merged**
