### PR TITLE
doc: capitalization for mesh

### PR DESCRIPTION
**Pull request by mia-ko**
NCSDK-6998: Updating capitalization for mesh and sample renaming

Signed-off-by: Mia Koen <mia.koen@nordicsemi.no>

### CODE REVIEW

**Comment by mia-ko** [comment]
Pay special attention to sample renaming, please. Just to be sure that I've managed to catch everything in the docs.
But, when it comes to sample renaming, we might need a round with updating other files than the rst ones too, right..?

**Review by trond-snekvik — CHANGES_REQUESTED** [review]
There are still some instances of Bluetooth Mesh in:
- README.rst
- doc/nrf/index.rst
- known_issues.rst
- ug_ble_controller.rst
- properties.rst
There are also quite a few in headers, kconfig and prj.conf files, do we want to address those as well?

**Comment by mia-ko** [comment]
> There are still some instances of Bluetooth Mesh in:
> 
> * README.rst
> * doc/nrf/index.rst
> * known_issues.rst
> * ug_ble_controller.rst
> * properties.rst
>   There are also quite a few in headers, kconfig and prj.conf files, do we want to address those as well?

properties.rst file is ok :) The Bluetooth Mesh occurrence is due to specification name. But the rest of the rst files should be addressed! I will fix that.
We should address the non-rst files too, yes. Am I supposed/"allowed" to do that?

**Comment by trond-snekvik** [comment]
> We should address the non-rst files too, yes. Am I supposed/"allowed" to do that?

Yes, go ahead!

**Review by trond-snekvik — APPROVED** [review]

**Review by trond-snekvik — CHANGES_REQUESTED** [review]
Needs rebase to resolve conflicts

**Review by trond-snekvik — APPROVED** [review]

**Review by omkar3141 — APPROVED** [review]

**Pull request merged**
