### PR TITLE
applications: asset_tracker_v2: fix LNA configuration in Windows build

### PR DESCRIPTION
**Pull request by tokangas**
Fixed AT commands used to configure GNSS LNA when application is built in Windows. For some reason the escaped Kconfig AT command string is parsed differently in Windows, which causes the LNA configuration to fail when ATv2 starts.

The problem is, that if a configuration string has two escaped percent signs, the generated configuration in Linux has two percent signs as expected, but in Windows there's only one.

Kconfig:
`default "AT\%\%XMAGPIO=1,0,0,1,1,1574,1577" if BOARD_NRF9160DK_NRF9160_NS`

Generated .config in Linux:
`CONFIG_GNSS_MODULE_AT_MAGPIO="AT%%XMAGPIO=1,0,0,1,1,1574,1577"`

Generated .config in Windows:
`CONFIG_GNSS_MODULE_AT_MAGPIO="AT%XMAGPIO=1,0,0,1,1,1574,1577"`

The actual root cause is somewhere in the Kconfig parsing, I guess, but this works around the issue so that ATv2 works properly when built in Windows.

CIA-529

### CODE REVIEW

**Review by jhn-nordic — APPROVED** [review]

**Review by coderbyheart — APPROVED** [review]

**Review by lemrey — APPROVED** [review]

**Review by simensrostad — APPROVED** [review]

**Review by jtguggedal — APPROVED** [review]
Nice catch, thanks!

**Comment by tokangas** [comment]
Had to update also the tests, because the `nrf_modem_at_printf()` mock doesn't get the actual AT command string, but only `"%s"`. To be able to check the string properly, the application code would have to be modified.

**Comment by plskeggs** [comment]
> Nice catch, thanks!

A new employee, Georges Larsen, found this during onboarding.

**Comment by glarsennordic** [comment]
Awesome!

One bit of minutia, it looks like the original commit that introduced this inconsistency:

https://github.com/nrfconnect/sdk-nrf/commit/5ed65dc037426206b103cc7ce3274de98b6cc93d

also doubled the percent signs on lines 41/42 inside gnss_module/CMakeLists.txt:

```
-DCONFIG_GNSS_MODULE_AT_MAGPIO="AT%XMAGPIO"
-DCONFIG_GNSS_MODULE_AT_COEX0="AT%XCOEX0"
```

became
```
-DCONFIG_GNSS_MODULE_AT_MAGPIO="AT%%XMAGPIO"
-DCONFIG_GNSS_MODULE_AT_COEX0="AT%%XCOEX0"
```

I suggest that this change be reverted with this PR to maintain consistency

**Comment by tokangas** [comment]
> I suggest that this change be reverted with this PR to maintain consistency

@glarsennordic Good catch, I missed that one. I've added it now.

> Also, the Jira ticket that first outlined this bug is CIA-529, can that be added to the commit message?

Thanks for the bug, I added it to the commit message.

**Pull request merged**
