### PR TITLE
treewide: add configurations for Thingy:91 X

### PR DESCRIPTION
**Pull request by maxd-nordic**
This patch adds configurations to samples and
applications that don't need code changes to
support the Thingy:91 X.

### CODE REVIEW

**Review by plskeggs — APPROVED** [review]
Seems OK, though we do not have any way to test this -- we have no Thingy:91Xs here yet.

**Review by stig-bjorlykke — APPROVED** [review]

**Review by SeppoTakalo — APPROVED** [review]

**Review by juhaylinen — APPROVED** [review]

**Comment by maxd-nordic** [comment]
`sample.cellular.modem_shell.app_fota` was broken by commit df8fcf03e62e4e6662771b984d107d7fcbca7803: manifest: pull nRF54L15 and nRF54H20 from upstream
Let's see if I can find out why TFM suddenly needs so much space

**Comment by maxd-nordic** [comment]
skipping mosh for now since the build is broken

**Comment by trantanen** [comment]
> skipping mosh for now since the build is broken

MOSH is in quarantine by the PR you mentioned and no idea why it's still built.

**Pull request merged**
