### PR TITLE
doc: chip: update for windows support

### PR DESCRIPTION
**Pull request by greg-fer**
Updated Required tools and Getting Started manually pages.
They now mention GN tool versions and Windows install steps.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

### CODE REVIEW

**Comment by greg-fer** [comment]
@rlubos , @tejlmand , can you have a look at changes in the versions.txt.in file and related ones?

**Comment by mbolivar-nordic** [comment]
I'm confused about why this isn't a part of https://github.com/nrfconnect/sdk-nrf/pull/3670. There are various shared lines. What's going on?

**Comment by LuDuda** [comment]
Fixed.

**Comment by greg-fer** [comment]
Forgot to close this one. Thanks for help, @LuDuda .

**Pull request closed without merging**
