### PR TITLE
manifest: Update Zephyr revision

### PR DESCRIPTION
**Pull request by anangl**
Update the zephyr module revision to pull in several bug fixes
related to pinctrl and updated PWM API.

Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>

### CODE REVIEW

**Comment by anangl** [comment]
Rebased.

**Comment by anangl** [comment]
Rebased.

**Comment by anangl** [comment]
Rebased.

**Comment by anangl** [comment]
Rebased.

**Review by gmarull — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
