### PR TITLE
manifest: nrf_modem: KConfig menu

### PR DESCRIPTION
**Pull request by lemrey**
Add a Kconfig menu for `nrf_modem`.

### CODE REVIEW

**Comment by DatGizmo** [comment]
Right now this PR runs all Integration tests because it changes sdk-nrfxlib in west.yml and there is no test-spec.yml in that repo yet.
You can add changes to this PR [nrfconnect/sdk-nrfxlib#687](https://github.com/nrfconnect/sdk-nrfxlib/pull/687) to make the test spec here more targeted

Then run CI here to update the test spec.

[Information about the test spec feature](https://projecttools.nordicsemi.no/confluence/display/NCS/Test+Spec)
[CI-Help for issues](https://ci-help.nordicsemi.no/)

**Comment by DatGizmo** [comment]
To get the manifest check to pass an update to the PR is needed for GitHub to use the correct .github/workflows/manifest.yml.

The best way to do this is to rebase the PR onto main, [so the fix is included.](https://github.com/nrfconnect/sdk-nrf/pull/7139)

A simple re trigger of the test sadly does not work as it will still use the faulty variant of the file.

**Comment by lemrey** [comment]
Thank you @DatGizmo

**Review by tejlmand — APPROVED** [review]
lgtm

**Review by eivindj-nordic — APPROVED** [review]

**Comment by lemrey** [comment]
Updated SHA: 5be8b3cdd2401a756b5509489155fac67740d072

**Review by rlubos — APPROVED** [review]

**Comment by lemrey** [comment]
Trying to re-run CI

**Comment by mbolivar-nordic** [comment]
@lemrey please rebase if still required

**Pull request closed without merging**
