### PR TITLE
docs: Include optional Find My docset to the build

### PR DESCRIPTION
**Pull request by doki-nordic**
This commit adds Find My docset to the documentation build if find-my module is enabled in west.yml.

Currently we are working in a separate fork to build Find My documentation. I clean it up and I see no reason why it should not be included into mainstream. It will be required sooner or later, if we want to integrate also documentation from private repos.

### CODE REVIEW

**Comment by doki-nordic** [comment]
@gmarull, what is the policy regarding `/doc/find-my/` directory? Should I add me or you as a code owner?

**Comment by carlescufi** [comment]
@doki-nordic thanks for the proposal. The issues we have identified:
- The GH action needs to be changed to add the find-my group before running `west update`
- The doc preview render will need to have access control for the find-my docset as well
- The publishing needs to be updated as per the internal ticket with IT

**Comment by doki-nordic** [comment]
@carlescufi, issues that you presenting are relevant if we want to publish the documentation with find-my optional module enabled. That's not my intention now. We should wait for it until we know how to actually publish them. This PR should change nothing in current documentation builds that are done outside Find My repo.

Intentions of this PR are:
* Provide an easy way to manually build documentation for Find My project.
* Improve automated builds that we are doing (for now) in context of Find My repo.
* Provide first step towards full documentation integration.

If you think that it is too early to introduce those changes, I have no problem with postponing this PR until we know more regarding publishing.

**Comment by carlescufi** [comment]
@umapraseeda @b-gent and @gmarull should we discuss this together with @doki-nordic?

**Pull request closed without merging**
