### PR TITLE
 drivers: gps: update the frequency range of external GPS amplifier

### PR DESCRIPTION
**Pull request by kpuusaari**
The GPS SNR test in AT%XRFTEST has since Modem FW v1.2.0 allowed to
use 1575.42 +/- 10MHz in the test. Therefore the default GPS frequency
range for external LNA control (AT%XCOEX0 or AT%XMAGPIO) is extended accordingly.

Signed-off-by: Kimmo Puusaari <kimmo.puusaari@nordicsemi.no>

### CODE REVIEW

**Comment by kpuusaari** [comment]
@jhn-nordic ping

**Comment by kpuusaari** [comment]
Note that is not mandatory for 1.3.0 release.

**Comment by rlubos** [comment]
@kpuusaari The PR seems to be blocked by the CI, could we get a rebase here?

**Comment by kpuusaari** [comment]
> 
> 
> @kpuusaari The PR seems to be blocked by the CI, could we get a rebase here?

Done, and all green.

**Pull request merged**
