### PR TITLE
VERSION+tags: 1.8.0

### PR DESCRIPTION
**Pull request by nvlsianpu**
Bump version for tagging.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Review by tejlmand — CHANGES_REQUESTED** [review]
We must get this updated as well:
https://github.com/nrfconnect/sdk-nrf/blob/73862fb496f3c397a28fbc9ec957e3ec29a8bee0/scripts/ncs-toolchain-version-minimum.txt#L3

to 1.8.0.

@nvlsianpu you want to include that update in this PR, or should I send a dedicated PR ?

**Comment by nvlsianpu** [comment]
`nrf-connect-sdk-toolchain=1.7.99 `
@tejlmand will add commit with that

**Comment by nvlsianpu** [comment]
@tejlmand Updated

**Review by shantha-14 — APPROVED** [review]

**Review by ns-tolu — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]
lgtm

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
