### PR TITLE
doc: nrf_802154: radio driver API doxygen fixes

### PR DESCRIPTION
**Pull request by ankuns**
This PR is required for application of corrections to doxygen documentation of sdk-nrfxlib/nrf_802154

### CODE REVIEW

**Comment by gmarull** [comment]
I still see a few `nrf_802154` warnings in the CI logs, e.g.
```
2021-09-15T12:09:54.1176208Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:262: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_ANTENNA_NONE' for \ref command
2021-09-15T12:09:54.1177692Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:225: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1179416Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:211: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1180711Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:212: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1182016Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:251: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1183987Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:237: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1185325Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:238: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1200448Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:262: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_ANTENNA_NONE' for \ref command
2021-09-15T12:09:54.1202274Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:225: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1203574Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:211: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1205052Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:212: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1207085Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:251: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1208686Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:237: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.1210519Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:238: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
2021-09-15T12:09:54.2228102Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:1396: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
2021-09-15T12:09:54.2239365Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:1396: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
2021-09-15T12:09:54.2979900Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:602: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
2021-09-15T12:09:54.2986926Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:553: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
2021-09-15T12:09:54.2993194Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:646: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
2021-09-15T12:09:54.3020464Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:602: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
2021-09-15T12:09:54.3027569Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:553: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
2021-09-15T12:09:54.3032760Z WARNING: /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:646: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
```

**Comment by FrancescoSer** [comment]
For reference, I'm getting these warnings locally:

WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:261: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_ANTENNA_NONE' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:224: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:210: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:211: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:250: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:236: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:237: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:601: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:1395: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:552: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:645: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:261: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_ANTENNA_NONE' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:224: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:210: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:211: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:250: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:236: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:237: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:601: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:1395: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:552: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:645: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/src/nrf_802154_trx.h:159: unable to resolve reference to 'nrf_802154_sl_ant_div_mode_set' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/src/nrf_802154_trx.h:160: unable to resolve reference to 'nrf_802154_sl_ant_div_antenna_set' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/src/nrf_802154_trx.h:159: unable to resolve reference to 'nrf_802154_sl_ant_div_mode_set' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/src/nrf_802154_trx.h:160: unable to resolve reference to 'nrf_802154_sl_ant_div_antenna_set' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:261: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_ANTENNA_NONE' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:224: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:210: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:211: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:250: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:236: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:237: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:261: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_ANTENNA_NONE' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:224: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:210: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:211: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:250: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:236: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:237: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:1395: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:1395: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:601: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:552: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:645: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:601: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:552: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:645: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:210: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:211: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:224: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:236: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:237: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:250: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:261: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_ANTENNA_NONE' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:552: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:601: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:645: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:1395: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/src/nrf_802154_trx.h:159: unable to resolve reference to 'nrf_802154_sl_ant_div_mode_set' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/src/nrf_802154_trx.h:160: unable to resolve reference to 'nrf_802154_sl_ant_div_antenna_set' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:210: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:211: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:224: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:236: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:237: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:250: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_MODE_MANUAL' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:261: unable to resolve reference to 'NRF_802154_SL_ANT_DIV_ANTENNA_NONE' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:1395: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:552: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:601: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command
WARNING: C:/git/ncs/nrfxlib/nrf_802154/driver/include/nrf_802154.h:645: unable to resolve reference to 'NRF_802154_TRANSMIT_METADATA_DEFAULT_INIT' for \ref command

**Comment by ankuns** [comment]
@FrancescoSer This PR contains only those changes that are required for proper doxygen generation of sdk-nrfxlib/nrf_802154 if appropriate chanes (covered by PR https://github.com/nrfconnect/sdk-nrfxlib/pull/552) were made. However dox update is made to internal sdk-nrf-802154 repo and will go to sdk-nrfxlib as part of bigger deployment with other fixes. If deployment happens, correct doxyfile will already be present here in sdk-nrf. It is obvoius that there are warnings on doc generation here, further PR with west.yml change updating sdk-nrfxlib will get rid all of them.
Could this be merged?

**Review by FrancescoSer — APPROVED** [review]

**Review by e-rk — APPROVED** [review]

**Comment by ankuns** [comment]
just commit --amend to trigger CI again

**Review by jciupis — APPROVED** [review]

**Comment by ankuns** [comment]
Promised change to sdk-nrfxlib go with PR
https://github.com/nrfconnect/sdk-nrf/pull/5645

**Comment by czeslawmakarski** [comment]
@gmarull Could you possibly review this PR? Thanks.

**Review by gmarull — APPROVED** [review]

**Pull request merged**
