### PR TITLE
samples: nrf9160: agps: add CONFIG_FPU=y

### PR DESCRIPTION
**Pull request by richardmccrae-nordicsemi**
Compilation failed with CONFIG_AGPS_SRC_SUPL=y stating
'Assertion failed: CONFIG_FP_SOFTABI is not supported.'

Adding CONFIG_FPU as is used in GPS sample resolves
this issue.

Signed-off-by: Richard McCrae <richard.mccrae@nordicsemi.no>

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Review by jtguggedal — APPROVED** [review]

**Review by lemrey — APPROVED** [review]
OK, but would it not be better to add
`select FPU` to `SUPL_CLIENT_LIB` in `nrf/lib/supl/Kconfig` instead?

**Comment by tokangas** [comment]
We're have plans to add a soft-float version of the SUPL library, after which `select FPU` would not be needed anymore. And another point for enabling FPU in the sample is that it's also needed for printing floats correctly.

**Review by tejlmand — CHANGES_REQUESTED** [review]
This doesn't look right.
Temporary blocking for further investigations.

**Comment by tejlmand** [comment]
Ok, took a closer look at this, and took in considerations of those comments:
> > OK, but would it not be better to add
> > select FPU to SUPL_CLIENT_LIB in nrf/lib/supl/Kconfig instead?
>
> We're have plans to add a soft-float version of the SUPL library, after which select FPU would not be needed anymore. 

The right thing here is to have either:
```
config SUPL_CLIENT_LIB
        bool "SUPL Client library"
        depends on FPU
```
or alternatively as @lemrey suggests:
```
config SUPL_CLIENT_LIB
        bool "SUPL Client library"
        select FPU
```

usually a `depends on` is a safer and cleaner choice, but in this case where a soft-float library will be provided in near future then a select can be simpler in this case.

The `select FPU` can then be removed when the new lib is in place.

This will also help users understanding the `SUPL_CLIENT_LIB` setting, as they can now see that this setting requires or selects FPU.

Just updating the `prj.conf` on a single sample does not reveal such dependency to users.

**Comment by tejlmand** [comment]
note, the `prj.conf` can still contain a `CONFIG_FPU=y` as that setting in itself is not wrong to have.

**Comment by richardmccrae-nordicsemi** [comment]
Change request addressed

**Review by tokangas — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]

**Comment by tokangas** [comment]
@tejlmand I finished the soft-float version of the SUPL library yesterday and it's now in review. The SUPL library is released independently of NCS and I discussed with BTT yesterday that the plan is to release this version before the summer holidays. I'm now wondering if we should have that `select FPU` in lib/supl/Kconfig in NCS 1.6.0 or if it would be better to remove it.

**Pull request merged**
