### PR TITLE
applications: asset_tracker: Remove unused GPS config

### PR DESCRIPTION
**Pull request by DurandA**
I can't find any reference to `GPS_USE_EXTERNAL`. I think it should be `NRF9160_GPS_ANTENNA_EXTERNAL` but
keeping `NRF9160_GPS_ANTENNA_ONBOARD` as default is probably preferred.

### CODE REVIEW

**Comment by DurandA** [comment]
As a side node, it seems that `NRF9160_GPS_COEX0_STRING` only applies to `BOARD_NRF9160DK_NRF9160NS` and not to `THINGY91_NRF9160NS`.

https://github.com/nrfconnect/sdk-nrf/blob/278b5e260b44193c4374a960a1480fdda767c2ef/drivers/gps/nrf9160_gps/Kconfig#L91-L94

I understand correctly, COEX0 enable/disable the LNA on the Thingy:91.
thingy-lna

As a reference, I asked if enabling `NRF9160_GPS_ANTENNA_EXTERNAL` disables the LNA on [DevZone](https://devzone.nordicsemi.com/f/nordic-q-a/66610/external-gps-antenna-on-thingy-91-pca20035-1-4-0).

**Comment by jtguggedal** [comment]
`GPS_USE_EXTERNAL` is referring to the option found here for using a non-simulated GPS:
https://github.com/nrfconnect/sdk-nrf/blob/0e456f9e56409db90b81bda2ed135cca4c356a56/applications/asset_tracker/Kconfig#L34
The naming of that option is indeed confusing, and should be changed to reflect better what it actually does.

Regarding `NRF9160_GPS_COEX0_STRING `, you are right that for Thingy:91 >= v.1.4.0 this should now set `NRF9160_GPS_ANTENNA_EXTERNAL` the same way it's done for nRF91 DK, to have the best external antenna performance. For earlier versions, MAGPIO pins are used to control the GPS enable signal, and the LNA also has to be enabled for the external antenna. 
I'll open a PR to fix this issue. Thanks for the heads up!

**Comment by DurandA** [comment]
> `GPS_USE_EXTERNAL` is referring to the option found here for using a non-simulated GPS:
> 
> https://github.com/nrfconnect/sdk-nrf/blob/0e456f9e56409db90b81bda2ed135cca4c356a56/applications/asset_tracker/Kconfig#L34

I forgot to remove the `Kconfig` reference to `GPS_USE_EXTERNAL` in the PR but I cannot find any reference to it in the code. Do you want to keep it?

**Comment by jtguggedal** [comment]
> I forgot to remove the `Kconfig` reference to `GPS_USE_EXTERNAL` in the PR but I cannot find any reference to it in the code. Do you want to keep it?

Oh right, I was looking at the wrong option.. Yes, you can remove it. That leaves only `config GPS_USE_SIM` as option in the choice `GPS_USE_EXTERNAL` also belonged to, so the whole choice thing can also be dropped, to leave `GPS_USE_SIM` as a regular option:
https://github.com/nrfconnect/sdk-nrf/blob/c9c1ac4a04298e1839e10bad4ca62e0528fbcede/applications/asset_tracker/Kconfig#L21-L25

PR for COEX0 on Thingy:91 is up: #3077

**Comment by DurandA** [comment]
`GPS_USE_EXTERNAL` is used in the _lwm2m_client_ sample. Do you want to maintain common configuration options for _asset_tracker_, _lwm2m_client and _lte_ble_gateway_ concerning the GPS use?

**Comment by jtguggedal** [comment]
> `GPS_USE_EXTERNAL` is used in the _lwm2m_client_ sample. Do you want to maintain common configuration options for _asset_tracker_, _lwm2m_client and _lte_ble_gateway_ concerning the GPS use?

Changing only the asset tracker is fine here. The use of `GPS_USE_EXTERNAL` is different in the LwM2M client sample, so it can be left as is. The LTE BLE gateway doesn't define this config, so it can also be left as is.

**Pull request closed without merging**
