### PR TITLE
nrf_security: Add cc312 support

### PR DESCRIPTION
**Pull request by frkv**
Adds support for CC312 in nrf_security through nrf_cc3xx_platform/nrf_cc3xx_mbedcrypto v0.9.3
Based on mbed TLS 2.23.0

References PRs in sdk-zephyr and sdk-nrfxlib (related PRs)

ref: NCSDK-4638

nrfxlib PR: https://github.com/nrfconnect/sdk-nrfxlib/pull/242
zephyr downstream PR: https://github.com/nrfconnect/sdk-zephyr/pull/346

Signed-off-by: Frank Audun Kvamtrø <frank.kvamtro@nordicsemi.no>

### CODE REVIEW

**Review by pdunaj — APPROVED** [review]

**Review by MarekPorwisz — CHANGES_REQUESTED** [review]
I think nrf/subsys/net/openthread/Kconfig needs to be updated as well

**Review by MarekPorwisz — APPROVED** [review]
My bad, the backend name was not changed

**Review by b-gent — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]

**Comment by frkv** [comment]
Note that the PR was green on build number 35 and there has been no additions to master after that

**Comment by tejlmand** [comment]
safe to merge

**Pull request merged**
