### PR TITLE
Integration quarantine part1

### PR DESCRIPTION
**Pull request by nordic-piks**

### CODE REVIEW

**Review by SeppoTakalo — APPROVED** [review]

**Review by aasinclair — APPROVED** [review]

**Review by SeppoTakalo — APPROVED** [review]

**Review by jtguggedal — APPROVED** [review]

**Review by doublemis1 — APPROVED** [review]
LGTM!

**Review by m-alperen-sener — APPROVED** [review]

**Review by eivindj-nordic — APPROVED** [review]

**Review by ns-tolu — APPROVED** [review]

**Comment by jfischer-no** [comment]
@nordic-piks Please rebase.

**Comment by thst-nordic** [comment]
is there a benefit of 23 commits instead of 1?
can we remove '[nrf noup]' since this is in sdk-nrf?

**Comment by jfischer-no** [comment]
@nordic-piks Remove DNM label when @thst-nordic comments and conflicts are resolved.

**Comment by nordic-piks** [comment]
> @nordic-piks Please rebase.

Rebased.

**Comment by nordic-piks** [comment]
> FYI: The CI for this change is not triggering zephyr twister because the manifest revision is not changed.
> 
> Is there a benefit of 23 commits instead of 1? can we remove '[nrf noup]' since this is in sdk-nrf?

I will try to execute also scope for twister.

Regarding number of commits - they are small and independent - touching different area of testing. If there is no requirement to limit number of commit, I prefer to leave them. They work as a list of test scope which was added to integration quarantine.

Removed [nrf noup] from commits, thanks.

**Comment by nordic-piks** [comment]
> > Regarding number of commits - they are small and independent - touching different area of testing. If there is no requirement to limit number of commit, I prefer to leave them. They work as a list of test scope which was added to integration quarantine.
> 
> 23 commits touching the same two files with identical "To limit integration scope" commit messages do not make any sense.

I will squash them.

**Comment by thst-nordic** [comment]
the cla-assistant service is struggling today.   I kicked it.

**Review by shanthanordic — APPROVED** [review]

**Pull request merged**
