### PR TITLE
samples: nrf9160: spm: Enable fault logging by default

### PR DESCRIPTION
**Pull request by rlubos**
Apparently some of the application faults (like null pointer
dereference) are handled by the secure domain. In case logging is
disabled in SPM and `CONFIG_RESET_ON_FATAL_ERROR` is enabled, the
application will reboot silently instead of printing out the actual
fault report.

Since it's not straghtforward to modify SPM configuration
from the actual application project, it's reasonable to set appropriate
defaults in the SPM configuration file.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by hakonfam** [comment]
Could you update the changelog?

**Comment by rlubos** [comment]
@hakonfam Sure, but I typically do it **after** the PR is actually merged.

**Comment by hakonfam** [comment]
> @hakonfam Sure, but I typically do it **after** the PR is actually merged.

Sounds good, AFAIK they should be in before the PR is merged so that it can be reviewed that it is updated. But I trust you ;)

**Comment by rlubos** [comment]
TBH I've never seen anyone actually reviewing changelog. IMO it should not be updated early since at this point I don't even know if the PR is going to be accepted or not.

**Comment by hakonfam** [comment]
To me the device still resets after printing the error, you don't see that?

**Comment by rlubos** [comment]
> To me the device still resets after printing the error, you don't see that?

I've noticed that the actual application config also matters, if the application does not set `CONFIG_RESET_ON_FATAL_ERROR=n` in its configuration, it will reboot anyway (any idea why this happens?). The same applies to log, if the application has logger disabled, the will be no printout.

**Comment by hakonfam** [comment]
I did some testing, and it seems that both configs must be set in both app and SPM to make a difference.

|  | App | SPM | Result |
| -| -| -|-|
| Logg  | 1 | 0 | 0 |
| | 0 | 1 | 0 |
| | 0 | 1 | 0 |
| | 1 | 1 | 1 |
| Reset  | 1 | 0 | 0 |
| | 0 | 1 | 0 |
| | 0 | 1 | 0 |
| | 1 | 1 | 1 |

I added the following patches:
```

```
/ * fatal_error.c */
#if defined(CONFIG_ARM_SECURE_FIRMWARE)
	LOG_ERR("Resetting system SECURE");
#else
	LOG_ERR("Resetting system NONSECURE");
#endif
```

```
/* log_output.c */
static const char *const severity[] = {
	NULL,
#if defined(CONFIG_ARM_SECURE_FIRMWARE)
	"SE-err",
#else
	"NS-err",
#endif
	"wrn",
	"inf",
	"dbg"
};
```

And I see the following 
```
*** Booting Zephyr OS build v2.3.0-rc1-ncs1-3-g2400b4921ea9  ***
Hello World! nrf5340pdk_nrf5340_cpuapp
[00:00:00.009,307] <NS-err> os: Exception occurred in Secure State
[00:00:00.009,307] <NS-err> os: ***** HARD FAULT *****
[00:00:00.009,307] <NS-err> os:   Fault escalation (see below)
[00:00:00.009,307] <NS-err> os: ***** BUS FAULT *****
[00:00:00.009,307] <NS-err> os:   Precise data bus error
[00:00:00.009,307] <NS-err> os:   BFAR Address: 0x50015504
[00:00:00.009,338] <NS-err> os: r0/a1:  0x00000000  r1/a2:  0x0000000a  r2/a3:  0x00000040
[00:00:00.009,338] <NS-err> os: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00008543
[00:00:00.009,338] <NS-err> os:  xpsr:  0x61000000
[00:00:00.009,338] <NS-err> os: Faulting instruction address (r15/pc): 0x00008544
[00:00:00.009,338] <NS-err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.009,338] <NS-err> os: Current thread: 0x200102a0 (unknown)
[00:00:00.094,451] <NS-err> fatal_error: Resetting system NONSECURE
```

**Comment by rlubos** [comment]
> I'm not able to explain why it is like this

Neither do I, that's why any feedback is appreciated.

> Anyway it seems like this PR should copy the configuration from app in to SPM instead of simply enabling logging by default in SPM.

And how to achieve that?

**Comment by hakonfam** [comment]
> > I'm not able to explain why it is like this
> 
> Neither do I, that's why any feedback is appreciated.

@ioannisg , any idea?
 
> > Anyway it seems like this PR should copy the configuration from app in to SPM instead of simply enabling logging by default in SPM.
> 
> And how to achieve that?

https://github.com/nrfconnect/sdk-nrf/blob/master/cmake/mcuboot.cmake#L80

**Comment by rlubos** [comment]
I did some extra investigation with debugger attached (and `CONFIG_RESET_ON_FATAL_ERROR` disabled). Tested on `at_client` with NULL pointer dereference at the beginning of the main function (of the Non-Secure FW).

On the faulty instruction, we end up in SPM's `z_fault_handler` (Secure FW). The fault is being processed, and now depending on the logger configuration:

* With logger disabled in SPM, we end up spinning in the `k_sys_fatal_error_handler` in the Secure FW. Since we never leave it nothing gets printed out. 

* With logger enabled in SPM, something weird happens on this instruction:
https://github.com/nrfconnect/sdk-zephyr/blob/master/drivers/serial/uart_nrfx_uarte.c#L1042
This routine is called at some point when SPM tries to log the fault. I've done asm stepping, and once the SPM tries to clear the NRF_UARTE_EVENT_ENDTX event, we end up in `z_arm_bus_fault`, but this time in the Non-Secure firmware. From that point the logs are printed and we end up spinning in the `k_sys_fatal_error_handler`, Non-Secure this time.
I have no clue why do we suddenly jump into Non-Secure fault handler but perhaps I miss something. Nontheless something is certainly off.

FYI @ioannisg 

Closing, since enabling a logger is not a valid fix.

**Pull request closed without merging**
