### PR TITLE
location + Wi-Fi: Remove tests from Quarantine

### PR DESCRIPTION
**Pull request by glarsennordic**
1. Revert a config change causing build error due to typo
2. Remove location + wifi tests from quarantine

### CODE REVIEW

**Comment by glarsennordic** [comment]
This time I actually performed and tested a build on top of the config, as I _**should**_ have done in https://github.com/nrfconnect/sdk-nrf/pull/18236

Sorry for the gaff

**Review by plskeggs — APPROVED** [review]

**Review by krish2718 — COMMENTED** [review]
We have a fix ready, so, should we still go ahead with this workaround?

**Review by jayteemo — APPROVED** [review]

**Review by krish2718 — APPROVED** [review]

**Comment by krish2718** [comment]
> We have a fix ready, so, should we still go ahead with this workaround?

https://github.com/nrfconnect/sdk-nrf/pull/17653 has the fix at Wi-Fi level, so, we can either merge it as this unblocks CI failures (windows) or modify the fix to remove the line altogether and wait for the actual fix to go in.

**Review by PerMac — CHANGES_REQUESTED** [review]
I checked locally and the failing sample builds with this fix https://jenkins-ncs.nordicsemi.no/job/latest/view/TWISTER_TESTS/job/night/job/sdk-nrf-windows/job/main/731/testReport/junit/nrf9160dk_nrf9160_ns_sample.cellular.nrf7002ek_wifi/scan/Install_toolchain_and_run_twister___Twister_NRF_9_10___sample_cellular_nrf7002ek_wifi_scan/

however, AFAIK this should fix the issue also on other platforms, that are currently under quarantine, correct? If so, please remove the corresponding entry(ies?) from the quarantine as well in this PR so we can see in the CI if it works   https://github.com/nrfconnect/sdk-nrf/blob/main/scripts/quarantine.yaml

**Comment by krish2718** [comment]
> I checked locally and the failing sample builds with this fix https://jenkins-ncs.nordicsemi.no/job/latest/view/TWISTER_TESTS/job/night/job/sdk-nrf-windows/job/main/731/testReport/junit/nrf9160dk_nrf9160_ns_sample.cellular.nrf7002ek_wifi/scan/Install_toolchain_and_run_twister___Twister_NRF_9_10___sample_cellular_nrf7002ek_wifi_scan/
> 
> however, AFAIK this should fix the issue also on other platforms, that are currently under quarantine, correct? If so, please remove the corresponding entry(ies?) from the quarantine as well in this PR so we can see in the CI if it works https://github.com/nrfconnect/sdk-nrf/blob/main/scripts/quarantine.yaml

I have reverted the original commit instead of fixing it and also remove two entries from nRF70 quarantine.

**Comment by PerMac** [comment]
I think the PR title and description is no more correct. I guess it doesn't matter from the git perspective but adjusting it also in github could prevent some potential confusion. @krish2718 is there any order this and #17653 should be merged in?

**Comment by krish2718** [comment]
> I think the PR title and description is no more correct. I guess it doesn't matter from the git perspective but adjusting it also in github could prevent some potential confusion. @krish2718 is there any order this and #17653 should be merged in?

Fixed, no specific order,I have already raised merge request for dependent PRs in #17653, so should go in soon.

**Review by PerMac — APPROVED** [review]

**Review by trantanen — APPROVED** [review]

**Pull request merged**
