### PR TITLE
samples: timeslot: Build for nRF53 in CI

### PR DESCRIPTION
**Pull request by rugeGerritsen**
This builds the sample for the network core and places the empty app
image on the application core.

Requires: https://github.com/nrfconnect/sdk-nrf/pull/3020

### CODE REVIEW

**Review by joerchan — APPROVED** [review]

**Comment by joerchan** [comment]
@rugeGerritsen Do you have an explanation for why CI is green, but there is a required dependency on another PR?

Also the dependant PR has a dependant PR. To help speed this up could you review that one as well?

**Comment by DatGizmo** [comment]
The new variant (nrf5340pdk_nrf5340_cpunet) needs to be added to the Jenkinsfile.
See: https://github.com/nrfconnect/sdk-nrf/blob/master/Jenkinsfile#L21

**Comment by rugeGerritsen** [comment]
> The new variant (nrf5340pdk_nrf5340_cpunet) needs to be added to the Jenkinsfile.
> See: https://github.com/nrfconnect/sdk-nrf/blob/master/Jenkinsfile#L21

@thst-nordic , can we add nrf53 there?

**Comment by rugeGerritsen** [comment]
Rebased to resolve merge conflict

**Review by hurricaneFromMoscow — APPROVED** [review]

**Comment by thst-nordic** [comment]
This will work for the current way of using sample.yaml. 
However, @PerMac is planning to change things to select platforms based on requirement labels instead of whitelisting.  

We can merge this, or talk to him about how it will work.

**Review by thst-nordic — APPROVED** [review]

**Comment by joerchan** [comment]
@rugeGerritsen Can you rebase this so that we can get a clean CI run? It is too old now.

**Comment by joerchan** [comment]
@rugeGerritsen Sorry about this, there was an problem in CI that has been fixed, please rebase again.

**Pull request merged**
