### PR TITLE
trusted_storage: switch to ZMS on nRF54L15

### PR DESCRIPTION
**Pull request by tomi-font**
And disallow NVS.

### CODE REVIEW

**Review by mia-ko — COMMENTED** [review]
Related doc PR: https://github.com/nrfconnect/sdk-nrf/pull/18027

**Comment by rlubos** [comment]
@nrfconnect/ncs-co-build-system @nrfconnect/ncs-aegir @nrfconnect/ncs-modem Please review

**Review by eivindj-nordic — APPROVED** [review]
LGTM, though, not sure why @nrfconnect/ncs-modem was added to this(?).

**Review by nordicjm — APPROVED** [review]

**Comment by tomi-font** [comment]
ping @nrfconnect/ncs-aegir

**Review by frkv — APPROVED** [review]
LGTM

**Pull request merged**
