### PR TITLE
tests: Add integration_platforms to ..yaml for applications and tests

### PR DESCRIPTION
**Pull request by simensrostad**
Add `integration_platforms` to `..yaml` for applications and tests.
Requested in https://github.com/nrfconnect/sdk-nrf/pull/5742.

### CODE REVIEW

**Comment by simensrostad** [comment]
@PerMac I'm using the `common` keyword in one of the `..yaml` files. I'm not an expect on yaml, could you verify the use of it?

**Comment by PerMac** [comment]
` UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:`. You can amend the title to e.g.:
`tests: Add integration_platforms to ..yaml for applications and tests`

**Comment by PerMac** [comment]
> @PerMac I'm using the `common` keyword in one of the `..yaml` files. I'm not an expect on yaml, could you verify the use of it?

You used `common:` correctly. Twister will copy whatever is in `common` to each scenario in `tests:`.

**Comment by simensrostad** [comment]
@PerMac Updated the commit title, thanks!

**Review by jtguggedal — APPROVED** [review]

**Comment by PerMac** [comment]
@simensrostad Can you please remove qemu_x86 from "integration_platforms" list? You can leave it in the platform_allow lists. It will cause errors when the integration mode is turn on in the CI (it is not used yet). We use gnuarmemb toolchain which supports only ARM architectures. AFAIK the qemu_x86 was always skipped in the CI before due to the toolchain. No skips are allowed in the integration mode on the integration platforms, hence the error will occure. 
@jtguggedal Do you want a support in the CI for qemu_x86? Like I said, it doesn't reflect ARM arch. Maybe you'd like to replace it with some other emulator? https://docs.zephyrproject.org/latest/guides/arch/arm_cortex_m.html#qemu
A suggestion is to try mps2_an385 which is the closest to Cortex-M4 used in nrf52840dk 
If you need qemu_x86 support we will think about expanding the CI workflow and rerunning tests with zephyr-sdk toolchain.

**Comment by jtguggedal** [comment]
> @simensrostad Can you please remove qemu_x86 from "integration_platforms" list? You can leave it in the platform_allow lists. It will cause errors when the integration mode is turn on in the CI (it is not used yet). We use gnuarmemb toolchain which supports only ARM architectures. AFAIK the qemu_x86 was always skipped in the CI before due to the toolchain. No skips are allowed in the integration mode on the integration platforms, hence the error will occure. @jtguggedal Do you want a support in the CI for qemu_x86? Like I said, it doesn't reflect ARM arch. Maybe you'd like to replace it with some other emulator? https://docs.zephyrproject.org/latest/guides/arch/arm_cortex_m.html#qemu A suggestion is to try mps2_an385 which is the closest to Cortex-M4 used in nrf52840dk If you need qemu_x86 support we will think about expanding the CI workflow and rerunning tests with zephyr-sdk toolchain.

@PerMac I think qemu_x86 was originally added because it's the only emulator that I'm aware of that supports network interface that we use for testing, so it's useful to ensure that changes don't break the platform support. But if it has actually never been built for qemu_x86 in CI, then I think we can just remove it if it will break CI. 
@jorgenmk Do you run nightly tests on qemu_x86?

**Comment by jorgenmk** [comment]
Removing qemu_x86 from `integration_platforms` is OK

**Comment by PerMac** [comment]
@jorgenmk I am worried they are not, due to toolchain mismatch as I explained above. I am doing some reevaluation of sdk-nrf CI and this is one of the issues found. Twister is called for qemu_x86 but skips all the tests. E.g. you can see this in this PR's results: https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-5758/2/artifact/twister_report-unittest-1.xml You can see that qemu_x86 is on the top of this report and states that 511/511 tests were skipped.
As proposed, we can modify the workflow to also add zephyr-sdk toolchain tests, where qemu_x86 is supported, but we need to evaluate the need for it.

**Comment by gopiotr** [comment]
I think, that problem with application build only on qemu_x86 (and not on qemu_cortex_m3) concern only `applications/asset_tracker/` test. 
@jorgenmk @jtguggedal Do you know what kind of network interface from qemu_x86 is used especially for this test, which is not available on qemu_cortex_m3, mps2_an385 or mps2_an521?

**Comment by jorgenmk** [comment]
@gopiotr Yes, `applications/asset_tracker` and also `samples/nrf9160/udp`. When these test were established there was limited or no networking in qemu_cortex and friends. I know at least qemu_cortex and mps2 support networking now, but making this change would require some work in the test framework.
@PerMac Sorry for the confusion - the tests mentioned by @jtguggedal are not executed using twister, they are part of the test-fw-nrfconnect-nrf_iot test plan.

**Comment by simensrostad** [comment]
@PerMac Could you look through the changes and approve if they are ok.

**Review by PerMac — APPROVED** [review]

**Pull request merged**
