### PR TITLE
applications: serial_lte_modem: use default C library

### PR DESCRIPTION
**Pull request by lemrey**
Use default C library.
Shaves off a lot of FLASH too :)

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
Markus and Tomi to approve.
This needs verification.

**Comment by MarkusLassila** [comment]
> Markus and Tomi to approve. This needs verification.


> Markus and Tomi to approve. This needs verification.

I'll run our nightly CI-tests against this branch with 9161.

**Comment by MarkusLassila** [comment]
I rebased this on top of main, and ran whatever additional tests I could. I could not ran the whole nightly set, but based on what I could ran, there were no issues related to this, and the flash and ram consumption was improved.

**Review by MarkusLassila — APPROVED** [review]

**Comment by lemrey** [comment]
I am not sure whether we need a changelog entry for this, since the functionality of SLM remains the same; I am removing the label but feel free to add it back if you think we need to mention something.

**Review by rlubos — APPROVED** [review]

**Pull request merged**
