### PR TITLE
net: lib: download_client: fix expected HTTP status

### PR DESCRIPTION
**Pull request by lemrey**
When not using TLS, the library made an HTTP range request
when requesting a resource from the server (requesting all the bytes).
This led the server to reply 206 but send the whole resource
in one HTTP message. This used to work, but a recently introduced
change expected the HTTP status in the response to be 200
when not using TLS, thus it started failing with EBADMSG.

This patch lets the library omit the Range header in the request,
(and expect 200) when downloading without TLS,
unless downloading from an offset.

@jbrzozoski would you like to have a look?

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Comment by jbrzozoski** [comment]
I can see the behavior I changed with my patch: it used to accept either 206 or 200 always but only log errors differently based on the setup.  My change made it explicitly require either 206 or 200 depending on the setup.

I tested my change in HTTP mode and didn't bump into this bug.

Your change looks good but now I'm nervous that some web servers could still reply with the wrong 2xx code.

Let me go do some quick tests...

**Comment by lemrey** [comment]
It is visible right now in the `samples/nrf9160/download` sample.

**Comment by jbrzozoski** [comment]
I apparently did all of my HTTP tests with CONFIG_DOWNLOAD_CLIENT_RANGE_REQUESTS=y

That was dumb of me.

**Comment by richardmccrae-nordicsemi** [comment]
I ran the sample without specifying CONFIG_DOWNLOAD_CLIENT_RANGE_REQUESTS and it ran as expected.

**Review by richardmccrae-nordicsemi — APPROVED** [review]
Tests passing

**Comment by jbrzozoski** [comment]
The differentiation between `HTTP_GET_RANGE` and `HTTPS_GET_RANGE` isn't specifically about HTTP vs HTTPS any more, it's more whether the GET should try to go all the way to the end of the file or stop before then.  I hadn't fully realized my tests were using DOWNLOAD_CLIENT_RANGE_REQUESTS because it was a side effect of having the modem DFU built in, which needs it for pauses, not HTTPS.

I'm technically okay with this change, but wonder if maybe the three HTTP GET templates might be better named something like `HTTP_GET_FULL`, `HTTP_GET_OFFSET`, and `HTTP_GET_PARTIAL_OFFSET`.

**Comment by lemrey** [comment]
I can rename them

**Comment by lemrey** [comment]
Renamed and added some comments for clarity.

**Comment by jbrzozoski** [comment]
LGTM :+1:

**Comment by rlubos** [comment]
@lemrey Can you have a look at the CI failures? They seem to be valid ones this time.

**Pull request merged**
