### PR TITLE
net: openthread: enable extra mbedtls modules by default

### PR DESCRIPTION
**Pull request by edmont**
Enable 'CONFIG_MBEDTLS_PK_WRITE_C' for OpenThread samples, useful for ecosystems.

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

KRKNWK-8609

### CODE REVIEW

**Comment by lmaciejonczyk** [comment]
Why all Thread samples need to be affected by this? If ecosystem samples need specific settings they should have an extra overlay for that.

**Comment by edmont** [comment]
@lmaciejonczyk the reason to do this is to generate OT libraries with proper mbedtls headers: https://github.com/edmont/sdk-nrfxlib/commit/07b49fd0427f9860f97ab812ce4330157eb5937d#diff-663455c7610d025e4b5b17b7a0d9c95de3dc5c2b532c050d96a12212eb3bb9e5R2889

But still investigating whether this is needed or not, that's why I moved the PR to draft.

**Comment by lmaciejonczyk** [comment]
> @lmaciejonczyk the reason to do this is to generate OT libraries with proper mbedtls headers: [edmont/sdk-nrfxlib@07b49fd#diff-663455c7610d025e4b5b17b7a0d9c95de3dc5c2b532c050d96a12212eb3bb9e5R2889](https://github.com/edmont/sdk-nrfxlib/commit/07b49fd0427f9860f97ab812ce4330157eb5937d#diff-663455c7610d025e4b5b17b7a0d9c95de3dc5c2b532c050d96a12212eb3bb9e5R2889)
> 
> But still investigating whether this is needed or not, that's why I moved the PR to draft.

It makes sense.

**Comment by edmont** [comment]
Closing since this is going to be addresses by another PR: https://github.com/nrfconnect/sdk-nrf/pull/3758/commits/9447b5035523e318806f53dc7ffdd63c666b7a50

**Pull request closed without merging**
