### PR TITLE
doc: Added documentation about logging possibilities in NCS.

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
Documentation about how to enable and configure different
logging modules and backends in NCS was added.

KRKNWK-6767

Signed-off-by: Kamil Kasperczyk kamil.kasperczyk@nordicsemi.no

### CODE REVIEW

**Comment by greg-fer** [comment]
I'll have a look once I'm back on Wednesday. If you're in a hurry, check with @b-gent about earlier review.

**Comment by kkasperczyk-no** [comment]
> I'll have a look once I'm back on Wednesday. If you're in a hurry, check with @b-gent about earlier review.

In that case, could you take a look at this @b-gent ? It would give me time to fix some fundamental mistakes earlier and finish it this week.

**Comment by b-gent** [comment]
> > I'll have a look once I'm back on Wednesday. If you're in a hurry, check with @b-gent about earlier review.
> 
> In that case, could you take a look at this @b-gent ? It would give me time to fix some fundamental mistakes earlier and finish it this week.

I should be able to check today but it is quite a bit.

**Comment by b-gent** [comment]
In the end, I didn't manage to do such a large review ad hoc today. Greg is back tomorrow and I'm sure he can handle it.

**Comment by kkasperczyk-no** [comment]
> In the end, I didn't manage to do such a large review ad hoc today. Greg is back tomorrow and I'm sure he can handle it.

Sure, no problem, thanks for trying.

**Review by greg-fer — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
