### PR TITLE
version: Update VERSION to 1.9.2-dev1

### PR DESCRIPTION
**Pull request by rlubos**
Update VERSION to 1.9.2-dev1.

### CODE REVIEW

**Comment by rlubos** [comment]
@gmarull @thst-nordic Any idea how to fix the documentation build here (note the PR is against v1.9-branch).

**Comment by rlubos** [comment]
> > @gmarull @thst-nordic Any idea how to fix the documentation build here (note the PR is against v1.9-branch).
> 
> doc build in that branch was using `ubuntu-latest`, maybe pin to `ubuntu-20.04`

Sorry, pin what and where exactly? I don't know the doc scripts so it's hard for me to follow. Please be more specific.

**Comment by gmarull** [comment]
> > > @gmarull @thst-nordic Any idea how to fix the documentation build here (note the PR is against v1.9-branch).
> > 
> > 
> > doc build in that branch was using `ubuntu-latest`, maybe pin to `ubuntu-20.04`
> 
> Sorry, pin what and where exactly? I don't know the doc scripts so it's hard for me to follow. Please be more specific.

Try changing to `ubuntu-20.04` here https://github.com/nrfconnect/sdk-nrf/blob/v1.9-branch/.github/workflows/docbuild.yml#L23

**Comment by rlubos** [comment]
@gmarull Changing the ubuntu version helped with the original problem, but now the doc build fails with:
> Error: Process completed with exit code 8.

I don't even see any more detailed error description. Any ideas?

**Comment by gmarull** [comment]
> @gmarull Changing the ubuntu version helped with the original problem, but now the doc build fails with:
> 
> > Error: Process completed with exit code 8.
> 
> I don't even see any more detailed error description. Any ideas?

Doxygen 1.9.2 is no longer downloadable from that URL, can you change https://github.com/nrfconnect/sdk-nrf/blob/v1.9-branch/.github/workflows/docbuild.yml#LL42C11-L42C91

to 

```
https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
```

**Comment by rlubos** [comment]
@gmarull Ok, seems we're one step further now. Yet another failure though:
```
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in breathe setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by gmarull** [comment]
CI is having fun with us today. I think you now need https://github.com/nrfconnect/sdk-nrf-next/commit/432e661ba8169f9ff7b2b6c3d0ebed103064f715

**Comment by gmarull** [comment]
> > CI is having fun with us today. I think you now need [nrfconnect/sdk-nrf-next@432e661](https://github.com/nrfconnect/sdk-nrf-next/commit/432e661ba8169f9ff7b2b6c3d0ebed103064f715)
> 
> Lots of fun, indeed. We're past the setup stage now, but the documentation build fails with the following:
> 
> ```
> Sphinx parallel build error:
> sphinx.errors.ExtensionError: Handler <function process_tables at 0x7f5eb1664c10> for event 'source-read' threw an exception (exception: __init__() takes 2 positional arguments but 3 were given)
> [2/14] Generating nrf/src/versions.txt
> FAILED: CMakeFiles/matter-html-all /home/runner/work/sdk-nrf/sdk-nrf/ncs/nrf/doc/_build/CMakeFiles/matter-html-all 
> ```
> 
> Spinx needs a version bump as well?

Hmm... maybe but I'm not sure. I guess another solution is to not touch breathe, and pin setuptools<=0.58 here https://github.com/nrfconnect/sdk-nrf/blob/v1.9-branch/.github/workflows/docbuild.yml#L49

```
sudo pip3 install -U setuptools<=0.58 wheel
```

**Comment by rlubos** [comment]
I've cleaned up the PR to include only version update

**Pull request merged**
