### PR TITLE
doc: Doc updates for the new layout

### PR DESCRIPTION
**Pull request by umapraseeda**
Doc updates for the new layout
[NCSDK-15339](https://projecttools.nordicsemi.no/jira/browse/NCSDK-15339)
To be merged after https://github.com/nrfconnect/sdk-nrf/pull/7650

Signed-off-by: Uma Praseeda <uma.praseeda@nordicsemi.no>

### CODE REVIEW

**Review by richabp — COMMENTED** [review]
I think we should also replace the doc search results png with the new one.

**Comment by umapraseeda** [comment]
> I think we should also replace the doc search results png with the new one.

Done

**Review by carlescufi — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Comment by gmarull** [comment]
note: screenshot needs update, doesn't show nrf entry in the navbar

**Comment by umapraseeda** [comment]
> note: screenshot needs update, doesn't show nrf entry in the navbar

Done

**Pull request merged**
