### PR TITLE
treewide: nrf_cloud: Update GPS to GNSS

### PR DESCRIPTION
**Pull request by glarsennordic**
nRF Cloud now fully supports use of the GNSS keyword for GNSS endpoints.

Replace all occurrences (relating to nRF Cloud GPS/GNSS) of GPS with GNSS.

CIA-729

Also, minor unit test bugfix due to merge conflict between #9153 and #9244

NCSDK-18035

Signed-off-by: Georges Oates_Larsen <georges.larsen@nordicsemi.no>

### CODE REVIEW

**Comment by glarsennordic** [comment]
Added changelogs, so this PR is ready for docs review, at least

**Review by peknis — APPROVED** [review]

**Comment by glarsennordic** [comment]
Ready for first-round review while I test various samples. It works for MMSS

**Review by plskeggs — APPROVED** [review]

**Review by jayteemo — APPROVED** [review]

**Comment by glarsennordic** [comment]
Since this works for 4/6 of the samples I need to test, it's probably going to work for the last two. I am going to open this up for full review while I test MOSH and RCL

**Comment by glarsennordic** [comment]
All directly modified samples have been confirmed to work

**Comment by plskeggs** [comment]
Seems like you could turn off DNM and get it merged now.  You have enough reviews.

**Review by simensrostad — APPROVED** [review]

**Comment by glarsennordic** [comment]
I will rebase and do so @plskeggs

**Comment by glarsennordic** [comment]
I'm going to request merge on this tomorrow, so last chance to get a review in if you have opinions

**Review by jhirsi — APPROVED** [review]

**Comment by rlubos** [comment]
Ugh, release notes conflict... @glarsennordic Please rebase.

**Comment by glarsennordic** [comment]
@rlubos Shoot, missed it by a hair. I'll get on that.

**Comment by glarsennordic** [comment]
Adding DNM until I get a chance to do some testing, there were some pretty important changes merged recently!

**Comment by glarsennordic** [comment]
@jayteemo I am 99.9% certain nothing here conflicts with your c2d topic PR, but do you mind glancing at the diff to sanity check? I am going to run a build with MMSS and make sure it works

**Review by jayteemo — APPROVED** [review]

**Comment by glarsennordic** [comment]
Thank you!!

**Comment by glarsennordic** [comment]
Twister is now failing due to bug with LWM2M unit tests likely related to https://github.com/nrfconnect/sdk-nrf/pull/9153

**Comment by glarsennordic** [comment]
@rlubos I am leaving DNM on for now since I have added this unit test bugfix, and I want to see if twister passes. But if  @juhaylinen approves of the bugfix, can you remove the DNM tag and merge anyways?

**Review by juhaylinen — APPROVED** [review]
Changes to lwm2m_client_utils unit tests look OK to me.

**Comment by glarsennordic** [comment]
Looks like @maxd-nordic also wrote a fix, and that has been merged, so I will remove the fix from my PR

https://github.com/nrfconnect/sdk-nrf/pull/9269

**Review by tokangas — APPROVED** [review]

**Review by SeppoTakalo — APPROVED** [review]

**Pull request merged**
