### PR TITLE
samples: crypto: add crypto tag for samples

### PR DESCRIPTION
**Pull request by nordic-piks**
Extend list of paths used to check if crypto tests/samples should be executed.

### CODE REVIEW

**Comment by nordic-piks** [comment]
The idea behind this change is to allow automatic detection of PRs not related to given code area.
In this case, there is defined tag (e.g. crypto) and files/folder with source code related to that area.
This list of files/folders is then compared to files changed in PR. If particular PR does not change them,
tests related to specified tag should not be executed - will be excluded.

**Review by miha-nordic — APPROVED** [review]

**Comment by nordic-piks** [comment]
> LGTM (But I wonder if TF-M tests and samples also should get this treatment)

Thanks, I will add them in separated PR.

**Comment by nordic-piks** [comment]
> Extend list of paths used to check if crypto tests/samples should be executed.

Here it is: https://github.com/nrfconnect/sdk-nrf/pull/16174

**Comment by nordic-piks** [comment]
DNM until NCS 2.7

**Review by tejlmand — APPROVED** [review]

**Pull request merged**
