### PR TITLE
doc: Fixes to the redirects.py

### PR DESCRIPTION
**Pull request by umapraseeda**
The changes are intended to get rid of the intermediate pages in Zoomin

### CODE REVIEW

**Review by gmarull — COMMENTED** [review]
there seem to be many spurious changes `, "`

**Comment by umapraseeda** [comment]
> there seem to be many spurious changes `, "`

Tried to make all the entries consistent as the example mentioned here:
https://github.com/nrfconnect/sdk-nrf/pull/17044/files#diff-e5180fe49174a7f4386d1131761cd0f4d3e42f7105415f4cdc178454257c884fR6 (with the space after comma)

**Comment by gmarull** [comment]
can style alignments be split from the actual content change?

**Comment by umapraseeda** [comment]
> can style alignments be split from the actual content change?

I will do that in another PR.

**Review by gmarull — APPROVED** [review]

**Review by richabp — APPROVED** [review]

**Pull request merged**
