### PR TITLE
thingy53: samples and applications: Use default MCUboot config

### PR DESCRIPTION
**Pull request by MarekPieta**
Change switches to using default MCUboot configuration. Thingy's MCUboot configurations defined for samples and applications are no longer needed and removed.

Jira: NCSDK-10921

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
@MarekPieta I merged https://github.com/nrfconnect/sdk-mcuboot/pull/168; please replace with SHA

**Comment by MarekPieta** [comment]
@mbolivar-nordic, done.
Sorry for response delay, I was on vacation yesterday and I had no access to computer.

**Review by joerchan — APPROVED** [review]

**Comment by MarekPieta** [comment]
Rebased on master and retriggered CI

**Comment by MarekPieta** [comment]
sdk-mcuboot commit SHA in west.yml was already updated on master. The commit updating it is dropped.

**Review by KAGA164 — APPROVED** [review]

**Pull request merged**
