### PR TITLE
manifest: Cleanup manifest whitelist

### PR DESCRIPTION
**Pull request by pdunaj**
civetweb was removed from Zephyr's manifest.
hal_st is unused.

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
Hi @carlescufi , is hal_st actually unused or is it there for a purpose?
From what I see there are some tools (beside hal) that are in Zephyr's manifest but we don't bring them to manifest. Is this intentional?

**Review by tejlmand — APPROVED** [review]
LGTM

**Review by carlescufi — APPROVED** [review]

**Comment by dchat-nordic** [comment]
Removing `hal_st` will **break** compilation for 14 drivers from upstream zephyr:

- hts221
- i3g4250d
- iis2dh
- iis2dlpc
- iis2iclx
- iis2mdc
- iis3dhhc
- ism330dhcx
- lis2ds12
- lis2dw12
- lis2mdl
- lps22hh
- lsm6dso
- stts751

These drivers use functions and register definitions from `hal_stl`

**Comment by kapi-no** [comment]
This change broke the Find My Thingy application. I have a fix incoming for it in the following PR:

https://github.com/nrfconnect/sdk-nrf/pull/8793

I am not sure why the integration tests weren't triggered when the manifest file was modified. Is it how it is supposed to work?

**Pull request merged**
