### PR TITLE
samples: crypto: Fixed modem issue for psa_tls on nRF9160 non-secure

### PR DESCRIPTION
**Pull request by magnev**
- Disabled modem library for psa_tls sample.

Signed-off-by: Magne Værnes <magne.varnes@nordicsemi.no>

### CODE REVIEW

**Review by lemrey — APPROVED** [review]
Looks good, but @magnev could we leave a comment either in the commit or in the project file itself, that we are disabling the modem library because the sample uses mbedTLS's stack (and enabling libmodem would enable socket offloading).

**Comment by Vge0rge** [comment]
> Looks good, but @magnev could we leave a comment either in the commit or in the project file itself, that we are disabling libmodem because the sample uses mbedTLS's stack (and enabling libmodem would enable socket offloading).

Not very familiar with the libmodem. @lemrey  Could you explain how the mbedlts stack is affected/affects the socket offloading functionality?

**Comment by lemrey** [comment]
It's the other way around. `libmodem` has `imply NET_SOCKETS_OFFLOAD` which lets socket APIs be offloaded to the nRF9160 modem. You need to keep it disabled if you want socket APIs to go through Zephyr's native stack and mbedTLS.

**Comment by Vge0rge** [comment]
> It's the other way around. `libmodem` has `imply NET_SOCKETS_OFFLOAD` which lets socket APIs be offloaded to the nRF9160 modem. You need to keep it disabled if you want socket APIs to go through Zephyr's native stack and mbedTLS.

Thanks for the explanation! @magnev  Please include this information to the commit message.

**Review by Vge0rge — APPROVED** [review]

**Pull request merged**
