### PR TITLE
Fix https_client build with TF-M and Mbed TLS

### PR DESCRIPTION
**Pull request by plskeggs**
Building the sdk-nrf/nrf9160/https_client sample with the overlay-tfm_mbedtls.conf was failing due to a missing Kconfig entry for Mbed TLS, as well as some incompatible settings for encryption.

Thanks to @frkv for the fixes.

### CODE REVIEW

**Review by joerchan — APPROVED** [review]

**Comment by joerchan** [comment]
@plskeggs Should this have the milestone for 2.0.0?

**Comment by rlubos** [comment]
@plskeggs Looks like a duplicate of https://github.com/nrfconnect/sdk-nrf/pull/7667. Does the sample actually work with your changes (not only build)? I've needed addtitional changes in the configuration in order to avoid heap starvation, but perhaps it could be addressed some other way as well (like in your PR).

**Comment by plskeggs** [comment]
I will admit I was not diligent regarding testing.  Frank changed some of the configuration regarding crypto, not just to enable Mbed TLS. It is likely your changes should be merged with these and then tested.

I can do so in about 8 hours from now.  If this needs to be done sooner, and you have time, please do so.

**Comment by rlubos** [comment]
> I will admit I was not diligent regarding testing. Frank changed some of the configuration regarding crypto, not just to enable Mbed TLS. It is likely your changes should be merged with these and then tested.
> 
> I can do so in about 8 hours from now. If this needs to be done sooner, and you have time, please do so.

I'll investigate this further, it actually seems that with https://github.com/nrfconnect/sdk-nrf/pull/7146 in place, the sample no longer builds again, neither with my changes nor yours :)

**Comment by rlubos** [comment]
I've combinded the changes and updated my PR: https://github.com/nrfconnect/sdk-nrf/pull/7667
It builds again, however the sample fails to connect to the server. After some investigation, it turns out that the cipher list sent in Client Hello to the server is empty. I've noticed that AES is disabled in the build, when I run the sample (sucessfully) with the software variant of mbed TLS I get the following list of ciphersuites:
image
@frkv What else to enable to get similar result with TFM? I don't understand how to enable AES_CBC with TFM, I'm not able to modify the Kconfig entries with `menuconfig` as they're marked as unavailable.

**Comment by rlubos** [comment]
ok, the sample now works again in https://github.com/nrfconnect/sdk-nrf/pull/7667 after some additional tweaks

**Pull request merged**
