### PR TITLE
crypto: Use immediate logging

### PR DESCRIPTION
**Pull request by torsteingrindvik**
UART output is sometimes garbled.
This hurts CI stability.
Use immediate logging instead.

Signed-off-by: Torstein Grindvik <torstein.grindvik@nordicsemi.no>

### CODE REVIEW

**Review by Vge0rge — APPROVED** [review]
Looks good to me, if you can better change the commit message to:
samples: crypto: blah blah blah

**Comment by torsteingrindvik** [comment]
Changed the commit msg prefix as requested.

**Comment by lemrey** [comment]
Why is it garbled, or rather, what is it garbled with?

**Comment by torsteingrindvik** [comment]
> Why is it garbled, or rather, what is it garbled with?

On occasions the output is interleaved in strange ways- i.e. parts of output appear out of order and such.
I have a hypothesis on why this happens, but I need time to prove it.
So for now I prioritize having CI stable.

**Pull request closed without merging**
