### PR TITLE
OCT-2505 ztest migration

### PR DESCRIPTION
**Pull request by koffes**

### CODE REVIEW

**Review by alexsven — APPROVED** [review]
Should the commit titles be changed to 'module: submodule: ztest migration' ?

**Review by gWacey — APPROVED** [review]

**Comment by koffes** [comment]
I will check.

**Comment by koffes** [comment]
Yes, I see the same issue. This is due to test-case-order. A fix has been pushed.

**Comment by koffes** [comment]
I have pushed the sw_codec_lc3 test with an intentional fault. Will be reverted.

**Review by erikrobstad — APPROVED** [review]

**Review by gopiotr — APPROVED** [review]

**Pull request merged**
