### PR TITLE
lib: date_time: Fix uptime to UTC time conversion

### PR DESCRIPTION
**Pull request by ewalt1**
Signed-off-by: Nick Ewalt <nicholasewalt@google.com>

### CODE REVIEW

**Comment by tokangas** [comment]
Hi Nick and thanks for your contribution!

Yes, indeed the logic in `date_time_uptime_to_unix_time_ms()` seems to be flawed and your PR fixes the issue.

You need to add some text to the commit message body, please check the failing CI compliance check.

**Comment by tokangas** [comment]
Hi Nick and thanks for your contribution!

Yes, indeed the logic in `date_time_uptime_to_unix_time_ms()` seems to be flawed and your PR fixes the issue.

You need to add some text to the commit message body, please check the failing CI compliance check.

**Comment by tokangas** [comment]
I added a commit to update the unit tests. The tests now check that the conversion works correctly. The test fails with current main, but passes with this PR.

**Comment by tokangas** [comment]
modem_shell and positioning tests are failing currently. It looks like the issue is in nRF Cloud, the cloud team is working on it.

**Comment by ewalt1** [comment]
Force pushed an amended commit message, you'll need to re-add your unit test commit.

**Review by rlubos — APPROVED** [review]

**Comment by glarsennordic** [comment]
Ha! Beat me to the punch! Well done, @ewalt1 

This fixes JIRA ticket NCSDK-14235.

However, this raises the question, is the sanity check on line 99 really valid?

```C
if (*uptime > uptime_now) {
```

It seems reasonable to me that someone might want to know the unix timestamp for an uptime that is in the near future.

In fact, this further raises some interpretation questions -- technically, all uptimes can be interpreted as an infinite number of Unix timestamps. For instance, if the uptime is currently 50ms, is the uptime 131071000ms equal to 1.05 seconds ago, or 1.5 days in the future? Either is technically correct!

The sanity check does protect against the scenario that someone measures uptime just before it rolls over, and then converts to a timestamp just after it rolls over. In such a scenario, the uptime would be interpreted as being in the distant future, and raise an error.

But I think it would be more reliable and more intuitive to just pick the closest valid interpretation of an uptime. For instance, if the current uptime is 1000, and someone passes 1050, that will be interpreted as 50 ms in the future, not 1.5 days in the past.

This approach would still protect against the sample-before-rollover, convert-after-rollover scenario, since the closest valid interpretation of the provided timestamp would remain the one in the past (at least, it would for about 0.75 days. If you're waiting more than a few hours to convert uptimes to timestamps, I think that's on you at that point)

@trantanen @tokangas thoughts? I can whip together a short and sweet PR to make these changes if you approve.

**Comment by ewalt1** [comment]
Personally I think allowing conversions for uptimes in the future would be fine, though I don't have a strong opinion on it.

Where does your value of 1.5 days come from? If it's meant to be the 32b overflow point you're off by a factor of 16. Even then it shouldn't matter since the uptime is supposed to be 64b. Am I missing something?

**Comment by glarsennordic** [comment]
k_uptime_get() returns a 64b integer, but it is based internally on either k_cycle_get_32(), or k_cycle_get_64().

Which of the two is used depends on the build target, and whether the target supports a 64 bit system tick count. In the case of an nrf9160 (which I picked arbitrarily), we have `CONFIG_TIMER_HAS_64BIT_CYCLE_COUNTER` disabled. I'm not sure whether the nrf9160 actually could support a 64b timer, but at the moment the uptime tick count is 32 bit.

Those ticks are converted to seconds by the converstion factor  CONFIG_SYS_CLOCK_TICKS_PER_SEC, which on the nrf9160 is configured at 32768. Ticks per millisecond, therefore, is 32.768. If the system timer overflows after 32 bits, the then uptime will overflow every `2^32/32.768 = 131072000 ms`


But honestly, the specific values I chose were just meant an an illustration. On a system with 64 bit tick timer, you're right, it wouldn't matter, but it would probably be wise to support build targets with 32 bit tick timer as well, especially since I'm pretty sure nrf9160 is one such build target

**Comment by ewalt1** [comment]
As far as I can tell CONFIG_TIMER_HAS_64BIT_CYCLE_COUNTER isn't a valid Zephyr Kconfig option anymore.

k_uptime_get() calls k_uptime_ticks() which calls sys_clock_tick_get() which returns curr_tick which is always a uint64_t.

https://github.com/zephyrproject-rtos/zephyr/blob/main/kernel/timeout.c#L15

**Comment by glarsennordic** [comment]
Nice, I stand corrected, at least from reading the latest zephyr source.

In that case it probably suffices to just outright remove the sanity check.

@trantanen @tokangas does this seem reasonable?

**Comment by ewalt1** [comment]
Sweet, glad it doesn't have to get complicated.

As far as negative and future uptimes are concerned I'll leave that up to you guys, I don't have a use case for either.

I will say that I'm still disappointed with the negative performance impact of the refactor that led to this bug. Here are the numbers from a profiling run I just did on the NRF9160:
    date_time_now went from 760 to 870 CPU cycles
    date_time_uptime_to_unix_time_ms went from 420 to 1260 CPU cycles
The old method of storing the correlation timepoints was much more efficient than computing a new one for each conversion.

**Comment by tokangas** [comment]
@trantanen is on a long vacation, so he's not around to comment. When reviewing the PR, I also though whether we should get rid of that check. I don't know the reason why such limitation has been there from the start, but at least now it should be straight forward to remove it and allow also future time stamps to be converted. Removing the check is fine for me and I will be glad to approve a PR which removes it.

@glarsennordic I don't see why the function couldn't convert negative values as well. The current implementation already works fine with those, so only the check for negative value should be removed. There's an unit test case for this as well, so a PR which removes the check should also remove that test case. And preferably also test that conversion for a negative uptime works as expected.

If the function behavior is modified, the API also needs to be updated. In my opinion, the current description could use some rework, it's quit complicated for such a simple function anyway.

@ewalt1 Sorry to hear that, this is something which most likely wasn't considered much when refactoring the code. I think the aim was only to simplify the code.

**Pull request merged**
