### PR TITLE
application: asset_tracker_v2: rename A-GNSS topics on AWS and Azure

### PR DESCRIPTION
**Pull request by coderbyheart**
#12568 changed to the better name, and this follows up with the cloud side changes in nRF Asset Tracker for AWS and Azure.

Cloud changes:
 - AWS: https://github.com/NordicSemiconductor/asset-tracker-cloud-aws-js/pull/1604
 - Azure: https://github.com/NordicSemiconductor/asset-tracker-cloud-azure-js/pull/601

### CODE REVIEW

**Review by simensrostad — APPROVED** [review]

**Review by maxd-nordic — APPROVED** [review]

**Review by simensrostad — APPROVED** [review]

**Comment by coderbyheart** [comment]
Rebased against main.

**Review by divipillai — APPROVED** [review]

**Comment by coderbyheart** [comment]
Rebased against main.

**Comment by coderbyheart** [comment]
Rebased against main.

**Comment by coderbyheart** [comment]
rebased again 😭

**Comment by coderbyheart** [comment]
Will rebase after 2.6.0 release. 😴

**Comment by coderbyheart** [comment]
Resolved conflicts.

**Comment by coderbyheart** [comment]
@maxd-nordic can you have a look at the build failures please?

```
10:03:42  INFO    - The following issues were found (showing the top 10 items):
10:03:42  INFO    - 1) applications.asset_tracker_v2.aws-all.sysbuild on thingy91x_nrf9151_ns error (Build failure)
10:03:42  INFO    - 2) applications.asset_tracker_v2.aws-pgps on nrf9160dk_nrf9160_ns error (Build failure)
10:03:42  INFO    - 3) applications.asset_tracker_v2.aws-pgps.sysbuild on nrf9160dk_nrf9160_ns error (Build failure)
10:03:42  INFO    - 4) applications.asset_tracker_v2.aws-pgps on nrf9161dk_nrf9161_ns error (Build failure)
10:03:42  INFO    - 5) applications.asset_tracker_v2.aws on nrf9151dk_nrf9151_ns error (Build failure)
10:03:42  INFO    - 6) applications.asset_tracker_v2.aws-all.sysbuild on thingy91_nrf9160_ns error (Build failure)
10:03:42  INFO    - 7) applications.asset_tracker_v2.aws-pgps.sysbuild on thingy91_nrf9160_ns error (Build failure)
10:03:42  INFO    - 8) applications.asset_tracker_v2.aws on thingy91_nrf9160_ns error (Build failure)
10:03:42  INFO    - 9) applications.asset_tracker_v2.aws-all on thingy91_nrf9160_ns error (Build failure)
10:03:42  INFO    - 10) applications.asset_tracker_v2.aws-pgps on thingy91x_nrf9151_ns error (Build failure)
10:03:42  INFO    - 
10:03:42  INFO    - To rerun the tests, call twister using the following commandline:
10:03:42  INFO    - west twister -p <PLATFORM> -s <TEST ID> --no-detailed-test-id, for example:
10:03:42  INFO    - 
10:03:42  INFO    - west twister -p thingy91x_nrf9151_ns -s applications.asset_tracker_v2.aws-pgps --no-detailed-test-id
10:03:42  INFO    - or with west:
10:03:42  INFO    - west build -p -b thingy91x_nrf9151_ns ../nrf/applications/asset_tracker_v2 -T applications.asset_tracker_v2.aws-pgps
10:03:42  INFO    - -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
10:03:42  INFO    - Run completed
```

**Comment by coderbyheart** [comment]
🎆

**Pull request merged**
