### PR TITLE
zephyr: update include paths to use <zephyr/...>

### PR DESCRIPTION
**Pull request by gmarull**
Zephyr has prefixed all of its includes with <zephyr/...>. While the old
mode can still be used (CONFIG_LEGACY_INCLUDE_PATH) and is still enabled
by default, it's better to be prepared for its removal in the future.

### CODE REVIEW

**Review by VeijoPesonen — APPROVED** [review]
samples: lwm2m_client: ok
subsys: net: lwm2m_client_utils: ok

**Review by junqingzou — APPROVED** [review]
Application Serial-LTE_Modem changes OK

**Review by pdunaj — APPROVED** [review]
I am giving you my approval of faith

**Review by eivindj-nordic — APPROVED** [review]

**Review by SeppoTakalo — APPROVED** [review]

**Review by KAGA164 — APPROVED** [review]
I did a quick check for the Bluetooth and the NFC subsystems and related samples. It looks good and I hope that it will work.

**Review by MarekPorwisz — APPROVED** [review]

**Comment by gmarull** [comment]
Jenkins fails with an unrelated failure:

```
INFO    - 77/95 qemu_cortex_m3            nrf5340_audio/max14690/nrf5340_audio.max14690_test FAILED Timeout (qemu)
11:24:12  INFO    - /jenkins_workspace/workspace/latest_sdk-nrf_PR-7550/twister-build/qemu_cortex_m3/nrf5340_audio/max14690/nrf5340_audio.max14690_test/handler.log
11:24:12  ERROR   - *** Booting Zephyr OS build v2.7.99-ncs1-4477-ga73fdfbe4d92  ***
11:24:12  Running test suite test_suite_max14690
11:24:12  ===================================================================
11:24:12  START - test_init_ok
11:24:12  E: ***** USAGE FAULT *****
11:24:12  E:   Illegal use of the EPSR
11:24:12  E: r0/a1:  0x00000001  r1/a2:  0x20000fd0  r2/a3:  0x00000002
11:24:12  E: r3/a4:  0x00000028 r12/ip:  0x00000000 r14/lr:  0x000011fb
11:24:12  E:  xpsr:  0x20000000
11:24:12  E: Faulting instruction address (r15/pc): 0x00000000
11:24:12  E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
11:24:12  E: Current thread: 0x200003c8 (test_init_ok)
11:24:12  E: Halting system
```

**Review by rakons — APPROVED** [review]

**Pull request merged**
