### PR TITLE
lib: lte_link_control: add support for limited service sleep type

### PR DESCRIPTION
**Pull request by tokangas**
Added support for modem sleep events because of limited service.

### CODE REVIEW

**Comment by tokangas** [comment]
I noticed that LTE LC modem sleep notifications do not support the `limited service` type. @jtguggedal and @simensrostad, do you know if there's a good reason why it has not been included earlier? Adding it is simple (unless there's a caveat) and I'm adding documentation for PSM usage (#10300) where this would be useful.

**Review by jtguggedal — APPROVED** [review]

**Comment by jtguggedal** [comment]
> I noticed that LTE LC modem sleep notifications do not support the `limited service` type. @jtguggedal and @simensrostad, do you know if there's a good reason why it has not been included earlier? Adding it is simple (unless there's a caveat) and I'm adding documentation for PSM usage (#10300) where this would be useful.

Can't think of a good reason, probably just an overlook at the time

**Review by trantanen — APPROVED** [review]

**Review by simensrostad — APPROVED** [review]
Lookin good

**Comment by tokangas** [comment]
There seems to be some unclarity when modem sends an %XMODEMSLEEP notification with type 3. This needs some further investigation, so flagging this as DNM for now.

**Comment by tokangas** [comment]
> There seems to be some unclarity when modem sends an `%XMODEMSLEEP` notification with type 3. This needs some further investigation, so flagging this as DNM for now.

Sleep notification with type 3 is not sent always in limited service, but it depends on the cell UE is camped on. Sleep type 3 is also used when out of coverage, i.e. no cell can be found.

I added descriptions for the enums, added support for the new sleep type in `modem_shell` and updated the PSM usage documentation which uses the limited service sleep notification.

**Review by jhirsi — APPROVED** [review]

**Review by hiltunent — APPROVED** [review]

**Review by peknis — APPROVED** [review]

**Pull request merged**
