### PR TITLE
manifest: Update to TF-M 1.6 and MBedTLS 3.1.0

### PR DESCRIPTION
**Pull request by joerchan**
Update the following dependencies:
- Update TF-M from 1.5 to 1.6.
- Update MBedTLS from 3.0.0 to 3.1.0.

Pull following additional fixes:
- Zephyr pull TF-M test repositories and zephyr TF-M patches.
- nrfxlib update nrf_security for mbedtls.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

test-sdk-nrf: sdk-nrf-PR-7933

### CODE REVIEW

**Comment by joerchan** [comment]
This brings in the update from zephyr for mbedtls and tf-m from: https://github.com/zephyrproject-rtos/zephyr/pull/44655

**Review by torsteingrindvik — APPROVED** [review]
TFM and crypto internal test pipelines against this PR were successful.

**Review by Vge0rge — APPROVED** [review]
LGTM

**Review by frkv — APPROVED** [review]
LGTM

**Pull request merged**
