### PR TITLE
boards: Enable stack protection only when available

### PR DESCRIPTION
**Pull request by pdunaj**
Don't try enabling HW_STACK_PROTECTION in board config files
but rather do it in its Kconfig.defconfig.
This is to make sure the option is not enabled when it is
actually not available due to dependencies not being met.

Jira:NCSDK-7594

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
The goal is to have a change that will change nothing but make sure that we don't get warnings during kcofnig processing.

**Comment by pdunaj** [comment]
I think we will also need the same change in zephyr/boards

**Review by MarekPieta — APPROVED** [review]

**Comment by pdunaj** [comment]
Hi @tejlmand , maybe you can check this?

**Comment by pdunaj** [comment]
Or @anangl , @ioannisg ?

**Review by anangl — APPROVED** [review]

**Comment by anangl** [comment]
@mbolivar-nordic Can this one be merged? I think it will create some merge conflicts in the upstream PR, but those should be quite easy to resolve.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@mbolivar-nordic I merged this one since it was required for some downstream work. Hopefully it won't cause any trouble for the upmerge as @anangl said.

**Comment by mbolivar-nordic** [comment]
> Hopefully it won't cause any trouble for the upmerge

Thanks for the heads-up. It's fine; I expect I'll be dealing with merge conflicts every day until we freeze sdk-nrf.

**Pull request merged**
