### PR TITLE
Revert "applications: machine_learning: Drop Thingy:52 configurations"

### PR DESCRIPTION
**Pull request by MarekPieta**
Bring back Thingy:52 support to nRF Machine Learning application. This reverts commit `0e49f08b348e45318557924426fb4fd0da703a70` and applies required configuration updates.

Jira: NCSDK-18215

### CODE REVIEW

**Review by shantha-14 — CHANGES_REQUESTED** [review]
There is an email thread initiate by Pawel, need approval and business agreement before we  decide to revert the changes,

**Comment by MarekPieta** [comment]
The PR was opened on @pdunaj request.

**Comment by MarekPieta** [comment]
The only observed issue is the fact that there is MPU fault when system enters deep sleep. We could workaround this issue disabling deep sleep state in the Kconfig (unless we find proper solution).

**Review by rakons — APPROVED** [review]

**Comment by MarekPieta** [comment]
Discussed with @pdunaj. The revert seems no longer needed. I close the PR.

Added note to the commit message to inform about the known issue related to crash when system is turned off.

**Pull request closed without merging**
