### PR TITLE
doc: release-notes-latest: Summarize networking changes from the upmerge

### PR DESCRIPTION
**Pull request by rlubos**
Filtered out only relevant ones for NCS .

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Review by jfischer-no — APPROVED** [review]

**Review by ru-fu — CHANGES_REQUESTED** [review]
Will add a commit.

**Review by ru-fu — COMMENTED** [review]
Added - please check and squash if okay. :)

**Comment by rlubos** [comment]
@ru-fu Thanks, I've squashed the fixes 👍

**Review by ru-fu — APPROVED** [review]

**Comment by carlescufi** [comment]
@rlubos please rebase

**Comment by rlubos** [comment]
@carlescufi Done

**Pull request merged**
