### PR TITLE
openthread: samples: Remove overlay-minimal.conf from RCP sample.

### PR DESCRIPTION
**Pull request by canisLupus1313**
Remove overlay-minimal.conf from RCP sample.

### CODE REVIEW

**Comment by lmaciejonczyk** [comment]
What do you think about removing overlay-minima.conf completely since we're not testing this configuration?

**Comment by canisLupus1313** [comment]
@lmaciejonczyk I think it's great idea.

**Review by lmaciejonczyk — APPROVED** [review]

**Review by edmont — CHANGES_REQUESTED** [review]
Please update Readme as well.

**Review by edmont — APPROVED** [review]
Maybe update changelog as well?

**Comment by canisLupus1313** [comment]
@edmont I think after a release 2.0 it can be done.

**Comment by edmont** [comment]
If the PR won't be merged for the release the changes can be applied already.

**Review by wiba-nordic — APPROVED** [review]

**Comment by wiba-nordic** [comment]
If the PR makes it to 2.0, release note entry can be combined with the one for CLI (Line 344).

**Pull request merged**
