### PR TITLE
slm: fix Thingy:91 full FOTA documentation

### PR DESCRIPTION
**Pull request by tomi-font**
Make explicit that it is not supported.

### CODE REVIEW

**Comment by mariusz-nordicsemi** [comment]
> @wiba-nordic Any idea on how to fix the documentation build (and what actually causes it to fail)?

I think the issue is related to the Protocol support table in Software maturity levels. There is a HomeKit entry present in this table but during the doc build no input value is found for this entry. But HomeKit is present on v2.5-branch.
@gmarull, @gautesl, do you know from where the input values for Protocol support table are taken when building doc on the PR?

**Comment by gautesl** [comment]
Hi, I am no longer a maintainer of the relevant code, so I will not be able to respond to future inquiries.

... However, Homekit was removed recently in https://github.com/nrfconnect/sdk-nrf/commit/7050fee512a49e673104a79b0a4ed421078d55d1#diff-b30571e67cf16ed1d2f79030ff3fde37fee497f19fb3d70dc25b1524eaf08329L223 from the main documentation, so I think a rebase should fix the problem.

**Review by SeppoTakalo — APPROVED** [review]

**Review by MarkusLassila — APPROVED** [review]

**Review by haakoneh — APPROVED** [review]

**Comment by divipillai** [comment]
> > @wiba-nordic Any idea on how to fix the documentation build (and what actually causes it to fail)?
> 
> I think the issue is related to the Protocol support table in Software maturity levels. There is a HomeKit entry present in this table but during the doc build no input value is found for this entry. But HomeKit is present on v2.5-branch. @gmarull, @gautesl, do you know from where the input values for Protocol support table are taken when building doc on the PR?

@gmarull : Could you check the doc-build failure here. https://github.com/nrfconnect/sdk-nrf/actions/runs/6744415676/job/18880302825?pr=12956#step:7:6116

As Wille mentioned the issue could be because, on v2.5-branch, In software maturity levels table, there is an entry for HomeKit. HomeKit has been removed from master and data related to this is missing.

**Comment by gmarull** [comment]
> > > @wiba-nordic Any idea on how to fix the documentation build (and what actually causes it to fail)?
> > 
> > 
> > I think the issue is related to the Protocol support table in Software maturity levels. There is a HomeKit entry present in this table but during the doc build no input value is found for this entry. But HomeKit is present on v2.5-branch. @gmarull, @gautesl, do you know from where the input values for Protocol support table are taken when building doc on the PR?
> 
> @gmarull : Could you check the doc-build failure here. https://github.com/nrfconnect/sdk-nrf/actions/runs/6744415676/job/18880302825?pr=12956#step:7:6116
> 
> As Wille mentioned the issue could be because, on the v2.5-branch, In software maturity levels table, there is an entry for HomeKit. HomeKit has been removed from the main, and data related to this is missing.

It's because homekit no longer exists in main, let me try to push a fix later or tomorrow (I'll try my best, since I'm busy)

**Comment by gmarull** [comment]
> > > > @wiba-nordic Any idea on how to fix the documentation build (and what actually causes it to fail)?
> > > 
> > > 
> > > I think the issue is related to the Protocol support table in Software maturity levels. There is a HomeKit entry present in this table but during the doc build no input value is found for this entry. But HomeKit is present on v2.5-branch. @gmarull, @gautesl, do you know from where the input values for Protocol support table are taken when building doc on the PR?
> > 
> > 
> > @gmarull : Could you check the doc-build failure here. https://github.com/nrfconnect/sdk-nrf/actions/runs/6744415676/job/18880302825?pr=12956#step:7:6116
> > As Wille mentioned the issue could be because, on the v2.5-branch, In software maturity levels table, there is an entry for HomeKit. HomeKit has been removed from the main, and data related to this is missing.
> 
> It's because homekit no longer exists in main, let me try to push a fix later or tomorrow (I'll try my best, since I'm busy). Btw, do you need render docs for this branch immediately? If not, feel free to merge and we'll fix it afterwards.

**Review by wiba-nordic — APPROVED** [review]

**Comment by wiba-nordic** [comment]
With the issue now confirmed, I'm okay if this one goes in before the fix.

**Comment by divipillai** [comment]
> With the issue now confirmed, I'm okay if this one goes in before the fix.

We can merge this PR, if needed (also confirmed with @gmarull). The doc issue is not PR specific, and changes related to the PR works as expected in the main.
cc: @shantha-14

**Comment by divipillai** [comment]
> > With the issue now confirmed, I'm okay if this one goes in before the fix.
> 
> We can merge this PR, if needed (also confirmed with @gmarull). The doc issue is not PR specific, and changes related to the PR works as expected in the main. cc: @shantha-14

@cvinayak : As per the above comments, the doc failure can be ignore, and the PR can be merged.

**Pull request merged**
