### PR TITLE
Fix issues building nrfxlib docs with Doxygen 1.8.17

### PR DESCRIPTION
**Pull request by utzig**
Fix deprecated Doxygen issues; bump nrfxlib to PR with fixes for Doxygen 1.8.17.

### CODE REVIEW

**Review by thst-nordic — APPROVED** [review]

**Comment by thst-nordic** [comment]
can this be merged before the toolchain upgrade?

**Comment by utzig** [comment]
> can this be merged before the toolchain upgrade?

Yes, it works on both 1.8.13 and 1.8.17. https://github.com/nrfconnect/sdk-nrfxlib/pull/333 must go in first.

**Comment by utzig** [comment]
These commits were added to #3388

**Pull request closed without merging**
