### PR TITLE
manifest: Batch nrfxlib update

### PR DESCRIPTION
**Pull request by Vge0rge**
See https://github.com/nrfconnect/sdk-nrfxlib/pull/501

### CODE REVIEW

**Review by tejlmand — APPROVED** [review]

**Review by frkv — APPROVED** [review]
LGTM pending addition of correct hash

**Comment by mbolivar-nordic** [comment]
Updated to point at #501 instead, which includes the original PR and some ohters

**Review by carlescufi — APPROVED** [review]

**Comment by frkv** [comment]
Will the test run to completion or will it be rebased before?

**Comment by mbolivar-nordic** [comment]
I've just rebased

**Pull request merged**
