### PR TITLE
Integrate nrfx 3.2.0

### PR DESCRIPTION
**Pull request by nika-nordic**
Associated PRs:
- https://github.com/nrfconnect/sdk-mcuboot/pull/280 (can be merged now, no dependency on this PR)
- https://github.com/nrfconnect/sdk-trusted-firmware-m/pull/110 (can be merged now, no dependency on this PR)
- https://github.com/nrfconnect/sdk-connectedhomeip/pull/333
- https://github.com/nrfconnect/sdk-homekit/pull/480 (confirmed by sdk-homekit maintainers that it is already merged)
- https://github.com/nrfconnect/sdk-find-my/pull/169

### CODE REVIEW

**Comment by nika-nordic** [comment]
CI status - there are two failures:
- `test-sdk-find-my` - missing `nrf_power` alignment, will be fixed on next CI run
- `test-fw-nrfconnect-zigbee` - runtime issue, reason unknown, waiting for support from Zigbee maintainers

**Review by anangl — APPROVED** [review]

**Comment by nordicjm** [comment]
Seeing 136 failures (and counting) in my PR which updates sdk-zephyr manifest, assuming this will fix them? https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12856/2/

**Comment by nordicjm** [comment]
Or can you just update sdk-zephyr commit to `908794942947d049b61603b728f8f15af17e4873` as this would vastly speed up CI runs

**Comment by nika-nordic** [comment]
> Seeing 136 failures (and counting) in my PR which updates sdk-zephyr manifest, assuming this will fix them? https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12856/2/

I guess this PR should fix them, as it aligns all affected modules to API change in nrfx.

> Or can you just update sdk-zephyr commit to 908794942947d049b61603b728f8f15af17e4873 as this would vastly speed up CI runs

should I do it now or wait for the PR CI to finish?

**Comment by nordicjm** [comment]
> should I do it now or wait for the PR CI to finish?

Since only 10 minutes into a possible 2 hour CI run, now please :)

**Comment by nika-nordic** [comment]
> > should I do it now or wait for the PR CI to finish?
> 
> Since only 10 minutes into a possible 2 hour CI run, now please :)

done as requested :)

**Comment by nordicjm** [comment]
@57300 @rlubos please approve this PR in place of other one

**Review by 57300 — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
