### PR TITLE
Update west.yml for new SDC in nrfxlib v2.4-branch

### PR DESCRIPTION
**Pull request by guwa**

### CODE REVIEW

**Comment by divipillai** [comment]
@gmarull : The homekit issue that was seen in the 2.5 branch is seen in the 2.4 branch. The fix is added in this PR as per PR https://github.com/nrfconnect/sdk-nrf/pull/13252. 

Could you please check and approve the PR is all looks good.

**Comment by gmarull** [comment]
could you guys just cherry-pick the commit from 2.5 branch?

**Comment by cvinayak** [comment]
> could you guys just cherry-pick the commit from 2.5 branch?

@gmarull it should be cherry-picked now... please approve this PR is ok by you.

**Comment by guwa** [comment]
The CI failure can be ignored after analysis. 
FEM CI failed due to "ValueError: SHA b'10b62d40f7b95454a4029afbe41571c252324ad2' could not be resolved, git returned: b'10b62d40f7b95454a4029afbe41571c252324ad2 missing'"
RS CI failed due to "ValueError: SHA b'3ca1fdc8a108f2ec9dd60a67225968ad1c74be19' could not be resolved, git returned: b'3ca1fdc8a108f2ec9dd60a67225968ad1c74be19 missing'"

The change should not affect these domain and can be ignored.

**Comment by guwa** [comment]
ble_mesh passsed with rerun. The failure was related with code checkout.

**Comment by shanthanordic** [comment]
Failures are accepted based on risk

**Review by shanthanordic — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Pull request merged**
