### PR TITLE
manifest: Update sdk-zephyr revision

### PR DESCRIPTION
**Pull request by tejlmand**
Update sdk-zephyr to pull in APPLICATION_CONFIG_DIR support in sysbuild.

### CODE REVIEW

**Review by nordicjm — CHANGES_REQUESTED** [review]
boot CI tests failing, FEM CI tests failing, crypto CI tests failing, rs CI tests failing, tfm CI tests failing, dfu CI tests failing, find-my CI tests failing, mcuboot CI tests failing. Needs to be fixed before merge

**Comment by kapi-no** [comment]
Find My tests CI failed due to the JUnit parser instability. This failure is irrelevant and could potentially be resolved by the Find My CI rerurn. @miha-nordic, please correct me if I am wrong

**Comment by nordicjm** [comment]
```
./sysbuild/application/zephyr/net_provision.hex
./sysbuild/application/zephyr/signed_by_b0_hci_ipc.hex
./sysbuild/application/zephyr/signed_by_mcuboot_and_b0_hci_ipc.hex
```
In wrong locations. Also this has the `sysbuild` prefix so doing `ninja sys` and pressing tab, instead of going to `sysbuild_` and showing menuconfig and guiconfig, shows over 180 files in the sysbuild folder which was discussed, the folder should have a prefix so it does not appear like that

**Comment by nordicjm** [comment]
> but afaik the files you mention are merged into other files and not intended to be used independently.

Only the provision file is like that, the rest are fully used and expected to be available. And the net provision should either be in the top level or in the folder for the application it is used for. `signed_by_b0_hci_ipc.hex/bin` is something customers can use to update if they do not use MCUboot to load the image or if they load it through their application (as `nrf_desktop` does). `signed_by_mcuboot_and_b0_hci_ipc.hex/bin` is used for updating from the application using MCUmgr, or from MCUboot using serial recovery

> _sysbuild (instead of sysbuild), but that also makes it look like it's private or similar, and not really what we mean.

Gets my vote and is simple.

**Comment by tejlmand** [comment]
> And the net provision should either be in the top level or in the folder for the application it is used for.

That's a good point. Will move to top-level, although image specific build folder might actually be more appropriate then I don't like sysbuild modules to start placing extra files in a build folder controlled by the image build.

> the rest are fully used and expected to be available. ...  is something customers can use to update if they do not use MCUboot to load the image or if they load it through their application

will move to top-level as well, but this comment made me wonder if we are actually documenting this.
Both in term of which build files can be expected to be available and where, as well as how to use those file when they are not using MCUboot.

> Gets my vote and is simple.

:+1:

**Comment by tejlmand** [comment]
@nordicjm files location has been moved and sysbuild app entry folder is renamed to `_sysbuild`

**Comment by nordicjm** [comment]
> @nordicjm files location has been moved and sysbuild app entry folder is renamed to `_sysbuild`

Still seeing them in wrong folder:
```
./zephyr/signed_by_b0_empty_net_core.hex    <-- should be up a folder
./zephyr/signed_by_mcuboot_and_b0_empty_net_core.hex <-- should be up a folder
./zephyr/signed_by_b0_empty_net_core.bin  <-- should be up a folder
./zephyr/signed_by_mcuboot_and_b0_empty_net_core.bin  <-- should be up a folder
./zephyr/signed_by_b0_mcuboot.hex <-- should be up a folder
./zephyr/signed_by_mcuboot_and_b0_mcuboot.hex <-- should be up a folder
./zephyr/signed_by_b0_empty_net_core.hex <-- should be up a folder
./zephyr/signed_by_mcuboot_and_b0_empty_net_core.hex <-- should be up a folder
./smp_svr/zephyr/zephyr.hex
./smp_svr/zephyr/zephyr.signed.hex
./mcuboot/zephyr/zephyr.hex
./empty_net_core/zephyr/zephyr.hex
./b0n/zephyr/zephyr.hex
./merged.hex
./b0n_container.hex
./net_provision.hex
./merged_CPUNET.hex
```

**Comment by tejlmand** [comment]
> Still seeing them in wrong folder:

Should be fixed now.

> Also it seems that the dfu_application.zip generated when B0 is enabled is in different directory than dfu_application.zip when MCUboot is enabled:

Fixed

**Comment by nordicjm** [comment]
wrong folder:
```
./zephyr/dfu_mcuboot.zip   <-- should be up a folder
```

Matter is broken, `samples/matter/light_bulb` build for `nrf5340dk/nrf5340/cpuapp`:
```
ninja: error: 'zephyr/signed_by_mcuboot_and_b0_ipc_radio.bin', needed by 'dfu_application.zip', missing and no known rule to make it
```

**Comment by tejlmand** [comment]
@nordicjm PTAL, all is fixed.
CI issues are caused by existing failures on main.

**Comment by nordicjm** [comment]
wrong folder:
```
./zephyr/dfu_mcuboot.zip   <-- should be up a folder
```

**Comment by doublemis1** [comment]
@nordicjm  @tejlmand 
Why is the milestoneset to NCS 2.7.0?
Is it some crucial fix?

**Review by doublemis1 — DISMISSED** [review]
Please remove NCS 2.7.0 milestone since it is not a bugfix.

**Comment by tejlmand** [comment]
> @nordicjm @tejlmand Why is the milestoneset to NCS 2.7.0? Is it some crucial fix?

Yes it is:
https://github.com/nrfconnect/sdk-nrf/pull/15857#issuecomment-2162362198
> If we want to maintain the production quality of the nRF Desktop app, we need this change that is blocked on the @tejlmand PR (dependency indicated in the PR description). Alternatively, we can lower the nRF Desktop quality from production to experimental following the VS code approach. However, going back to the experimental quality for NCS 2.7.0 needs wider discussion from relevant stakeholders.
>
> On a separate note, we had a different arrangement with @carlescufi and @tejlmand, as this change was supposed to be part of NCS 2.7.0.

**Review by nordicjm — APPROVED** [review]

**Comment by doublemis1** [comment]
> Member
Please add bugfix label and report to @shanthanordic 
Also good to have a impact on other projects since it touches build system in last days of bugfixing.

**Pull request merged**
