### PR TITLE
manifest: Zephyr upmerge with ipc_service changes

### PR DESCRIPTION
**Pull request by ArekBalysNordic**
Changed default value of IPC priority which fixes an issue with IPC's priority in the Matter Network.

### CODE REVIEW

**Review by LuDuda — APPROVED** [review]

**Review by emob-nordic — APPROVED** [review]
Could you force push and resolve conflicts?

**Comment by ArekBalysNordic** [comment]
Closing This PR - The commit with IPC changes was merged recently to SDK-zephyr, so we can wait for the next Zephyr upmerge.

**Comment by pdunaj** [comment]
@ArekBalysNordic - I think we need to cherry pick the change into the sdk-zephyr. why closing this PR?

**Comment by ArekBalysNordic** [comment]
Recently it was blocked by a previous Zephyr-SDK upmerge, and honestly, I forgot about it. Meantime this commit: https://github.com/zephyrproject-rtos/zephyr/pull/44981 was merged to Zephyr upstream. In Matter, we have a workaround for now in our samples, and we don't need to cherry-pick this commit before NCS 2.0.0 release. We can wait for the next SDK-zephyr upmerge. So I closed this PR for now.

**Comment by emob-nordic** [comment]
@ArekBalysNordic You made a workaround but we also need this fix in for NCS-2.0.0. @volodymyr-bondarchuk has created similar sets of PR to have this cherry-picked, but we spotted you've already made this. We didn't want to duplicate so we closed https://github.com/nrfconnect/sdk-zephyr/pull/812 and asked if you could rebase as you were the first one.

@volodymyr-bondarchuk  let's reopen your sets of PRs then.

**Comment by ArekBalysNordic** [comment]
@emob-nordic It's my fault that I didn't close these PRs before. Sorry for that. We didn't want to cherry-pick this commit before NCS 2.0 release, but if you need this change, go ahead, reopen your PR, and let me know when it will be done. I will check it on our samples.

**Comment by emob-nordic** [comment]
@ArekBalysNordic Nothing to be sorry about. I didn't know you have already covered issues on your side. Sorry for noise.

**Pull request closed without merging**
