### PR TITLE
doc: getting started: Update system-wide instructions

### PR DESCRIPTION
**Pull request by carlescufi**
This includes pulling some changes from upstream Zephyr that clarify the installation on macOS, aside from reworking the system-wide installation instructions.

### CODE REVIEW

**Comment by greg-fer** [comment]
The doc preview is returning 404 despite a green doc build. @carlescufi , @gmarull , could you check if it was correctly deployed to _dev?

**Comment by gmarull** [comment]
> The doc preview is returning 404 despite a green doc build. @carlescufi , @gmarull , could you check if it was correctly deployed to _dev?

can you rebase? a potential fix has just been merged

**Comment by greg-fer** [comment]
@LuDuda , can you have a look at the update to the GN installation steps? Thanks.

**Comment by carlescufi** [comment]
> > The doc preview is returning 404 despite a green doc build. @carlescufi , @gmarull , could you check if it was correctly deployed to _dev?
> 
> can you rebase? a potential fix has just been merged

@gmarull still getting 404

**Comment by gmarull** [comment]
Weird, uploads are successful: https://github.com/nrfconnect/sdk-nrf/actions/runs/6848479742/job/18618756762#logs

**Review by greg-fer — APPROVED** [review]

**Pull request merged**
